### ISSUE TITLE
Wine can't install DX9

### ISSUE THREAD

**Issue by 00de** [mmtrt/leagueoflegends#10]
When attempting to install, I get the WINE Error "There has been an error. Unknown error while running C:/Riot Games\League of Legends/Prerequisites/Dx9/dxsetup.exe /silent". I have checked that that folder and file are there, and they are. I also checked if the file is corrupted by trying to install it thru just double clicking it, and it installs just fine.

**Comment by 00de** [comment]
I tried both EUW and EUNE

**Comment by mmtrt** [comment]
try installing both versions of `openal` see which distro you have installed use this [link](https://www.codeweavers.com/support/wiki/diag/missinglibopenal) if this does not fix your issue then you have to install wine dependencies for you distro [link](https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell/)
