### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Getta91** [mmtrt/leagueoflegends#100]
Hi ! This is just a little message in order to thanks you for all your work. You are always there when people needs help with the snap package and you made this like a huge project. So... Thank you.
Lol, this snap package is taking a big part of my life ;)

EDIT: HAPPY100 ISSUES

**Comment by mmtrt** [comment]
Thank you for using it and your kind words that means a lot.

Though this snap was a side project at that time when I was testing wine snaps then I thought why not create league snap then eventually many users started using more.

**Comment by Getta91** [comment]
Well looks like your dream came true! :3
