### ISSUE TITLE
terminate called after throwing an instance of 'dxvk::DxvkError'

### ISSUE THREAD

**Issue by Drox17** [mmtrt/leagueoflegends#101]
drox17@drox17-desktop:~$ sudo leagueoflegends
LeagueClient.exe(00000009): ALWAYS| Application Version:9.20.292.351 - CL:2920351 - Build Date:Oct 04 2019 - Build Time:13:46:43
LeagueClient.exe(00000009): ALWAYS| Direct Launch not configured for league_of_legends.live in environment '' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
LeagueClient.exe(0000002E): ALWAYS| Tracing worker thread running.
LeagueClient.exe(00000009): ALWAYS| Running LeagueClient version 9.20.292.351
LeagueClient.exe(0000002E): ALWAYS| Keeping up to 10 tracing logs.
LeagueClient.exe(0000002E): ALWAYS| Tracing CompactJsonWriter at C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-12-20T12-18-18_8_LeagueClient-tracing.json
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Init
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded plugin manifest file plugin-manifest.json.
LeagueClient.exe(00000009): ALWAYS| Begin Launch Ux Process
LeagueClient.exe(00000009): ALWAYS| End Launch Ux Process
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Mounted all WadFiles in 11.224 milliseconds.
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded all plugins in 123.908 milliseconds. All warming in 0.000 milliseconds. All loading in 75.931 milliseconds.
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Initializing plugins
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-client-config: 1.6.1
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-rso-auth: 1.8.24
LeagueClient.exe(00000032): ALWAYS|        rcp-be-lol-rso-auth| RSOClient::SetRSOConfig url: https://auth.riotgames.com/token, clientId: lol, scopes: openid offline_access lol ban profile email phone
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-patch: 1.5.96
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-patcher: 1.20.35
LeagueClient.exe(00000009): ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__rads__patcher_operation
common.os_platform: Windows
common.application_name: LeagueClient
common.application_version: 9.20.292.351
common.cef_version: 3.2623.1397.gaf139d7
common.installation_id: x9Y/+Q==
common.locale: es_MX
common.machine_id: g6NRvDrA0EC3SwbGoAXM2g==
common.os_version_major: 7
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: LA1
common.session_id: adb3113a-0cbc-2546-9bd0-0775ec628b28
initial_check: true
cdn: akamai
last_host_ip: 200.75.200.219
success: success
operation_type: check
patchline: live-la1-win
patcher: chunking
published_at: 2019-12-18T23:12:32.993000
version: 79
url: https://lol.secure.dyn.riotcdn.net/channels/public/live-la1-win.json
LeagueClient.exe(00000009): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(00000032): ALWAYS|        rcp-be-lol-rso-auth| rso-auth: OpenID configuration fetch succeeded after 1 tries
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-riot-messaging-service: 1.3.10
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-entitlements: 0.0.28
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-bootstrap: 1.0.20
LeagueClient.exe(00000009): ALWAYS| Phase End - Initializing plugins - duration was 601.80ms
LeagueClient.exe(00000009): ALWAYS| Foundation is now running.
LeagueClient.exe(0000003F): ALWAYS|       rcp-be-client-config| Updated public config for LeagueClient with 67 entries
LeagueClient.exe(00000009): ALWAYS| Phase End - Init - duration was 1066.29ms
LeagueClient.exe(00000009): ALWAYS| Phase Begin - MainLoop
LeagueClient.exe(00000031): ALWAYS|        rcp-be-lol-rso-auth| Client is configured. RSO Proxy: true
005b:err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
005b:err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
terminate called after throwing an instance of 'dxvk::DxvkError'

abnormal program termination

**Comment by mmtrt** [comment]
Please don't launch snap with sudo, that error looks like dxvk is failing to load vulkan devices, make sure your system has all required pkgs installed for vulkan.

**Comment by Ignacy-s** [comment]
Please also remember that wine is still a somewhat *beta* program, and as is, it often requires a several `start, crash, kill, restart` attempts before it kicks in and runs, even when we call it "working".
In my case it's on average 2 times before it works. It sometimes has to be killed more times.

In `bash`, this for loop greps for processes with windows and league in name (ignoring case), get's their process id and kills them:
`for tobekilled in windows league; do kill -9 $(ps aux  | grep -v grep | grep -i $tobekilled | awk '{ print $2}') ; done` all in one line
