### ISSUE TITLE
Unable to start a game (two different computers, Ubunty 19.10)

### ISSUE THREAD

**Issue by Amoki** [mmtrt/leagueoflegends#104]
Hi!
I can't start a game for about two months. The launcher works well but I have a splat when a game starts.

I tried on my desktop (AMD CPU and GPU) and my laptop (Intel CPU and GPU). Both are on Ubuntu 19.10.

[lol.log](https://github.com/mmtrt/leagueoflegends/files/4035128/lol.log)

As there are no open or recently closed issues, I suppose not everyone has this problem :/

Do you have any clue?

Thanks for this awesome tool!

**Comment by mmtrt** [comment]
You need to create fresh `wineprefix` check #7 for guide since this is needed for `wine` version upgrade otherwise game crashes.

**Comment by Amoki** [comment]
Recreating WINEPREFIX did it. Thanks again! :D
