### ISSUE TITLE
Blitz.gg

### ISSUE THREAD

**Issue by mpfaraujo** [mmtrt/leagueoflegends#105]
Is there a way to include blitz.gg add on in the same preffix than league? i couldnt ..

**Comment by mmtrt** [comment]
I could implement it but this needs testing I'll try and then post update regarding this but after 14th Jan.

**Comment by mmtrt** [comment]
I've added blitz.gg ee31201050f94333ca0c6566e49418472025d590 should be enough and make sure you have updated this snap in order to get this.

Install it from region dialog selection then install game and launch blitz by this command after installing it `leagueoflegends.blitzgg`

**Comment by moezemara** [comment]
> I've added blitz.gg [ee31201](https://github.com/mmtrt/leagueoflegends/commit/ee31201050f94333ca0c6566e49418472025d590) should be enough and make sure you have updated this snap in order to get this.
> 
> Install it from region dialog selection then install game and launch blitz by this command after installing it `leagueoflegends.blitzgg`

I have updated the snap and installed `leagueoflegends.blitzgg` command on eune but nothing happens after that

**Comment by mmtrt** [comment]
> I have updated the snap and installed leagueoflegends.blitzgg command on eune but nothing happens after that

It won't work because its not installed in `wineprefix` so you need to install it.

See #7 for guide
