### ISSUE TITLE
Wine Fsync

### ISSUE THREAD

**Issue by Getta91** [mmtrt/leagueoflegends#106]
Hi! I have a fsync kernel and i would be pleased if I could use fsync option on the snap. Is there anyway to do this? Perhaps, are you using wine-lol ? 'Cos its needed in order to use fsync (or even esync)? Thanks you in advance!

**Comment by mmtrt** [comment]
update wine-staging snap from beta and update league snap to get this fsync up and running and do report of this as I can't test snap due to nvidia driver issue on snapd.

**Comment by mmtrt** [comment]
works fine, shows `fsync is up and running`
