### ISSUE TITLE
[Suggestion] Update to Wine 5.0

### ISSUE THREAD

**Issue by Bloodiko** [mmtrt/leagueoflegends#107]
Heya -
Since wine 5.0 is now released, are you going to try if you can get the wine 5.0 release to work with lol ?  
it may run way more stable - hopefully

**Comment by mmtrt** [comment]
I have already compiled and tested `wine 5.0` which is currently released on AppImage side but for snap side I've already created `wine 5.0` snap and built with league fixes currently waiting to be used. For now only league snap need changes to use `wine-platform-5-staging` snap.
