### ISSUE TITLE
unable to install with dxvk

### ISSUE THREAD

**Issue by adserba** [mmtrt/leagueoflegends#109]
Hi, I am unable to install league with vulkan support, this is the error:

006d:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
006d:err:module:find_forwarded_export module not found for forward 'winevulkan.wine_vkGetInstanceProcAddr' used by L"C:\\windows\\system32\\vulkan-1.dll"
LeagueClient.exe(0000002D): ALWAYS| Foundation is now running.
LeagueClient.exe(0000002D): ALWAYS| Phase End - Init - duration was 384.26ms
LeagueClient.exe(0000002D): ALWAYS| Phase Begin - MainLoop
wine: Call from 0x7bc94bb1 to unimplemented function vulkan-1.dll.vkGetInstanceProcAddr, aborting

**Comment by adserba** [comment]
I had the game runing well with dxvk, but decided to update wine-platform-5-staging. I followed step by step instructions, but the game was laggy,and the dxvk_hud disappered so decided to reinstall. and that's where I'm stuck. Any suggestions?

**Comment by mmtrt** [comment]
client is crashing for me with dxvk enabled anyway I'm investigating the issue will post update.

**Comment by mmtrt** [comment]
Pushed update issue is fixed now.

**Comment by adserba** [comment]
thank you!
