### ISSUE TITLE
Unstoppable bug-splat before logging to client

### ISSUE THREAD

**Issue by ghost** [mmtrt/leagueoflegends#110]
Hello. I've been trying to install LoL on Ubuntu 18.04 for some time now.

I'm doing:
snap install --edge leagueoflegends --devmode
snap refresh --candidate wine-platform-runtime
snap refresh --candidate wine-platform-5-staging
leagueoflegends

Was also trying (after removing lol and wine from snap):
snap install --edge leagueoflegends --devmode
WINEARCH=win32 snap refresh --candidate wine-platform-runtime
WINEARCH=win32 snap refresh --candidate wine-platform-5-staging
WINEARCH=win32 leagueoflegends

and also changing windows to XP in leagueoflegends.winecfg.

Each of all combinations of these options (XP/7 & default/win32) gives same result - first:
0042:err:module:__wine_process_init L"C:\\windows\\system32\\.exe" not found
then, after re-run, it downloads a bit, but after getting to login screen there's bugsplat, then client restarts and gets bugsplatted again.

What am I missing? What should I attach to help with diagnose?

**Comment by mmtrt** [comment]
did you tried creating fresh wineprefix see #7 for guide or maybe don't use this `WINEARCH=win32` when settting up league see if this helps.

**Comment by kartofl** [comment]
> did you tried creating fresh wineprefix see #7 for guide

Yes, I did. Also tried to run and install everything with and without WINEARCH=win32.

Even stranger thing - when I do install client choosing NA I'm able to login and run tutorial, just bugsplatting while going to shop or collection. When choosing EUW/EUNE I'm not even able to get to launcher update.

**Comment by mmtrt** [comment]
can you tell info about your system, like gpu, drivers, os and is it pc or laptop

**Comment by kartofl** [comment]
PC, i7-2600, geforce gtx750ti 2gb (nvidia-driver-435), 8gb ram. Ubuntu 18.04.
Don't know what else and how to get it.

**Comment by Fisk24** [comment]
Im also having this issue. I can get to a black client window then it just bugsplats and tries to launch again endlessly. I installed it using NA and I cant even log in.

**Comment by Fisk24** [comment]
For what its worth I found this the first time I launched leagueoflegends from the terminal

003e:err:module:__wine_process_init L"C:\\windows\\system32\\.exe" not found

This occurred the first time the command was run after a fresh install of the snap package. After digging around in the scripts it seems like the the game is supposed to launch automatically after it installs everything. This error could be related to that because the script did not in-fact launch the app the first time it was executed. I had to run it a second time and now we are here.

**Comment by eralmansouri** [comment]
I have this same issue. This error occurs when I run the game, and the bugsplat shows before the client starts.

> LeagueClient.exe(0000003F):   WARN|           rcp-be-lol-patch| Patcher: Couldn't load release manifest during install verification: Manifest file not found on disk
LeagueClient.exe(0000003F):  ERROR|           rcp-be-lol-patch| Patcher: Error extracting game version from content metadata: Metadata file doesn't exist
LeagueClient.exe(00000009): ALWAYS| Ux state set to HideAll.
LeagueClient.exe(00000009): ALWAYS| Ux state set to Quit.

It also tries to launch again endlessly. RTX 2080 i5 nvidia-driver-440 Ubuntu 18.04
