### ISSUE TITLE
Blitz install fails. Wine locks game to 60 on 144hz monitor

### ISSUE THREAD

**Issue by Siju21** [mmtrt/leagueoflegends#111]
The blits app keeps failing to install, it tells me to view the logs, but when I click on "view logs" nothing happens. Tried setting it up on a fresh prefix and everything... No luck. Also, when I turn on Vsync in-game, the game locks to 60, if I uncap it, it fluctuates.

Also, forgive me for being a noob, but  how can I disable the dxvk hud? It covers  up some stats numbers (like enemy AD/AP)  in-game.

**Comment by mmtrt** [comment]
- I've to investigate blitz issue.
- for vsync issue try wine virtual desktop from `leagueoflegends.winecfg`
- you can add envar `export DXVK_HUD=0` as global to `/etc/profile` or `/etc/environment` to permanently disable hud or you can just launch game with hud disable like this first `export DXVK_HUD=1` terminal then hit enter then `leagueoflegends` command to launch game with hud disable this only disables hud for single terminal session.

**Comment by Siju21** [comment]
I've managed to fix blitz by making a symlink of your snap's wine directory to replace my .wine folder in home. Then I installed the latest dot net from microsoft, which autoinstalled to your wine prefix. Blitz still couldn't load the installer, so I changed the OS setting to windows 7, which allowed it to install. Now I have it running by adding blitz to the application list in the winecfg and setting it to run in windows 7. I guess the latest blitz refuses to work in XP.
I tried doing virtual desktop but it stays locked at 60. My monitor has freesync but that doesn't do me any good on the current drivers.

**Comment by mmtrt** [comment]
> I have tried doing what you said, adding the envar to either or even both profile and environment
Heck, I've even tried adding it to my .profile in my home directory. Tried launching with export dxvk=1 followed by leagueoflegends in terminal, but still have that HUD blocking my view of that corner.

`export DXVK_HUD=0` with zero disables it I'd written 1 which enables it by mistake sorry about that.

`export DXVK_HUD=0` You need to add this to either `profile` **OR** `environment`  **OR** `.profile` in one file not on all these files after that `logout` or `reboot` system to take effect

`env | grep DXVK` command to check envar shows `export DXVK_HUD=0` then its disabled

> I tried doing virtual desktop but it stays locked at 60. My monitor has freesync but that doesn't do me any good on the current drivers.

Maybe try disabling your desktop compositing.

**Comment by Siju21** [comment]
Alright the hud's outta the way. I'm not sure how to disable desktop composition, but I just tried killing the shell after launching league, but still no luck. the game stays vsynced at 60fps. Perhaps it's an issue with the amd driver I'm using? I'm currently using this repo for my RX580 https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers
Should I be using another driver on Ubuntu 19.10?

**Comment by mmtrt** [comment]
snaps use provided drivers from within snap on `intel` `amd/ati` and on non prop driver for `nv` gpus.

Try this updates runtime snap which has packages updated from `oibaf` ppa

`snap refresh --beta wine-platform-runtime`

**Comment by Siju21** [comment]
I believe I fixed it. I had to purge the default drivers included with the ubuntu installation, then reinstall oibaf drivers. Now I get 144fps, but only if I play in borderless mode. If I go fullscreen, it stays at 60 with vsync enabled. Perhaps wine has a setting that controls the refresh rate along with the resolution?
