### ISSUE TITLE
Allow using gamemode

### ISSUE THREAD

**Issue by vilgotf** [mmtrt/leagueoflegends#114]
I'm unable to just use `gamemoderun leagueoflegends`, I'm assuming this needs some workaround.
[gamemode](https://github.com/FeralInteractive/gamemode)

**Comment by mmtrt** [comment]
I did investigate getting this working but couldn't get it to work will do further testing will let you know.

**Comment by lil-arch** [comment]
I tkink that all you need to do is run on your terminal:
`gamemoderun leagueoflegends`
or you could manually enable the systemd service and disable it when not wanting to play anymore.
