### ISSUE TITLE
Audio distorted and glitchy when starting League using 32-bit audio and pulseaudio

### ISSUE THREAD

**Issue by newhoa** [mmtrt/leagueoflegends#115]
I'm using the snap on Ubuntu 19.10. Using this config

/etc/pulse/daemon.conf

`default-sample-format = s32le`

When audio is playing and then League is launched (or if you launch league then play audio), the audio will become glitchy and distorted. Sometimes you only need to start the client, sometimes it doesn't distort until getting into an actual game, but it does always do it.

Exiting league, changing to s16le, and restarting pulseaudio fixes the problem (I think also just restarting Pulse once League is started may also fix it). My sound card supports both s32le and s16le but obviously I'd like to use the better bit depth quality if I could.

It seems that Wine/League is trying to use 16-bit audio. Is there any way to change this? The audio tab under leagueoflegends.winecfg doesn't have any options for that. I tried leagueoflegends.winetricks to see if there was any audio options but it won't launch.

Thanks to anyone who could shed some light on this or point me in the right direction.

edited: Forgot to add OS and League package.

**Comment by mmtrt** [comment]
try using 

`export PULSE_LATENCY_MSEC=60`

or try changes from

https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Laggy_sound
