### ISSUE TITLE
After every game, my client disappear, and I need to reinstall leagueoflegends snap

### ISSUE THREAD

**Issue by banmarkovic** [mmtrt/leagueoflegends#116]
After every game, I'm unable to return to client. When I try to run command "snap run leagueoflegends", it gets stuck. When I kill the processes and rerun the command, downloading starts again like I reinstalled leagueoflegends. I'm on Ubuntu 18.04.

**Comment by mmtrt** [comment]
that shouldn't happen client working fine here without such issue here.

**Comment by ShauniArima** [comment]
Sometimes the client takes a very long time to start or to display the game result. I'll provide some logs the next time that I have that problem.

**Comment by TheHaricover** [comment]
Try rebooting your PC instead of killing the processes. Rebooting for each game is not really convenient but at least it will prevent league to DL itself over again (if yours work like mine)
