### ISSUE TITLE
Is there a way to run this snap with proton instead of wine?

### ISSUE THREAD

**Issue by bes1002t** [mmtrt/leagueoflegends#118]
Hi,

I've installed the league of legends snap client on my fedora31 machine. There are many warnings that this is not fully working and there could be several bugs (I had to install this snap in dev mode).

So I would like to try using this snap with Steams proton api. Maybe this is working better, since proton is working pretty well for many many other games (even non steam games). Is there a way to get this snap working with proton instead of wine?

**Comment by mmtrt** [comment]
league needs `wine` with some patches applied to it **OR**  it needs both `wine` and `glibc` patched for it.
Depends which patches are used. 

There isn't `proton` snap available though you can compile custom `proton` with league patches inorder to play league with it without need of snap.

**Comment by bes1002t** [comment]
proton is wine with some patches on top (I think not the special patches the snap is providing). 

Anyway, for me the snap with wine is working out of the box and I did not find any bugs so far.
