### ISSUE TITLE
Anti-cheat kernel driver

### ISSUE THREAD

**Issue by aironsouza** [mmtrt/leagueoflegends#119]
Not exactly an issue but ... I heard that this will be the end of the league on Linux. Like, for good. When RIOT implement this will mean the end of this project as well?

https://na.leagueoflegends.com/en-pl/news/dev/dev-null-anti-cheat-kernel-driver/

ps.:Thank you for this amazing solution. It runs better on Linux than Windows in my machine.

**Comment by mmtrt** [comment]
Yeah that will be end of this `snap` but there is possibility if `WINE` devs could advance in implementing changes that may work game again though not sure what future holds for `league` in Linux we'll see.

**Comment by aironsouza** [comment]
Ok then, let's wait. Btw, I do not want to open another issue just for that but maybe you can help me with another question:

I play on a big screen (Ubuntu 20.04 gnome 3.36.1) with 4k resolution and the scale at 200%. LoL runs at 1080p (my laptop don't handle 4k well)

Problem: As soon as the game goes fullscreen, my scale is set back to 100%. So, if I do an alt+tab or after the game finished, my scale is 100%. There is something I can do to avoid this behavior? It happens with you too?

**Comment by mmtrt** [comment]
maybe try to use `wine` virtual desktop from graphics tab in `winecfg`.

`leagueoflegends.winecfg`
