### ISSUE TITLE
Fixing lag spikes

### ISSUE THREAD

**Issue by Zeredder** [mmtrt/leagueoflegends#12]
Running Kubuntu 18.04 with a Nvidia gtx 960m on Optimus laptop. Using nvidia driver 390.
Game runs well, gets 80 fps at max settings, but gets massive lagspikes every 3-5 seconds. Dropping down to 10fps.

What should I try to fix this? Upgrading Nvidia Driver is out of the question as I already bricked my last OS doing so.

**Comment by mmtrt** [comment]
check cpu usage if its `100%` then try killing `league client` when you are in-game after loading should help.

**Comment by Zeredder** [comment]
CPU usage hovers around 30%, with or without the client killed. Intel core i7-6700hq.
Lag spikes continue to happen. Mostly only when a lot of stuff is coming out at once, like at the start of a teamfight, and small stutters when a new wave of minions appears on screen. Most noticeable in ARAM.

**Comment by mmtrt** [comment]
does that issue also happen with you when playing this game without this `snap`.

**Comment by Zeredder** [comment]
That issue does not happen without this snap, but I have only been able to run the game in training without the snap. The game crashes whenever I join a real match using other methods.
