### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by takaduhkha** [mmtrt/leagueoflegends#120]
There's no sound in the client or game. 
I have Wine installed and winecfg audio test gives the sound.

**Comment by mmtrt** [comment]
anything in log, also which audio device you have and which port is in use by it?

**Comment by takaduhkha** [comment]
No logs cause I ended up reinstalling the system after messing with it too much. Not sure if I want to try again unless there's just some simple solution to this problem.

It's generic audio, I don't really know how to find more info or the port. Can you help with it?

**Comment by mmtrt** [comment]
I mean which audio device uses port in your system is it built-in speaker OR is it usb headset OR 3.5mm jack headset/speaker?

**Comment by takaduhkha** [comment]
Oh in this case it's the last option, jack.

**Comment by takaduhkha** [comment]
I'm on Ubuntu 18.04 if it helps.

**Comment by mmtrt** [comment]
it's similar issue like #13 maybe try my suggestion from there.

**Comment by takaduhkha** [comment]
As I wrote in first post I have Wine installed.

**Comment by mmtrt** [comment]
ah my bad sorry btw which audio stack you use I presume pulse audio which comes defualt in ubuntu.

**Comment by takaduhkha** [comment]
yes, pulse audio

**Comment by mmtrt** [comment]
can you test snap update with recent changes see if it fixes anything.

**Comment by takaduhkha** [comment]
I did „sudo snap refresh”. It worked! Thank you. Going to test if everything works now. Yeeeeah!
