### ISSUE TITLE
LibGL error, what should I do?

### ISSUE THREAD

**Issue by santiagvs** [mmtrt/leagueoflegends#122]
GPU: NVidia GeForce GT 420, Intel i5 3470

Hi, I've been trying to run League of Legends on Debian 10 Buster by this method, and when I use `snap run league of legends` it returns me this error: 

`kephas@kephas:~$ snap run leagueoflegends
LeagueClient.exe(00000009): ALWAYS| Application Version:9.20.292.351 - CL:2920351 - Build Date:Oct 04 2019 - Build Time:13:46:43
LeagueClient.exe(00000009): ALWAYS| Direct Launch not configured for league_of_legends.live in environment '' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
LeagueClient.exe(0000002E): ALWAYS| Tracing worker thread running.
LeagueClient.exe(00000009): ALWAYS| Running LeagueClient version 9.20.292.351
LeagueClient.exe(0000002E): ALWAYS| Keeping up to 10 tracing logs.
LeagueClient.exe(0000002E): ALWAYS| Tracing CompactJsonWriter at C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2020-04-23T12-55-21_8_LeagueClient-tracing.json
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Init
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded plugin manifest file plugin-manifest.json.
LeagueClient.exe(00000009): ALWAYS| Begin Launch Ux Process
LeagueClient.exe(00000009): ALWAYS| End Launch Ux Process
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Mounted all WadFiles in 7.628 milliseconds.
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded all plugins in 61.092 milliseconds. All warming in 0.000 milliseconds. All loading in 32.558 milliseconds.
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Initializing plugins
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-client-config: 1.6.1
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-rso-auth: 1.8.24
LeagueClient.exe(0000003C): ALWAYS|        rcp-be-lol-rso-auth| RSOClient::SetRSOConfig url: https://auth.riotgames.com/token, clientId: lol, scopes: openid offline_access lol ban profile email phone
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-patch: 1.5.96
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-patcher: 1.20.35
LeagueClient.exe(0000003C): ALWAYS|        rcp-be-lol-rso-auth| rso-auth: OpenID configuration fetch succeeded after 1 tries
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-riot-messaging-service: 1.3.10
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-entitlements: 0.0.28
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-bootstrap: 1.0.20
LeagueClient.exe(00000009): ALWAYS| Phase End - Initializing plugins - duration was 299.52ms
LeagueClient.exe(00000009): ALWAYS| Foundation is now running.
LeagueClient.exe(00000009): ALWAYS| Phase End - Init - duration was 575.09ms
LeagueClient.exe(00000009): ALWAYS| Phase Begin - MainLoop
LeagueClient.exe(00000009): ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__rads__patcher_operation
common.os_platform: Windows
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 9.20.292.351
common.cef_version: 3.2623.1397.gaf139d7
common.installation_id: b/mgkQ==
common.locale: pt_BR
common.os_version_major: 7
common.machine_id: yDpUlO6Wc0G3xDw5sZslSg==
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: BR
common.session_id: 69ce9fee-a0f1-664a-a7b7-d6cef8c21b9c
initial_check: true
cdn: akamai
last_host_ip: 23.215.131.226
success: success
operation_type: check
patchline: live-br-win
patcher: chunking
published_at: 2020-04-15T08:03libGL error: No matching fbConfigs or visuals found
:47.023000
verslibGL error: failed to load driver: swrast
ion: 100
url: https://lol.secure.dyn.riotcdn.net/channX Error:  GLXBadContext
  Request Major code 154e (GLX)
  Request Minor code 6 ()
l  Error Serial #243
  Current Serial #242s
/public/live-br-win.json`

How to fix it?

![Captura de tela em 2020-04-23 13-01-22](https://user-images.githubusercontent.com/50297911/80121334-8bfb1a80-8562-11ea-91da-70591d71444a.png)

**Comment by mmtrt** [comment]
snap can't find libgl so its failing that shouldn't happen, can you post info of this,

`apt list --installed | grep nvidia`

**Comment by CobraKay** [comment]
> snap can't find libgl so its failing that shouldn't happen, can you post info of this,
> 
> `apt list --installed | grep nvidia`

`kephas@kephas:~$ apt list --installed | grep nvidia

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

glx-alternative-nvidia/stable,now 1.0.0 amd64 [installed,automatic]
libegl-nvidia-legacy-390xx0/stable,now 390.116-1 amd64 [installed,automatic]
libegl-nvidia-legacy-390xx0/stable,now 390.116-1 i386 [installed]
libgl1-nvidia-legacy-390xx-glvnd-glx/stable,now 390.116-1 amd64 [installed,automatic]
libgles-nvidia-legacy-390xx1/stable,now 390.116-1 amd64 [installed,automatic]
libgles-nvidia-legacy-390xx2/stable,now 390.116-1 amd64 [installed,automatic]
libglx-nvidia-legacy-390xx0/stable,now 390.116-1 amd64 [installed,automatic]
libnvidia-egl-wayland1/stable,now 1:1.1.2-1 amd64 [installed]
libnvidia-egl-wayland1/stable,now 1:1.1.2-1 i386 [installed]
libnvidia-legacy-390xx-cfg1/stable,now 390.116-1 amd64 [installed,automatic]
libnvidia-legacy-390xx-eglcore/stable,now 390.116-1 amd64 [installed,automatic]
libnvidia-legacy-390xx-eglcore/stable,now 390.116-1 i386 [installed,automatic]
libnvidia-legacy-390xx-glcore/stable,now 390.116-1 amd64 [installed,automatic]
libnvidia-legacy-390xx-ml1/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-detect/stable,now 418.74-1 amd64 [installed]
nvidia-egl-common/stable,now 418.74-1 amd64 [installed,automatic]
nvidia-installer-cleanup/stable,now 20151021+9 amd64 [installed,automatic]
nvidia-kernel-common/stable,now 20151021+9 amd64 [installed,automatic]
nvidia-legacy-390xx-alternative/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-legacy-390xx-driver-bin/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-legacy-390xx-driver-libs/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-legacy-390xx-driver/stable,now 390.116-1 amd64 [installed]
nvidia-legacy-390xx-egl-icd/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-legacy-390xx-kernel-dkms/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-legacy-390xx-kernel-support/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-legacy-390xx-vdpau-driver/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-legacy-390xx-vulkan-icd/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-modprobe/stable,now 418.56-1 amd64 [installed,automatic]
nvidia-persistenced/stable,now 418.56-1 amd64 [installed,automatic]
nvidia-settings-legacy-390xx/stable,now 390.116-1 amd64 [installed,automatic]
nvidia-support/stable,now 20151021+9 amd64 [installed,automatic]
nvidia-vulkan-common/stable,now 418.74-1 amd64 [installed,automatic]
xserver-xorg-video-nvidia-legacy-390xx/stable,now 390.116-1 amd64 [installed,automatic]
`

**Comment by mmtrt** [comment]
can you please install a small helper snap and run a few commands?

sudo snap install snapd-hacker-toolbelt

snapd-hacker-toolbelt.busybox ls /var/lib/snapd/lib/gl

cat /sys/modules/nvidia/version
