### ISSUE TITLE
Error when login - Cannot find auth service

### ISSUE THREAD

**Issue by Pongelupe** [mmtrt/leagueoflegends#123]
Whenever I try to login I get this error about not finding the auth service. I'm playing at Ubuntu 19.10 eoan with the following kernel x86_64 Linux 5.3.0-46-generic. I've played with the snap before this error.

The complete log is attached.

Plz help me! I wanna play so bad  hahahahaha
[log_lol.txt](https://github.com/mmtrt/leagueoflegends/files/4537243/log_lol.txt)

**Comment by mmtrt** [comment]
can you post info of

`snap list | grep wine`

**Comment by Pongelupe** [comment]
yes, for sure!

wine-platform-5-staging  5.0.0                       7     latest/candidate  mmtrt          -
wine-platform-runtime    v1.0                        126   latest/candidate  mmtrt          -

**Comment by Pongelupe** [comment]
After this last patch the error still occurs

**Comment by mmtrt** [comment]
maybe try creating fresh `wineprefix` read pinned issue #7 for guidance.
