### ISSUE TITLE
Voice chat doesn't work and too much ping

### ISSUE THREAD

**Issue by Ferbrod** [mmtrt/leagueoflegends#124]
Since last update (April 29th) I can't use char voice, I "join" the call but nobody can hear me or me to them.
And another thing, when I'm using wifi i get a lot of ping, and i know it's not my network because when I connect the wired conection works perfectly.

**Comment by Haru-Fujimura** [comment]
i also have this problem. it seems that certain audio drivers arent included  in the wine distro.
