### ISSUE TITLE
Chat needs long time to connect

### ISSUE THREAD

**Issue by bes1002t** [mmtrt/leagueoflegends#125]
In Linux the chat in champion selection needs about 30s to connect. Because of this I always has to choose the lane which is left. In Windows I'm always the first in chat.

Are there any ways I could debug this?

**Comment by mmtrt** [comment]
try this see if it works,

'https://www.reddit.com/r/leagueoflinux/comments/gajxej/league_of_legends_client_friend_list_fix/?utm_medium=android_app&utm_source=share'
