### ISSUE TITLE
Riot Client black screen / stuck at startup after clean install

### ISSUE THREAD

**Issue by slauko** [mmtrt/leagueoflegends#127]
hello,
i recently changed distros , from fedora to arch and installed this snap .. on fedora everything worked fine, on arch however i had some problems at installing, for example some fonts where missing when it asked me wich server i want to play, but no problem i still got it to install the right server ... first login was ok, to patch gamefiles to recent patch with old lolclient, chat wasnt working tho(because i still doesnt used riot client)..so i restarted and now i cant login, it downloaded the riotclient at second startup and installed, then started it and now i only have a black window i can move around but nothing shows up in it 

![riotclient](https://user-images.githubusercontent.com/28165655/81701718-b1e15400-946a-11ea-9393-e12e93294be1.png)

`christoph:~ $ leagueoflegends
Fontconfig warning: FcPattern object weight does not accept value [0 45)
000000.002|   OKAY| Running from cwd 'C:\Riot Games\League of Legends'.
000000.003| ALWAYS| Application Version:10.9.318.6057 - CL:3186057 - Build Date:Apr 23 2020 - Build Time:18:02:04
000000.004|   OKAY| Initial working directory: "C:\Riot Games\League of Legends"
000000.005|   OKAY| Current process: "C:\Riot Games\League of Legends\LeagueClient.exe"
000000.006|   OKAY| Command line arguments:
000000.010| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__event
common.os_platform: Windows
common.application_name: LeagueClient
common.application_version: 10.9.318.6057
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: Pm29qA==
common.locale: en_GB
common.os_version_major: 7
common.machine_id: 
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: EUW
common.session_id: 
event_name: startup
crash_reporter: crashpad
000000.015| ALWAYS| Queued Dradis event to be sent.
000000.016| ALWAYS| Direct Launch enabled for league_of_legends.live in environment 'live' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
000000.018| ALWAYS| Found Riot Client live install (C:/Riot Games/Riot Client/RiotClientServices.exe)
000000.045|   OKAY| Launched Riot Client with process 57
000000.046| ALWAYS| Riot Client started. Exiting with the expectation of being restarted (ExitForDirectLaunch).
0071:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
000005.828|   OKAY| EventCollector: 0 events remaining after thread join
000005.833|   OKAY| Shut down EventCollector in 821 milliseconds
christoph:~ $ 
`
console output (deleted machine nad session id's , idk if private data)

would be nice if someone could help me out :/

**Comment by mmtrt** [comment]
try deleting `Riot Client` dir see if it helps.

`"$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games/Riot Client"`
