### ISSUE TITLE
Client closing and reopening

### ISSUE THREAD

**Issue by KorraHarraway** [mmtrt/leagueoflegends#128]
Kernel: 5.3
OpenGL:  4.6  Mesa 20.0.6
Vulkan:  1.0.65
Display Driver:  intel 2.99.917
Snap: 2.44.5

Problem:
Client often close and after a good while it reloads.
If it happens during champion selection and I couldnt come back until having enough time to select champion it counts as a quit. So playing ranked games is mostly discouraging :(

When running `snap run leagueoflegends` in terminal I keep receiving this message:

> WS_getaddrinfo Failed to resolve your host name IP

Don't know if there is something to do.

Best,

**Comment by RyanDoesMath** [comment]
I am getting this error also. This is the error that I am getting when it happens.

> 0133:err:winediag:FILE_CreateFile Too many open files, ulimit -n probably needs to be increased
00ad:err:ole:CoUninitialize Mismatched CoUninitialize

**Comment by mmtrt** [comment]
maybe increase `ulimit` or try disabling esync and fsync `export WINESYNC=0 WINEFSYNC=0` then launch game `snap run leagueoflegends`
