### ISSUE TITLE
Weird characters on installation

### ISSUE THREAD

**Issue by gbaranski** [mmtrt/leagueoflegends#129]
I'm using KDE Manjaro Linux, 5.6.11 kernel.

![Screenshot_20200514_164955](https://user-images.githubusercontent.com/34353640/81949431-24853780-9603-11ea-80ba-761d96a073c1.png)

**Comment by mmtrt** [comment]
it's `snapd` issue you can check thread for info regarding issue.

https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484
