### ISSUE TITLE
no sound in-game

### ISSUE THREAD

**Issue by 7013145** [mmtrt/leagueoflegends#13]
as per title, when i enter a game there is no sounds. client itself has no issues with sounds (or anything else) any idea as to why this is the case, and what i could try to solve it?

**Comment by mmtrt** [comment]
if `wine` is not installed on your system then try installing its needed pkgs for your distro might fix your issue [link](https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell/).
