### ISSUE TITLE
retrying (60 sec) wine issue ?

### ISSUE THREAD

**Issue by dikdust** [mmtrt/leagueoflegends#131]
After the first install (I have some strange font problem unrelated to  #129) the games works only one time after the updates, no matter how I do, reinstall - wineprefix ...

I begin to obtain line like

007e:err:ntdll:RtlpWaitForCriticalSection section 0x7bec87e0 "loader.c: loader_section" wait timed out in thread 007e, blocked by 0039, retrying (60 sec)

and the client doesn't start

or

000421.301|   OKAY|           rcp-be-lol-patch| Patchsieve is enabled.
000421.431|   OKAY|           rcp-be-lol-patch| Patchsieve response: {"releases":[{"release":{"product":"lol","id":"A7C273F1209CB831","labels":{"branch":{"values":["releases-10-10"]},"buildtracker_config":{"values":["public-win32-packed-now-public"]},"code":{"values":["public"]},"content":{"values":["release"]},"cpuarch":{"values":["x86"]},"platform":{"values":["windows"]},"riot:artifact_type_id":{"values":["lol-game-client"]},"riot:artifact_version_id":{"values":["10.10.3203039+branch.releases-10-10.code.public.content.release.cpuarch.x86.platform.windows"]},"riot:cpu_arch":{"values":["x86"]},"riot:platform":{"values":["windows"]},"riot:revision":{"values":["3203039"]}}},"compat_version":{"id":"10.10.3203039+branch.releases-10-10.code.public.content.release"},"download":{"url":"https://lol.secure.dyn.riotcdn.net/channels/public/releases/A7C273F1209CB831.manifest","scd_required":false}}]}
000421.452|   OKAY|           rcp-be-lol-patch| Patchsieve Game Patch Url="https://lol.secure.dyn.riotcdn.net/channels/public/releases/A7C273F1209CB831.manifest"
000421.455|   OKAY| Patcher: Started file download for URL https://lol.secure.dyn.riotcdn.net/channels/public/live-euw-win.json with ID 8 over connection 0 to server 151.29.122.19
000421.524|   OKAY| Patcher: Completed 393-byte 0-range file download request with ID 8 / 4a88b23 to server 151.29.122.19 from CDN akamai via POP a151-29-122-15.deploy.akamaitechnologies.com over connection 0 for URL https://lol.secure.dyn.riotcdn.net/channels/public/live-euw-win.json after 0.069 secs, 393 downloaded bytes and 0 retries

with League of legend startscreen stuck on display and loop of above log 

Is there anything I could try ? I'm on ubuntu 18.04 with last snap

**Comment by mmtrt** [comment]
can you post `snap list | grep wine`

**Comment by dikdust** [comment]
wine-platform-5-staging  5.0.0     7     latest/candidate  mmtrt       -
wine-platform-runtime    v1.0      140   latest/beta       mmtrt       -

**Comment by mmtrt** [comment]
these snap looks fine and that loader issue happens usually close all processes regarding league and relaunching with few try resolves maybe check this,
