### ISSUE TITLE
Lol fica travado na logo

### ISSUE THREAD

**Issue by KingDead098** [mmtrt/leagueoflegends#132]
Depois de fazer o login como geralmente faço o cliente fecha e fica na logo do lol estático, da primeira vez que instalei abriu normalmente só não aparecia o chat nem os campeões na hora de escolher.
![Captura de tela de 2020-06-03 14-29-36](https://user-images.githubusercontent.com/66381685/83668664-b6e77e00-a5a6-11ea-80d3-00178b33fd9f.png)

**Comment by KingDead098** [comment]
meu texto eu escrevi certinho ai deu alguma coisa

**Comment by mmtrt** [comment]
para problema de bate-papo, leva tempo para aparecer no cliente. e para o campeão, ele funciona bem para mim no modo de prática.

você pode postar informações sobre o seu sistema operacional Linux usando.

escreva o problema em inglês da próxima vez ou use o google translate se for difícil escrever obrigado.

**Comment by biro1557** [comment]
Comigo Também está acontecendo, uso o Linux mint 19.3

**Comment by Wanderson-Oliveira** [comment]
I also have the same problem.
I log in and then the client won't open.

[System]
OS:              Linux Mint 20 ulyana
Arch:            x86_64
Kernel:          5.4.0-40-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             7.7 GB
Swap:            2.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 20.0.8
OpenGL Core:     4.6 (Core Profile) Mesa 20.0.8
OpenGL ES:       OpenGL ES 3.2 Mesa 20.0.8
Vulkan:          Supported
