### ISSUE TITLE
Wine Installation Path?

### ISSUE THREAD

**Issue by GalGreenfield** [mmtrt/leagueoflegends#134]
Hello,

I understand that the snap also installs wine as a dependency.
Where does it install it?

It's not recognized by neither bash nor zsh (`whereis`, `which` and `wine` don't work).
I want to add it to my `$PATH` variable but I've no idea what file even to add to the path.

**Comment by mmtrt** [comment]
This `snap` uses `wine-platform-5-staging` & `wine-platform-runtime` snaps respectively are basically content snap which does not provides any `launchers` or `exec` commands but are mounted in this snap root path to expose there content to be used..

`wine` used by this `snap` should be here

`/snap/wine-platform-5-staging/current/opt/wine-staging/`

`libs` used by this `snap` should be in here

`/snap/wine-platform-runtime/current/`

**Comment by GalGreenfield** [comment]
Is there any way to add all the commands that come with wine to these content snaps, so I don't have to have 2 versions of wine in my system?

I barely know anything about wine and snap, so I'd appreciate references/explanations if there's anything I'm missing here.

**Comment by GalGreenfield** [comment]
> This `snap` uses `wine-platform-5-staging` & `wine-platform-runtime` snaps respectively are basically content snap which does not provides any `launchers` or `exec` commands but are mounted in this snap root path to expose there content to be used..
> 
> `wine` used by this `snap` should be here
> 
> `/snap/wine-platform-5-staging/current/opt/wine-staging/`
> 
> `libs` used by this `snap` should be in here
> 
> `/snap/wine-platform-runtime/current/`

I don't have the directory /snap/wine-platform-5-staging/current/ - only its parent directory (/snap/wine-platform-5-staging), whose children directories are named `11` and `7`. I'm currently running both client and game, if it matters.

**Comment by mmtrt** [comment]
If current dir doesn't exists then use greater num dir,

Well you can create a custom script to use `wine` from these `PATHS` but do note that runtime snap has custom built i386 glibc which is needed for league to work though I'm not sure if it will work outside snap env.

**Comment by GalGreenfield** [comment]
Firstly, thanks for the information so far.

Secondly, my shell is unable to find `wine-platform-runtime` and `wine-platform-5-staging` via:
 - `which`
 - `whereis`

How come that it can't find them? Could it be because of restrictions from the installation, as they were installed "via" the `leagueoflegends` snap? I did need to install it with `--devmode`, as snapd required me to do that (gave me an error that I need to install it with either `--demove` or `--jailmode`).
