### ISSUE TITLE
2 Wine Installations Making leagueoflegends Not Fun

### ISSUE THREAD

**Issue by GalGreenfield** [mmtrt/leagueoflegends#136]
As `leagueoflegends` uses its own Wine platform and runtime, and I wanted to use Wine programs, I installed Wine separately via my package manager.

However, after installing it, the client never started after logging in.

This is preventing me from using Wine and any Wine program unless I want t have the game working.
How can I debug this?

**Comment by Bloodiko** [comment]
The Client does Start eventually 
but it takes around 40 -60 seconds for me 
Try run the Command in the Terminal - It will either show you something like "Double Free or Corrupted" (Then it wont start) , or it will start eventually

If it doesnt start - use "leagueoflegends.wineserver" in a terminal (to kill it) and start again

**Comment by GalGreenfield** [comment]
Thanks, I think I just needed to wait longer.
