### ISSUE TITLE
Starting `leagueoflegends` brings back installer - installation not saved?

### ISSUE THREAD

**Issue by GalGreenfield** [mmtrt/leagueoflegends#138]
I installed the snap on a fresh installation of Kubuntu 20.04 - snapd came preinstalled.

Every time I launch leagueoflegends (from either the .desktop file or by running `snap run leagueoflegends`) thet installed is opened instead of the client - it's as if the installation isn't saved.

What's the reason for this issue? I updated Wine as the installer required. Could it be that the Wine configuration isn't set up properly by the installer? Whenever I start leagueoflegends again I see only the region selection option, not the warning message from beforehand about Wine.

Completely removing `wine-platform-5-staging`, `wine-platform-runtime` and `leagueoflegends` and reinstalling them does not work.

**Comment by mmtrt** [comment]
This could be due to recent changes now league snap uses newer riot client and make sure complete the initial client update download. Also use leagueoflegends command see if any error happens.

**Comment by GalGreenfield** [comment]
I don't entirely understand what you wrote, but I did complete the full client update and played the game a few times and it worked fine. I do get one error:
> You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

I got that error before I started having this issue so I ignored it (I think it was before the recent change of the snap package using the newer Riot client). It might be relevant now. However, after the installation of the client and updating it, the game works fine, so I'm not entirely sure if it's a problem or not, and if it is the source of the problem and I somehow change the Wine prefix to 32 bit, will it install the game in 32 bit as well? I want to play it in 64 bit for better performance.

**Comment by GalGreenfield** [comment]
I'd really appreciate the help, I keep reinstalling the game every time I want to play.

**Comment by mmtrt** [comment]
Try removing league snap complete data `~/snap/leagueoflegends`

**Comment by GalGreenfield** [comment]
> Try removing league snap complete data by deleting this dir `~/snap/leagueoflegends`

It didn't help - I get the same behavior.

Do look at this, though - the script creates a directory that already exists. I don't remember if when the snap worked correctly if it created the directory every single time I ran the snap, but it does it now:

```
❯ cd /home/galgreenfield/snap/leagueoflegends/common

❯ ls -la
total 32
drwxr-xr-x 7 galgreenfield galgreenfield 4096 Jul  1 17:16  .
drwxr-xr-x 4 galgreenfield galgreenfield 4096 Jul  1 17:07  ..
drwxrwxr-x 4 galgreenfield galgreenfield 4096 Jul  1 17:09  .cache
drwxrwxr-x 6 galgreenfield galgreenfield 4096 Jul  1 17:08  .config
drwxrwxr-x 3 galgreenfield galgreenfield 4096 Jul  1 17:16 'League of Legends'
drwxrwxr-x 3 galgreenfield galgreenfield 4096 Jul  1 17:07  .local
-rw-rw-r-- 1 galgreenfield galgreenfield  180 Jul  1 17:34  .wget-hsts
drwxrwxr-x 4 galgreenfield galgreenfield 4096 Jul  1 17:35  .wine
❯ snap run leagueoflegends
Executing mkdir -p /home/galgreenfield/snap/leagueoflegends/common
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: f34b450a051c00e13a5473ad9580ee33d1099b4b8307b25ca01ff73c159ef3c1 with wine-5.0 (Staging) and WINEARCH=win64
Executing w_do_call d3dx9
Executing mkdir -p /home/galgreenfield/snap/leagueoflegends/common
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

```

**Comment by mmtrt** [comment]
Use this old revision of snap see if this still happens

unpack zip & install snap file manually with this command,

`sudo snap install lol_75.snap --dangerous`

[lol_75.zip](https://github.com/mmtrt/leagueoflegends/files/4859862/lol_75.zip)

**Comment by GalGreenfield** [comment]
> Use this old revision of snap see if this still happens
> 
> unpack zip & install snap file manually with this command but make sure terminal is in path of unpacked zip dir,
> 
> `sudo snap install lol_75.snap --dangerous`
> 
> [lol_75.zip](https://github.com/mmtrt/leagueoflegends/files/4859862/lol_75.zip)

When I try to install it (with the command you provided) I get an error:
> error: cannot open "lol_75.snap"

There's nothing printed further than that.

**Comment by GalGreenfield** [comment]
I just want to leave a note here:
When I tried to instlal it (after unzipping it), I got the following error:
> error: snap "lol_75.snap" requires devmode or confinement override

So I ran `sudo snap install lol_75.snap --dangerous --devmode`
Then it started installing, and after a few seconds I got the following error:
> Mount snap "leagueoflegends" (unset)                                                                                             /error: change finished in status "Undone" with no error message



> Use this old revision of snap see if this still happens
> 
> unpack zip & install snap file manually with this command but make sure terminal is in path of unpacked zip dir,
> 
> `sudo snap install lol_75.snap --dangerous`
> 
> [lol_75.zip](https://github.com/mmtrt/leagueoflegends/files/4859862/lol_75.zip)

**Comment by GalGreenfield** [comment]
Update: installing it without `--dangerous` but with devmode (`sudo snap install lol_75.snap --devmode) seems make the installation succeed - I'll test the game itself and update with results.

**Comment by GalGreenfield** [comment]
Okay, so I succesfully installed the game in a non-PBE server (EUNE) and tested it - it worked fine from my test (I played a single Normal Teamfight Tactics game). I haven't tested further than that.

However, after exiting the client and running the snap again (I tried it multiple times), the client didn't auto-updae to the new client. So I couldn't play on PBE, which is mainly *right now* what I want to do.

I then uninstalled the snap with purging it (`sudo snap remove leagueoflegends --purge`).

I then reinstalled the snap and chose to install the PBE installation and got these errors, that I think I get with the new snap as well:
>Executing mkdir -p /home/galgreenfield/snap/leagueoflegends/common
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: f34b450a051c00e13a5473ad9580ee33d1099b4b8307b25ca01ff73c159ef3c1 with wine-5.0 (Staging) and WINEARCH=win64
Executing w_do_call d3dx9
Executing mkdir -p /home/galgreenfield/snap/leagueoflegends/common
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_d3dx9 
Executing mkdir -p /home/galgreenfield/snap/leagueoflegends/common/.cache/winetricks/directx9
Executing cd /home/galgreenfield/snap/leagueoflegends/common/.cache/winetricks/directx9
Downloading https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe to /home/galgreenfield/snap/leagueoflegends/common/.cache/winetricks/directx9
--2020-07-02 17:33:13--  https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe
Resolving download.microsoft.com (download.microsoft.com)... 95.100.196.146, 2a02:26f0:128:190::e59, 2a02:26f0:128:186::e59
Connecting to download.microsoft.com (download.microsoft.com)|95.100.196.146|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 100271992 (96M) [application/octet-stream]
Saving to: ‘directx_Jun2010_redist.exe’

directx_Jun2010_redist.exe     100%[==================================================>]  95.63M  10.3MB/s    in 9.4s    

2020-07-02 17:33:23 (10.2 MB/s) - ‘directx_Jun2010_redist.exe’ saved [100271992/100271992]

Executing cd /home/galgreenfield/Games
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp -L -F *d3dx9*x86* /home/galgreenfield/snap/leagueoflegends/common/.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/syswow64 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x86.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x86.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp -L -F *d3dx9*x64* /home/galgreenfield/snap/leagueoflegends/common/.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2005_d3dx9_25_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2006_d3dx9_30_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/apr2007_d3dx9_33_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2005_d3dx9_27_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2007_d3dx9_35_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2008_d3dx9_39_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/aug2009_d3dx9_42_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/dec2005_d3dx9_28_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/dec2006_d3dx9_32_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/feb2005_d3dx9_24_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/feb2006_d3dx9_29_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2005_d3dx9_26_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2007_d3dx9_34_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2008_d3dx9_38_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/jun2010_d3dx9_43_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/mar2008_d3dx9_37_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/mar2009_d3dx9_41_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/nov2007_d3dx9_36_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/nov2008_d3dx9_40_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Executing cabextract -q -d /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/system32 -L -F d3dx9*.dll /home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x64.cab
/home/galgreenfield/snap/leagueoflegends/common/.wine/dosdevices/c:/windows/temp/oct2006_d3dx9_31_x64.cab: WARNING; possible 5960 extra bytes at end of file.
Using native override for following DLLs: d3dx9_24 d3dx9_25 d3dx9_26 d3dx9_27 d3dx9_28 d3dx9_29 d3dx9_30
Executing wine regedit /S C:\windows\Temp\override-dll.reg
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg
Using native override for following DLLs: d3dx9_31 d3dx9_32 d3dx9_33 d3dx9_34 d3dx9_35 d3dx9_36 d3dx9_37
Executing wine regedit /S C:\windows\Temp\override-dll.reg
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg
Using native override for following DLLs: d3dx9_38 d3dx9_39 d3dx9_40 d3dx9_41 d3dx9_42 d3dx9_43
Executing wine regedit /S C:\windows\Temp\override-dll.reg
Executing wine64 regedit /S C:\windows\Temp\override-dll.reg
/snap/leagueoflegends/x1/bin/sommelier: line 431: cd: /home/galgreenfield/snap/leagueoflegends/common/.wine/drive_c/Riot Games/League of Legends: No such file or directory
wine: cannot find '/home/galgreenfield/snap/leagueoflegends/common/.wine/drive_c/Riot Games/League of Legends/LeagueClient.exe'

**Comment by GalGreenfield** [comment]
Okay, I think I got it!

The solution was to install the latest snap, and select a live server installation (e.g EUNE).
Then in the (new) client, log into a PBE account, and *the client itself* will select to download and install the PBE installation. 
I think the snap has some issue with PBE, but this method seems to work.

Please do update in the README of this repo and in the game's snap page.
