### ISSUE TITLE
Error code 9S

### ISSUE THREAD

**Issue by titirocki** [mmtrt/leagueoflegends#139]
All works fine but in the launcher, the play button display "Can't connect the LOL Servers, error code : 9S "
![Capture-dAAcran-du-2020-07-01-08-29-17-ConvertImage](https://user-images.githubusercontent.com/23188350/86212126-c6db8900-bb77-11ea-8560-afbbe4f184d1.png)
I tested on a Windows laptop connected to the same network and it works fine.
Is this a known issue ?

**Comment by m4rcus25** [comment]
yes it, you might wanna check at reddit/leagueoflinux for some trouble shooting tips. For me personally deleting the Riot Client folder under ~/snap/leagueoflegends/common/.wine/drive_c/Riot games/ worked. After youve deleted it and it worked for you, you might wanna add the folder again and restrict writing access to it. This has one caveat though , your friend list will be disabled, however you can still manually invite people to your lobby.

Hope that helped
Cheers :)

**Comment by titirocki** [comment]
Thank you for the fast reply,
Indeed, I deleted the Riot Client folder, restarted the client, and once it download the update, I have the same error :(
I will check the Reddit for some more ideas.

**Comment by m4rcus25** [comment]
Do not download the update though. Delete the folder and add a new Riot Client folder with restricted writing access so league cant update it automatically. Once you do so you will see an error pop up, click exit and then restart. I was probably a little unclear on that. (Also it worked yesterday without those extra steps)

Cheers :)

**Comment by dawidpstrak** [comment]
Restarting router (changing ip) solved this in my case

**Comment by PabloCuadros** [comment]
For me this error does not appear when I first install it... But after I restart my pc it will appear with no help. The good thing is the even the mic works more than fine on the fisrt try.

 This will happen again if I reinstall the game (by that I mean that the game will work fine before restarting my pc).
