### ISSUE TITLE
The mouse does not work within the game

### ISSUE THREAD

**Issue by tchurusca** [mmtrt/leagueoflegends#142]
As soon as the game starts, after loading the characters, the mouse does not work, the click just moves, but I cannot click to move the character, nor to buy anything. Mouse does not wor
![image](https://user-images.githubusercontent.com/67879548/86543543-0d254500-bef6-11ea-91aa-7f0eaa0f414a.png)

In the image is where the mouse does not work.

If you can help me with something I would be very grateful

**Comment by mmtrt** [comment]
try game with wine virtual desktop,

`leagueoflegends.winecfg`

**Comment by Getta91** [comment]
I had the same problem. Press Enter twice and u will get a resize of your window. Then just go in the settings and put back your resolution.
