### ISSUE TITLE
 Login only is working. The client doesn't even open.

### ISSUE THREAD

**Issue by Wanderson-Oliveira** [mmtrt/leagueoflegends#143]
When I install the first time it works, after closing the client stops working.
I can login, open the upload and close.

[System]
OS: Linux Mint 20 ulyana
Arch: x86_64
Kernel: 5.4.0-40-generic
Desktop: X-Cinnamon
Display Server: x11

[CPU]
Vendor: GenuineIntel
Model: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Physical cores: 2
Logical cores: 4

[Memory]
RAM: 7.7 GB
Swap: 2.0 GB

[Graphics]
Vendor: Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 20.0.8
OpenGL Core: 4.6 (Core Profile) Mesa 20.0.8
OpenGL ES: OpenGL ES 3.2 Mesa 20.0.8
Vulkan: Supported

**Comment by mmtrt** [comment]
try changing `windows` version to `windows 10` via `winecfg`

`leagueoflegends.winecfg`

**Comment by Wanderson-Oliveira** [comment]
> try changing `windows` version to `windows 10` via `winecfg`
> 
> `leagueoflegends.winecfg`

Sorry, but not working.... :(

**Comment by biro1557** [comment]
I have the same problem. Only, sometimes, the customer starts but does not open the game. I try to reconnect, but it doesn't work. I installed Lol Via snapd recently.

**Comment by mmtrt** [comment]
Maybe try installing drivers 32bit support see if this fixes.
 https://github.com/lutris/docs/blob/master/InstallingDrivers.md

**Comment by GalGreenfield** [comment]
My client crashes after logging in - not sure it's related to this issue or not.
It used to work just fine.
