### ISSUE TITLE
Bug old client patch10.16

### ISSUE THREAD

**Issue by GregBueno** [mmtrt/leagueoflegends#146]
Hi, 
I'm following the steps described in README to install lol in Ubuntu 18.04.
I've tried to solve the problem with issue https://github.com/mmtrt/leagueoflegends/issues/83 and https://github.com/mmtrt/leagueoflegends/issues/128
But my league of legends client still in older client version and not connect in chat.
I'm using leagueoflegends.winecfg with Windowns 10
Result of the command `snap list | grep wine`
wine-platform-5-staging          5.0.0                       7     latest/candidate  mmtrt         -
wine-platform-runtime            v1.0                        164   latest/beta       mmtrt         -

![DeepinScreenshot_select-area_20200812233927](https://user-images.githubusercontent.com/48804211/90088557-98fc6f00-dcf5-11ea-9606-d1a08a767550.png)
![DeepinScreenshot_select-area_20200812234104](https://user-images.githubusercontent.com/48804211/90088574-a154aa00-dcf5-11ea-932b-370cdb1723dc.png)

In terminal this message appers
![image](https://user-images.githubusercontent.com/48804211/90088889-7159d680-dcf6-11ea-8b1f-a101dda1d0e0.png)

**Comment by mmtrt** [comment]
Launcher shows small dialog near play button to update you could have missed it or it didn't happen to show, might take few logins or few matches to actually update though it happens randomly.

**Comment by GregBueno** [comment]
So, i should keep trying login @mmtrt ?

**Comment by mmtrt** [comment]
You can try,

**Comment by GregBueno** [comment]
I've applied all update packages..
It's very intereting.I can play with the older lancher, but doesn't load chat.
I tried to remove folder "Riot Client" in /snap/leagueoflegends/common/.wine/drive_c/Riot Games/Riot Client to generate again and the game doesn't open with new launch.

**Comment by GregBueno** [comment]
After delete folder _Riot Client_ the launch open downloading updates.
Monitoring, lol process appers. If I try to open lol again doesn't open.
I had to apply this code:
`for f in RiotClientServices.exe RiotClientCrashHandler.exe; do sudo chmod 0 "$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games/Riot Client/$f"; sudo chown root:root "$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games/Riot Client/$f"; done` 

![image](https://user-images.githubusercontent.com/48804211/90094141-8f7a0380-dd03-11ea-8a49-279b48e989e6.png)

**Comment by mmtrt** [comment]
That command will block launcher from updating to new client

**Comment by GregBueno** [comment]
I let the process running for 6 hours and lol doesn't update...

**Comment by GregBueno** [comment]
Anyone can help me ?

**Comment by henricazottes** [comment]
@GregBueno did you manage to make it work? I have the same erros:

```
000076.931| ALWAYS|            rcp-be-lol-chat| beginning job 'lol-chat.connector.reconnect' with expected delay of seconds 2 after 7.000000 seconds
000076.933| ALWAYS|            rcp-be-lol-chat| Beginning authentication with chat server
000076.935| ALWAYS|            rcp-be-lol-chat| authenticating with the chat service...
000077.187| ALWAYS|            rcp-be-lol-chat| chat connection state change : Session closed, possibly due to error (4)
000077.188|   WARN|            rcp-be-lol-chat| closed chat session with enum 'XMPP version error'
000077.190| ALWAYS|            rcp-be-lol-chat| disconnected from the chat service because 'XMPP version error'...
000077.193|   WARN|            rcp-be-lol-chat| chat session disconnected - XMPP version error
000077.195|  ERROR|            rcp-be-lol-chat| chat server authentication failed with code 3: 'XMPP version error'
```
(pasting images is bad for referencing ;))
