### ISSUE TITLE
Can't install .NET framwork for blitz.gg (Linux Mint)

### ISSUE THREAD

**Issue by xDrev** [mmtrt/leagueoflegends#147]
![dotnet](https://user-images.githubusercontent.com/70174234/91898324-2b42c380-ec61-11ea-856a-3c272a0ef25f.png)
I cant seem to get microsoft .NET framework to install. It consistently freezes at this point.

![image](https://user-images.githubusercontent.com/70174234/91898646-a7d5a200-ec61-11ea-9067-bd4fcdc99793.png)
![image](https://user-images.githubusercontent.com/70174234/91898840-f71bd280-ec61-11ea-992c-e88e3c05dbed.png)

I tried it on mint 19.3 and now again on a fresh install of mint 20.

**Comment by mmtrt** [comment]
`winetricks` isn't installing dotnet from 3 and above though I'm not sure but that's why its installing manually and failing I've tested same issue here.

**Comment by xDrev** [comment]
Is there a workaround for installing blitz?
