### ISSUE TITLE
Invalid launch

### ISSUE THREAD

**Issue by linuxninja39** [mmtrt/leagueoflegends#154]
After installing, I'm getting a windows popup that has a title of "Invalid Launch" and a message that says "We can't launch the game this way. Please launch the game directly"
![image](https://user-images.githubusercontent.com/1441674/96603383-35705e00-12b1-11eb-8c4d-3d54b3f4b50f.png)

**Comment by mmtrt** [comment]
Closing fix 2f8e889829c41de3f6b223091b11d8be60f0db0b

**Comment by linuxninja39** [comment]
Ty for fixing this so quickly! You totally rock!
