### ISSUE TITLE
Client crashes after a game

### ISSUE THREAD

**Issue by Meliot-cpu** [mmtrt/leagueoflegends#155]
As title the client stop working after I play a match I have to kill LeagueOfLegend process and restart it.
I have to do like that or is a bug?

**Comment by mmtrt** [comment]
Disable low spec mode in league client.

**Comment by Meliot-cpu** [comment]
it work for 2 or 3 games and now the client don't even open

**Comment by ParkerdeWaal** [comment]
I can confirm this is happening to me as well now -- disabling low spec mode hasn't seem to have changed anything.

**Comment by Meliot-cpu** [comment]
yeah I have to kill all the process and launch again the client

**Comment by sincomerlo** [comment]
From reddit:
You can fix this issue by manually killing the winedbg process.

**Comment by Meliot-cpu** [comment]
I read it but i can't find the process

**Comment by juanmarques** [comment]
Killing the winedbg process worked for me :D 
Tks.
