### ISSUE TITLE
all good but don't lunch client

### ISSUE THREAD

**Issue by ChtarbeRaf** [mmtrt/leagueoflegends#156]
Hello, 

I just reinstalled league of legends after uninstall because it doesn't work anymore, and it seems that I did all in a nice way, 
but when I try to lunch it, the logo LEAGUE OF LEGENDS appears but after a few seconds it desapears and nothing else shows up... any suggestions ? Have I cancelled something that I didn't have to when I tried to uninstall ? 
Thanks for yours answers ^o^

Raffaele

**Comment by mmtrt** [comment]
does launcher even shows after launching, maybe try launching client from terminal & post any useful log from there.
`snap run leagueoflegends`

**Comment by ChtarbeRaf** [comment]
(why the first paragraph is "barré" ? don't know the word in English)

**Comment by Alekc89** [comment]
For me the Riot Client shows up, but I always get this error message in the console after login:

err:rpc:I_RpcGetBuffer no binding
ALSA lib conf.c:3816:(config_file_open) cannot access file /etc/alsa/conf.d/10-samplerate.conf
ALSA lib conf.c:3736:(snd_config_hooks_call) function snd_config_hook_load returned error: No such file or directory
ALSA lib conf.c:4190:(snd_config_update_r) hooks failed, removing configuration
01f4:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
00d1:err:ole:CoUninitialize Mismatched CoUninitialize


As an effect the game just terminates.

**Comment by Alekc89** [comment]
Is there a bugfix? Is there anything to make the game start without deleting the Riot Client Folder?

**Comment by ChtarbeRaf** [comment]
Hello, what do you mean with "deleting the riot client folder" ? Is this an idea to fix this issue ? 
your problem seems a bit different from mine, because that says cannot access file /etc ...
but I don't actually know how to fix it... maybe you can try to open lol with administrator rights ? 
you have to write 
-> sudo su and type your password.
Than try ->  snap run leagueoflegends

and hope that work for you ! ;)

for me that went good, that opened installation client, that downloaded all good but as usual, the game didn't open at least. at the end i got this : **Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected**
(a lot of times) and **0086:err:module:__wine_process_init L"C:\\windows\\system32\\.exe" not found** 
and **009a:err:rpc:I_RpcGetBuffer no binding**
and **0184:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found**
etc... any idea to fix this ? 

Thanks for your time
