### ISSUE TITLE
DLL libraries not found

### ISSUE THREAD

**Issue by ghost** [mmtrt/leagueoflegends#157]
```
$ leagueoflegends
000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
0009:err:module:import_dll Library MSVCP140.dll (which is needed by L"C:\\Riot Games\\League of Legends\\LeagueClient.exe") not found
0009:err:module:import_dll Library MSVCP140.dll (which is needed by L"C:\\Riot Games\\League of Legends\\GCloudVoice.dll") not found
0009:err:module:import_dll Library GCloudVoice.dll (which is needed by L"C:\\Riot Games\\League of Legends\\LeagueClient.exe") not found
0009:err:module:import_dll Library vivoxsdk.dll (which is needed by L"C:\\Riot Games\\League of Legends\\LeagueClient.exe") not found
0009:err:module:LdrInitializeThunk Importing dlls for L"C:\\Riot Games\\League of Legends\\LeagueClient.exe" failed, status c0000135
```

Not much to say. I'm trying to install this snap for a month or two, looking everywhere I can (issues here and posts on Reddit) to resolve all the issues I stumble upon, but can't seem to make it work (almost did one day, but after one IA game, my friend list broke, and reinstalling the snap did broke the entire thing).

It's very pleasant to have someones knowing how to make this *thing* (talking about the game itself) work on Linux though

**Comment by mmtrt** [comment]
That could be broken install thats why missing dll files, try clean install after complete remove
`snap remove --purge leagueoflegends`

**Comment by TheHaricover** [comment]
I tried `snap install --edge leagueoflegends` as it's written in the "INSTALL" part of the readme but snap is telling me I must use `--devmode` or `--jailmode` so I used `snap install --devmode --edge leagueoflegends`

I let the game install itself until after the new launcher downloaded 2.1GB, it tried to start the client, I got the League of Legends logo and then it disappeared leaving me alone with this :
