### ISSUE TITLE
Doesn't open after the first time it's closed

### ISSUE THREAD

**Issue by NatoBoram** [mmtrt/leagueoflegends#16]
Once the client is closed, there are no way to open it back. Launching it from the terminal only prompts what's in #15.

**Comment by mmtrt** [comment]
sometimes game launcher does not close properly so you have to terminate from `htop` or `top` or `gnome-monitor` or any other task manager tool to close the game processes.

**Comment by NatoBoram** [comment]
Is it possible to package all dependencies inside the snap, or have scripts so the snap can download the appropriate dependencies and use them inside its confinement?

**Comment by mmtrt** [comment]
It is possible but then again other distros have differences in the packages. I'm using prebuilt packages so wine would need to be patched for different paths associated when it is built from sources. if I ship it with all the packages then again snap will need the wine deps installed on the distro in order work properly.
