### ISSUE TITLE
[libdrm/amdgpu issue]

### ISSUE THREAD

**Issue by paulohp7** [mmtrt/leagueoflegends#160]
Hello there!

After installing everything properly and doing `sudo run leagueoflegends` I got the following message:

/usr/share/libdrm/amdgpu.ids: No such file or directory

and nothing works.

Any idea about this problem?

Thanks for the snap! cya.

**Comment by TheHaricover** [comment]
I got the same issue, even if it doesn't seem (to me) to be the main issue. I found this post of snapcrafters talking about a very similar problem : https://forum.snapcraft.io/t/problem-with-libdrm-and-amdgpu-pro/9421
I don't understand everything, and will try to better understand what they mean + look at other forums/posts.

**Comment by mmtrt** [comment]
does this still happen with this change f625958bd708c4dbbab0057bc6493544bffc628c maybe update league snap.

**Comment by TheHaricover** [comment]
It seems the error is gone for me now. I still can't start league of legends but it doesn't seem to be linked to this issue.

Thank you !
