### ISSUE TITLE
Error sending 1 events to https://data.riotgames.com/collector/v2/events: 0

### ISSUE THREAD

**Issue by eddgon88** [mmtrt/leagueoflegends#161]
after install and pick the server (i play in LAN), the client shows me the following message "our servers are not available ..."

![image](https://user-images.githubusercontent.com/73730243/98849899-b21ad600-2432-11eb-98e6-c66e2e4ef94c.png)

![image](https://user-images.githubusercontent.com/73730243/98850200-26ee1000-2433-11eb-89c7-cd796e673882.png)

there is the logs:

Executing mkdir -p /home/edgar/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 8e180b094e9cde430a89ee98ca63855bfacf3479b030b9bd4fe24bbd261ee04a with wine-5.6.1.r0.g4c160ec8 ( TkG Staging Esync Fsync Vkd3d ) and WINEARCH=win64
Executing w_do_call d3dx9
Executing mkdir -p /home/edgar/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
d3dx9 already installed, skipping
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
live.la1.exe(00000009): ALWAYS| App Root: Z:/tmp
live.la1.exe(00000009): ALWAYS| Command line arguments:
    --mode
    unattended
live.la1.exe(00000009):   WARN| No version found in system.yaml, computing it. Patch version may be inaccurate
live.la1.exe(00000009):   WARN| Failed to set locale en_US because it is not supported by the install
live.la1.exe(00000009):   WARN| Failed to set locale en_US because it is not supported by the install
live.la1.exe(00000009):   WARN| Failed to set locale en_US because it is not supported by the install
live.la1.exe(00000009): ALWAYS| Splash screen initialized.
live.la1.exe(00000009): ALWAYS| Setting window size to 392x488.
live.la1.exe(00000009): ALWAYS| Keeping window hidden.
live.la1.exe(00000009): ALWAYS| Centering screen on monitor.
live.la1.exe(00000009): ALWAYS| Keeping window hidden.
live.la1.exe(00000009): ALWAYS| Successfully transitioned to new screen (not draggable).
live.la1.exe(00000009): ALWAYS| InstallRemotingServer: starting remoting server on port 43291
live.la1.exe(0000002C): ALWAYS| Starting agent
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
live.la1.exe(0000002B): ALWAYS| Connecting to https://127.0.0.1:42075
live.la1.exe(0000002B): ALWAYS| Connection succeeded!
live.la1.exe(0000002A):   WARN| HttpEventSender: Error sending 1 events to https://data.riotgames.com/collector/v2/events: 0 (HTTP response code 403, retry count 0) - 
live.la1.exe(00000009): ALWAYS| Splash screen now visible.
live.la1.exe(00000009): ALWAYS| Window visibility changed from false to true.
live.la1.exe(0000002B): ALWAYS| Connection is valid!
live.la1.exe(0000002C): ALWAYS| Agent launched and connection established
live.la1.exe(0000002C): ALWAYS| Successfully elevated installer agent.
live.la1.exe(0000002A):   WARN| HttpEventSender: Error sending 2 events to https://data.riotgames.com/collector/v2/events: 0 (HTTP response code 403, retry count 0) - 
live.la1.exe(0000002A):   WARN| HttpEventSender: Error sending 2 events to https://data.riotgames.com/collector/v2/events: 0 (HTTP response code 403, retry count 0) - 
live.la1.exe(00000009): ALWAYS| Show in taskbar changed from false to true.
live.la1.exe(00000009): ALWAYS| Setting window size to 392x488.
live.la1.exe(00000009): ALWAYS| Keeping window visible.
live.la1.exe(00000009): ALWAYS| Successfully transitioned to new screen (draggable).
live.la1.exe(00000009): ALWAYS| Received NativeScreenManager::Quit. Reason: ErrorScreen::RestartAction
live.la1.exe(00000009): ALWAYS| Finished waiting for launcher threads.
live.la1.exe(00000009): ALWAYS| UxLoop complete.
live.la1.exe(00000009): ALWAYS| InstallRemotingServer: stopping remoting server
live.la1.exe(00000009): ALWAYS| Stopping agent
live.la1.exe(00000009): ALWAYS| Restarting "Z:\tmp\live.la1.exe"
live.la1.exe(00000009): ALWAYS| Success! Exiting
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
live.la1.exe(0000002A):   WARN| HttpEventSender: Error sending 1 events to https://data.riotgames.com/collector/v2/events: 0 (HTTP response code 403, retry count 0) - 
003c:err:module:__wine_process_init L"C:\\windows\\system32\\.exe" not found

**Comment by mmtrt** [comment]
did you tried another region see if that has same issue?

**Comment by eddgon88** [comment]
yes, i tried a few days a go. But yesterday magically works. i don't do anything new.
