### ISSUE TITLE
0000:err:seh:segv_handler_early Got unexpected trap 14 during process initialization

### ISSUE THREAD

**Issue by gerstavros** [mmtrt/leagueoflegends#163]
Hello. Just tried this snap. After installing the game, client opens, downloads the game data, and after login it crashes.
Trying to run again the game from menu, it opens again the script installer to download again the lol installer etc, although it's already installed. Tried that again, it run as "repair" but crashed after login.
i run the game manually
WINEARCH=win64 WINEPREFIX=~/snap/leagueoflegends/common/.wine/ /var/lib/snapd/snap/wine-platform-5-staging/current/opt/wine-staging/bin/wine /run/media/nobody/Steam/RIOT/Riot Games/League of Legends/LeagueClient.exe and the following error appears
0000:err:seh:segv_handler_early Got unexpected trap 14 during process initialization

**Comment by mmtrt** [comment]
manual launching like that won't work, just make sure after 2.1gb download from launcher first time just close it without login account then relaunch client then login and wait for it to start.

**Comment by gerstavros** [comment]
I deleted everything, installed again the script, run it, installed game, downloaded the 2.1GB data, closed the client, after runing again the app, starts again the script for downloading the installer.
$ leagueoflegends
Executing mkdir -p /home/stalin/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please 
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 8e180b094e9cde430a89ee98ca63855bfacf3479b030b9bd4fe24bbd261ee04a with wine-5.6.1.r0.g4c160ec8 ( T
Executing w_do_call d3dx9
Executing mkdir -p /home/stalin/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please 
------------------------------------------------------
d3dx9 already installed, skipping
Gtk-Message: 14:03:25.363: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:03:25.363: Failed to load module "window-decorations-gtk-module"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"

**Comment by gerstavros** [comment]
I deleted everything, installed again the script, run it, installed game, downloaded the 2.1GB data, closed the client, after runing again the app, starts again the script for downloading the installer.
`$ leagueoflegends
Executing mkdir -p /home/stalin/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please 
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 8e180b094e9cde430a89ee98ca63855bfacf3479b030b9bd4fe24bbd261ee04a with wine-5.6.1.r0.g4c160ec8 ( T
Executing w_do_call d3dx9
Executing mkdir -p /home/stalin/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please 
------------------------------------------------------
d3dx9 already installed, skipping
Gtk-Message: 14:03:25.363: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:03:25.363: Failed to load module "window-decorations-gtk-module"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"`

**Comment by gerstavros** [comment]
I deleted everything, installed again the script, run it, installed game, downloaded the 2.1GB data, closed the client, after runing again the app, starts again the script for downloading the installer.
_$ leagueoflegends
Executing mkdir -p /home/stalin/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please 
------------------------------------------------------
Using winetricks 20200412-next - sha256sum: 8e180b094e9cde430a89ee98ca63855bfacf3479b030b9bd4fe24bbd261ee04a with wine-5.6.1.r0.g4c160ec8 ( T
Executing w_do_call d3dx9
Executing mkdir -p /home/stalin/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please 
------------------------------------------------------
d3dx9 already installed, skipping
Gtk-Message: 14:03:25.363: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:03:25.363: Failed to load module "window-decorations-gtk-module"
Fontconfig warning: "/etc/fonts/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"_

**Comment by mmtrt** [comment]
maybe should have waited for some time for client to install 2.1gb update that why it can't find leagueclient exe then asks for redownload.
