### ISSUE TITLE
Game increases cpu and ram load upon starting, stalls

### ISSUE THREAD

**Issue by Haru-Fujimura** [mmtrt/leagueoflegends#165]
Hi,

I tried to start a normal, then a custom game, and experienced this bug twice.
Upon starting the client in bash i saw:
``` ALSA lib conf.c:3816:(config_file_open) cannot access file /etc/alsa/conf.d/10-samplerate.conf
ALSA lib conf.c:3736:(snd_config_hooks_call) function snd_config_hook_load returned error: No such file or directory
ALSA lib conf.c:4190:(snd_config_update_r) hooks failed, removing configuration
00e3:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
0143:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
```

where the last line was repeated ad-infinitum.

My specs are; 
Ubuntu: Release 20.10 (Groovy Gorilla) 64-bit
Kernel Linux 5.8.0-34-generic x86_64
AMD Ryzen 7 3700X 8-Core Processor × 16 
llvmpipe (LLVM 10.0.1, 256 bits) - not recognizing Radeon RX 570 !

**Comment by mmtrt** [comment]
Try `wine-platform-runtime` from edge update channel see if it fixes not recognizing gpu issue.

**Comment by Haru-Fujimura** [comment]
Not a client bug
