### ISSUE TITLE
error when starting league of legends

### ISSUE THREAD

**Issue by paulo8448** [mmtrt/leagueoflegends#166]
game does not start shows an error screen
[backtrace.txt](https://github.com/mmtrt/leagueoflegends/files/5833898/backtrace.txt)
in the terminal he tries to install the most failed game and shows the error in wine.
![Captura de tela de 2021-01-19 02-57-07](https://user-images.githubusercontent.com/33562708/104993878-4ccefc80-5a02-11eb-9e30-7ad87140f69d.png)

Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x11002057).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:11002057 ESP:0032d5e8 EBP:0032d6e0 EFLAGS:00210246(  R- --  I  Z- -P- )
 EAX:00000000 EBX:35638000 ECX:3403ca08 EDX:fffffffc
 ESI:00000000 EDI:341180c0
Stack dump:
0x0032d5e8:  35618000 3561c000 3403ca08 3400c140
0x0032d5f8:  00000000 2760ad40 00000000 2760ad40
0x0032d608:  00000002 0032d640 11f64906 2760adf8
0x0032d618:  00000000 2760add8 2760ade0 00000000
0x0032d628:  00000000 00000000 00000000 00000000
0x0032d638:  00000000 0032d6b0 27650860 0032d690
Backtrace:
=>0 0x11002057 EntryPoint+0xffffffff() in libcef (0x0032d6e0)
  1 0x10ffd940 EntryPoint+0xffffffff() in libcef (0x0032d7ac)
  2 0x10ffd741 EntryPoint+0xffffffff() in libcef (0x0032d7f8)
  3 0x10ffe802 EntryPoint+0xffffffff() in libcef (0x0032d83c)
  4 0x11000512 EntryPoint+0xffffffff() in libcef (0x0032e694)
  5 0x11000140 EntryPoint+0xffffffff() in libcef (0x0032e804)
  6 0x10fffe1f EntryPoint+0xffffffff() in libcef (0x0032e8c4)
  7 0x10ff3cd8 EntryPoint+0xffffffff() in libcef (0x0032e934)
  8 0x10ff3210 EntryPoint+0xffffffff() in libcef (0x0032e964)
  9 0x10fd8ede EntryPoint+0xffffffff() in libcef (0x0032e97c)
  10 0x10ff58c8 EntryPoint+0xffffffff() in libcef (0x0032e998)
  11 0x10ff3409 EntryPoint+0xffffffff() in libcef (0x0032e9f4)
  12 0x10ff3a1b EntryPoint+0xffffffff() in libcef (0x0032ea38)
  13 0x10ff3ce6 EntryPoint+0xffffffff() in libcef (0x0032eaa8)
  14 0x10ff3210 EntryPoint+0xffffffff() in libcef (0x0032ead8)
  15 0x10fd8ede EntryPoint+0xffffffff() in libcef (0x0032eaf0)
  16 0x10ff58c8 EntryPoint+0xffffffff() in libcef (0x0032eb0c)
  17 0x10ff3409 EntryPoint+0xffffffff() in libcef (0x0032eb68)
  18 0x10ff3a1b EntryPoint+0xffffffff() in libcef (0x0032ebac)
  19 0x10ff3ce6 EntryPoint+0xffffffff() in libcef (0x0032ec1c)
  20 0x10ff3210 EntryPoint+0xffffffff() in libcef (0x0032ec4c)
  21 0x10fd8ede EntryPoint+0xffffffff() in libcef (0x0032ec64)
  22 0x10ff58c8 EntryPoint+0xffffffff() in libcef (0x0032ec80)
  23 0x10ff3409 EntryPoint+0xffffffff() in libcef (0x0032ecdc)
  24 0x10ff3a1b EntryPoint+0xffffffff() in libcef (0x0032ed20)
  25 0x10ff3ce6 EntryPoint+0xffffffff() in libcef (0x0032ed90)
  26 0x10ff3210 EntryPoint+0xffffffff() in libcef (0x0032edc0)
  27 0x10fd8ede EntryPoint+0xffffffff() in libcef (0x0032edd8)
  28 0x10f9ddc3 EntryPoint+0xffffffff() in libcef (0x0032ee34)
  29 0x10d0ab7a EntryPoint+0xffffffff() in libcef (0x0032ee8c)
  30 0x10d0a188 EntryPoint+0xffffffff() in libcef (0x0032ef34)
  31 0x10b8a905 EntryPoint+0xffffffff() in libcef (0x0032ef94)
  32 0x10c50ad7 EntryPoint+0xffffffff() in libcef (0x0032f008)
  33 0x10c51072 EntryPoint+0xffffffff() in libcef (0x0032f080)
  34 0x10c5196f EntryPoint+0xffffffff() in libcef (0x0032f090)
  35 0x1268cebd EntryPoint+0x7c8f65() in libcef (0x0032f154)
  36 0x101a68c5 EntryPoint+0xffffffff() in libcef (0x0032f1b0)
  37 0x114c7ade EntryPoint+0xffffffff() in libcef (0x0032f290)
  38 0x114c739d EntryPoint+0xffffffff() in libcef (0x0032f3d8)
  39 0x114c7cd5 EntryPoint+0xffffffff() in libcef (0x0032f3f8)
  40 0x101a68c5 EntryPoint+0xffffffff() in libcef (0x0032f454)
  41 0x1017283f EntryPoint+0xffffffff() in libcef (0x0032f598)
  42 0x10172243 EntryPoint+0xffffffff() in libcef (0x0032f618)
  43 0x101a80a7 EntryPoint+0xffffffff() in libcef (0x0032f63c)
  44 0x10172570 EntryPoint+0xffffffff() in libcef (0x0032f66c)
  45 0x1017252d EntryPoint+0xffffffff() in libcef (0x0032f694)
  46 0x1279abce EntryPoint+0x8d6c76() in libcef (0x0032f858)
  47 0x11ae9050 EntryPoint+0xffffffff() in libcef (0x0032f878)
  48 0x11ae8f0d EntryPoint+0xffffffff() in libcef (0x0032f8c4)
  49 0x11ae84e3 EntryPoint+0xffffffff() in libcef (0x0032f8d4)
  50 0x100a1208 EntryPoint+0xffffffff() in libcef (0x0032f9b0)
  51 0x1007330d EntryPoint+0xffffffff() in libcef (0x0032f9d4)
  52 0x006a13a7 EntryPoint+0xffffffff() in riotclientuxrender (0x0032f9f0)
  53 0x00451874 EntryPoint+0xffffffff() in riotclientuxrender (0x0032fec8)
  54 0x004539c5 EntryPoint+0xffffffff() in riotclientuxrender (0x0032ff20)
  55 0x7b451859 in kernel32 (+0x31858) (0x0032ff48)
  56 0x7b451cbf in kernel32 (+0x31cbe) (0x0032ffd8)
  57 0x7b45186a in kernel32 (+0x31869) (0x0032ffec)
0x11002057 EntryPoint+0xffffffff in libcef: movb	%al,0x00000000
Modules:
Module	Address			Debug info	Name (58 modules)
PE	  400000-  7fb000	Export          riotclientuxrender
PE	  800000-  9b7000	Deferred        ffmpeg
PE	10000000-13527000	Export          libcef
PE	7b020000-7b03c000	Deferred        kernelbase
PE	7b420000-7b5f1000	Export          kernel32
PE	7bc30000-7bc47000	Deferred        ntdll
PE	7bdc0000-7bdc4000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	7bdd0000-7bdd4000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	7bdf0000-7bdf4000	Deferred        api-ms-win-core-string-l1-1-0
PE	7be00000-7be04000	Deferred        api-ms-win-core-localization-l1-2-1
PE	7be10000-7be14000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	7be30000-7be34000	Deferred        api-ms-win-core-synch-l1-2-0
PE	7be40000-7be44000	Deferred        kerberos
PE	7be60000-7be66000	Deferred        uxtheme
PE	7c260000-7c265000	Deferred        winex11
PE	7cfc0000-7cfc5000	Deferred        bcrypt
PE	7d000000-7d048000	Deferred        crypt32
PE	7d110000-7da0c000	Deferred        shell32
PE	7db70000-7db77000	Deferred        dnsapi
PE	7dba0000-7dba7000	Deferred        iphlpapi
PE	7dbd0000-7dbd8000	Deferred        netapi32
PE	7dc10000-7dc15000	Deferred        secur32
PE	7dc60000-7dce0000	Deferred        winmm
PE	7dd30000-7dd48000	Deferred        oleacc
PE	7dd80000-7dd84000	Deferred        wtsapi32
PE	7dda0000-7dda4000	Deferred        dhcpcsvc
PE	7ddb0000-7ddbd000	Deferred        mpr
PE	7ddf0000-7de13000	Deferred        wininet
PE	7de90000-7dea4000	Deferred        urlmon
PE	7df20000-7df24000	Deferred        userenv
PE	7df40000-7df47000	Deferred        ws2_32
PE	7df80000-7df86000	Deferred        jsproxy
PE	7dfa0000-7dfa7000	Deferred        winhttp
PE	7e010000-7e01e000	Deferred        oleaut32
PE	7e120000-7e126000	Deferred        imm32
PE	7e160000-7e1b6000	Deferred        comctl32
PE	7e2a0000-7e2aa000	Deferred        aclui
PE	7e2f0000-7e31d000	Deferred        ole32
PE	7e430000-7e436000	Deferred        shcore
PE	7e460000-7e50d000	Deferred        comdlg32
PE	7e560000-7e56e000	Deferred        winspool
PE	7e5c0000-7e5d2000	Deferred        shlwapi
PE	7e620000-7e625000	Deferred        psapi
PE	7e650000-7e65e000	Deferred        gdi32
PE	7e7a0000-7e7ad000	Deferred        rpcrt4
PE	7e830000-7e849000	Deferred        setupapi
PE	7e8e0000-7e9d4000	Deferred        user32
PE	7eb00000-7eb04000	Deferred        sechost
PE	7eb40000-7eb4d000	Deferred        advapi32
PE	7eba0000-7eba4000	Deferred        usp10
PE	7ec20000-7ec48000	Deferred        ucrtbase
PE	7ed10000-7ed15000	Deferred        version
PE	7eea0000-7eea3000	Deferred        wow64cpu
PE	f7790000-f7794000	Deferred        dwrite
PE	f7950000-f7965000	Deferred        msvcrt
PE	f7b70000-f7b77000	Deferred        dbghelp
PE	f7be0000-f7be4000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	f7bf0000-f7bf4000	Deferred        api-ms-win-security-systemfunctions-l1-1-0
Threads:
process  tid      prio (all id:s are in hex)
0000000c services.exe
	00000104    0
	00000103    0
	00000022    0
	0000001f    0
	00000018    0
	00000011    0
	0000000e    0
	0000000d    0
0000000f plugplay.exe
	00000015    0
	00000014    0
	00000010    0
00000016 winedevice.exe
	0000001c    0
	0000001b    0
	0000001a    0
	00000019    0
	00000017    0
0000001d winedevice.exe
	00000023    0
	00000021    0
	00000020    0
	0000001e    0
00000024 explorer.exe
	00000028    0
	00000027    0
	00000026    0
	00000025    0
00000069 RiotClientServices.exe
	["c:/Riot Games/Riot Client/RiotClientServices.exe" --agent --agent-bootstrap --riotclient-app-port=38723 --riotclient-auth-token=oB1BCPL9riEBKi6nf1HRSg --app-root=Z:/tmp "--data-root=C:/ProgramData/Riot Games/Metadata" "--update-root=C:/ProgramData/Riot Games/Metadata/live.br/Update" "--log-root=C:/users/bulat/Local Settings/Application Data/Riot Games/live.br/Logs" "--user-data-root=C:/users/bulat/Local Settings/Application Data/Riot Games/live.br"]
	00000072    0
	00000071    0
	00000070    0
	0000006f    0
	0000006e    0
	0000006d    0
	0000006c    0
	0000006b    0
	0000006a    0
00000077 RiotClientServices.exe
	["c:/Riot Games/Riot Client/RiotClientServices.exe" --mode unattended --launch-product=league_of_legends --launch-patchline=live --force-auto-patch --region=BR --locale=pt_BR --session-id=6d4b8e01-669a-4141-bc7a-9d9cd5c44974 --install-flow --agent-pid=105 --agent-port=43805 --agent-auth-token=FoanBi-YqLt638gem2f1tw]
	000000ee    0
	000000ed    0
	000000ec    0
	000000eb    0
	000000ea    0
	000000e9    0
	000000e8    0
	000000e7    0
	000000e6    0
	000000e5    0
	000000e4    0
	000000df    0
	000000de    0
	000000dd    0
	000000dc    0
	000000d3    0
	000000d2    0
	000000d1    0
	000000d0    0
	000000cf    0
	000000ce    0
	000000cd    0
	000000cc    0
	000000cb    0
	000000c4    0
	000000bc    0
	000000ba    0
	000000b9    0
	000000b8    0
	000000b4    0
	000000b3    0
	000000b1    0
	000000b0    0
	000000af    0
	000000ae    0
	000000ad    0
	000000ac    0
	000000ab    0
	000000aa    0
	000000a9    0
	000000a8    0
	000000a7    0
	000000a6    0
	000000a5    0
	000000a4    0
	000000a3    0
	000000a2    0
	000000a1    0
	000000a0    0
	0000009f    0
	0000009e    0
	0000009d    0
	0000009c    0
	0000009b    0
	0000009a    0
	00000099    0
	0000008d    0
	0000007e    0
	0000007d    0
	0000007c    0
	0000007b    0
	0000007a    0
	00000079    0
	00000078    0
0000008e RiotClientCrashHandler.exe
	["c:\Riot Games\Riot Client\RiotClientCrashHandler.exe" --no-rate-limit "--attachment=2021-01-19T02-48-41_119_Riot_Client.0.log=C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2021-01-19T02-48-41_119_Riot Client.0.log" "--attachment=2021-01-19T02-48-41_119_Riot_Client.log=C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2021-01-19T02-48-41_119_Riot Client.log" "--attachment=__sentry-breadcrumb1=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\e54f26cc-aa59-4199-7ac3-5cea29a894fe.run\__sentry-breadcrumb1" "--attachment=__sentry-breadcrumb2=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\e54f26cc-aa59-4199-7ac3-5cea29a894fe.run\__sentry-breadcrumb2" "--attachment=__sentry-event=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\e54f26cc-aa59-4199-7ac3-5cea29a894fe.run\__sentry-event" "--database=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client" "--metrics-dir=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client" --url=https://sentry.io:443/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a --initial-client-data=0x10c,0x110,0x11c,0x108,0x120,0x14848190,0x148481a0,0x148481b0]
	00000098    0
	00000097    0
	00000095    0
	00000094    0
	00000093    0
	00000092    0
	00000091    0
	00000090    0
	0000008f    0
000000bf RiotClientUx.exe
	["c:/Riot Games/Riot Client/UX/RiotClientUx.exe" --app-port=41547 --remoting-auth-token=OSKuX6vWHo3TWrDeShlxZQ --app-pid=119 "--log-dir=C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client/Logs" "--user-data-root=C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client" "--app-root=c:/Riot Games/Riot Client" --crashpad-environment=KeystoneFoundationLiveWin]
	00000137    0
	00000136    0
	0000012a    0
	00000128    0
	00000127    0
	00000124    0
	00000123    0
	00000122    0
	00000121    0
	00000120    0
	0000011c    0
	00000115    0
	00000114    0
	00000113    0
	00000111    0
	00000110    0
	0000010f    0
	0000010e    0
	0000010d    0
	0000010c    0
	0000010b    0
	0000010a    0
	00000109    0
	00000108    0
	00000107    0
	00000106    0
	00000102    0
	00000101    0
	00000100    0
	000000ff    0
	000000fe    0
	000000fd    0
	000000fc    0
	000000f0    0
	000000c0    0
000000f1 RiotClientCrashHandler.exe
	["c:\Riot Games\Riot Client\RiotClientCrashHandler.exe" --no-rate-limit "--attachment=2021-01-19T02-48-51_191_RiotClientUx.0.log=C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/2021-01-19T02-48-51_191_RiotClientUx.0.log" "--attachment=2021-01-19T02-48-51_191_RiotClientUx.log=C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/2021-01-19T02-48-51_191_RiotClientUx.log" "--attachment=__sentry-breadcrumb1=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\247310dd-5439-458c-74b8-162c03cb921b.run\__sentry-breadcrumb1" "--attachment=__sentry-breadcrumb2=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\247310dd-5439-458c-74b8-162c03cb921b.run\__sentry-breadcrumb2" "--attachment=__sentry-event=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\247310dd-5439-458c-74b8-162c03cb921b.run\__sentry-event" "--database=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx" "--metrics-dir=C:\users\bulat\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx" --url=https://sentry.io:443/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a --initial-client-data=0xb0,0xb4,0xb8,0xac,0xbc,0x8b1eb0,0x8b1ec0,0x8b1ed0]
	000000fb    0
	000000fa    0
	000000f9    0
	000000f8    0
	000000f7    0
	000000f5    0
	000000f4    0
	000000f3    0
	000000f2    0
00000125 (D) c:\Riot Games\Riot Client\UX\RiotClientUxRender.exe
	["c:\Riot Games\Riot Client\UX\RiotClientUxRender.exe" --type=renderer --no-sandbox --disable-databases --lang=en-US --lang=en-US --log-file="C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --disable-spell-checking --enable-pinch --device-scale-factor=1 --num-raster-threads=2 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --channel="191.0.2143920091\988434247" /prefetch:1 --app-name=RiotClient --ux-name=RiotClientUx --ux-helper-name=RiotClientUxHelper --log-dir="C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/" --app-port=41547 --crashpad-environment=KeystoneFoundationLiveWin --user-data-root="C:/users/bulat/Local Settings/Application Data/Riot Games/Riot Client" --app-root="c:/Riot Games/Riot Client"]
	0000013b    0
	00000138    0
	00000135    0
	00000134    0
	00000133    0
	00000132    0
	00000131    0
	00000130    0
	0000012f    0
	0000012e    0
	0000012d    0
	0000012c    0
	00000126    0 <==
0000013c explorer.exe
	00000141    0
	00000140    0
	0000013f    0
	0000013d    0
System information:
    Wine build: wine-5.6.1.r0.g4c160ec8 ( TkG Staging Esync Fsync Vkd3d )
    Platform: i386 (WOW64)
    Version: Windows 8
    Host system: Linux
    Host version: 5.4.0-62-generic

**Comment by mmtrt** [comment]
Try again with complete remove game with purge.

`snap remove --purge leagueoflegends`
