### ISSUE TITLE
error when starting league of legends

### ISSUE THREAD

**Issue by ProbeConstructor** [mmtrt/leagueoflegends#169]
game does not start shows an error screen, this is what backtrace.txt shows: 
Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x11002057).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:11002057 ESP:0032d5e8 EBP:0032d6e0 EFLAGS:00210246(  R- --  I  Z- -P- )
 EAX:00000000 EBX:27638000 ECX:43e3ca08 EDX:fffffffc
 ESI:00000000 EDI:43f180c0
Stack dump:
0x0032d5e8:  27618000 2761c000 43e3ca08 43e0c140
0x0032d5f8:  00000000 4a40ad40 00000000 4a40ad40
0x0032d608:  00000002 0032d640 11f64906 4a40adfc
0x0032d618:  00000000 4a40addc 4a40ade0 00000000
0x0032d628:  00000000 00000000 00000000 00000000
0x0032d638:  00000000 0032d6b0 4a450860 0032d690
Backtrace:
=>0 0x11002057 EntryPoint+0xffffffff() in libcef (0x0032d6e0)
  1 0x10ffd940 EntryPoint+0xffffffff() in libcef (0x0032d7ac)
  2 0x10ffd741 EntryPoint+0xffffffff() in libcef (0x0032d7f8)
  3 0x10ffe802 EntryPoint+0xffffffff() in libcef (0x0032d83c)
  4 0x11000512 EntryPoint+0xffffffff() in libcef (0x0032e694)
  5 0x11000140 EntryPoint+0xffffffff() in libcef (0x0032e804)
  6 0x10fffe1f EntryPoint+0xffffffff() in libcef (0x0032e8c4)
  7 0x10ff3cd8 EntryPoint+0xffffffff() in libcef (0x0032e934)
  8 0x10ff3210 EntryPoint+0xffffffff() in libcef (0x0032e964)
  9 0x10fd8ede EntryPoint+0xffffffff() in libcef (0x0032e97c)
  10 0x10ff58c8 EntryPoint+0xffffffff() in libcef (0x0032e998)
  11 0x10ff3409 EntryPoint+0xffffffff() in libcef (0x0032e9f4)
  12 0x10ff3a1b EntryPoint+0xffffffff() in libcef (0x0032ea38)
  13 0x10ff3ce6 EntryPoint+0xffffffff() in libcef (0x0032eaa8)
  14 0x10ff3210 EntryPoint+0xffffffff() in libcef (0x0032ead8)
  15 0x10fd8ede EntryPoint+0xffffffff() in libcef (0x0032eaf0)
  16 0x10ff58c8 EntryPoint+0xffffffff() in libcef (0x0032eb0c)
  17 0x10ff3409 EntryPoint+0xffffffff() in libcef (0x0032eb68)
  18 0x10ff3a1b EntryPoint+0xffffffff() in libcef (0x0032ebac)
  19 0x10ff3ce6 EntryPoint+0xffffffff() in libcef (0x0032ec1c)
  20 0x10ff3210 EntryPoint+0xffffffff() in libcef (0x0032ec4c)
  21 0x10fd8ede EntryPoint+0xffffffff() in libcef (0x0032ec64)
  22 0x10ff58c8 EntryPoint+0xffffffff() in libcef (0x0032ec80)
  23 0x10ff3409 EntryPoint+0xffffffff() in libcef (0x0032ecdc)
  24 0x10ff3a1b EntryPoint+0xffffffff() in libcef (0x0032ed20)
  25 0x10ff3ce6 EntryPoint+0xffffffff() in libcef (0x0032ed90)
  26 0x10ff3210 EntryPoint+0xffffffff() in libcef (0x0032edc0)
  27 0x10fd8ede EntryPoint+0xffffffff() in libcef (0x0032edd8)
  28 0x10f9ddc3 EntryPoint+0xffffffff() in libcef (0x0032ee34)
  29 0x10d0ab7a EntryPoint+0xffffffff() in libcef (0x0032ee8c)
  30 0x10d0a188 EntryPoint+0xffffffff() in libcef (0x0032ef34)
  31 0x10b8a905 EntryPoint+0xffffffff() in libcef (0x0032ef94)
  32 0x10c50ad7 EntryPoint+0xffffffff() in libcef (0x0032f008)
  33 0x10c51072 EntryPoint+0xffffffff() in libcef (0x0032f080)
  34 0x10c5196f EntryPoint+0xffffffff() in libcef (0x0032f090)
  35 0x1268cebd EntryPoint+0x7c8f65() in libcef (0x0032f154)
  36 0x101a68c5 EntryPoint+0xffffffff() in libcef (0x0032f1b0)
  37 0x114c7ade EntryPoint+0xffffffff() in libcef (0x0032f290)
  38 0x114c739d EntryPoint+0xffffffff() in libcef (0x0032f3d8)
  39 0x114c7cd5 EntryPoint+0xffffffff() in libcef (0x0032f3f8)
  40 0x101a68c5 EntryPoint+0xffffffff() in libcef (0x0032f454)
  41 0x1017283f EntryPoint+0xffffffff() in libcef (0x0032f598)
  42 0x10172243 EntryPoint+0xffffffff() in libcef (0x0032f618)
  43 0x101a80a7 EntryPoint+0xffffffff() in libcef (0x0032f63c)
  44 0x10172570 EntryPoint+0xffffffff() in libcef (0x0032f66c)
  45 0x1017252d EntryPoint+0xffffffff() in libcef (0x0032f694)
  46 0x1279abce EntryPoint+0x8d6c76() in libcef (0x0032f858)
  47 0x11ae9050 EntryPoint+0xffffffff() in libcef (0x0032f878)
  48 0x11ae8f0d EntryPoint+0xffffffff() in libcef (0x0032f8c4)
  49 0x11ae84e3 EntryPoint+0xffffffff() in libcef (0x0032f8d4)
  50 0x100a1208 EntryPoint+0xffffffff() in libcef (0x0032f9b0)
  51 0x1007330d EntryPoint+0xffffffff() in libcef (0x0032f9d4)
  52 0x006b0547 EntryPoint+0xffffffff() in riotclientuxrender (0x0032f9f0)
  53 0x00451f14 EntryPoint+0xffffffff() in riotclientuxrender (0x0032fec8)
  54 0x00454065 EntryPoint+0xffffffff() in riotclientuxrender (0x0032ff20)
  55 0x7b451859 EntryPoint+0x7e8() in kernel32 (0x0032ff48)
  56 0x7b451cbf EntryPoint+0xc4e() in kernel32 (0x0032ffd8)
  57 0x7b45186a EntryPoint+0x7f9() in kernel32 (0x0032ffec)
0x11002057 EntryPoint+0xffffffff in libcef: movb	%al,0x00000000
Modules:
Module	Address			Debug info	Name (58 modules)
PE	  400000-  80b000	Export          riotclientuxrender
PE	  810000-  9c7000	Deferred        ffmpeg
PE	10000000-13527000	Export          libcef
PE	7b020000-7b2c8000	Deferred        kernelbase
PE	7b420000-7b719000	Dwarf           kernel32
PE	7bc30000-7beab000	Deferred        ntdll
PE	7bde0000-7bdec000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	7bdf0000-7bdfc000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	7be00000-7be0c000	Deferred        api-ms-win-core-string-l1-1-0
PE	7be20000-7be2d000	Deferred        api-ms-win-core-localization-l1-2-1
PE	7be30000-7be3c000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	7be50000-7be5d000	Deferred        api-ms-win-core-synch-l1-2-0
PE	7be60000-7be63000	Deferred        kerberos
PE	7be80000-7beff000	Deferred        uxtheme
PE	7c260000-7c264000	Deferred        winex11
PE	7cfe0000-7d01c000	Deferred        bcrypt
PE	7d010000-7d248000	Deferred        crypt32
PE	7d010000-7d248000	Deferred        secur32
PE	7d010000-7d248000	Deferred        netapi32
PE	7d010000-7d248000	Deferred        dnsapi
PE	7d010000-7d248000	Deferred        iphlpapi
PE	7d010000-7d248000	Deferred        winmm
PE	7d200000-7d349000	Deferred        oleacc
PE	7d200000-7d349000	Deferred        wtsapi32
PE	7d200000-7d349000	Deferred        dhcpcsvc
PE	7d2d0000-7d3be000	Deferred        wininet
PE	7d2d0000-7d3be000	Deferred        mpr
PE	7d430000-7d67a000	Deferred        urlmon
PE	7d430000-7d67a000	Deferred        userenv
PE	7d430000-7d67a000	Deferred        winhttp
PE	7d430000-7d67a000	Deferred        jsproxy
PE	7d430000-7d67a000	Deferred        ws2_32
PE	7d430000-7d67a000	Deferred        oleaut32
PE	7d5b0000-7d905000	Deferred        aclui
PE	7d5b0000-7d905000	Deferred        comctl32
PE	7d5b0000-7d905000	Deferred        imm32
PE	7d5b0000-7d905000	Deferred        ole32
PE	7d700000-7dac5000	Deferred        shcore
PE	7da40000-7e336000	Deferred        shell32
PE	7e460000-7e679000	Deferred        comdlg32
PE	7e460000-7e679000	Deferred        winspool
PE	7e460000-7e679000	Deferred        shlwapi
PE	7e460000-7e679000	Deferred        psapi
PE	7e460000-7e679000	Deferred        gdi32
PE	7e650000-7eaec000	Deferred        setupapi
PE	7e650000-7eaec000	Deferred        rpcrt4
PE	7e8e0000-7eeba000	Deferred        user32
PE	7e8e0000-7eeba000	Deferred        advapi32
PE	7e8e0000-7eeba000	Deferred        sechost
PE	7e8e0000-7eeba000	Deferred        version
PE	7e8e0000-7eeba000	Deferred        ucrtbase
PE	7e8e0000-7eeba000	Deferred        wow64cpu
PE	7eba0000-7ebad000	Deferred        usp10
PE	f76b0000-f76b3000	Deferred        dwrite
PE	f7750000-f7924000	Deferred        msvcrt
PE	f7990000-f7b92000	Deferred        dbghelp
PE	f7990000-f7b92000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	f7990000-f7b92000	Deferred        api-ms-win-security-systemfunctions-l1-1-0
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	000000d4    0
	00000055    0
	000000fa    0
	00000027    0
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000024    0
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000025 svchost.exe
	00000029    0
	00000028    0
	00000026    0
0000002a explorer.exe
	0000002e    0
	0000002d    0
	0000002c    0
	0000002b    0
000001f9 RiotClientServices.exe
	["c:/Riot Games/Riot Client/RiotClientServices.exe" "--rso-auth.platform=NA1" "--region=NA" "--locale=en_US" "--priority-launch-pid=499" "--priority-launch-path=C:\Riot Games\League of Legends\LeagueClient.exe" "--upgrade-install-path=C:\Riot Games\League of Legends" "--upgrade-product=league_of_legends" "--upgrade-patchline=live" "--upgrade-flow"]
	00000073    0
	0000004f    0
	00000057    0
	00000056    0
	00000053    0
	0000005b    0
	00000075    0
	00000074    0
	0000006b    0
	0000006a    0
	00000069    0
	00000070    0
	00000071    0
	0000006e    0
	0000006c    0
	00000064    0
	00000051    0
	00000050    0
	0000005f    0
	0000005e    0
	0000005d    0
	0000005c    0
	00000049    0
	0000004a    0
	00000046    0
	00000047    0
	0000004b    0
	00000048    0
	00000015    0
	00000014    0
	00000044    0
	00000201    0
	00000200    0
	000001ff    0
	000001fe    0
	000001fd    0
	000001fc    0
	000001fb    0
	000001fa    0
00000204 RiotClientCrashHandler.exe
	["c:\Riot Games\Riot Client\RiotClientCrashHandler.exe" --no-rate-limit "--attachment=2021-02-08T22-59-05_505_Riot_Client.0.log=C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2021-02-08T22-59-05_505_Riot Client.0.log" "--attachment=2021-02-08T22-59-05_505_Riot_Client.log=C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2021-02-08T22-59-05_505_Riot Client.log" "--attachment=__sentry-breadcrumb1=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\31f72e64-caeb-4597-170b-2622196dfef8.run\__sentry-breadcrumb1" "--attachment=__sentry-breadcrumb2=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\31f72e64-caeb-4597-170b-2622196dfef8.run\__sentry-breadcrumb2" "--attachment=__sentry-event=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\31f72e64-caeb-4597-170b-2622196dfef8.run\__sentry-event" "--database=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client" "--metrics-dir=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client" --url=https://sentry.io:443/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a --initial-client-data=0xe4,0xe8,0xec,0xd4,0xf0,0x1119aeb0,0x1119aec0,0x1119aed0]
	00000045    0
	0000003a    0
	00000039    0
	0000000a    0
	0000000b    0
	0000000c    0
	00000207    0
	00000206    0
	00000205    0
00000088 RiotClientUx.exe
	["c:/Riot Games/Riot Client/UX/RiotClientUx.exe" --app-port=39423 --remoting-auth-token=Gx_nDaELMBl3QvFyTNnBKg --app-pid=505 "--log-dir=C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs" "--user-data-root=C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client" "--app-root=c:/Riot Games/Riot Client" --crashpad-environment=KeystoneFoundationLiveWin]
	0000017b    0
	0000016e    0
	0000015a    0
	00000159    0
	00000156    0
	00000153    0
	00000152    0
	00000151    0
	00000150    0
	0000014e    0
	0000014d    0
	00000167    0
	000000fb    0
	000000ec    0
	00000128    0
	00000127    0
	00000126    0
	00000120    0
	0000011d    0
	0000011c    0
	0000011b    0
	0000011a    0
	00000119    0
	000000db    0
	000000dc    0
	00000111    0
	000000d3    0
	000000d5    0
	000000d2    0
	000000c9    0
	000000ca    0
	000000a7    0
	00000099    0
	0000009b    0
	00000098    0
	0000009a    0
	000000d0    0
	00000096    0
	00000089    0
00000097 RiotClientCrashHandler.exe
	["c:\Riot Games\Riot Client\RiotClientCrashHandler.exe" --no-rate-limit "--attachment=2021-02-08T22-59-13_136_RiotClientUx.0.log=C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/2021-02-08T22-59-13_136_RiotClientUx.0.log" "--attachment=2021-02-08T22-59-13_136_RiotClientUx.log=C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/2021-02-08T22-59-13_136_RiotClientUx.log" "--attachment=__sentry-breadcrumb1=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\072e4fe4-2325-435a-e24b-a8d13788e6c7.run\__sentry-breadcrumb1" "--attachment=__sentry-breadcrumb2=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\072e4fe4-2325-435a-e24b-a8d13788e6c7.run\__sentry-breadcrumb2" "--attachment=__sentry-event=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\072e4fe4-2325-435a-e24b-a8d13788e6c7.run\__sentry-event" "--database=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx" "--metrics-dir=C:\users\reloj\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx" --url=https://sentry.io:443/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a --initial-client-data=0xbc,0xc0,0xc4,0xb8,0xc8,0x8c1f10,0x8c1f20,0x8c1f30]
	000000ce    0
	000000c8    0
	000000c5    0
	00000092    0
	00000093    0
	0000009e    0
	0000009d    0
	0000009c    0
	00000094    0
0000011e RiotClientUxRender.exe
	["c:\Riot Games\Riot Client\UX\RiotClientUxRender.exe" --type=gpu-process --channel="136.0.769287111\596251272" --no-sandbox --lang=en-US --log-file="C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --supports-dual-gpus=false --gpu-driver-bug-workarounds=3,11,25,54 --gpu-vendor-id=0x0000 --gpu-device-id=0x0000 --gpu-driver-vendor --gpu-driver-version --lang=en-US --log-file="C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" /prefetch:2 --app-name=RiotClient --ux-name=RiotClientUx --ux-helper-name=RiotClientUxHelper --log-dir="C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/" --app-port=39423 --crashpad-environment=KeystoneFoundationLiveWin --user-data-root="C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client" --app-root="c:/Riot Games/Riot Client"]
	00000157    0
	00000158    0
	00000169    0
	00000168    0
	00000132    0
	0000012a    0
	00000166    0
	0000013e    0
	00000165    0
	0000014b    0
	00000109    0
	000000e2    0
	0000014c    0
	0000011f    0
00000154 (D) c:\Riot Games\Riot Client\UX\RiotClientUxRender.exe
	["c:\Riot Games\Riot Client\UX\RiotClientUxRender.exe" --type=renderer --no-sandbox --disable-databases --lang=en-US --lang=en-US --log-file="C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --disable-spell-checking --device-scale-factor=1 --num-raster-threads=2 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553 --channel="136.1.385583091\600038908" /prefetch:1 --app-name=RiotClient --ux-name=RiotClientUx --ux-helper-name=RiotClientUxHelper --log-dir="C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/" --app-port=39423 --crashpad-environment=KeystoneFoundationLiveWin --user-data-root="C:/users/reloj/Local Settings/Application Data/Riot Games/Riot Client" --app-root="c:/Riot Games/Riot Client"]
	00000178    0
	00000173    0
	0000016d    0
	00000149    0
	00000171    0
	00000170    0
	0000016c    0
	00000160    0
	00000161    0
	00000164    0
	00000163    0
	00000162    0
	0000015d    0
	0000015e    0
	00000155    0 <==
00000177 explorer.exe
	00000179    0
	0000017a    0
	00000174    0
	00000175    0
System information:
    Wine build: wine-5.6.1.r0.g4c160ec8 ( TkG Staging Esync Fsync Vkd3d )
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 5.8.0-41-generic

**Comment by RealZimboGuy** [comment]
+1
