### ISSUE TITLE
Black Screen on window exit

### ISSUE THREAD

**Issue by WarpWing** [mmtrt/leagueoflegends#170]
Hello! So I installed the snap yesterday and played it fine for 1 game which was dope. After that though, I went to switch out of windows to change my music and then I went back to the game and it just showed black with the league ingame cursor. But now when I enter the match, it just shows the black screen and it won't automatically go fullscreen therefore causing a black screen.

**Comment by VasquezLab** [comment]
The same thing happened to me, I played very well for two weeks. And now it only opens black screen, even the music is heard and the cursor is seen when it passes over a button

**Comment by rastok** [comment]
Same for me too. 
I see only the black square screen. 
However, I have been playing since April 2021 till yesterday(Aug 28)
