### ISSUE TITLE
Problem with HotKeys

### ISSUE THREAD

**Issue by davide-tonetto-884585** [mmtrt/leagueoflegends#172]
I try to change the HotKeys for the camera, but now I can't more use a hotkey to unblock the camera. I try to reset it to default but nothing changed.

**Comment by mmtrt** [comment]
try WINE virtual desktop in graphics tab see if it fixes this issue also could it be a hotkey conflicting with desktop env predefined hotkeys.

`leagueoflegends.winecfg`
