### ISSUE TITLE
Client Loses Control in Windowed Mode

### ISSUE THREAD

**Issue by Haru-Fujimura** [mmtrt/leagueoflegends#173]
Hi,

When in Windowd mode, it becomes impossible to access the game. The controls do not work and only upon relogging does it become possible to access the game window.

**Comment by mmtrt** [comment]
did you tried game with WINE virtual desktop see if it fixes this issue.

`leagueoflegends.winecfg`

**Comment by Haru-Fujimura** [comment]
no i didnt. I wasnt really interested in going that far. For now, the issue only occurs the first time the window is changed in game, but it is still problematic in windowed mode when it attempts to capture the mouse/ keyboard sometimes.
Sometimes, multiple alt-tabbing is necessary.
