### ISSUE TITLE
Client error - Mint 20.1 / Ubuntu 20.04

### ISSUE THREAD

**Issue by kaicovsky** [mmtrt/leagueoflegends#176]
![error](https://user-images.githubusercontent.com/56416998/120221517-ed38f700-c214-11eb-91fb-ec2ee41f6e4f.png)

Client doesn't even open

**Show details:**

0x126fe566 EntryPoint+0xffffffff in libcef: int	$3
Modules:
Module	Address			Debug info	Name (72 modules)
PE	  400000-  81f000	Export          riotclientuxrender
PE	  820000-  a20000	Deferred        ffmpeg
PE	 1c20000- 1cda000	Deferred        chrome_elf
PE	10000000-159c4000	Export          libcef
PE	7a840000-7a849000	Deferred        opengl32
PE	7b020000-7b03c000	Deferred        kernelbase
PE	7b420000-7b5f1000	Export          kernel32
PE	7b970000-7b974000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	7b990000-7b994000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	7b9a0000-7b9a4000	Deferred        api-ms-win-core-string-l1-1-0
PE	7b9b0000-7b9b4000	Deferred        api-ms-win-core-localization-l1-2-1
PE	7b9d0000-7b9d4000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	7b9e0000-7b9e4000	Deferred        api-ms-win-core-synch-l1-2-0
PE	7bc30000-7bc47000	Deferred        ntdll
PE	7bff0000-7bff4000	Deferred        kerberos
PE	7c370000-7c376000	Deferred        uxtheme
PE	7c960000-7c965000	Deferred        winex11
PE	7ca00000-7ca05000	Deferred        psapi
PE	7ca20000-7ca24000	Deferred        dhcpcsvc
PE	7ca30000-7ca36000	Deferred        ncrypt
PE	7ca50000-7cb2c000	Deferred        cryptui
PE	7cb80000-7cb86000	Deferred        jsproxy
PE	7cba0000-7cba7000	Deferred        winhttp
PE	7cbe0000-7cbe4000	Deferred        dxva2
PE	7cc10000-7cc15000	Deferred        d3d9
PE	7cc60000-7cc6e000	Deferred        winspool
PE	7ccb0000-7cd5d000	Deferred        comdlg32
PE	7cdb0000-7cdbd000	Deferred        mpr
PE	7cdf0000-7ce13000	Deferred        wininet
PE	7ce90000-7cea4000	Deferred        urlmon
PE	7cf20000-7cf3d000	Deferred        credui
PE	7cf60000-7cf65000	Deferred        d3d11
PE	7d010000-7d01a000	Deferred        wined3d
PE	7d170000-7d175000	Deferred        dxgi
PE	7d1b0000-7d1b4000	Deferred        dwrite
PE	7d230000-7d236000	Deferred        dwmapi
PE	7d250000-7d258000	Deferred        propsys
PE	7d270000-7d274000	Deferred        userenv
PE	7d2a0000-7d2a7000	Deferred        dbghelp
PE	7d310000-7d315000	Deferred        bcrypt
PE	7d350000-7d398000	Deferred        crypt32
PE	7d430000-7d437000	Deferred        wintrust
PE	7d470000-7d475000	Deferred        hid
PE	7d480000-7d484000	Deferred        wtsapi32
PE	7d4a0000-7d4a5000	Deferred        uiautomationcore
PE	7d4c0000-7d4d8000	Deferred        oleacc
PE	7d540000-7d547000	Deferred        dnsapi
PE	7d570000-7d578000	Deferred        netapi32
PE	7d5b0000-7d5b5000	Deferred        secur32
PE	7d610000-7d61e000	Deferred        oleaut32
PE	7d730000-7d7b0000	Deferred        winmm
PE	7d7f0000-7d7f6000	Deferred        imm32
PE	7d820000-7d824000	Deferred        usp10
PE	7d880000-7d8d6000	Deferred        comctl32
PE	7d9d0000-7d9da000	Deferred        aclui
PE	7da10000-7da3d000	Deferred        ole32
PE	7db50000-7db56000	Deferred        shcore
PE	7db90000-7db9e000	Deferred        gdi32
PE	7dcf0000-7dcfd000	Deferred        rpcrt4
PE	7dda0000-7ddc8000	Deferred        ucrtbase
PE	7de90000-7de95000	Deferred        version
PE	7deb0000-7dec9000	Deferred        setupapi
PE	7df60000-7e054000	Deferred        user32
PE	7e180000-7e192000	Deferred        shlwapi
PE	7e200000-7eafc000	Deferred        shell32
PE	7ec10000-7ec14000	Deferred        sechost
PE	7ec60000-7ec6d000	Deferred        advapi32
PE	7ecc0000-7ecc7000	Deferred        iphlpapi
PE	7ecf0000-7ecf7000	Deferred        ws2_32
PE	7eea0000-7eea3000	Deferred        wow64cpu
PE	f7b60000-f7b64000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	f7b70000-f7b74000	Deferred        api-ms-win-security-systemfunctions-l1-1-0
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	0000012e    0
	000000fc    0
	00000021    0
	0000001a    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	0000001e    0
	0000001d    0
	0000001c    0
	0000001b    0
	00000019    0
0000001f winedevice.exe
	00000024    0
	00000023    0
	00000022    0
	00000020    0
00000025 explorer.exe
	00000106    0
	00000029    0
	00000028    0
	00000027    0
	00000026    0
00000085 RiotClientServices.exe
	["c:/Riot Games/Riot Client/RiotClientServices.exe" --agent --agent-bootstrap --riotclient-app-port=46875 --riotclient-auth-token=eGbl6Q9G7cETrILJliRxpA --app-root=Z:/tmp "--data-root=C:/ProgramData/Riot Games/Metadata" "--update-root=C:/ProgramData/Riot Games/Metadata/live.br/Update" "--log-root=C:/users/kaico/Local Settings/Application Data/Riot Games/live.br/Logs" "--user-data-root=C:/users/kaico/Local Settings/Application Data/Riot Games/live.br"]
	0000008e    0
	0000008d    0
	0000008c    0
	0000008b    0
	0000008a    0
	00000089    0
	00000088    0
	00000087    0
	00000086    0
00000093 RiotClientServices.exe
	["c:/Riot Games/Riot Client/RiotClientServices.exe" --mode unattended --launch-product=league_of_legends --launch-patchline=live --force-auto-patch --region=BR --locale=pt_BR --session-id=0e95c2c3-8024-484f-b54e-18937d11608b --install-flow --agent-pid=133 --agent-port=43569 --agent-auth-token=90h9LzfjGyYmPxDLdYS0Kg]
	00000109    0
	00000107    0
	00000105    0
	000000f9    0
	000000f8    0
	000000f7    0
	000000f6    0
	000000f5    0
	000000f4    0
	000000f3    0
	000000ed    0
	000000ec    0
	000000eb    0
	000000ea    0
	000000e9    0
	000000e8    0
	000000e7    0
	000000e6    0
	000000e5    0
	000000e4    0
	000000e3    0
	000000e2    0
	000000e1    0
	000000e0    0
	000000df    0
	000000de    0
	000000dd    0
	000000dc    0
	000000db    0
	000000d6    0
	000000d5    0
	000000d4    0
	000000d3    0
	000000d1    0
	000000d0    0
	000000cf    0
	000000ce    0
	000000cd    0
	000000cc    0
	000000cb    0
	000000ca    0
	000000c9    0
	000000c8    0
	000000c7    0
	000000c6    0
	000000c5    0
	000000c4    0
	000000c3    0
	000000c2    0
	000000c1    0
	000000c0    0
	000000bf    0
	000000be    0
	000000bd    0
	000000bc    0
	000000bb    0
	000000ba    0
	000000b9    0
	000000ad    0
	0000009a    0
	00000099    0
	00000098    0
	00000097    0
	00000096    0
	00000095    0
	00000094    0
000000ae RiotClientCrashHandler.exe
	["c:\Riot Games\Riot Client\RiotClientCrashHandler.exe" --no-rate-limit "--attachment=2021-05-31T13-32-52_147_Riot_Client.0.log=C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2021-05-31T13-32-52_147_Riot Client.0.log" "--attachment=2021-05-31T13-32-52_147_Riot_Client.log=C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2021-05-31T13-32-52_147_Riot Client.log" "--attachment=__sentry-breadcrumb1=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\09903ee6-20f3-436f-8ca6-89f10025a68e.run\__sentry-breadcrumb1" "--attachment=__sentry-breadcrumb2=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\09903ee6-20f3-436f-8ca6-89f10025a68e.run\__sentry-breadcrumb2" "--attachment=__sentry-event=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\09903ee6-20f3-436f-8ca6-89f10025a68e.run\__sentry-event" "--database=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client" "--metrics-dir=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client" --url=https://sentry.io:443/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a --initial-client-data=0x114,0x118,0x11c,0x110,0x128,0x10876148,0x10876158,0x10876168]
	000000b8    0
	000000b7    0
	000000b6    0
	000000b4    0
	000000b3    0
	000000b2    0
	000000b1    0
	000000b0    0
	000000af    0
00000103 RiotClientUx.exe
	["c:/Riot Games/Riot Client/UX/RiotClientUx.exe" --app-port=46027 --remoting-auth-token=Tlc3W8iMixfhAVWfsfWP1A --app-pid=147 "--log-dir=C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs" "--user-data-root=C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client" "--app-root=c:/Riot Games/Riot Client" --crashpad-environment=KeystoneFoundationLiveWin]
	000001ab    0
	000001aa    0
	000001a9    0
	000001a8    0
	000001a7    0
	000001a4    0
	000001a3    0
	00000137    0
	00000136    0
	00000135    0
	00000134    0
	00000133    0
	00000131    0
	00000130   -2
	0000012d    0
	0000012c    0
	0000012b    0
	0000012a    0
	00000127    0
	00000126    0
	00000125    0
	00000122    0
	00000121    0
	00000120    0
	0000011f    0
	0000011e    0
	0000011c    0
	0000011b    0
	0000011a   -2
	00000119    0
	00000118    0
	00000117    0
	00000116    0
	0000010a    0
	00000104    0
0000010b RiotClientCrashHandler.exe
	["c:\Riot Games\Riot Client\RiotClientCrashHandler.exe" --no-rate-limit "--attachment=2021-05-31T13-32-57_259_RiotClientUx.0.log=C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/2021-05-31T13-32-57_259_RiotClientUx.0.log" "--attachment=2021-05-31T13-32-57_259_RiotClientUx.log=C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/2021-05-31T13-32-57_259_RiotClientUx.log" "--attachment=__sentry-breadcrumb1=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\3691f5c1-ac37-42e8-8104-b9419e06892e.run\__sentry-breadcrumb1" "--attachment=__sentry-breadcrumb2=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\3691f5c1-ac37-42e8-8104-b9419e06892e.run\__sentry-breadcrumb2" "--attachment=__sentry-event=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\3691f5c1-ac37-42e8-8104-b9419e06892e.run\__sentry-event" "--database=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx" "--metrics-dir=C:\users\kaico\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx" --url=https://sentry.io:443/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a --initial-client-data=0xb4,0xb8,0xbc,0xb0,0xc0,0x8d5df8,0x8d5e08,0x8d5e18]
	00000115    0
	00000114    0
	00000112    0
	00000111    0
	00000110    0
	0000010f    0
	0000010e    0
	0000010d    0
	0000010c    0
00000128 RiotClientUxRender.exe
	["c:\Riot Games\Riot Client\UX\RiotClientUxRender.exe" --type=gpu-process --field-trial-handle=544,11348190989089436689,17824530684961760606,131072 --disable-features=HardwareMediaKeyHandling,NetworkService --no-sandbox --log-file="C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --product-version="RiotClient/32.0.3 (CEF 74)" --lang=en-US --gpu-preferences=KAAAAAAAAADgAAAgAQAAAAAAAAAAAGAAAAAAABAAAAAIAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAFAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAQAAAAUAAAAQAAAAAAAAAAEAAAAGAAAA --log-file="C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --service-request-channel-token=14377430985138702476 --mojo-platform-channel-handle=556 /prefetch:2 --app-name=RiotClient --ux-name=RiotClientUx --ux-helper-name=RiotClientUxHelper --log-dir="C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/" --app-port=46027 --crashpad-environment=KeystoneFoundationLiveWin --user-data-root="C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client" --app-root="c:/Riot Games/Riot Client"]
	0000015c    0
	0000015b    0
	0000015a    0
	00000159    0
	00000158    0
	00000157    0
	00000156    0
	00000155   -2
	00000154    0
	00000153    0
	0000013a    0
	00000139    0
	00000138    0
	00000129    0
000001ae (D) c:\Riot Games\Riot Client\UX\RiotClientUxRender.exe
	["c:\Riot Games\Riot Client\UX\RiotClientUxRender.exe" --type=renderer --no-sandbox --autoplay-policy=no-user-gesture-required --force-device-scale-factor=1 --log-file="C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --field-trial-handle=544,11348190989089436689,17824530684961760606,131072 --disable-features=HardwareMediaKeyHandling,NetworkService --lang=en-US --log-file="C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --product-version="RiotClient/32.0.3 (CEF 74)" --disable-extensions --disable-spell-checking --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=17664567212488951046 --renderer-client-id=3 --mojo-platform-channel-handle=936 /prefetch:1 --app-name=RiotClient --ux-name=RiotClientUx --ux-helper-name=RiotClientUxHelper --log-dir="C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/" --app-port=46027 --crashpad-environment=KeystoneFoundationLiveWin --user-data-root="C:/users/kaico/Local Settings/Application Data/Riot Games/Riot Client" --app-root="c:/Riot Games/Riot Client"]
	000001cb    0
	000001c6    0
	000001c5    0
	000001c4    0
	000001c3    0
	000001c2    0
	000001c1    0
	000001c0   -2
	000001bf    0
	000001be    0
	000001bd    0
	000001bc    0
	000001bb    0
	000001ba    0
	000001b9    0
	000001b8    0
	000001b7    0
	000001b6   -2
	000001b5    0
	000001b4    0
	000001b3    0
	000001b2    0
	000001b1    0
	000001af    0 <==
000001cc explorer.exe
	000001d0    0
	000001cf    0
	000001ce    0
	000001cd    0
System information:
    Wine build: wine-5.6.1.r0.g4c160ec8 ( TkG Staging Esync Fsync Vkd3d )
    Platform: i386 (WOW64)
    Version: Windows 8
    Host system: Linux
    Host version: 5.4.0-73-generic

**Comment by kaiqueri** [comment]
when i run the command from terminal:

kaico@The-Gimp:~$ leagueoflegends
000b:err:wineboot:process_run_key **Error running cmd** L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
000000.000|   OKAY| Running from cwd 'C:\Riot Games\League of Legends'.
000000.002| ALWAYS| Application Version:11.11.377.6311 - CL:3776311 - Build Date:May 24 2021 - Build Time:16:16:05
000000.006|   OKAY| Initial working directory: "C:\Riot Games\League of Legends"
000000.008|   OKAY| Current process: "C:\Riot Games\League of Legends\LeagueClient.exe"
000000.010|   OKAY| Command line arguments:
000000.013|   OKAY| Enabling Data API Dradis collection with endpoint: https://ekg.riotgames.com/messages
000000.024| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__event
common.os_platform: Windows
common.application_name: LeagueClient
common.application_version: 11.11.377.6311
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: 4ZwPtA==
common.locale: en_US
common.os_version_major: 10
common.machine_id: U9y/s0xzIECV0E85A0WRUA==
common.os_edition: Ultimate N, x64
common.os_version_minor: 
common.region: NA
common.session_id: 918d8020-2efd-0e48-80e2-0cac8813988a
event_name: startup
crash_reporter: none
000000.037| ALWAYS| Queued Dradis event to be sent.
000000.039| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__event
common.os_platform: Windows
common.application_name: LeagueClient
common.application_version: 11.11.377.6311
common.cef_version: 74.1.19+gb62bacf+chromium-74.0.3729.157
common.installation_id: 4ZwPtA==
common.locale: en_US
common.os_version_major: 10
common.machine_id: U9y/s0xzIECV0E85A0WRUA==
common.os_edition: Ultimate N, x64
common.os_version_minor: 
common.region: NA
common.session_id: 918d8020-2efd-0e48-80e2-0cac8813988a
contents: aW5zdGFsbDoNCiAgICBnbG9iYWxzOg0KICAgICAgICBsb2NhbGU6ICJlbl9VUyINCiAgICAgICAgcmVnaW9uOiAiTkEiDQogICAgcGF0Y2hlcjoNCiAgICAgICAgY2xpZW50X21pZ3JhdGVkOiB0cnVlDQogICAgICAgIGNsaWVudF9wYXRjaGVyX2F2YWlsYWJsZTogdHJ1ZQ0KICAgICAgICBnYW1lX21pZ3JhdGVkOiB0cnVlDQogICAgICAgIGdhbWVfcGF0Y2hlcl9hdmFpbGFibGU6IHRydWUNCiAgICAgICAgdG9nZ2xlczoNCiAgICAgICAgICAgIG5ld19jbGllbnRfcGF0Y2hlcjogMA0KICAgICAgICAgICAgbmV3X2dhbWVfcGF0Y2hlcjogMA0KICAgIHRlbGVtZXRyeToNCiAgICAgICAgZnJlc2hfaW5zdGFsbGF0aW9uOiB0cnVlDQogICAgICAgIGluc3RhbGxhdGlvbl9pZDogIjRad1B0QT09Ig0K
**event_name: local_settings_load_error**
filename: C:/Riot Games/League of Legends/Config/LeagueClientSettings.yaml
**error: Error opening file: Error code 3: Path not found.**
000000.061| ALWAYS| Queued Dradis event to be sent.
000000.063| ALWAYS| Direct Launch enabled for league_of_legends.live in environment 'live' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
000000.069| ALWAYS| Found Riot Client live install (c:/Riot Games/Riot Client/RiotClientServices.exe)
000000.139|   OKAY| Launched Riot Client with process 44
000000.140| ALWAYS| Riot Client started. Exiting with the expectation of being restarted (ExitForDirectLaunch).
0072:err:rpc:I_RpcGetBuffer no binding
000006.712|   OKAY| EventCollector: 0 events remaining after thread join
000006.713|   OKAY| Shut down EventCollector in 1693 milliseconds
wine: Unhandled exception 0x80000003 in thread 11e at address 126FE566 (thread 011e), starting debugger...

**Comment by Alekc89** [comment]
I think if you click on "close" a working client respawns that randomly crashes?
