### ISSUE TITLE
Crash after login 

### ISSUE THREAD

**Issue by DixydL** [mmtrt/leagueoflegends#179]
000016.451|  ERROR|           rcp-be-lol-patch| Patchsieve - Could not fetch game download url from https://sieve.services.riotcdn.net/api/v1/products/lol/version-sets/EUN1?q[artifact_type_id]=lol-game-client&q[platform]=windows&q[published]=true, response code: 0, failure message: Shutting down, body: 
000016.460| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__patchsieve_error
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 11.17.393.0607
common.cef_version: 91.1.21+g9dd45fe+chromium-91.0.4472.114
common.installation_id: 0l+bUA==
common.locale: en_GB
common.os_version_major: 10
common.machine_id: J5KYKGgnlEeMl9Du75dKHA==
common.os_edition: Ultimate N, x64
response_code: 0
common.os_platform: Windows
common.os_version_minor: 
common.region: EUNE
common.session_id: 00ed0eca-a74c-6045-a242-d9f078531aa7
body: 
query_url: https://sieve.services.riotcdn.net/api/v1/products/lol/version-sets/EUN1?q[artifact_type_id]=lol-game-client&q[platform]=windows&q[published]=true
event_name: patchsieve_request_failed
failure_message: Shutting down
000016.468| ALWAYS| Queued Dradis event to be sent.
000016.469|   OKAY| Patcher: Started file download for URL https://lol.secure.dyn.riotcdn.net/channels/public/live-eune-win.json with ID 3 over connection 0 to server 62.140.236.144
000016.475|   OKAY|           rcp-be-lol-patch| Patcher: Cancelling log cleanup job
000016.476|   OKAY| Patcher: Cancelling download request with ID 3
000016.477|   WARN| Couldn't queue job "lol-patch.check-update" to module rcp-be-lol-patch because the module is stopped.
000016.480| ALWAYS|             Plugin Manager| Finalizing plugin rcp-be-lol-client-config
000016.482| ALWAYS|             Plugin Manager| Finalizing plugin rcp-be-lol-rso-auth
000016.483| ALWAYS|             Plugin Manager| Finalizing plugin rcp-be-client-config
000016.501| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__client_config_availability
common.application_name: LeagueClient
common.client_id: lol
totalRequests: 1
common.application_version: 11.17.393.0607
common.cef_version: 91.1.21+g9dd45fe+chromium-91.0.4472.114
common.installation_id: 0l+bUA==
common.locale: en_GB
common.os_version_major: 10
common.machine_id: J5KYKGgnlEeMl9Du75dKHA==
common.os_edition: Ultimate N, x64
common.os_platform: Windows
common.os_version_minor: 
failedRequests: 0
common.region: EUNE
common.session_id: 00ed0eca-a74c-6045-a242-d9f078531aa7
duration: 0
successfulRequests: 1
endpoint: GET /api/v1/config/
serviceScope: 
000016.507| ALWAYS| Queued Dradis event to be sent.
000016.508| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__client_config_latency
common.application_name: LeagueClient
common.client_id: lol
totalRequests: 1
common.application_version: 11.17.393.0607
common.cef_version: 91.1.21+g9dd45fe+chromium-91.0.4472.114
common.installation_id: 0l+bUA==
common.locale: en_GB
common.os_version_major: 10
common.machine_id: J5KYKGgnlEeMl9Du75dKHA==
common.os_edition: Ultimate N, x64
common.os_platform: Windows
common.os_version_minor: 
common.region: EUNE
common.session_id: 00ed0eca-a74c-6045-a242-d9f078531aa7
latencyMax: 263
duration: 0
latencyP99: 263
latencyAvg: 263
latencyP95: 263
serviceScope: 
000016.514| ALWAYS| Queued Dradis event to be sent.
000016.516| ALWAYS| Phase End - Uninitializing plugins - duration was 3821.66ms
000016.517| ALWAYS|             Plugin Manager| Closing connection to external client
000016.527| ALWAYS| Phase End - Uninit - duration was 3866.12ms
000016.531| ALWAYS| TracingAppModule stopped
000017.082|   OKAY| RemotingServer: Closing connection from 127.0.0.1:37804.
000017.093| ALWAYS| Tracing stopping
000017.094| ALWAYS| Joining tracing worker thread.
000017.177| ALWAYS|                    Tracing| Tracing worker thread exiting.
000017.178| ALWAYS| Tracing stopped
000020.009|   OKAY| EventCollector: 4 events remaining after thread join
000020.811|   OKAY| Shut down EventCollector in 801 milliseconds

**Comment by mmtrt** [comment]
Update fix released snaps.

`snap refresh`

`snap refresh --edge --devmode leagueoflegends`
