### ISSUE TITLE
PC shuts down

### ISSUE THREAD

**Issue by MRolandd** [mmtrt/leagueoflegends#18]
While in-game my PC randomly shuts down while I'm playing. Usually like 2-3 times / game. I've seen that is happening mostly during a lot of action or teamfights. Personally it shouldn't be a problem with 8 ram/ i7 and 4gb gpu nvidia. I mean it never happened on windows or in any program on linux.
EDIT: It's really at random times

**Comment by KrDimitrov** [comment]
Maybe its hardware related? If its really that random, it probably is. Check if its overheating, maybe run a stress test and see what happens.

**Comment by MRolandd** [comment]
> Maybe its hardware related? If its really that random, it probably is. Check if its overheating, maybe run a stress test and see what happens.

Well for sure it's a linux problem, or one with this LoL snap. On Windows doesn't happen at all
