### ISSUE TITLE
Client is broken due to CEF 91 update

### ISSUE THREAD

**Issue by mmtrt** [mmtrt/leagueoflegends#180]
https://www.reddit.com/r/leagueoflinux/comments/pb4wqy/did_the_upgrade_to_cef91_as_part_of_1117_break

**Comment by mmtrt** [comment]
Update: pushed fix release update to `wine-5-platform-staging` game working now.

**Comment by sofuncheung** [comment]
Hi mate, thanks for maintaining this game!

Just wanna report that after refreshing the snap, the client now launches but it's a black screen.

**Comment by mmtrt** [comment]
Install dxvk in wineprefix.

`leagueoflegends.winetricks dxvk191`

**Comment by mmtrt** [comment]
Update: fixed runtime candidate builds with build released and added dxvk install by default to league snap. Hopefully fresh install shouldn't have black client issue.

**Comment by DirkyJerky** [comment]
Working on Ubuntu, after a fresh prefix and installing 32 bit nvidia driver libraries
