### ISSUE TITLE
Black Screen in Client

### ISSUE THREAD

**Issue by GamingPLXD** [mmtrt/leagueoflegends#181]
So after login and league start up i can click in it but it's black

i've tried deleting client dir but i had the same issue

terminal output:
`WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
000000.003|   OKAY| Running from cwd 'C:\Riot Games\League of Legends'.
000000.003| ALWAYS| Application Version:11.17.393.0607 - CL:3930607 - Build Date:Aug 19 2021 - Build Time:17:22:22
000000.003|   OKAY| Initial working directory: "C:\Riot Games\League of Legends"
000000.004|   OKAY| Current process: "C:\Riot Games\League of Legends\LeagueClient.exe"
000000.004|   OKAY| Command line arguments:
000000.005|   OKAY| Enabling Data API Dradis collection with endpoint: https://ekg.riotgames.com/messages
000000.012| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__event
common.os_platform: Windows
common.application_name: LeagueClient
common.application_version: 11.17.393.0607
common.cef_version: 91.1.21+g9dd45fe+chromium-91.0.4472.114
common.installation_id: UlwZgw==
common.locale: en_GB
common.os_version_major: 10
common.machine_id: WQ6C8fInMUmbIoMUA2QwPQ==
common.os_edition: Ultimate N, x64
common.os_version_minor: 
common.region: EUNE
common.session_id: b1269c28-aece-8d45-9bb7-e1b42eaefaa1
event_name: startup
crash_reporter: crashpad
000000.012| ALWAYS| Queued Dradis event to be sent.
000000.013| ALWAYS| Direct Launch enabled for league_of_legends.live in environment 'live' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
000000.013| ALWAYS| Found associated Riot Client install (c:/Riot Games/Riot Client/RiotClientServices.exe)
000000.065|   OKAY| Launched Riot Client with process 268
000000.065| ALWAYS| Riot Client started. Exiting with the expectation of being restarted (ExitForDirectLaunch).
0224:err:rpc:I_RpcGetBuffer no binding
000005.819|   OKAY| EventCollector: 0 events remaining after thread join
000005.819|   OKAY| Shut down EventCollector in 809 milliseconds
Jakkun@localhost:~> LeagueClientUx pid: 18428
Waiting for port 46623
03dc:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
09bc:err:module:load_so_dll failed to load .so lib "/snap/leagueoflegends/91/wine-platform/wine-staging/lib/wine/d3d12.dll.so": libvkd3d.so.1: cannot open shared object file: No such file or directory`

**Comment by GamingPLXD** [comment]
btw i'm using openSUSE Tumbleweed

**Comment by mmtrt** [comment]
try this,
`snap refresh --beta wine-platform-runtime`

**Comment by GamingPLXD** [comment]
still black

**Comment by mmtrt** [comment]
@GamingPLXD https://github.com/mmtrt/leagueoflegends/issues/180#issuecomment-907626553

**Comment by GamingPLXD** [comment]
it works now

thanks!

**Comment by sofuncheung** [comment]
> it works now
> 
> thanks!

How did you solve the black screen problem mate? I refreshed with beta wine-platform-runtime and rebooted but it's still black
