### ISSUE TITLE
Vulkan / DXVK Overlay

### ISSUE THREAD

**Issue by m4rcus25** [mmtrt/leagueoflegends#183]
hello there,
So ive updated to the new version today, which works very nicely (thanks for that btw :) ).
However i get the vulkan overlay with fps counter and graphics card description in the top left and i cant seem to find a way to disable it. The only suggestions ive found were things using lutris and the official documentation. I really dont know how to access the neccessary commands though, if anyone has any suggestion on how to disable that overlay id would be greatly appreciated.
Thanks in advance :)

**Comment by mmtrt** [comment]
add `export DXVK_HUD=0` to linux environment for permanent disable `OR` run that in terminal then run `leagueoflegends` command for temporary disable.

**Comment by m4rcus25** [comment]
Thank your very much :) <3
