### ISSUE TITLE
Entering a game causes a crash

### ISSUE THREAD

**Issue by TrueNohaynicks** [mmtrt/leagueoflegends#184]
When I create a custom game, an error message appears and on the client the message to reconnect. The crash report system creates a .tmp i can't open. I can't upload the file too.

**Comment by blaisdellma** [comment]
I have a similar issue. I joined a PvP game and got through champion selection but then the game crashes and kicks me back to the client's reconnect screen. Reconnecting results in the same crash and getting kicked back to the client. I was able to get github to upload the .tmp crash log by manually changing the extension to .log
[PKM9565.log](https://github.com/mmtrt/leagueoflegends/files/7071843/PKM9565.log)

**Comment by mmtrt** [comment]
Snap now uses `dxvk` which is required for client to work still could break for some with incapable `vulkan` gpu. Make sure install required `vulkan` drivers and `vulkan` libs for both `amd64 i386`

OR 

one could disable dxvk for game main exe see https://github.com/mmtrt/leagueoflegends/issues/182

**Comment by TrueNohaynicks** [comment]
With the settings on #182 it works, but on left top corner there is a debug thing.
![imagen](https://user-images.githubusercontent.com/72631891/131252764-37992806-f120-4bb2-8e55-aa6d6e71c8d9.png)

**Comment by mmtrt** [comment]
Thats dxvk hud you can disable it see #183

**Comment by TrueNohaynicks** [comment]
I don't understand how can i change that.

**Comment by blaisdellma** [comment]
I verified that I had already installed the vulkan drivers and libraries (vulkan-icd-loader, vulkan-intel, vulkan-radeon, lib32-vulkan-icd-loader, lib32-vulkan-intel, and lib32-vulkan-radeon are installed by default on Manjaro).

I tried the fix in #182 but I'm still getting the same crash on game launch.

**Comment by mmtrt** [comment]
@blaisdellma did you install dxvk itself in wineprefix see https://github.com/mmtrt/leagueoflegends/issues/180#issuecomment-907626553

**Comment by blaisdellma** [comment]
Yes, I did.

Here's the .tmp file (changed to .log to upload to github) generated by the crash report system. I don't know how to read/decipher it though. [PKM2822.log](https://github.com/mmtrt/leagueoflegends/files/7073204/PKM2822.log)

**Comment by mmtrt** [comment]
@blaisdellma that tmp file is useless, run league from terminal `snap run leagueoflegends` should log, is this fresh install or old install before 11.17 update if yes then do fresh install also which gpu you have, is this laptop by any chance.

**Comment by blaisdellma** [comment]
Yes, this is on a Thinkpad T480 with i5-8250U and Intel UHD 620.
I did install before 11.17 and I'm going to do a fresh install now.

**Comment by blaisdellma** [comment]
Did a fresh install and now the fix works. Thanks for your help.
