### ISSUE TITLE
black client after fresh install

### ISSUE THREAD

**Issue by pabazhenov** [mmtrt/leagueoflegends#186]
Hi everyone!

Still have black screen after login. 

I saw this thread https://github.com/mmtrt/leagueoflegends/issues/180 and i did these commands (installed dxvk191 and updated wine-runtime with beta arg), but it still give me black screen. Then i did fresh install (removed snap with --purge arg and installed it again).
i dunno where i go wrong.

if i run league from terminal, game closes after login and give me this:

[pikachu@pikapika ~]$ leagueoflegends
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
fsync: up and running.
000000.002|   OKAY| Running from cwd 'C:\Riot Games\League of Legends'.
000000.002| ALWAYS| Application Version:11.17.393.0607 - CL:3930607 - Build Date:Aug 19 2021 - Build Time:17:22:22
000000.002|   OKAY| Initial working directory: "C:\Riot Games\League of Legends"
000000.003|   OKAY| Current process: "C:\Riot Games\League of Legends\LeagueClient.exe"
000000.004|   OKAY| Command line arguments:
000000.005|   OKAY| Enabling Data API Dradis collection with endpoint: https://ekg.riotgames.com/messages
000000.012| ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__event
common.os_platform: Windows
common.application_name: LeagueClient
common.application_version: 11.17.393.0607
common.cef_version: 91.1.21+g9dd45fe+chromium-91.0.4472.114
common.installation_id: KA7rJA==
common.locale: ru_RU
common.os_version_major: 7
common.machine_id: y1i/Owuf7kKH4m7rRUIJ8w==
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: RU
common.session_id: b654ab25-4eec-dd40-94f2-9e4250c82eaa
event_name: startup
crash_reporter: crashpad
000000.012| ALWAYS| Queued Dradis event to be sent.
000000.012| ALWAYS| Direct Launch enabled for league_of_legends.live in environment 'live' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
000000.013| ALWAYS| Found associated Riot Client install (c:/Riot Games/Riot Client/RiotClientServices.exe)
000000.087|   OKAY| Launched Riot Client with process 276
000000.087| ALWAYS| Riot Client started. Exiting with the expectation of being restarted (ExitForDirectLaunch).
0238:err:rpc:I_RpcGetBuffer no binding
000005.948|   OKAY| EventCollector: 0 events remaining after thread join
000005.948|   OKAY| Shut down EventCollector in 938 milliseconds
[pikachu@pikapika ~]$ MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

fixme:vkd3d_create_device: Unsupported feature level 0xc100.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

fixme:vkd3d_create_device: Unsupported feature level 0xc000.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

LeagueClientUx pid: 18781
Waiting for port 44741
05a4:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
[pikachu@pikapika ~]$ 01d0:err:ole:CoUninitialize Mismatched CoUninitialize

**Comment by mmtrt** [comment]
Which gpu you have also do you have vulkan drivers and vulkan libraries install for amd64 i386 install on system

**Comment by pabazhenov** [comment]
screenfetch output:

[pikachu@pikapika ~]$ screenfetch

 ██████████████████  ████████     pikachu@pikapika
 ██████████████████  ████████     OS: Manjaro 21.1.1 Pahvo
 ██████████████████  ████████     Kernel: x86_64 Linux 5.10.60-1-MANJARO
 ██████████████████  ████████     Uptime: 36m
 ████████            ████████     Packages: 1477
 ████████  ████████  ████████     Shell: bash 5.1.8
 ████████  ████████  ████████     Resolution: 1366x768
 ████████  ████████  ████████     DE: KDE 5.85.0 / Plasma 5.22.4
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: macOS-Dark-6.0-dark [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Mkos-Big-Sur-Night
 ████████  ████████  ████████     Disk: 337G / 1,2T (31%)
 ████████  ████████  ████████     CPU: Intel Core i3-8130U @ 4x 3.4GHz [58.0°C]
 ████████  ████████  ████████     GPU: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
                                  RAM: 3388MiB / 7852MiB

Pacman -Qe output  (bold are vulk libs):

[pikachu@pikapika ~]$ pacman -Qe
acpi 1.7-3
acpid 2.0.32-2
alsa-firmware 1.2.4-2
alsa-utils 1.2.5.1-1
android-tools 31.0.2-1
android-udev 20210501-1
apparmor 3.0.3-1
appimagelauncher 2.2.0-6
ark 21.08.0-1
avahi 0.8+20+gd1e71b3-1
b43-fwcutter 019-3
bash 5.1.008-3
bluedevil 1:5.22.4-1
btrfs-progs 5.13.1-1
bzip2 1.0.8-4
cantata 2.4.2-1
cdparanoia 10.2-8
cdrdao 1.2.4-2
clementine 1.4.0rc1+495+g10bf5dc17-4
coreutils 8.32-1
cpupower 5.13-1
crda 4.14-4
cronie 1.5.7-2
cryptsetup 2.4.0-1
device-mapper 2.03.13-1
dhclient 4.4.2.P1-1
dhcpcd 9.4.0-1
diffutils 3.8-1
discord 0.0.15-1
dmidecode 3.3-1
dmraid 1.0.0.rc16.3-13
dnsmasq 2.85-1
dolphin 21.08.0-1
dolphin-plugins 21.08.0-1
dosfstools 4.2-1
dvd+rw-tools 7.1-9
e2fsprogs 1.46.4-1
ecryptfs-utils 111-4
efibootmgr 17-2
emovix 0.9.0-8
exfat-utils 1.3.0-2
f2fs-tools 1.14.0-2
ffmpeg 2:4.4-4
ffmpegthumbs 21.08.0-1
file 5.40-5
filelight 21.08.0-1
filesystem 2021.01.19-1
findutils 4.8.0-1
firefox 91.0.2-1
fwupd 1.6.3-1
gawk 5.1.0-1
gcc-libs 11.1.0-1
gconf-sharp 2.24.4-7
gettext 0.21-1
glibc 2.33-5
gnome-icon-theme 3.12.0-6
gnome-keyring 1:40.0-1
gnome-themes-extra 3.28-2
google-chrome 92.0.4515.159-1
grep 3.6-1
grub 2.06-1
grub-theme-manjaro 20.2-12
gst-libav 1.18.4-1
gst-plugins-bad 1.18.4-11
gst-plugins-base 1.18.4-1
gst-plugins-good 1.18.4-2
gst-plugins-ugly 1.18.4-2
gtk3 1:3.24.30-2
gvfs 1.48.1-1
gvfs-afc 1.48.1-1
gvfs-gphoto2 1.48.1-1
gvfs-mtp 1.48.1-1
gvfs-nfs 1.48.1-1
gvfs-smb 1.48.1-1
gwenview 21.08.0-1
gzip 1.10-3
htop 3.0.5-1
illyria-wallpaper 1.4-1
inetutils 2.1-1
intel-ucode 20210608-1
inxi 3.3.06.1-1
iproute2 5.13.0-1
iputils 20210722-1
jfsutils 1.1.15-7
kaccounts-providers 21.08.0-1
kamera 21.08.0-1
kate 21.08.0-1
kcalc 21.08.0-1
kde-gtk-config 5.22.4-1
kdeconnect 21.08.0-1
kdegraphics-thumbnailers 21.08.0-1
kdenetwork-filesharing 21.08.0-1
kdeplasma-addons 5.22.4-1
keditbookmarks 21.08.0-1
kernel-alive 0.5-1
kfind 21.08.0-1
kgamma5 5.22.4-1
khelpcenter 21.08.0-1
khotkeys 5.22.4-1
kimageformats 5.85.0-1
kinfocenter 5.22.4-1
kio-extras 21.08.0-1
kmenuedit 5.22.4-1
konsole 21.08.0-3
konversation 21.08.0-1
kscreen 5.22.4-1
kscreenlocker 5.22.4-1
ksshaskpass 5.22.4-1
ksysguard 5.22.0-1
ksystemlog 21.08.0-1
kvantum-qt5 0.20.1-1
kwallet-pam 5.22.4-1
kwalletmanager 21.08.0-1
kwayland-integration 5.22.4-1
kwin 5.22.4-1
kwrited 5.22.4-1
less 1:590-1
lib32-libcanberra 0.30+2+gc0620e4-5
lib32-libva-intel-driver 2.4.1-1
lib32-libva-mesa-driver 21.2.1-1
lib32-libva-vdpau-driver 0.7.4-6
lib32-mesa-demos 8.4.0-2
lib32-mesa-vdpau 21.2.1-1
**lib32-vulkan-intel 21.2.1-1
lib32-vulkan-radeon 21.2.1-1**
libcanberra 0.30+2+gc0620e4-5
libdvdcss 1.4.3-1
libktorrent 21.08.0-1
libva-intel-driver 2.4.1-1
libva-mesa-driver 21.2.1-1
libva-vdpau-driver 0.7.4-5
licenses 20200427-1
linux54 5.4.142-1
linux54-virtualbox-host-modules 6.1.26-7
logrotate 3.18.1-1
lvm2 2.03.13-1
mailspring 1.9.1-1
man-db 2.9.4-2
man-pages 5.12-2
manjaro-alsa 20210109-1
manjaro-application-utility 1.3.3-5
manjaro-browser-settings 20201114-1
manjaro-documentation-en 20181009-1
manjaro-firmware 20160419-1
manjaro-hello 0.6.6-9
manjaro-hotfixes 2018.08-6
manjaro-kde-settings 20210813-2
manjaro-printer 20200215-2
manjaro-pulse 20210109-1
manjaro-release 21.1.1-1
manjaro-settings-manager-kcm 0.5.6-15
manjaro-settings-manager-knotifier 0.5.6-15
manjaro-system 20210612-1
manjaro-wallpapers-18.0 1.4-3
manjaro-zsh-config 0.20-3
mdadm 4.1-2
memtest86+ 5.31b-1
mesa-demos 8.4.0-4
mesa-vdpau 21.2.1-1
mhwd 0.6.5-2
mhwd-db 0.6.5-15
milou 5.22.4-1
mkinitcpio-openswap 0.1.0-3
mobile-broadband-provider-info 20201225-1
modemmanager 1.16.10-1
mpd 0.22.11-1
mtpfs 1.1-4
nano 5.8-1
networkmanager 1.32.10-1
networkmanager-openconnect 1.2.7dev+65+gca4187c-1
networkmanager-openvpn 1.8.14-1
networkmanager-pptp 1.2.9dev+10+gb41b0d0-4
networkmanager-vpnc 1.2.7dev+20+gdca3aea-2
nfs-utils 2.5.4-1
nobeep 1.0.0-1
noto-fonts 20201226-2
noto-fonts-cjk 20201206-2
noto-fonts-emoji 20210625-1
nss-mdns 0.15.1-1
ntfs-3g 2017.3.23-5
ntp 4.2.8.p15-1
numlockx 1.2-5
obs-studio 27.0.1-2
okular 21.08.0-1
openresolv 3.12.0-1
openshot 2.5.1-4
openssh 8.7p1-1
os-prober 1.79-1
oxygen 5.22.4-1
oxygen-icons 1:5.85.0-1
p7zip 1:17.04-1
pacman 6.0.0-2
pamac-cli 10.1.3-3
pamac-gtk 10.1.3-3
pamac-tray-icon-plasma 0.1.2-4
partitionmanager 21.08.0-1
pciutils 3.7.0-1
perl 5.34.0-2
perl-file-mimeinfo 0.30-2
phonon-qt5-gstreamer 4.10.0-2
plasma-desktop 5.22.4-1
plasma-nm 5.22.4-1
plasma-pa 5.22.4-1
plasma-simplemenu 1.0.12-1
plasma-workspace 5.22.4-3
plasma-workspace-wallpapers 5.22.4-1
poppler-data 0.4.10-1
powerdevil 5.22.4-1
powertop 2.14-1
print-manager 21.08.0-1
procps-ng 3.3.17-1
psmisc 23.4-1
pulseaudio-bluetooth 15.0-1
pulseaudio-ctl 1.70-1
pulseaudio-zeroconf 15.0-1
python-pillow 8.3.1-1
python-pip 20.3.4-1
python-pyqt5 5.15.4-1
python-pysmbc 1.0.23-2
python-reportlab 3.5.68-2
qbittorrent 4.3.7-1
qt5-imageformats 5.15.2-1
qt5-virtualkeyboard 5.15.2-1
reiserfsprogs 3.6.27-3
rsync 3.2.3-4
ruby 3.0.2-1
s-nail 14.9.22-1
samba 4.14.7-1
screenfetch 3.9.1-1
sddm 0.19.0-6
sddm-breath2-theme 1.0.18-5
sddm-kcm 5.22.4-1
seahorse 1:40.0-1
sed 4.8-1
shadow 4.8.1-4
skanlite 21.08.0-1
snapd 2.51.3-2
snapd-glib 1.54-1
spectacle 21.08.0-1
spectre-meltdown-checker 0.44-1
sshfs 3.7.2-1
steam-manjaro 1.0.0.71-1
sudo 1.9.7.p2-1
sysfsutils 2.1.1-1
system-config-printer 1.5.15-1
systemd 248.7-1
systemd-fsck-silent 239-1
systemd-kcm 1.2.1-5
systemd-sysvcompat 248.7-1
systemsettings 5.22.4-1
tar 1.34-1
teamviewer 15.21.4-1
terminus-font 4.49.1-2
texinfo 6.8-2
timeshift 20.11.1.r28.gefed117-2
tlp 1.3.1-2
transcode 1.1.7-38
ttf-dejavu 2.37+18+g9b5d1b2f-3
ttf-droid 20121017-10
ttf-inconsolata 1:3.000-3
ttf-indic-otf 0.2-11
ttf-liberation 2.1.4-1
ttf-ms-fonts 2.0-12
udiskie 2.3.3-1
udisks2 2.9.3-1
unarchiver 1.10.7-4
usb_modeswitch 2.6.1-1
usbutils 014-1
util-linux 2.37.2-1
vcdimager 2.0.1-4
vi 1:070224-5
virtualbox 6.1.26-1
**vkd3d 1.2-1**
vlc 3.0.16-3
**vulkan-intel 21.2.1-1
vulkan-radeon 21.2.1-1**
wallpapers-2018 1.2-1
wallpapers-juhraya 1.1-2
wget 1.21.1-1
which 2.21-5
wine 6.15-1
wine-gecko 2.47.2-2
wine-mono 6.3.0-1
winetricks 20210206-1
wpa_supplicant 2:2.9-8
xdg-desktop-portal 1.8.1-1
xdg-desktop-portal-kde 5.22.4-1
xdg-user-dirs 0.17-3
xdg-utils 1.1.3+19+g9816ebb-1
xf86-input-elographics 1.4.2-2
xf86-input-evdev 2.10.6-2
xf86-input-libinput 1.1.0-1
xf86-input-void 1.4.1-5
xf86-video-amdgpu 21.0.0-1
xf86-video-ati 1:19.1.0-2
xf86-video-intel 1:2.99.917+916+g31486f40-1
xf86-video-nouveau 1.0.17-1
xfsprogs 5.13.0-1
xorg-server 1.20.13-3
xorg-twm 1.0.11-1
xorg-xinit 1.4.1-3
xorg-xkill 1.0.5-2
xz 5.2.5-1
yakuake 21.08.0-1
zensu 0.3-1

**Comment by pabazhenov** [comment]
it seems dxvk 191 wasnt installed on my system as lib. At off reps there is no dxvk lib. I installed it from AUR and it helped.

**Comment by mmtrt** [comment]
You were missing vulkan loader deps as you install dxvk from aur which has vulkan loader as required pkg were install with it help fixing issue.

**Comment by pabazhenov** [comment]
Yep, it helped. Game is fine now. Thank you.
