### ISSUE TITLE
Not opening client

### ISSUE THREAD

**Issue by GeorgiPeev03** [mmtrt/leagueoflegends#188]
Hi, I've just done a fresh install of Mint 20.2 Uma and the installation and launching of LoL goes fine... up to this point. After which it simply does not launch the client itself, not even after waiting a certain amount of time, it just acts as if nothing happened. This is the point it stops at, the logo fading afterwards and nothing loading [https://imgur.com/a/Eqh2qFl](url)

**Comment by mmtrt** [comment]
Can you info about your system.

Also try installing `runtime & wine staging` snaps from beta branch if you didn't try.

**Comment by GeorgiPeev03** [comment]
> Can you info about your system.
> 
> Also try installing `wine-platform-runtime & wine-platform-5-staging` snaps from beta branch if you didn't try if it still doesn't launch then do reinstall of league snap after removing with this command.
> 
> `snap remove --purge leagueoflegends`

This is my system information, believe it should be enough to run league at the first place, the minimum reqs are 2 GB RAM (I've got 4) and 2 GHz processor (mine is 4x1.6) soo I honestly don't know. Here's the full specs if you can find something, LoL used to run on Windows some 9-10 months ago when I last played [https://termbin.com/q5zsa ](url)

I believe it automatically required me to install them when I tried to launch league. 

Yeah, I do have these snaps, after running the commands for installation I see this: [https://imgur.com/a/R4dtb46](url)

Alrighty, gonna try reinstalling

**Comment by mmtrt** [comment]
System should be able to run it. I mean refresh them if these are install,

```
sudo snap refresh --beta wine-platform-runtime
sudo snap refresh --beta wine-platform-5-staging
```

Also remove league snap data if you launch league snap before refreshing wine snaps.

`~/snap/leagueoflegends`

**Comment by GeorgiPeev03** [comment]
Alright, this time it did open, but it threw me into that same black screen the OP before me was at. And I see it hasn't really been resolved? Damn

**Comment by mmtrt** [comment]
Anything interesting in log after launching game from terminal.

`snap run leagueoflegends`


Can you post info of

`snap list | grep -e wine -e leagueoflegends`

`apt list --installed | grep -e mesa -e vulkan`

**Comment by Synaxis** [comment]
i my case i installed wine and wine32 then cd folder and sudo wine ./LeagueClient.exe

**Comment by anonwins** [comment]
> i my case i installed wine and wine32 then cd ~/snap/leagueoflegends/common/.wine/drive_c/Riot Games/League of Legends and sudo wine ./LeagueClient.exe

Which version of wine/wine32? Thanks

**Comment by fragmatyc** [comment]
:+1: for me. Had this behavior, then I uninstalled and reinstalled and now I get the black screen with nothing suspicious in the logs.

**Comment by fragmatyc** [comment]
So... just to help :

When I launch the snap, I see :
```
snap run leagueoflegends
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
```

But the login shows. When I log in, I see :
`fixme:vkd3d_create_device: Unsupported feature level 0xc100.`

Then :
```
LeagueClientUx pid: 736
Waiting for port 34513
05d0:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
```
Then I wait for... 2 - 3 minutes and get :
![image](https://user-images.githubusercontent.com/8171878/133905371-14b01306-e8d3-43c6-a8f4-edc67eb97c76.png)

and nothing else in the logs. It stays like this for ever.

Running :
```
sudo snap list | grep -e wine -e leagueoflegends
leagueoflegends          1.0                         91     latest/edge       mmtrt               devmode
wine-platform-4-staging  4.21                        37     latest/stable     mmtrt               -
wine-platform-5-stable   5.0.3                       16     latest/stable     mmtrt               -
wine-platform-5-staging  5.18                        32     latest/candidate  mmtrt               -
wine-platform-6-stable   6.0.1                       8      latest/stable     mmtrt               -
wine-platform-runtime    v1.0                        238    latest/candidate  mmtrt               -
```

And :

```
apt list --installed | grep -e mesa -e vulkan

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libegl-mesa0/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libegl1-mesa/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libegl1-mesa-dev/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libgl1-mesa-dev/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libgl1-mesa-dri/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libgl1-mesa-glx/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libglapi-mesa/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libgles2-mesa-dev/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libglu1-mesa/bionic,now 9.0.0-2.1build1 amd64 [installed,automatic]
libglu1-mesa-dev/bionic,now 9.0.0-2.1build1 amd64 [installed]
libglx-mesa0/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libosmesa6/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libvulkan1/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed,automatic]
libwayland-egl1-mesa/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
mesa-common-dev/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
mesa-va-drivers/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
mesa-vdpau-drivers/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
```

**Comment by fragmatyc** [comment]
Update
I added this
```
apt list --installed | grep -e vulkan

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libvulkan1/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed]
mesa-vulkan-drivers/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
vulkan-utils/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed]
```
And then installed dxvk-1.9.1, but it does the same thing, same output, same result.

**Comment by mmtrt** [comment]
@fragmatyc seems like your system is missing `i386` drivers & vulkan pkgs could be reason its failing.

**Comment by marceloazvedo** [comment]
I have this issue too 😞
