### ISSUE TITLE
Client doesn't open after logging in

### ISSUE THREAD

**Issue by 23scurtu** [mmtrt/leagueoflegends#189]
I was having issues with the game crashing after champ select, so I decided to completely reinstalled league snap using 

`snap remove --purge leagueoflegends`
`sudo rm -rf ~/snap/leagueoflegends`

After reinstalling, the client allows me to login, but then after loading for a while it stops loading and all riot/leage processes are gone, as if nothing happened. Running through the terminal revealed nothing out of the ordinary in the terminal log.

**Comment by mmtrt** [comment]
All processes closing after login that happens some time so try again and wait patiently for client to show up after login takes approximately 4m+.

**Comment by 23scurtu** [comment]
That doesn't work, it never shows up even after half an hour. I'm familiar with the client taking 4m+ to appear, this time it doesn't appear at all.

**Comment by Alekc89** [comment]
Wine shows this error window popup "A program on your system has crashed, but WineDbg was unable to attach to the process to obtain a backtrace"

**Comment by Alekc89** [comment]
Release:	21.10
Codename:	impish
