### ISSUE TITLE
Game freezes after game when using scaling in Kubuntu 18.04 64-bit

### ISSUE THREAD

**Issue by ryanjuza** [mmtrt/leagueoflegends#19]
Using a 4k monitor, I had scaled the game to 1600x900 in full screen mode. After a game of Nexus Blitz, the game window closed properly and went back to the client. My whole computer was at 1600x900 though, with the client hidden. I went into settings and changed it back to 3840x2160, but upon trying to interact with the client, it was frozen. Had to kill in system monitor.

**Comment by ryanjuza** [comment]
UPDATE:  Tried some alt-tabbing and minimizing/opening window and it eventually worked.

**Comment by mmtrt** [comment]
you can change screen dpi from winecfg see if that helps in scaling.

from graphics tab in winecfg change dpi.

`leagueoflegends.winecfg`
