### ISSUE TITLE
League won't open after login in

### ISSUE THREAD

**Issue by esvuv** [mmtrt/leagueoflegends#190]
After login in, riot client disappears and after waiting 3-4 minutes nothing happened. I did reinstall like 3 times(with same result).
![image](https://user-images.githubusercontent.com/90131796/132939454-d740c461-f637-4618-8d48-5274f8a27326.png)

**Comment by mmtrt** [comment]
Anything in log after launching from terminal.

`snap run leagueoflegends`

**Comment by esvuv** [comment]
> Anything in log after launching from terminal.
> 
> `snap run leagueoflegends`

same issue after this

**Comment by mmtrt** [comment]
can you post `snap list  | grep wine`.

**Comment by esvuv** [comment]
> can you post `snap list | grep wine`.

![image](https://user-images.githubusercontent.com/90131796/132945015-98080a25-e60e-41ad-8781-80c4c4e2aed4.png)

**Comment by mmtrt** [comment]
wine snap looks old revision can you update it.

`snap refresh`

 and snap purge league snap and try again installing

`snap remove --purge leagueoflegends`

**Comment by esvuv** [comment]
> wine snap looks old revision can you update it.
> 
> `snap refresh`
> 
> and snap purge league snap and try again installing
> 
> `snap remove --purge leagueoflegends`

still same issue lol

**Comment by mmtrt** [comment]
lol 😅,

Try `leagueoflegends.winetricks dxvk`

Also did you login after `180mb` and `2.9gb` update if so then you have to close client wait few minutes then relaunch.

**Comment by esvuv** [comment]
>  did you login after `180mb` and `2.9gb`

i did login after 180mb and 2.5gb update

**Comment by esvuv** [comment]
now even riot client dont work

**Comment by mmtrt** [comment]
Jeez this rito client is painfull I'll try to reproduce this issue locally.

**Comment by esvuv** [comment]
okey

**Comment by esvuv** [comment]
![image](https://user-images.githubusercontent.com/90131796/132946999-f62cb5de-b747-4059-95e1-983706d6e041.png)

**Comment by esvuv** [comment]
IT STARTED

**Comment by esvuv** [comment]
sorry for that, and thanks for help dude

**Comment by mmtrt** [comment]
Yeah no problem, it takes time to bootup client on waiting for port
