### ISSUE TITLE
Black screen on Debian10

### ISSUE THREAD

**Issue by Windows11isjustcopyoflinux** [mmtrt/leagueoflegends#196]
Hello,im have problem with LoL client is just pitch black.
Im was using leagueoflegends snap before but im reinstalled in and got this error in log:
Log:
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
fixme:vkd3d_create_device: Unsupported feature level 0xc100.
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
fixme:vkd3d_create_device: Unsupported feature level 0xc000.
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete

**Comment by mmtrt** [comment]
Can you update league snap and try again I've pushed some changes to snap.

**Comment by Windows11isjustcopyoflinux** [comment]
Thenks it worked :).
