### ISSUE TITLE
lol starts installing then disappear

### ISSUE THREAD

**Issue by dimchana** [mmtrt/leagueoflegends#198]
had typed all the commands in terminal. game has been downloaded. press install button and then the window disappears and nothing happens

**Comment by mmtrt** [comment]
Anything in log after launching it from terminal.

**Comment by dimchana** [comment]
> Anything in log after launching it from terminal.

this stuff is what i got.

**Comment by dimchana** [comment]
after the last image nothing happens and it just disappears.it doesnt even loading

**Comment by mmtrt** [comment]
Usually it takes time for launcher to show up though it could take more time if its install hdd.

**Comment by dimchana** [comment]
i think that i have already waited for too long :P

**Comment by mmtrt** [comment]
Can you post information of 

`snap list | grep -e wine -e league`

Also

`apt list --installed | grep -e vulkan -e mesa -e nvidia`

**Comment by mmtrt** [comment]
`snap run leagueoflegends` on terminal then post info.

**Comment by dimchana** [comment]
snap run leagueoflegends
Executing mkdir -p /home/georgios/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20210206-next - sha256sum: dbcb01e57092118f2e142799ae2b66c18e71537df294820a8210f4d65bf43557 with wine-5.18 ( TkG Staging Esync Fsync Vkd3d ) and WINEARCH=win64
Executing w_do_call d3dx9
Executing mkdir -p /home/georgios/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
d3dx9 already installed, skipping
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
0494:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
04b8:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
georgios@georgios-Compaq-CQ58-Notebook-PC:~$ Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected

**Comment by dimchana** [comment]
this is info from the last command

**Comment by dimchana** [comment]
snap list | grep -e wine -e league
leagueoflegends          1.0                    101    latest/edge       mmtrt       devmode
wine-platform-5-staging  5.18                   32     latest/candidate  mmtrt       -
wine-platform-runtime    v1.0                   244    latest/candidate  mmtrt       -
georgios@georgios-Compaq-CQ58-Notebook-PC:~$ apt list --installed | grep -e vulkan -e mesa -e nvidia

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libegl-mesa0/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
libegl1-mesa/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
libgl1-mesa-dri/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 i386 [installed,automatic]
libgl1-mesa-glx/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
libglapi-mesa/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 i386 [installed,automatic]
libgles2-mesa/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
libglu1-mesa/bionic,now 9.0.0-2.1build1 i386 [installed,automatic]
libglx-mesa0/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
libnvidia-cfg1-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
libnvidia-common-470/bionic,bionic,now 470.82.00-0ubuntu0.18.04.1 all [installed,automatic]
libnvidia-compute-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
libnvidia-decode-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
libnvidia-encode-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
libnvidia-extra-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
libnvidia-fbc1-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
libnvidia-gl-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
libnvidia-ifr1-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
libosmesa6/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
libvulkan1/bionic,now 1.1.126.0-2~gpu18.04.1 amd64 [installed]
libwayland-egl1-mesa/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
mesa-utils/bionic,now 8.4.0-1 amd64 [installed]
mesa-va-drivers/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
mesa-vulkan-drivers/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed,automatic]
nvidia-compute-utils-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
nvidia-dkms-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
nvidia-driver-465/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed]
nvidia-driver-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
nvidia-kernel-common-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
nvidia-kernel-source-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
nvidia-prime/bionic-updates,bionic-updates,now 0.8.16~0.18.04.1 all [installed,automatic]
nvidia-prime-applet/tricia,tricia,now 1.0.8 all [installed]
nvidia-settings/bionic,bionic-updates,bionic-security,now 470.57.01-0ubuntu0.18.04.1 amd64 [installed,automatic]
nvidia-utils-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]
xserver-xorg-video-nvidia-470/bionic,now 470.82.00-0ubuntu0.18.04.1 amd64 [installed,automatic]

**Comment by dimchana** [comment]
this is the first two commands that you told me

**Comment by mmtrt** [comment]
Ah it's laptop with nvidia, did you tried launching from league nvidia optimus startmenu entry.

**Comment by mmtrt** [comment]
I'm not seeing nvidia driver i386 pkgs that could cause issues.

**Comment by dimchana** [comment]
is wine somehow connected to this problem?

**Comment by mmtrt** [comment]
I'll try to reproduce this issue though could take time b/c I'm reinstalling linux on my system.

Luckily I've Nvidia gpu I'll test.

**Comment by dimchana** [comment]
p install wine-platform-5-staging
[sudo] password for georgios:
Reading Lists of Packages ... Completed
Construction of a Dependency Tree
Read a description of the current situation ... Completed
The wine package is virtual and is provided by:
   wine-development 3.6-1
   winehq-stable 4.0 ~ bionic
You need to choose one for installation.

E: The wine package does not have a candidate installation
E: Unable to locate the winetrickssnap package
E: Unable to locate the install package
E: Unable to locate the wine-platform-5-staging package
georgios @ georgios-Compaq-CQ58-Notebook-PC: ~ $

**Comment by mmtrt** [comment]
It could be anything drivers, wine, game's recent patch changes, snapd changes or it's update, or my recent snap changes.

Thing is I don't play lol anymore it was long ago due to frequent electricity blackouts (third world country). I only have installed it due to this snap, I'll move gamedata and fresh install for reproducing the issue.

**Comment by dimchana** [comment]
thnxx

**Comment by mmtrt** [comment]
You could try lutris in the mean time.

**Comment by dimchana** [comment]
i tried again lutris right now(because yesterday didnt install the game) . after your commands its fine with lutris. thank youuuuuu. you can close the topic

**Comment by dimchana** [comment]
![Uploading Στιγμιότυπο από 2021-11-04 18-02-29.png…]()

**Comment by dimchana** [comment]
![Στιγμιότυπο από 2021-11-04 18-02-29](https://user-images.githubusercontent.com/93720088/140375351-e22e2dd9-d785-4888-8caf-b61c1350723a.png)

**Comment by dimchana** [comment]
image freezed here

**Comment by dimchana** [comment]
![Στιγμιότυπο από 2021-11-04 18-04-39](https://user-images.githubusercontent.com/93720088/140375572-5cd2ab86-5d88-42a2-a2f9-c0affa9f757c.png)

**Comment by dimchana** [comment]
now i cant even find it to open it hahhah

**Comment by dimchana** [comment]
![Στιγμιότυπο από 2021-11-04 18-29-46](https://user-images.githubusercontent.com/93720088/140379800-550b7df4-8a12-494c-bcfb-06f829aa59a7.png)

**Comment by Alekc89** [comment]
During the installation for me the client also did not show up but I observed that my internet downloaded something very fast. If you have a huge downstream, it is a sign that the installation works. Just be patient.
