### ISSUE TITLE
Fullscreen window doesn't close after leaving the game

### ISSUE THREAD

**Issue by Soulthym** [mmtrt/leagueoflegends#20]
I tried to close a custom game after a few seconds (was testing my fps for my graphics card config) and the gaming window didn't close

**Comment by loysollivier** [comment]
Same here. Can you provide debugging steps @mmtrt ?

**Comment by mmtrt** [comment]
@loysollivier provide logs from terminal after launching game from terminal and when that happens. Also can you provide info of the system, like graphic drivers, have dual gpu or have many monitors used??

**Comment by loysollivier** [comment]
Could you tell me how to launch the game from terminal ?

System:
- Laptop: Razer Blade TX
- NVIDIA GeForce RTX 2070
- Ubuntu 16.04 up-to-date
- External display on HDMI (laptop display disabled)

I will try and launch it without the second monitor too.

**Comment by mmtrt** [comment]
by typing `snap run leagueoflegends`
