### ISSUE TITLE
snap  wine-platform-5-staging error

### ISSUE THREAD

**Issue by spacelegolas** [mmtrt/leagueoflegends#201]
Hello team,

I just tried to install LoL via snap and this is the result.
I cannot find anything on this..

"
You need to update wine-platform-5-staging snap.

Which has league patched wine-staging

You can do this with command:
snap refresh --candidate wine-platform-5-staging

Unable to init server: Could not connect: Connection refused

(yad:69638): Gtk-WARNING **: 23:27:11.594: cannot open display: 
kindrobot@darkroom:~$ snap refresh --candidate wine-platform-5-stagin
snap "wine-platform-5-stagin" is not installed
kindrobot@darkroom:~$ snap install wine-platform-5-staging
snap "wine-platform-5-staging" is already installed, see 'snap help
       refresh'
kindrobot@darkroom:~$ snap refresh --candidate wine-platform-5-staging
error: cannot refresh "wine-platform-5-staging": cannot query the store for
       updates: got unexpected HTTP status code 408 via POST to
       "https://api.snapcraft.io/v2/snaps/refresh"
"
kindrobot@darkroom:~$ snap version
snap    2.52.1
snapd   2.52.1
series  16
ubuntu  21.04
kernel  5.11.0-40-generic

**Comment by mmtrt** [comment]
It literally says you have to update wine snap anyway use these two commands to update required snaps for league.

```
snap refresh --candidate wine-platform-runtime
snap refresh --candidate wine-platform-5-staging
```

**Comment by spacelegolas** [comment]
snap refresh --candidate wine-platform-5-staging
error: cannot refresh "wine-platform-5-staging": cannot query the store for
updates: got unexpected HTTP status code 408 via POST to
"https://api.snapcraft.io/v2/snaps/refresh"

This happened. I cannot update it.
