### ISSUE TITLE
How to remove the vulkan driver fps HUD overlay?

### ISSUE THREAD

**Issue by Alekc89** [mmtrt/leagueoflegends#202]
I found this info on [reddit](https://www.reddit.com/r/leagueoflinux/comments/c9zgej/how_do_i_remove_the_video_card_driver_vulkan_fps/):

`"you're probably using a launcher script, see if the line 'export DXVK_HUD=1' is in there, if it is, delete it."
`

Do I need to set a system variable on my system or does this come with the snap's league of legends launcher?

**Comment by mmtrt** [comment]
See https://github.com/mmtrt/leagueoflegends/issues/183#issuecomment-907680906
