### ISSUE TITLE
 Quick launch

### ISSUE THREAD

**Issue by ParkerdeWaal** [mmtrt/leagueoflegends#205]
Seems that a somewhat hacky solution to the long load time problem has been posted over to Reddit https://www.reddit.com/r/leagueoflinux/comments/srn0wt/future_is_now/

Might be worth incorporating this into the snap release.

**Comment by mmtrt** [comment]
This should be fixed now with current revisions of snap required.

**Comment by Gedally** [comment]
thanks [FakedCake](https://www.reddit.com/user/FakedCake/) @mmtrt  @ParkerdeWaal  works like a charm :tada:

**Comment by mmtrt** [comment]
@Gedally well I'm not using these scripts at all but recent wine [patch](https://www.reddit.com/r/leagueoflinux/comments/ubqwyk/comment/i6aj8bg/) which fixes delay issue.

**Comment by Gedally** [comment]
@mmtrt then take it as a general thank you (and all the others that contribute) that everything works as it does.

**Comment by mmtrt** [comment]
Yeah thanks and thanks to everyone helping linux community for fixing league issues, sure it took time but we got it done in the end.
