### ISSUE TITLE
Cannot launch game - Failed to load libGL

### ISSUE THREAD

**Issue by half-shell** [mmtrt/leagueoflegends#208]
Hello,

First of all, thank you for maintaining this package and helping out for arising issues.

## Description
The issue I am having is when trying to launch a game. All things related to the game client itself are fine, everything works seamlessly.

However, when trying to launch a game, I end up with a wine error with the message:
`Could not Initialize Graphics Device`
![image](https://user-images.githubusercontent.com/13107199/172009035-59b4ed8f-5101-4277-9d4e-c5c14429a0cb.png)

Looking at the logs, it seems that there's an issue over the version of of `glibc`, where the wine-runtime seems to want to reach for `glibc=2.34`.

Looking at my current version, it seems that I have `glibc=2.35`. Looking at downgrading, it seems that my distro (Archlinux) never had that version in their [package repos](https://archive.archlinux.org/packages/g/glibc/), and even then, it is the first time this issue pops up.

**EDIT**: It seems that even those logs get to pop _before_ the game tries to launch. So it might not even be related. Do you have any way of getting wine logs for a deeper dive?

## Logs
```
2022/06/04 16:49:40.609070 cmd_run.go:597: WARNING: XAUTHORITY environment value is not a clean path: "/home/brick/.Xauthority"
01f8:err:rpc:I_RpcGetBuffer no binding
02e0:err:wgl:init_opengl Failed to load libGL: /snap/leagueoflegends/127/wine-runtime/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl32/libGLdispatch.so.0)
02e0:err:wgl:init_opengl OpenGL support is disabled.
067c:err:wgl:init_opengl Failed to load libGL: /snap/leagueoflegends/127/wine-runtime/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl32/libGLdispatch.so.0)
067c:err:wgl:init_opengl OpenGL support is disabled.
0718:err:wgl:init_opengl Failed to load libGL: /snap/leagueoflegends/127/wine-runtime/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl32/libGLdispatch.so.0)
0718:err:wgl:init_opengl OpenGL support is disabled.
0788:err:wgl:init_opengl Failed to load libGL: /snap/leagueoflegends/127/wine-runtime/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl32/libGLdispatch.so.0)
0788:err:wgl:init_opengl OpenGL support is disabled.
07c4:err:wgl:init_opengl Failed to load libGL: /snap/leagueoflegends/127/wine-runtime/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl32/libGLdispatch.so.0)
07c4:err:wgl:init_opengl OpenGL support is disabled.
07ac:err:wgl:init_opengl Failed to load libGL: /snap/leagueoflegends/127/wine-runtime/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /var/lib/snapd/lib/gl32/libGLdispatch.so.0)
07ac:err:wgl:init_opengl OpenGL support is disabled.
```
------ 
I can't really wrap my head around what is really going on here, and hope that you'd be able to provide some insight as to what the issue actually is.

If I'm understanding correctly, the wine-runtime is trying to use my local `glibc` lib?
Or does it have its own version of it?

Do you have any idea of what I could try to fix this issue?

I also tried changing windows' version through `snap run leagueoflegends.winecfg`, as well as disabling/enabling usage of DX9 through league of legends' settings.

**Comment by mmtrt** [comment]
Which gpu you have and drivers.

**Comment by nbeny** [comment]
same issue

```
0168:err:winediag:WS_getaddrinfo Failed to resolve your host name IP
021c:err:rpc:I_RpcGetBuffer no binding
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
0654:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
06d0:err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x10150
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
10f4:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

Which gpu you have and drivers.
which command can get you the result of gpu and drivers ?

**Comment by EternalRisen** [comment]
@nbeny I have the same issue on my laptop, the workaround was using [Optimus Manager](https://github.com/Askannz/optimus-manager) for laptops with nvidia optimus, unsure if using `snap run leagueoflegends.leagueoflegendsnv` will work or not, but I do know the former worked for me

**Comment by half-shell** [comment]
Sorry for not getting back to you @mmtrt @EternalRisen. It solved "on itself" after an update and I forgot to close this issue.

I'll do that now.
