### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by M1ck0** [mmtrt/leagueoflegends#209]
This is the only error I get in console when I start game with `leagueoflegends`
```
...
10c0:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
10c0:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
10c0:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
10c0:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1104:err:x11settings:X11DRV_Settings_AddOneMode Maximum modes (8) exceeded
1150:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
```
Client runs, I can select champion and everything, it presents black screen when that game loads. Only black screen with in game mouse cursor.

Game is updated to the latest version, this issue started few days ago.

I am playing on Arch Linux

**Comment by mmtrt** [comment]
Did you install dxvk if not then try.

`snap run leagueoflegends.winetricks dxvk`

**Comment by M1ck0** [comment]
Yes. I get this message with that command `dxvk already installed, skipping`.

I was able to play league for few days, and then this happened.

**Comment by mmtrt** [comment]
Could be new game update broke it again I'll retest locally.

**Comment by mmtrt** [comment]
Also try removing `dxgi` dlloverride from winecfg.

**Comment by M1ck0** [comment]
I removed `dxgi` already. Only thing left is reinstalling the game

**Comment by M1ck0** [comment]
I am currently reinstalling the game, and I'll get back with te results.

**Comment by EternalRisen** [comment]
I can at least confirm on my end that removing dxgi worked, at least with being able to launch the game client

**Comment by EternalRisen** [comment]
though I do get a failure to initialize graphics engine when I enter a game...

**Comment by M1ck0** [comment]
removing `dxgi` does get me into the client, but I still can't access anything after champion selection. Tried with and without optimus.

**Comment by mmtrt** [comment]
Try this see if this fixes blackscreen issue.

```
export DXVK_STATE_CACHE=0

snap run leagueoflegends

```

**Comment by EternalRisen** [comment]
What fixed it for me was also check marking DX9 legacy mode, could be something with the current DX and league, however freezing at the 6-10 minute mark still happens, not really an issue though tbh

**Comment by EternalRisen** [comment]
@mmtrt do you think it might work better if you were to use steam proton instead of just wine itself?

**Comment by mmtrt** [comment]
@EternalRisen we are using old wine src where last league libc changes work not sure that old wine src could work with proton.

**Comment by EternalRisen** [comment]
I have proton-ge installed from the AUR and was able to successfully initiate the client with no issues so far

**Comment by EternalRisen** [comment]
I'd say with how far steam compatibility has come, especially with the steam deck, there definitely has been some improvements

**Comment by M1ck0** [comment]
> Try this see if this fixes blackscreen issue.

```
export DXVK_STATE_CACHE=0

snap run leagueoflegends
```


This resolved my issue, I can play the game, it just freezes once between 7-8 minutes in-game, but only for a few seconds so it's not a big deal. Thank you @mmtrt

**Comment by mmtrt** [comment]
added changes to snap now no longer need to manually do that.
