### ISSUE TITLE
Switchable graphics

### ISSUE THREAD

**Issue by Soulthym** [mmtrt/leagueoflegends#21]
Alright so this isn't really a bug, more like a feature request or asking for a tip.
I game on my laptop, so I use bumblebee(under Arch but that shouldn't really matter).
Thus to use my Nvidia graphics cards, I usually type `optirun` before the command.
Is there a way to add custom startup commands to run the game?

**Comment by iamkucuk** [comment]
What is the progress regarding this problem?

**Comment by Soulthym** [comment]
@iamkucuk it seemed to work, or at least to not break my setup, but I didn't have time to test it well. I won't have said laptop for another month so I cannot test any further.
Will try again when I can and report on it. In the mean time maybe you can try for yourself and see if it works?

**Comment by iamkucuk** [comment]
Just tried for a brief period of time.

`Primusrun leagueoflegends` command seems not to working as desired. Game opens, gpu switches for a brief time but after that it switches back again.

`optirun leagueoflegends` command seems to switch successfully. A noticable improvement of FPS count. Seems like breaks audio.

**Comment by Soulthym** [comment]
I don't know why the audio would do that, but it's good to know that the GPU works with optirun (since it was the feature I asked for). I think there might be something in settings for audio, I really am not sure why it does this.

**Comment by iamkucuk** [comment]
> I don't know why the audio would do that, but it's good to know that the GPU works with optirun (since it was the feature I asked for). I think there might be something in settings for audio, I really am not sure why it does this.

How can I manipulate the wine settings for a snap package like this one?
