### ISSUE TITLE
How to activate virtual desktop for wine installed with snap?

### ISSUE THREAD

**Issue by Mk-arc** [mmtrt/leagueoflegends#213]
Usually I would just run "winecfg" and activate virtual desktop. Not sure how it works with this installation?

**Comment by mmtrt** [comment]
`leagueoflegends.winecfg`

**Comment by Mk-arc** [comment]
ah yes. It works :) thanks! I will close this issue.

Btw. Everything in game works just fine, thanks for this repo!
