### ISSUE TITLE
The launcher launches but the game does not start

### ISSUE THREAD

**Issue by shamiiow** [mmtrt/leagueoflegends#217]
here is the error:
Unhandled exception: unimplemented function DXGI.DLL.CreateDXGIFactory1@8 called in 32-bit code (0x7bca44f9).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7bca44f9 ESP:0031e7e8 EBP:0031e84c EFLAGS:00000216(   - --  I   -A-P- )
 EAX:6a922036 EBX:0031e7f4 ECX:00e23470 EDX:00e234b0
 ESI:00000001 EDI:00000000
Stack dump:
0x0031e7e8:  00000000 003f8000 00000000 80000100
0x0031e7f8:  00000001 00000000 7bca44f9 00000002
0x0031e808:  6a92232c 6a922036 00000000 0140230e
0x0031e818:  0401014c 00000000 00001000 003f500e
0x0031e828:  0031e850 7b0ec520 00000000 00000000
0x0031e838:  0031e888 7bcef1ab 00c814d4 000081ed
Backtrace:
=>0 0x7bca44f9 (0x0031e84c)
  1 0x0032001e (0x0031e928)
  2 0x6a56b743 in d3d11 (+0x2b742) (0x0031eae8)
  3 0x02e6ab20 EntryPoint+0xffffffff() in libglesv2 (0x0031ebc4)
  4 0x02e69bb3 EntryPoint+0xffffffff() in libglesv2 (0x0031ed50)
  5 0x02e8f726 EntryPoint+0xffffffff() in libglesv2 (0x0031ee20)
  6 0x02e8fb49 EntryPoint+0xffffffff() in libglesv2 (0x0031ee38)
  7 0x02d31b86 EntryPoint+0xffffffff() in libglesv2 (0x0031ef2c)
  8 0x02cc53b8 EntryPoint+0xffffffff() in libglesv2 (0x0031ef54)
  9 0x02cc6b58 EntryPoint+0xffffffff() in libglesv2 (0x0031ef88)
  10 0x1287a896 EntryPoint+0xffffffff() in libcef (0x0031f0a4)
  11 0x128794cb EntryPoint+0xffffffff() in libcef (0x0031f0c0)
  12 0x131ab557 EntryPoint+0xffffffff() in libcef (0x0031f194)
  13 0x128867d7 EntryPoint+0xffffffff() in libcef (0x0031f1b0)
  14 0x1288651e EntryPoint+0xffffffff() in libcef (0x0031f1fc)
  15 0x12886638 EntryPoint+0xffffffff() in libcef (0x0031f254)
  16 0x129bf1c4 EntryPoint+0xffffffff() in libcef (0x0031f4e0)
  17 0x12d378a2 EntryPoint+0xffffffff() in libcef (0x0031f6d0)
  18 0x123ae814 EntryPoint+0xffffffff() in libcef (0x0031f6e8)
  19 0x123aee4d EntryPoint+0xffffffff() in libcef (0x0031f734)
  20 0x123ae423 EntryPoint+0xffffffff() in libcef (0x0031f75c)
  21 0x123ae4b7 EntryPoint+0xffffffff() in libcef (0x0031f774)
  22 0x123ae4f8 EntryPoint+0xffffffff() in libcef (0x0031f794)
  23 0x12d57b94 EntryPoint+0xffffffff() in libcef (0x0031f850)
  24 0x123d43d1 EntryPoint+0xffffffff() in libcef (0x0031f870)
  25 0x1000113d EntryPoint+0xffffffff() in libcef (0x0031f8a4)
  26 0x004cd716 EntryPoint+0xffffffff() in leagueclientuxrender (0x0031f8d8)
  27 0x00449d8c EntryPoint+0xffffffff() in leagueclientuxrender (0x0031fe78)
  28 0x0044a3e5 EntryPoint+0xffffffff() in leagueclientuxrender (0x0031fed0)
  29 0x7b647e21 in kernel32 (+0x27e20) (0x0031fee8)
  30 0x7b648517 in kernel32 (+0x28516) (0x0031ffd8)
  31 0x7b647e32 in kernel32 (+0x27e31) (0x0031ffec)
0x7bca44f9: addl	$12,%esp
Modules:
Module	Address			Debug info	Name (94 modules)
PE	  400000-  6cb000	Export          leagueclientuxrender
PE	  6d0000-  929000	Deferred        ffmpeg
PE	 1ba0000- 1bf6000	Deferred        libegl
PE	 1c20000- 1d1e000	Deferred        chrome_elf
PE	 2930000- 2cb5000	Deferred        d3dcompiler_47
PE	 2cc0000- 3569000	Export          libglesv2
PE	10000000-17da1000	Export          libcef
PE	62440000-627a4000	Deferred        d3d9
PE	6a540000-6a938000	Export          d3d11
PE	7a840000-7a849000	Deferred        opengl32
PE	7aee0000-7af1e000	Deferred        concrt140
PE	7b020000-7b03c000	Deferred        kernelbase
PE	7b220000-7b224000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	7b240000-7b244000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	7b250000-7b254000	Deferred        api-ms-win-core-string-l1-1-0
PE	7b260000-7b264000	Deferred        api-ms-win-core-localization-l1-2-1
PE	7b280000-7b284000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	7b290000-7b294000	Deferred        api-ms-win-core-synch-l1-2-0
PE	7b520000-7b524000	Deferred        kerberos
PE	7b620000-7b7f2000	Export          kernel32
PE	7bc30000-7bc48000	Deferred        ntdll
PE	7c430000-7c435000	Deferred        winex11
PE	7c5f0000-7c5f3000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	7c610000-7c613000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	7c620000-7c623000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	7c630000-7c635000	Deferred        api-ms-win-crt-math-l1-1-0
PE	7c650000-7c653000	Deferred        api-ms-win-crt-time-l1-1-0
PE	7c660000-7c664000	Deferred        api-ms-win-crt-string-l1-1-0
PE	7c680000-7c684000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	7c690000-7c693000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	7c6b0000-7c6b3000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	7c6c0000-7c6c4000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	7c6d0000-7c6d4000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	7c6f0000-7c705000	Deferred        vcruntime140
PE	7c730000-7c751000	Deferred        msvcr120
PE	7c850000-7c8bd000	Deferred        msvcp140
PE	7c940000-7c949000	Deferred        esent
PE	7c960000-7c966000	Deferred        ncrypt
PE	7c970000-7c974000	Deferred        wevtapi
PE	7c990000-7c994000	Deferred        dhcpcsvc
PE	7c9a0000-7ca7c000	Deferred        cryptui
PE	7cab0000-7cab6000	Deferred        jsproxy
PE	7cad0000-7cad7000	Deferred        winhttp
PE	7cb10000-7cb1d000	Deferred        mpr
PE	7cb50000-7cb75000	Deferred        wininet
PE	7cbf0000-7cc04000	Deferred        urlmon
PE	7cc90000-7ccad000	Deferred        credui
PE	7ccc0000-7ccc4000	Deferred        dxva2
PE	7cd00000-7cd16000	Deferred        msvcrt
PE	7cdb0000-7ce5d000	Deferred        comdlg32
PE	7cec0000-7cec6000	Deferred        uxtheme
PE	7cf10000-7cf1e000	Deferred        winspool
PE	7cf60000-7cf66000	Deferred        dwmapi
PE	7cf80000-7cf84000	Deferred        dwrite
PE	7d010000-7d015000	Deferred        hid
PE	7d030000-7d034000	Deferred        wtsapi32
PE	7d050000-7d056000	Deferred        bcrypt
PE	7d090000-7d0d8000	Deferred        crypt32
PE	7d170000-7d177000	Deferred        wintrust
PE	7d1b0000-7d1b6000	Deferred        imm32
PE	7d1d0000-7d1d4000	Deferred        usp10
PE	7d240000-7d296000	Deferred        comctl32
PE	7d380000-7d386000	Deferred        shcore
PE	7d3b0000-7d3c2000	Deferred        shlwapi
PE	7d410000-7d41a000	Deferred        aclui
PE	7d460000-7dd5d000	Deferred        shell32
PE	7de60000-7de64000	Deferred        userenv
PE	7dea0000-7dea7000	Deferred        dnsapi
PE	7dec0000-7dec8000	Deferred        netapi32
PE	7df10000-7df15000	Deferred        secur32
PE	7df60000-7df78000	Deferred        oleacc
PE	7dfb0000-7dfb5000	Deferred        uiautomationcore
PE	7dfd0000-7dfd8000	Deferred        propsys
PE	7e000000-7e080000	Deferred        winmm
PE	7e100000-7e10a000	Deferred        wined3d
PE	7e280000-7e4ea000	Deferred        dxgi
PE	7e280000-7e4ea000	Deferred        gdi32
PE	7e280000-7e4ea000	Deferred        setupapi
PE	7e280000-7e4ea000	Deferred        rpcrt4
PE	7e570000-7e579000	Deferred        combase
PE	7e5c0000-7e5c5000	Deferred        version
PE	7e600000-7e6f4000	Deferred        user32
PE	7e840000-7e86d000	Deferred        ole32
PE	7e980000-7e98e000	Deferred        oleaut32
PE	7ea90000-7ea97000	Deferred        sechost
PE	7ead0000-7eadd000	Deferred        advapi32
PE	7eb30000-7eb37000	Deferred        iphlpapi
PE	7eb60000-7eb67000	Deferred        ws2_32
PE	7ebd0000-7ecf0000	Deferred        ucrtbase
PE	7ecc0000-7ecc7000	Deferred        dbghelp
PE	7eeb0000-7eeb3000	Deferred        wow64cpu
PE	edef0000-edef4000	Deferred        rtworkq
PE	ee620000-ee626000	Deferred        mfplat
PE	ef080000-ef086000	Deferred        mf
Threads:
process  tid      prio (all id:s are in hex)
00000020 RiotClientServices.exe
	["C:\Riot Games\Riot Client\RiotClientServices.exe"]
	00000024    0
	000000d4    0
	000000d8    0
	000000dc    0
	000000e0    0
	000000e4    0
	000000e8    0
	00000164    0
	00000190    0
	00000194    0
	00000198    0
	0000019c    0
	000001a0    0
	000001a4    0
	000001b0    0
	000001b4    0
	000001b8    0
	000001bc    0
	000001c0    0
	000001c4    0
	000001c8    0
	000001cc    0
	000001d0    0
	000001d4    0
	000001d8    0
	000001e0    0
	000001e4    0
	000001e8    0
	000001ec    0
	000001f0    0
	000001f4    0
	000001f8    0
	000001fc    0
	00000200    0
	00000204    0
	00000208    0
	0000020c    0
	00000210    0
	00000214    0
	00000218    0
	0000021c    0
	00000220    0
	00000224    0
	00000228    0
	0000022c    0
	00000230    0
	00000234    0
	00000238    0
	0000023c    0
	00000240    0
	00000244    0
	00000248    0
	00000260    0
	00000264    0
	00000268    0
	0000026c    0
	00000270    0
	00000274    0
	0000027c    0
	0000032c    0
	00000334    0
	0000091c    0
	00000920    0
	00000924    0
	00000928    0
	0000092c    0
	00000930    0
	0000093c   15
	00000b5c    0
00000030 services.exe
	00000034    0
	00000038    0
	00000044    0
	0000005c    0
	00000074    0
	000000b4    0
0000003c winedevice.exe
	00000040    0
	0000004c    0
	00000050    0
	00000094    0
00000054 plugplay.exe
	00000058    0
	00000060    0
	00000064    0
	00000068    0
	00000084    0
	000003d0    0
	000003d4    0
	000007c0    0
	00000934    0
	00000938    0
	00000b08    0
	00000b0c    0
0000006c winedevice.exe
	00000070    0
	00000078    0
	0000007c    0
	00000080    0
	0000008c    0
	00000090    0
00000098 explorer.exe
	0000009c    0
	000000a0    0
	000000a4    0
	00000330    0
000000ac rpcss.exe
	000000b0    0
	000000bc    0
	000000c0    0
	000000c4    0
	000000c8    0
	000000cc    0
	00000428    0
00000168 RiotClientCrashHandler.exe
	["C:\Riot Games\Riot Client\RiotClientCrashHandler.exe" --no-rate-limit "--attachment=2023-01-15T14-32-14_32_Riot_Client.0.log=C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2023-01-15T14-32-14_32_Riot Client.0.log" "--attachment=2023-01-15T14-32-14_32_Riot_Client.log=C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2023-01-15T14-32-14_32_Riot Client.log" "--attachment=__sentry-breadcrumb1=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\4c469e75-8a4e-4626-86f9-7682bfb144b0.run\__sentry-breadcrumb1" "--attachment=__sentry-breadcrumb2=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\4c469e75-8a4e-4626-86f9-7682bfb144b0.run\__sentry-breadcrumb2" "--attachment=__sentry-event=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client\4c469e75-8a4e-4626-86f9-7682bfb144b0.run\__sentry-event" "--database=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client" "--metrics-dir=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\Riot Client" --url=https://sentry.io:443/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a --initial-client-data=0x118,0x11c,0x120,0x114,0x124,0x181f0db8,0x181f0dc8,0x181f0dd8]
	0000016c    0
	00000170    0
	00000174    0
	00000178    0
	0000017c    0
	00000180    0
	00000184    0
	00000188    0
	0000018c    0
00000324 RiotClientUx.exe
	["C:/Riot Games/Riot Client/UX/RiotClientUx.exe" --app-port=46611 --remoting-auth-token=3227hs1qTmYs3Z_tDDKXsA --app-pid=32 "--log-dir=C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs" "--user-data-root=C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client" "--app-root=C:/Riot Games/Riot Client" --crashpad-environment=KeystoneFoundationLiveWin]
	00000328    0
	00000344    0
	00000370    0
	00000374    0
	00000378    0
	00000380   -2
	00000384    0
	00000388    0
	0000038c    0
	00000390    0
	00000394    0
	00000398    0
	000003a8    0
	000003ac    0
	000003b0    0
	000003bc    0
	000003c4    0
	000003c8    0
	000003cc    0
	000003dc   -2
	000003e0    0
	000003e8    0
	000003ec    0
	000003f0    0
	000003f4    0
	000003f8    0
	0000043c    0
	00000444    0
	0000044c    0
	00000450    0
	00000454    0
	00000458    0
	00000464    0
	00000584    0
	0000058c    0
	000005e4   15
	00000ba4    0
	00000bd4    0
00000348 RiotClientCrashHandler.exe
	["C:\Riot Games\Riot Client\RiotClientCrashHandler.exe" --no-rate-limit "--attachment=2023-01-15T14-32-18_804_RiotClientUx.0.log=C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/2023-01-15T14-32-18_804_RiotClientUx.0.log" "--attachment=2023-01-15T14-32-18_804_RiotClientUx.log=C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/2023-01-15T14-32-18_804_RiotClientUx.log" "--attachment=__sentry-breadcrumb1=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\393e0039-689a-4b62-49d3-3c3c747b49ce.run\__sentry-breadcrumb1" "--attachment=__sentry-breadcrumb2=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\393e0039-689a-4b62-49d3-3c3c747b49ce.run\__sentry-breadcrumb2" "--attachment=__sentry-event=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx\393e0039-689a-4b62-49d3-3c3c747b49ce.run\__sentry-event" "--database=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx" "--metrics-dir=C:\users\shamiiow\Local Settings\Application Data\Riot Games\Riot Client\Crashes\RiotClientUx" --url=https://sentry.io:443/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a --initial-client-data=0xa8,0xac,0xb0,0xa4,0xb4,0x8de0a8,0x8de0b8,0x8de0c8]
	0000034c    0
	00000350    0
	00000354    0
	00000358    0
	0000035c    0
	00000360    0
	00000364    0
	00000368    0
	0000036c    0
00000418 explorer.exe
	0000041c    0
	00000420    0
	00000424    0
00000468 RiotClientUxRender.exe
	["C:\Riot Games\Riot Client\UX\RiotClientUxRender.exe" --type=renderer --no-sandbox --autoplay-policy=no-user-gesture-required --enable-experimental-web-platform-features --force-device-scale-factor=1 --log-file="C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --field-trial-handle=528,14956897140342152919,15565871879400195006,131072 --disable-features=HardwareMediaKeyHandling,NetworkService --lang=en-US --log-file="C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --product-version="RiotClient/63.0.5 (CEF 74)" --disable-extensions --disable-spell-checking --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=8824919151207106216 --renderer-client-id=3 --mojo-platform-channel-handle=924 /prefetch:1 --app-name=RiotClient --ux-name=RiotClientUx --ux-helper-name=RiotClientUxHelper --log-dir="C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/" --app-port=46611 --crashpad-environment=KeystoneFoundationLiveWin --user-data-root="C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client" --app-root="C:/Riot Games/Riot Client"]
	0000046c    0
	00000474    0
	00000478    0
	0000047c    0
	00000480    0
	00000484    0
	00000488   -2
	0000048c    0
	00000490    0
	00000494    0
	00000498    0
	0000049c    0
	000004a0    0
	000004a4    0
	000004a8    0
	000004ac    0
	000004b0   -2
	000004b4    0
	000004b8    0
	000004bc    0
	000004c0    0
	000004c4    0
	000004c8    0
	00000580    0
	000005d8    1
	000005dc    1
	000005e0    1
	000005f4   15
00000518 RiotClientUxRender.exe
	["C:\Riot Games\Riot Client\UX\RiotClientUxRender.exe" --type=gpu-process --field-trial-handle=528,14956897140342152919,15565871879400195006,131072 --disable-features=HardwareMediaKeyHandling,NetworkService --no-sandbox --log-file="C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --product-version="RiotClient/63.0.5 (CEF 74)" --lang=en-US --gpu-preferences=KAAAAAAAAADgAAAgAQAAAAAAAAAAAGAAAAAAABAAAAAIAAAAAAAAACgAAAAEAAAAIAAAAAAAAAAoAAAAAAAAADAAAAAAAAAAOAAAAAAAAAAQAAAAAAAAAAAAAAAFAAAAEAAAAAAAAAAAAAAABgAAABAAAAAAAAAAAQAAAAUAAAAQAAAAAAAAAAEAAAAGAAAA --use-gl=swiftshader-webgl --log-file="C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/debug.log" --service-request-channel-token=3586079954522966098 --mojo-platform-channel-handle=584 /prefetch:2 --app-name=RiotClient --ux-name=RiotClientUx --ux-helper-name=RiotClientUxHelper --log-dir="C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client UX Logs/" --app-port=46611 --crashpad-environment=KeystoneFoundationLiveWin --user-data-root="C:/users/shamiiow/Local Settings/Application Data/Riot Games/Riot Client" --app-root="C:/Riot Games/Riot Client"]
	0000051c    0
	00000520    0
	00000524    0
	00000528    0
	00000530    0
	00000534    0
	00000538   -2
	0000053c    0
	00000540    0
	00000544    0
	00000548    0
	0000054c    0
	00000550    0
	00000554    0
	00000558    0
	0000055c    0
00000958 LeagueClient.exe
	0000095c    0
	0000098c    0
	00000990    0
	00000994    0
	00000998    0
	0000099c    0
	000009a0    0
	000009a4    0
	000009a8    0
	000009ac    0
	000009b0    0
	000009b4    0
	000009b8    0
	000009bc    0
	000009c0    0
	000009c4    0
	000009c8    0
	000009cc    0
	000009d0    0
	000009d4    0
	000009d8    0
	000009e4    0
	000009e8    0
	000009ec    0
	000009f0    0
	000009f4    0
	000009f8    0
	000009fc    0
	00000a00    0
	00000a04    0
	00000a08    0
	00000a0c    0
	00000a10    0
	00000a14    0
	00000a18    0
	00000a1c    0
	00000a20    0
	00000a24    0
	00000a28    0
	00000a2c    0
	00000a30    0
	00000a34    0
	00000a38    0
	00000a3c    0
	00000a40    0
	00000a44    0
	00000a48    0
	00000a4c    0
	00000a50    0
	00000a54    0
	00000a58    0
	00000a5c    0
	00000a60    0
	00000a64    0
	00000a68    0
	00000a78    0
	00000a84    0
	00000a88    0
	00000a90    0
	00000b28    0
	00000b2c    0
	00000b30    0
	00000b70    0
	00000b74    0
00000964 LeagueCrashHandler.exe
	["c:\Riot Games\League of Legends\LeagueCrashHandler.exe" "--database=C:/users/shamiiow/Local Settings/Application Data/Riot Games/League of Legends/LeagueClient/Crashes" "--metrics-dir=C:/users/shamiiow/Local Settings/Application Data/Riot Games/League of Legends/LeagueClient/Crashes" --url=https://sentry.io/api/1442968/minidump/?sentry_key=819c51f9b27f4f4b8cf6811c04fda544 --initial-client-data=0x7c,0x80,0x84,0x78,0x88,0x19783a4,0x19783b4,0x19783c4]
	00000968    0
	0000096c    0
	00000970    0
	00000974    0
	00000978    0
	0000097c    0
	00000980    0
	00000984    0
	00000988    0
	00000a94    0
	00000a98    0
	00000a9c    0
	00000b38    0
	00000b3c    0
	00000b40    0
00000a70 LeagueClientUx.exe
	00000a74    0
	00000aa0    0
	00000aa4    0
	00000aa8    0
	00000ab0   -2
	00000ab8    0
	00000abc    0
	00000ac0    0
	00000ac4    0
	00000ac8    0
	00000acc    0
	00000ad0    0
	00000ad4    0
	00000ad8    0
	00000adc    0
	00000ae0    0
	00000ae4    0
	00000aec    0
	00000af8    0
	00000afc    0
	00000b00    0
	00000b04    0
	00000b10   -2
	00000b14    0
	00000b18    0
	00000b1c    0
00000bb0 (D) c:\Riot Games\League of Legends\LeagueClientUxRender.exe
	["c:\Riot Games\League of Legends\LeagueClientUxRender.exe" --type=gpu-process --field-trial-handle=588,4787675642065867430,2019543026587253799,131072 --disable-features=CookiesWithoutSameSiteMustBeSecure,HardwareMediaKeyHandling,SameSiteByDefaultCookies --no-sandbox --log-file="c:\Riot Games\League of Legends\debug.log" --user-agent-product="LeagueOfLegendsClient/13.1.489.3737 (CEF 91)" --lang=en-US --gpu-preferences=SAAAAAAAAADgACgwAAAAAAAAAAAAAAAAAABgAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAHgAAAAAAAAAKAAAAAQAAAAgAAAAAAAAACgAAAAAAAAAMAAAAAAAAAA4AAAAAAAAABAAAAAAAAAAAAAAAAUAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAABAAAABQAAABAAAAAAAAAAAQAAAAYAAAAIAAAAAAAAAAgAAAAAAAAA --log-file="c:\Riot Games\League of Legends\debug.log" --mojo-platform-channel-handle=360 /prefetch:2 --app-name=LeagueClient --ux-name=LeagueClientUx --ux-helper-name=LeagueClientUxHelper --log-dir="LeagueClient Logs" --app-port=46281 --output-base-dir="c:\Riot Games\League of Legends" --crash-reporting=crashpad --crash-environment=EUW1 --crash-pipe="\\.\pipe\crashpad_2392_YCLNRDRGFJYSNZFG" --app-log-file-path="c:/Riot Games/League of Legends/Logs/LeagueClient Logs/2023-01-15T14-34-51_2392_LeagueClient.log" --primary-ux-log-file-path="c:/Riot Games/League of Legends/Logs/LeagueClient Logs/2023-01-15T14-34-52_2672_LeagueClientUx.log"]
	00000bb4    1 <==
	00000bb8    0
	00000bbc    0
	00000bc0    0
	00000bc4    0
	00000bd0    0
System information:
    Wine build: wine-5.18 ( TkG Staging Esync Fsync Vkd3d )
    Platform: i386 (WOW64)

How can I fix that ?

**Comment by mmtrt** [comment]
did u installed `dxvk`?

**Comment by shamiiow** [comment]
I think, I did this command : snap run leagueoflegends.winetricks dxvk194
and it's say that :
------------------------------------------------------
warning: Your version of wine 5.18 is no longer supported upstream. You should upgrade to 6.x
------------------------------------------------------
Executing mkdir -p /home/shamiiow/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 918989a44c3442e1eb84f38746253ab099fa36746468af95f28d089548fb53f2 with wine-5.18 ( TkG Staging Esync Fsync Vkd3d ) and WINEARCH=win64
------------------------------------------------------
warning: Calling dxvk194 is deprecated, please use dxvk1094 instead
------------------------------------------------------
Executing w_do_call dxvk1094
Executing mkdir -p /home/shamiiow/snap/leagueoflegends/common
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
dxvk1094 already installed, skipping

any idea ?

**Comment by mmtrt** [comment]
winetricks does not installs old `dxvk` by default now in you have to pass force flag `-f` to complete the install.
`snap run leagueoflegends.winetricks -f dxvk194`

**Comment by shamiiow** [comment]
> did u installed `dxvk`?



> did u installed `dxvk`?

I think, I did this command : snap run leagueoflegends.winetricks dxvk194
and it's say that :

Executing mkdir -p /home/shamiiow/snap/leagueoflegends/common

warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

Using winetricks 20220411-next - sha256sum: 918989a44c3442e1eb84f38746253ab099fa36746468af95f28d089548fb53f2 with wine-5.18 ( TkG Staging Esync Fsync Vkd3d ) and WINEARCH=win64

warning: Calling dxvk194 is deprecated, please use dxvk1094 instead

Executing w_do_call dxvk1094
Executing mkdir -p /home/shamiiow/snap/leagueoflegends/common

warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

dxvk1094 already installed, skipping

**Comment by shamiiow** [comment]
> winetricks does not installs old `dxvk` by default now in you have to pass force flag `-f` to complete the install. `snap run leagueoflegends.winetricks -f dxvk194`

idk why but the game starting now, I did nothing (I run the command before my post).. so I think it's good but it's weird

**Comment by shamiiow** [comment]
> winetricks does not installs old `dxvk` by default now in you have to pass force flag `-f` to complete the install. `snap run leagueoflegends.winetricks -f dxvk194`

well..now there is no error message, the game just don't start
