### ISSUE TITLE
Crash on tranning room and now I can't get out of 5 min ban timmer.

### ISSUE THREAD

**Issue by Keviny9** [mmtrt/leagueoflegends#22]
I'm trying to get this game working in Xubuntu 16.04.5 but after running a game in tranning rom it crashed then I got a 5min ban which I can't finish it. When the timmer hits 0 I get out of queue and need to wait the 5 min ban again.
keviny@Lenovo-3000:~$ snap list | grep leagueoflegends
leagueoflegends  1.0                21    edge      mmtrt            jailmode

And

keviny@Lenovo-3000:~$ sudo lspci | grep VGA 
01:00.0 VGA compatible controller: NVIDIA Corporation G92 [GeForce GTS 250] (rev a2)

**Comment by mmtrt** [comment]
Make sure your system have all wine packages installed also nvidia gl packages as well.

**Comment by Keviny9** [comment]
Thank You, I´ll test

**Comment by Keviny9** [comment]
I am used Wine Stagging

**Comment by stuartfoxcroft** [comment]
Since the training room is technically a custom game (that's how it appears in the match history as well) you shouldn't receive any queue timers from leaving, either through choice or by the game crashing. Sounds like an issue with Riot rather than an issue with the snap.
