### ISSUE TITLE
Shortcut not generated on Pop!OS

### ISSUE THREAD

**Issue by colonnezi** [mmtrt/leagueoflegends#224]
Hi, i've reinstalled my OS on my SSD drive and have migrated from ubuntu to POP!OS. After installing the game (had to run trough #223 again to properly install so repository admin might check if it's relevant), it's running perfectly but the shortcut was not created like in ubuntu. Game runs normally via the run command in terminal.

**Comment by mmtrt** [comment]
IDK how popOS handles snapd menu items tho you can here installed snaps desktop menu items.

`/var/lib/snapd/desktop/applications`

**Comment by colonnezi** [comment]
not good enough it seems 
![image](https://user-images.githubusercontent.com/96270092/227386987-114f133f-8559-4178-a5ad-5794d9f19972.png)
Thanks anyway!
