### ISSUE TITLE
Launcher works fine but game crashes right after start

### ISSUE THREAD

**Issue by pabazhenov** [mmtrt/leagueoflegends#226]
![lol_crash](https://user-images.githubusercontent.com/50327552/230167886-ef6db256-b1a0-4188-b082-22a71b676aff.png)

It happens every time when i try to start game (custom,normal,ranked etc) since last game update. Launcher works perfectly fine, but game client just crashes (after crash reconnect button appears and if i click on it, game will try to load and crashes again).

Terminal output:
pikachu@localhost:~> snap run leagueoflegends
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
The operation completed successfully
0268:err:rpc:I_RpcGetBuffer no binding
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

LeagueClientUx pid: 11382
Waiting for port 37047
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
0870:err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x10148
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.
pikachu@localhost:~> 

Also tried to launch through lutris. Having same problem with it. I think its last update patch, but not sure its just me or somebody else faced with this problem too.

P.S. I did fresh install snap leagueoflegends.
P.P.S. found this thread on reddit: https://www.reddit.com/r/leagueoflinux/comments/12cei7t/patch_137_feedback_megathread_transition_to_64bit/
It seems problem is massive and no solution there yet.

**Comment by colonnezi** [comment]
Yeah i have the same issue, the maintainer of this repository has said on issues before that he already was aware, so we need just a little patience

**Comment by Definite007** [comment]
I hope we get the solution soon

**Comment by ardarandir** [comment]
is anyone NOT experiencing this or is this effecting every install?

**Comment by Definite007** [comment]
> is anyone NOT experiencing this or is this effecting every install?

It being experienced by everyone since 4 days now

**Comment by silk1100** [comment]
Are there any updates regarding this issue?

**Comment by retrospectivedevs** [comment]
Seems like Riot has fixed the issue and some other people who are patching it have applied some fix, i hope mmtrt will also apply some fix soon

**Comment by mmtrt** [comment]
update snap and test again changes are not tested idk if it works.

`snap refresh`

NOTE: Must have install `leagueoflegends` from `beta` branch and `wine-platform-7-staging-core20` from `candidate` branch

**Comment by Definite007** [comment]
When will it come to edge version dev mode?

**Comment by colonnezi** [comment]
> update snap and test again changes are not tested idk if it works.
> 
> `snap refresh`
> 
> NOTE: Must have install `leagueoflegends` from `beta` branch and `wine-platform-7-staging-core20` from `candidate` branch

Worked for me. Was able to play a coop game normally so probably issue fixed.

**Comment by Definite007** [comment]
> update snap and test again changes are not tested idk if it works.
> 
> `snap refresh`
> 
> NOTE: Must have install `leagueoflegends` from `beta` branch and `wine-platform-7-staging-core20` from `candidate` branch

Still not working tried fresh install of beta version with given settings

**Comment by ardarandir** [comment]
> > update snap and test again changes are not tested idk if it works.
> > `snap refresh`
> > NOTE: Must have install `leagueoflegends` from `beta` branch and `wine-platform-7-staging-core20` from `candidate` branch
> 
> Still not working tried fresh install of beta version with given settings, getting the same system error

I can confirm, issue is persisting.

**Comment by dmaccoll** [comment]
Had to do a 

`snap refresh leagueoflegends --beta --devmode`

to get it working, as without the extra options it reported all was up to date. Even after that, the first run failed when starting the Riot client. After much use of `ps` and `kill`, a restart was successful. I was able to test the tutorial, which went fine - or as fine as it ever does on this old Haswell rig with a GTX 750. These days I mainly play TFT from the Riot client, will test when I have more time - hopefully tomorrow (Sunday).

**Comment by Definite007** [comment]
> Had to do a
> 
> `snap refresh leagueoflegends --beta --devmode`
> 
> to get it working, as without the extra options it reported all was up to date. Even after that, the first run failed when starting the Riot client. After much use of `ps` and `kill`, a restart was successful. I was able to test the tutorial, which went fine - or as fine as it ever does on this old Haswell rig with a GTX 750. These days I mainly play TFT from the Riot client, will test when I have more time - hopefully tomorrow (Sunday).

This command now updated the lol client but didn't change anything regarding the system error in Ubuntu 22.04

**Comment by dmaccoll** [comment]
My bad, forgot to say I'm on Mint 21.1 over here.

I can confirm that I was able to play a Normal game of TFT just now with no issues other than the expected performance ones.

**Comment by Definite007** [comment]
After fresh Install, Now the error has changed to "Could not Initialize Graphics Device" i thought it will be removed after restart, but it didn't go... Hope we find a solution for it soon

**Comment by Definite007** [comment]
I started the practice tool today and it worked i don't know who fixed it but now it is working on Ubuntu 22.04

**Comment by mmtrt** [comment]
I added kisak mesa pkgs to runtime snap yesterday might have fixed for you.

**Comment by abetatos** [comment]
Experiencing the same problem as the image. The banner pops up about 5-6 times. I realized that it pops up a new error message every time the "/usr/share/libdrm/amdgpu.ids: No such file or directory" appears: 
![imagen](https://github.com/mmtrt/leagueoflegends/assets/76526314/db73c3ed-4824-474d-8b19-0043110d9a1c)
I have an nvidia gpu, could that be the problem? Is there any extra driver I should be installing?

**Comment by mmtrt** [comment]
@abetatos which nv drivers you have also is it laptop/PC with amd cpu & nv gpu

**Comment by abetatos** [comment]
@mmtrt It is a PC with specs: 

- CPU: I have an AMD Ryzen 7 7700. I did not install any extra driver. 
- GPU:  I have a rtx 4070 and installed the nvidia drivers 530 (nvidia-driver-530 nvidia-dkms-530)

ismod info: 

Module                  Size  Used by
fcomm                 86016  4
ccm                    20480  3
cmac                   16384  3
algif_hash             16384  1
algif_skcipher         16384  1
af_alg                 32768  6 algif_hash,algif_skcipher
nvidia_uvm           1433600  0
intel_rapl_msr         20480  0
intel_rapl_common      40960  1 intel_rapl_msr
nvidia_drm             77824  2
nvidia_modeset       1273856  3 nvidia_drm
edac_mce_amd           36864  0
bnep                   28672  2
nvidia              55750656  108 nvidia_uvm,nvidia_modeset
amdgpu              11313152  13
snd_hda_codec_realtek   163840  1
snd_hda_codec_generic   102400  1 snd_hda_codec_realtek
ledtrig_audio          16384  1 snd_hda_codec_generic
snd_hda_codec_hdmi     86016  2
snd_hda_intel          53248  4
iwlmvm                610304  0
snd_intel_dspcfg       36864  1 snd_hda_intel
snd_intel_sdw_acpi     20480  1 snd_intel_dspcfg
snd_hda_codec         176128  4 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek
snd_hda_core          114688  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek
mac80211             1314816  1 iwlmvm
snd_hwdep              20480  1 snd_hda_codec
binfmt_misc            24576  1
kvm                  1130496  0
btusb                  61440  0
iommu_v2               24576  1 amdgpu
libarc4                16384  1 mac80211
snd_pcm               155648  4 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,snd_hda_core
nls_iso8859_1          16384  1
crct10dif_pclmul       16384  1
gpu_sched              49152  1 amdgpu
btrtl                  24576  1 btusb
drm_ttm_helper         16384  1 amdgpu
ghash_clmulni_intel    16384  0
btbcm                  24576  1 btusb
aesni_intel           376832  6
ttm                    98304  2 amdgpu,drm_ttm_helper
snd_seq_midi           20480  0
iwlwifi               503808  1 iwlmvm
snd_seq_midi_event     16384  1 snd_seq_midi
drm_display_helper    184320  1 amdgpu
btintel                40960  1 btusb
crypto_simd            16384  1 aesni_intel
snd_rawmidi            45056  1 snd_seq_midi
btmtk                  16384  1 btusb
cryptd                 24576  3 crypto_simd,ghash_clmulni_intel
cec                    81920  1 drm_display_helper
joydev                 32768  0
snd_seq                77824  2 snd_seq_midi,snd_seq_midi_event
bluetooth             827392  34 btrtl,btmtk,btintel,btbcm,bnep,btusb,rfcomm
input_leds             16384  0
rapl                   20480  0
rc_core                65536  1 cec
snd_seq_device         16384  3 snd_seq,snd_seq_midi,snd_rawmidi
cfg80211             1044480  3 iwlmvm,iwlwifi,mac80211
ecdh_generic           16384  2 bluetooth
gigabyte_wmi           20480  0
snd_timer              40960  2 snd_seq,snd_pcm
ecc                    40960  1 ecdh_generic
wmi_bmof               16384  0
drm_kms_helper        200704  5 drm_display_helper,amdgpu,nvidia_drm
i2c_algo_bit           16384  1 amdgpu
fb_sys_fops            16384  1 drm_kms_helper
snd                   114688  19 snd_hda_codec_generic,snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_timer,snd_pcm,snd_rawmidi
syscopyarea            16384  1 drm_kms_helper
sysfillrect            20480  1 drm_kms_helper
sysimgblt              20480  1 drm_kms_helper
soundcore              16384  1 snd
ccp                   110592  0
mac_hid                16384  0
sch_fq_codel           24576  2
msr                    16384  0
parport_pc             53248  0
ppdev                  24576  0
lp                     28672  0
parport                73728  3 parport_pc,lp,ppdev
drm                   581632  15 gpu_sched,drm_kms_helper,drm_display_helper,nvidia,amdgpu,drm_ttm_helper,nvidia_drm,ttm
pstore_blk             16384  0
ramoops                32768  0
pstore_zone            32768  1 pstore_blk
reed_solomon           28672  1 ramoops
efi_pstore             16384  0
ip_tables              32768  0
x_tables               57344  1 ip_tables
autofs4                45056  2
hid_generic            16384  0
usbhid                 65536  0
hid                   159744  2 usbhid,hid_generic
crc32_pclmul           16384  0
nvme                   49152  2
ahci                   49152  0
r8169                 102400  0
xhci_pci               24576  0
i2c_piix4              32768  0
libahci                49152  1 ahci
xhci_pci_renesas       20480  1 xhci_pci
realtek                32768  1
nvme_core             147456  3 nvme
wmi                    32768  2 gigabyte_wmi,wmi_bmof
video                  65536  0

I don't know why I do have amdgpu, thought that was only for the AMD's gpu devices. 
If you need any extra information let me know.

**Comment by mmtrt** [comment]
did you tried launching game with leagueoflegends (nvidia optitmus) from start menu see if that helps.

**Comment by abetatos** [comment]
Yes and same behaviour, i even tried to run in the first one for wine to create an environment adapted to nvidia. The problem is that with nvidia optimus I don't see the trace and don't know how to launch it from terminal.

**Comment by mmtrt** [comment]
command for launching with optimus

`snap run leagueoflegends.leagueoflegendsnv`

also can you test see which gpu showing on overlay in vkcube

`snap run leagueoflegends.vkcube`

and vkcube-nv that having optimus env set

`snap run leagueoflegends.vkcube-nv`

also post info of

`snap run leagueoflegends.vulkaninfo --summary`
