### ISSUE TITLE
Wandering if its possible to install legends of runeterra via ingame riot client and it works...?

### ISSUE THREAD

**Issue by colonnezi** [mmtrt/leagueoflegends#228]
Title pretty much... I know you have another repository to the game and i would want to play it in my pc too (better for deckbuilding).

**Comment by colonnezi** [comment]
Can someone help me fix this??

**Comment by mmtrt** [comment]
well first you are using not supported game by this snap even which have separate snap built already with game needed changes.

try using `virtual desktop`



closing this issue not related to `league of legends`
