### ISSUE TITLE
Alert window appeared updating to 9.2

### ISSUE THREAD

**Issue by Petrux25** [mmtrt/leagueoflegends#23]
Hello, today I updated to 9.2 version and when I opened the game, a pop out window appeared saying that if I was playing on a virtual machine, Windows XP or Vista, I would be able to play until May because Riot Games is [ending support](https://na.leagueoflegends.com/en/news/riot-games/announcements/ending-support-windows-xp-and-vista) for those OS in that month.

**Comment by mmtrt** [comment]
This snap likely will be broken as well but if wine developers not fix the LoL issues when using Win7 with wineprefix surely they will come with something who knows anything could happen.
