### ISSUE TITLE
I think that the client is having memory leak

### ISSUE THREAD

**Issue by colonnezi** [mmtrt/leagueoflegends#231]
I've reinstalled the game as i needed to upgrade my ssd to a new m.2 one, initially game was fine but after i've tried to install another game on lutris (Horizon zero dawn gog version), for some reason the game today wasn't working fine. Actually, i wasn't able to initiate the game after the client. I've tried to reinstall it, but for some reason the client is sucking up all my RAM.
![Captura de tela de 2023-08-22 22-11-46](https://github.com/mmtrt/leagueoflegends/assets/96270092/ac0ac181-4a38-4fba-a9af-6e22b8771278)

**Comment by colonnezi** [comment]
also it's taking a really long time to start...

**Comment by colonnezi** [comment]
Terminal is giving me this:
`tito@jarvis-v6x:~/Área de Trabalho$ snap run leagueoflegends
0644:err:rpc:I_RpcGetBuffer no binding
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
LeagueClientUx pid: 221124
Waiting for port 38847
/snap/leagueoflegends/152/bin/lolfix: line 23: kill: (221124) - No such process`

**Comment by mmtrt** [comment]
use league snap from beta branch also you will need fresh `wineprefix` for that b/c of new `wine`.

for memory usage it seems to use more ram now then before maybe they changed client.

**Comment by colonnezi** [comment]
where do i store the new wineprefix?
any fix for the memory usage?

**Comment by colonnezi** [comment]
tried reinstalling it, but now i cant install (after i select the region).

**Comment by mmtrt** [comment]
redo again I guess with purge remove league snap

**Comment by colonnezi** [comment]
What other dependencies should I purge too? I tried that yesterday (remove purge league of legends, the wine-platform runtime and the wine-7-candidate that is in the main page)

**Comment by colonnezi** [comment]
also getting this error on terminal:    Gtk-Message: 18:48:34.218: Failed to load module "canberra-gtk-module"

**Comment by colonnezi** [comment]
![image](https://github.com/mmtrt/leagueoflegends/assets/96270092/8344c1a9-b1c6-428f-b70e-063882c7804d)
ok i've removed all snaps and tried to reinstall again, now for some reason the wineprefix is not building lol

> Gtk-Message: 19:29:41.581: Failed to load module "canberra-gtk-module"
> Gtk-Message: 19:29:41.581: Failed to load module "canberra-gtk-module"
> tito@jarvis-v6x:~/Área de Trabalho$ snap refresh --candidate wine-platform-5-staging
> wine-platform-5-staging (candidate) 5.18 from Taqi Raza (mmtrt) refreshed
> tito@jarvis-v6x:~/Área de Trabalho$ snap list
> Name                     Version          Rev    Tracking          Publisher   Notes
> bare                     1.0              5      latest/stable     canonical✓  base
> core18                   20230703         2790   latest/stable     canonical✓  base
> core20                   20230801         2015   latest/stable     canonical✓  base
> gtk-common-themes        0.1-81-g442e511  1535   latest/stable     canonical✓  -
> leagueoflegends          1.0              152    latest/edge       mmtrt       devmode
> snapd                    2.60.2           19993  latest/stable     canonical✓  snapd
> wine-platform-5-staging  5.18             36     latest/candidate  mmtrt       -
> wine-platform-runtime    v1.0             349    latest/stable     mmtrt       -
> tito@jarvis-v6x:~/Área de Trabalho$ snap run leagueoflegends
> /snap/leagueoflegends/152/bin/sommelier: line 835: yad: command not found
> touch: cannot touch '/home/tito/snap/leagueoflegends/common/.wine/drive_c/windows/system32/winemenubuilder.exe': No such file or directory
> env: ‘/snap/leagueoflegends/152/wine-runtime/bin/winetricks’: No such file or directory
> env: ‘/snap/leagueoflegends/152/wine-runtime/bin/winetricks’: No such file or directory
> /snap/leagueoflegends/152/bin/sommelier: line 446: yad: command not found
> tito@jarvis-v6x:~/Área de Trabalho$ snap install --candidate wine-platform-7-staging-core20
> wine-platform-7-staging-core20 (candidate) 7.0.8 from Taqi Raza (mmtrt) installed
> tito@jarvis-v6x:~/Área de Trabalho$ snap list
> Name                            Version          Rev    Tracking          Publisher   Notes
> bare                            1.0              5      latest/stable     canonical✓  base
> core18                          20230703         2790   latest/stable     canonical✓  base
> core20                          20230801         2015   latest/stable     canonical✓  base
> gtk-common-themes               0.1-81-g442e511  1535   latest/stable     canonical✓  -
> leagueoflegends                 1.0              152    latest/edge       mmtrt       devmode
> snapd                           2.60.2           19993  latest/stable     canonical✓  snapd
> wine-platform-5-staging         5.18             36     latest/candidate  mmtrt       -
> wine-platform-7-staging-core20  7.0.8            27     latest/candidate  mmtrt       -
> wine-platform-runtime           v1.0             349    latest/stable     mmtrt       -
> tito@jarvis-v6x:~/Área de Trabalho$ snap run leagueoflegends
> /snap/leagueoflegends/152/bin/sommelier: line 835: yad: command not found
> touch: cannot touch '/home/tito/snap/leagueoflegends/common/.wine/drive_c/windows/system32/winemenubuilder.exe': No such file or directory
> env: ‘/snap/leagueoflegends/152/wine-runtime/bin/winetricks’: No such file or directory
> env: ‘/snap/leagueoflegends/152/wine-runtime/bin/winetricks’: No such file or directory
> /snap/leagueoflegends/152/bin/sommelier: line 446: yad: command not found

**Comment by colonnezi** [comment]
Update: I've been able to install the client, and launch the game via lutris using the WINE-GELOL.
But, the heavy RAM usage continues. Not related with the snap but i think that is useful information

**Comment by colonnezi** [comment]
After some tests, i want to share the last update:
The Excessive RAM usage happens only when downloading the game after you login.
Probably the files downloaded stay in RAM until new files replaces them.
