### ISSUE TITLE
Patch 13.23 - Game crashes after champ select

### ISSUE THREAD

**Issue by SomnusVeritas** [mmtrt/leagueoflegends#234]
After updating the game to Patch 13.23, the game crashes after champ select.
![crash report](https://github.com/mmtrt/leagueoflegends/assets/133667014/2a360301-3d32-4969-81ee-2942b1ff5ed9)

I tried reinstalling the game completely, after removing the game with snap remove --purge leagueoflegends

Console Output:
```
023c:err:rpc:I_RpcGetBuffer no binding
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
LeagueClientUx pid: 93817
Waiting for port 35349
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
06e4:err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x10148
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.


```

**Comment by linuxninja39** [comment]
+1

**Comment by mmtrt** [comment]
it is broken for all atm so [check](https://old.reddit.com/r/leagueoflinux/comments/180lp0b/patch_1323_megathread/) for fixes by community.

**Comment by Jerome-Schaezeli** [comment]
I have the same problem since this new painter champ has came. 
It's weird because I also can't connect in windows afterward. It says : Can't connect to the server when I try to "reconnect"
I don't know.

**Comment by froid1911** [comment]
i hate riot

**Comment by blegouix** [comment]
https://github.com/NelloKudo/WineBuilder/releases/tag/wine-lol-9.0-rc1

**Comment by mmtrt** [comment]
@blegouix thanks


wine update pushed test

`snap refresh --candidate wine-platform-7-staging-core20`
