### ISSUE TITLE
This snap have reached EOL due to Anti Cheat changes by Riot.

### ISSUE THREAD

**Issue by mmtrt** [mmtrt/leagueoflegends#235]
Riot is adding Vanguard kernel-level anti-cheat in League of Legends.

https://www.youtube.com/watch?v=9U_jEzKf0_0&t=732s

EDIT:

and it is released.

https://www.leagueoflegends.com/en-us/news/game-updates/patch-14-9-notes

Snap is removed for public installs.

**Comment by froid1911** [comment]
mhhh. good bye riot. will definitly not switch to windows. since every other game works on linux.
anyway thanks @mmtrt  for all your effort! you did a really good job!
