### ISSUE TITLE
"You are on an unsupported Operating System."

### ISSUE THREAD

**Issue by JekoTronik** [mmtrt/leagueoflegends#236]
![Screenshot_20240222_133007](https://github.com/mmtrt/leagueoflegends/assets/20554184/80e854ad-a762-4811-90cb-d7d442620259)

leagueoflegends snap is up to date.

**Comment by mmtrt** [comment]
change `wineprefix` base os to `windows 10` with this command.

`leagueoflegends.winecfg`
