### ISSUE TITLE
can't update client after new patch

### ISSUE THREAD

**Issue by ajvztr** [mmtrt/leagueoflegends#25]
![2019-02-23 12-21-38](https://user-images.githubusercontent.com/37624006/53284445-c6ea9e00-3765-11e9-9704-3a6b07c2cb7b.png)

**Comment by mmtrt** [comment]
Recent buggy update that have broke the client for many users yet I don't have that issue with recent patch tough I don't do league that much these days.

it's a leagueoflegends issue or wine issue not this snap issue so I can't do much in that regard.

follow it for issue workarounds suggusted by many linux users.
www.reddit.com/r/leagueoflinux

**Comment by viniciocoelho** [comment]
Same here. Is there any solution? Thanks.

**Comment by ajvztr** [comment]
> Same here. Is there any solution? Thanks.

It's problem with wine. Here discus:
https://www.reddit.com/r/leagueoflinux/comments/at4ln8/login_issues_ubuntu_18041/?st=JSI15L95&sh=0e7f6c7e

**Comment by adserba** [comment]
in client settings --initiate full repair
it will update and then works
