### ISSUE TITLE
Erro de Net

### ISSUE THREAD

**Issue by Hyperedy** [mmtrt/leagueoflegends#27]
Eu baixei LoL por snap instalei tudo certinho quando abre o launch para fazer login deveria atualizar baixar atualizações, mas não faz isso aparece que esta sem net só que estou com net, ate estou escrevendo esse tópico quem poder me ajudar agradeço.

**Comment by mmtrt** [comment]
Atualização recente com bugs causa problemas para muitos usuários e também o Riot confirmou que os problemas irão liberar a correção, então não sei quando eles corrigem o patch de atualização. Também não falo português então é o google traduzido. Por favor, escreva em inglês para que eu possa entender obrigado.

**Comment by freefri** [comment]
Hi, I think same problem here. Can you post a link to Riot boards about this problem?

![image](https://user-images.githubusercontent.com/2754631/53658997-9d94ab00-3c5a-11e9-8e8b-318bfefa8fca.png)

**Comment by endersonmenezes** [comment]
Same problem here, on any server!

**Comment by newhoa** [comment]
People on reddit have discussed it being a DNS issue. [Wine 4.3 just released with DNS changes and people are reporting that it may have fixed this problem](https://www.reddit.com/r/leagueoflinux/comments/awbta1/wine_43_released_changes_on_dns_records/).

**Comment by freefri** [comment]
Maybe an update to wine 4.3 is needed in https://github.com/mmtrt/wine-platform ?

**Comment by mmtrt** [comment]
Temporary sharing snap fix until wine-staging releases, it did fix login issue but I can not get into the game it just crashes after timer ends.

[leagueoflegends_1.0_multi.zip](https://github.com/mmtrt/leagueoflegends/files/2923612/leagueoflegends_1.0_multi.zip)

* unpack zip.
* `snap install leagueoflegends_1.0_multi.snap --dangerous --devmode`
* `snap disconnect leagueoflegends:wine-platform-plug`
* `snap refresh wine-platform --edge`
* `snap connect leagueoflegends:wine-platform-plug wine-platform:wine-base-devel`
* test game.

**Comment by newhoa** [comment]
> snap refresh wine-platform --edge

That update seems to have fixed it for me! I've restarted about 4 times and have had no error so far. I'll post again if I run into any problems. Hopefully others can confirm this works.

**Comment by freefri** [comment]
Hi, few days ago I've removed the game files and I was getting stack in this screen while installing the game:

![image](https://user-images.githubusercontent.com/2754631/53866018-d1702780-3ff0-11e9-931c-9472244ea465.png)

I thought it was the same DNS problem, but now I've updated wine-platform to latest --edge and I still get stack in that screen

**Comment by newhoa** [comment]
Did you remove the game files from the snap folder? If so it's probably trying to load files it can't find. I'd recommend uninstalling and reinstalling the snap.  Be sure to backup any replays or configs you may have saved. Then from the terminal run snap remove leagueoflegends. And then install it again.

**Comment by freefri** [comment]
I've removed again the whole directory `snap/leagueoflegends`, I've removed the snap `snap remove leagueoflegends` and installed it again `snap install --edge --devmode leagueoflegends` (and the snap directory was again created automatically) and I get stack in the same window as before, without any progress.

**Comment by mmtrt** [comment]
pushed update to wine-platform which changes its base to use core18..

`snap refresh --edge wine-platform`
`snap refresh --edge --devmode leagueoflegends`

@freefri  see if this fixes your issue.

**Comment by endersonmenezes** [comment]
It seems that the direct snap fixed the problem, but manually I upgraded Wine to 4.3 and stopped the error.

**Comment by freefri** [comment]
I've got further in the installation process, but I'm still stacked in the login screen. 

![image](https://user-images.githubusercontent.com/2754631/54224694-5203bc00-44fa-11e9-8915-0a0786ef5e77.png)

But the last days, I've recognized that my computer is having problems to load certain websites (sometimes the css is not loaded, sometimes some images are missing... but usually when I press F5 it works). I guess is not possible that wine or the game is playing with my dns, right?

**Comment by freefri** [comment]
Today the game got magically fixed? or a new release was deployed?

Anyway, I confirm it is working now for me.

**Comment by dragonwebeu** [comment]
Opening client is working for me, but  in game is broken. Heres picture(right side) Any ideas? https://www.upload.ee/image/9693013/Screenshot_from_2019-03-13_20-09-50.png

**Comment by mmtrt** [comment]
@dragonwebeu update league snap now with loging enable and post wine log when in game from terminal.

**Comment by dragonwebeu** [comment]
@mmtrt I did, this is picture after that:
![Screenshot from 2019-03-13 22-17-55](https://user-images.githubusercontent.com/7014691/54311850-1d693080-45de-11e9-9674-4dd2a3a433e4.png)

No idea what going on with graphics. I played 2-3 games yesterday evening and everything was OK. 

 ```
snap refresh --edge wine-platform
snap refresh --edge --devmode leagueoflegends
```
I even uninstalled both snap's and reinstalled them but still same problem.

**Comment by mmtrt** [comment]
@dragonwebeu try game with one monitor disabled see if it works.

**Comment by dragonwebeu** [comment]
> @dragonwebeu try game with one monitor disabled see if it works. which gpu & drivers you are using.
Still same, Even unplugged it from laptop.
Linux Open-source drivers. I have Nvidia GPU - 1GB Quadro FX 880M.

**Comment by mmtrt** [comment]
@dragonwebeu Install nvidia drivers then try again the game and most likely open source drivers are causing these graphical issues.

**Comment by freefri** [comment]
I have to say that I still have login in issues from time to time, here the command line output:
```
dnsapi:dns_map_options option DNS_QUERY_WIRE_ONLY not implemented
```

```
008b:fixme:kernelbase:AppPolicyGetThreadInitializationType 0xfffffffa, 0x3b2fea4
0088:fixme:process:SetProcessDEPPolicy (3): stub
0088:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0088:fixme:ntdll:EtwEventRegister ({d2d578d9-2936-45b6-a09f-30e32715f42d}, 0x101acae0, 0x1326caf8, 0x132e5d88) stub.
0088:fixme:gdi:GdiInitializeLanguagePack stub
0088:fixme:font:get_outline_text_metrics failed to read full_nameW for font L"Ani"!
004d:fixme:win:FlashWindowEx 0x32e658 - semi-stub
0066:fixme:winsock:GetAddrInfoExW Unsupported cancel handle
0066:fixme:dnsapi:dns_map_options option DNS_QUERY_WIRE_ONLY not implemented
0066:fixme:winsock:GetAddrInfoExW Unsupported cancel handle
0066:fixme:dnsapi:dns_map_options option DNS_QUERY_WIRE_ONLY not implemented
002d:fixme:ntdll:server_ioctl_file Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
002d:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
002d:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (_IOR('t', 123, 4))
00c6:fixme:thread:RtlCreateUserThread stack_reserve != 0 is unimplemented
00c6:fixme:thread:RtlCreateUserThread stack_reserve != 0 is unimplemented
00c6:fixme:thread:RtlCreateUserThread stack_reserve != 0 is unimplemented
00c6:fixme:thread:RtlCreateUserThread stack_reserve != 0 is unimplemented
00c6:fixme:thread:RtlCreateUserThread stack_reserve != 0 is unimplemented
0066:fixme:winsock:GetAddrInfoExW Unsupported cancel handle
0066:fixme:dnsapi:dns_map_options option DNS_QUERY_WIRE_ONLY not implemented
002d:fixme:ntdll:server_ioctl_file Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
002d:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
002d:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (_IOR('t', 123, 4))
0066:fixme:winsock:GetAddrInfoExW Unsupported cancel handle
0066:fixme:dnsapi:dns_map_options option DNS_QUERY_WIRE_ONLY not implemented
0066:fixme:winsock:GetAddrInfoExW Unsupported cancel handle
0066:fixme:dnsapi:dns_map_options option DNS_QUERY_WIRE_ONLY not implemented
0066:fixme:winsock:GetAddrInfoExW Unsupported cancel handle
0066:fixme:dnsapi:dns_map_options option DNS_QUERY_WIRE_ONLY not implemented
002d:fixme:ntdll:server_ioctl_file Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
002d:fixme:winsock:server_ioctl_sock Unsupported ioctl 4004747b (device=4004 access=1 func=d1e method=3)
002d:fixme:winsock:WSAIoctl unsupported WS_IOCTL cmd (_IOR('t', 123, 4))
```

**Comment by freefri** [comment]
In the last days, I'm not having issues connecting... maybe the issue was fixed and we can close it?
