### ISSUE TITLE
Fps dorps randomly

### ISSUE THREAD

**Issue by Enialixe** [mmtrt/leagueoflegends#28]
I'am run game in linux mint 19.1, wine 4.3 nvidia geforce 940 mx, nvidia-drivers-418. 
The nvidia video card is definitely used during the game, but micro-freezes occur periodically due to a fall in fps from 80-90 to 20. I tried to close the client during the game, set the fps limit to 60, this did not help. Maybe there is something else that I could do to prevent it? Thank you for your help.

**Comment by mmtrt** [comment]
maybe try running the game on different wine or application without this snap see if that solves performance issue.

**Comment by Enialixe** [comment]
Yes, I fixed it. Thank you and sorry for taking your time.
