### ISSUE TITLE
Bug with release 1.0 

### ISSUE THREAD

**Issue by cflemi12** [mmtrt/leagueoflegends#29]
`snap run leagueoflegends`

produces the error

`/snap/leagueoflegends/23/bin/sommelier: line 245: 13099 Segmentation fault      (core dumped) env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${WINE_EXE}"`

**Comment by dragonwebeu** [comment]
Same, seems something with wine-platform?

**Comment by cflemi12** [comment]
ah, i'm an idiot. it's solved in the previous bug thread. 
https://github.com/mmtrt/leagueoflegends/issues/27#issuecomment-471974532
