### ISSUE TITLE
Installer Downloads then Nothing Happens

### ISSUE THREAD

**Issue by Aerodin** [mmtrt/leagueoflegends#30]
Ubuntu 18.04.2.  This was working fine the last 2 weeks, then today the lobby would load but not the game.  

Uninstalled and reinstalled the snap to see if this would fix the issue, now it won't proceed to install the game after the download finishes.

**Comment by mmtrt** [comment]
make sure you have install latest revisions of snaps from edge

`snap refresh --edge wine-platform`
`snap refresh --edge --devmode leagueoflegends`

**Comment by Aerodin** [comment]
Tried that.

At least now an error shows up after the download finishes:
https://imgur.com/RiXoO3e

**Comment by mmtrt** [comment]
Thats weird never had that directx error, can you post 
`snap info leagueoflegends`
`snap info wine-platform`

**Comment by Aerodin** [comment]
Sure - info dump is below.

snap info leagueoflegends
name:      leagueoflegends
summary:   leagueoflegends is MOBA game developed and published by Riot Games.
publisher: Taqi Raza (mmtrt)
license:   unset
description: |
  * League of Legends is a 3D, third-person multiplayer online battle arena
  (MOBA) game. The game consists of 3 current running game modes: Summoner's
  Rift, Twisted Treeline, and Howling Abyss. Another game mode, The Crystal
  Scar, has since been removed. Players compete in matches, lasting anywhere
  from 20 to 60 minutes on average. In each game mode teams work together to
  achieve a victory condition, typically destroying the core building (called
  the Nexus) in the enemy team's base after bypassing a line of defensive
  structures called turrets, or towers.
  
  * In League of Legends, players assume the role of an unseen "summoner"
  that controls a "champion" with unique abilities and battle against a team
  of other players or computer-controlled champions. The goal is usually to
  destroy the opposing team's "nexus", a structure which lies at the heart of
  a base protected by defensive structures, although other distinct game
  modes exist as well. Each League of Legends match is discrete, with all
  champions starting off fairly weak but increasing in strength by
  accumulating items and experience over the course of the game. The
  champions and setting blend a variety of elements, including high fantasy,
  steampunk, and Lovecraftian horror.
  
  * League of Legends was generally well received upon its release in 2009,
  and has since grown in popularity, with an active and expansive fanbase. By
  July 2012, League of Legends was the most played PC game in North America
  and Europe in terms of the number of hours played. As of January 2014, over
  67 million people played League of Legends per month, 27 million per day,
  and over 7.5 million concurrently during peak hours. League has among the
  largest footprints of any game in streaming media communities on platforms
  such as YouTube and Twitch; it routinely ranks first in the most-watched
  hours. In September 2016 the company estimated that there are over 100
  million active players each month. The game's popularity has led it to
  expand into merchandise, with toys, accessories, apparel, as well as
  tie-ins to other media through music videos, web series, documentaries, and
  books.
commands:
  - leagueoflegends
  - leagueoflegends.wineboot
  - leagueoflegends.winecfg
  - leagueoflegends.winetricks
snap-id:      TnAzZk88wGeE2DHZLeX5DMJrAC5kdGj5
tracking:     edge
refresh-date: today at 23:10 PDT
channels:
  stable:    –                        
  candidate: –                        
  beta:      –                        
  edge:      1.0 2019-03-13 (25) 90kB devmode
installed:   1.0            (25) 90kB devmode

---------------------------------------------------------------------------

snap info wine-platform
name:      wine-platform
summary:   wine platform snap that provides WINE base for win application snaps
publisher: Taqi Raza (mmtrt)
contact:   https://github.com/mmtrt/wine-platform
license:   unset
description: |
  This snap provides WINE base via content interface to be used by other
  snaps that are depended on WINE so snap developers that create WINE snaps
  can leverage this base snap to connect their WINE snaps.
  
  Features:
  
  Snap provides WINE releases can be used by other snaps.
  
  • wine-stable
  • wine-devel
  • wine-staging
  
  Currently following snaps are using this snap:
  
  • anifx
  • anituner
  • cncra
  • cncra2yr
  • cnctsun
  • fooba2000
  • irfanview
  • leagueoflegends
  • liveforspeed
  • multicommander
  • notepad-plus-plus
  • notepad3
  • pspad
  • resourcehacker
  • utorrent
  • winsnap
  
  Note:  This snap does not provides any ability to run WIN applications from
  itself but it only shares libraries and WINE releases PATHS that are
  available via content interface.
snap-id:      V4TYgOiFFjZdiZB5hzH3TBJZl0FtxHfw
tracking:     edge
refresh-date: today at 22:39 PDT
channels:
  stable:    3.0.4-4.0 2019-02-20 (88) 430MB -
  candidate: ↑                               
  beta:      ↑                               
  edge:      3.0.4-4.3 2019-03-12 (96) 440MB -
installed:   3.0.4-4.3            (96) 440MB -

**Comment by mmtrt** [comment]
both snaps looks fine, but it looks like installer wants to run directx setup and fails miserably. which point that error shown can you tell if I could reproduce.

**Comment by Aerodin** [comment]
Install a fresh copy of the wine-platform snap and LeagueOfLegends snap in that order on Ubuntu 18.04.2 LTS.  Run League of Legends => League of Legends prompt to Select Game Installer Region comes up, Default NA option is fine, hit Install. => Download reaches 100%, box disappears => Error appears.

**Comment by mmtrt** [comment]
it is currently broken so rito have changed installers I've tested EUW NA same issue.

**Comment by mmtrt** [comment]
fixed that issue with recent `wine-platform` snap update now it should work fine. Please test and confirm it.

`snap refresh --edge wine-platform`

**Comment by Aerodin** [comment]
Can confirm from earlier this morning the issue is fixed.  Thanks!
