### ISSUE TITLE
Client Crashes on new update

### ISSUE THREAD

**Issue by Aerodin** [mmtrt/leagueoflegends#31]
Picture of the crash errors I'm getting on Ubuntu 18.04.2 LTS: 
https://i.imgur.com/yKPh5Mo.png

Unhandled exception: illegal instruction in 32-bit code (0x7eb3c0a1).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb3c0a1 ESP:0032f18c EBP:0032f1a8 EFLAGS:00010202(  R- --  I   - - - )
 EAX:7eb3c0ff EBX:7ea10000 ECX:00000000 EDX:00000001
 ESI:0032f2f9 EDI:7ffd8000
Stack dump:
0x0032f18c:  7e971004 00000000 00000000 0032f730
0x0032f19c:  7ea10000 0032f2f8 7ffd8000 0032f258
0x0032f1ac:  7e97192b 7eb3c0a0 00000000 00000000
0x0032f1bc:  0032f730 00000000 7bc62186 0032f1f0
0x0032f1cc:  0000006e 00000000 00000000 ffffffff
0x0032f1dc:  00000000 00000000 00000000 7eb3c0a0
Backtrace:
=>0 0x7eb3c0a1 WNetEnumCachedPasswords+0xf71() in mpr (0x0032f1a8)
  1 0x7e97192b HOOKPROC_wrapper+0x93a() in user32 (0x0032f258)
  2 0x7e971bd8 HOOKPROC_wrapper+0xbe7() in user32 (0x0032f538)
  3 0x7e972391 CallMsgFilterW+0x40() in user32 (0x0032f578)
  4 0x7e962030 IsDialogMessageW+0x7f() in user32 (0x0032f6f8)
  5 0x7e9628ec IsDialogMessageW+0x93b() in user32 (0x0032f768)
  6 0x7e962b0f DialogBoxParamW+0x9e() in user32 (0x0032f7a8)
  7 0x0040ce67 EntryPoint+0xffffffff() in bssndrpt (0x0032f914)
  8 0x00403c3b EntryPoint+0xffffffff() in bssndrpt (0x0032fe5c)
  9 0x004028f0 EntryPoint+0xffffffff() in bssndrpt (0x0032fe64)
  10 0x00423731 in bssndrpt (+0x23730) (0x0032feb0)
  11 0x7b4687b9 call_process_entry+0x18() in kernel32 (0x0032fed8)
  12 0x7b46a7da ExitProcess+0x200d() in kernel32 (0x0032ffd8)
  13 0x7b4687ca call_process_entry+0x29() in kernel32 (0x0032ffec)
0x7eb3c0a1 WNetEnumCachedPasswords+0xf71 in mpr: 	
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Export          bssndrpt
PE	  460000- 3a8c000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b804000	Dwarf           kernel32<elf>
  \-PE	7b420000-7b804000	\               kernel32
ELF	7bc00000-7bd38000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bd38000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d204000-7d230000	Deferred        iphlpapi<elf>
  \-PE	7d210000-7d230000	\               iphlpapi
ELF	7d276000-7d2b9000	Deferred        uxtheme<elf>
  \-PE	7d280000-7d2b9000	\               uxtheme
ELF	7d2bb000-7d2c2000	Deferred        libxfixes.so.3
ELF	7d2c2000-7d2ce000	Deferred        libxcursor.so.1
ELF	7d47f000-7d4b1000	Deferred        libexpat.so.1
ELF	7d4b1000-7d4fc000	Deferred        libfontconfig.so.1
ELF	7d4fc000-7dee5000	Deferred        shell32<elf>
  \-PE	7d510000-7dee5000	\               shell32
ELF	7df33000-7df6d000	Deferred        libpng16.so.16
ELF	7df6d000-7e02a000	Deferred        libfreetype.so.6
ELF	7e02a000-7e03d000	Deferred        libxi.so.6
ELF	7e03d000-7e041000	Deferred        libxcomposite.so.1
ELF	7e041000-7e04e000	Deferred        libxrandr.so.2
ELF	7e04e000-7e05a000	Deferred        libxrender.so.1
ELF	7e05a000-7e061000	Deferred        libxxf86vm.so.1
ELF	7e061000-7e065000	Deferred        libxinerama.so.1
ELF	7e065000-7e06f000	Deferred        librt.so.1
ELF	7e06f000-7e08a000	Deferred        libbsd.so.0
ELF	7e08a000-7e091000	Deferred        libxdmcp.so.6
ELF	7e091000-7e095000	Deferred        libxau.so.6
ELF	7e095000-7e0c1000	Deferred        libxcb.so.1
ELF	7e0c1000-7e20b000	Deferred        libx11.so.6
ELF	7e20b000-7e220000	Deferred        libxext.so.6
ELF	7e220000-7e2b2000	Deferred        winex11<elf>
  \-PE	7e230000-7e2b2000	\               winex11
ELF	7e2b2000-7e3dd000	Deferred        oleaut32<elf>
  \-PE	7e2d0000-7e3dd000	\               oleaut32
ELF	7e3dd000-7e415000	Deferred        ws2_32<elf>
  \-PE	7e3e0000-7e415000	\               ws2_32
ELF	7e415000-7e439000	Deferred        imm32<elf>
  \-PE	7e420000-7e439000	\               imm32
ELF	7e439000-7e47f000	Deferred        usp10<elf>
  \-PE	7e440000-7e47f000	\               usp10
ELF	7e47f000-7e5be000	Deferred        comctl32<elf>
  \-PE	7e490000-7e5be000	\               comctl32
ELF	7e5be000-7e5d9000	Deferred        aclui<elf>
  \-PE	7e5c0000-7e5d9000	\               aclui
ELF	7e5d9000-7e736000	Deferred        ole32<elf>
  \-PE	7e5f0000-7e736000	\               ole32
ELF	7e736000-7e75b000	Deferred        shcore<elf>
  \-PE	7e740000-7e75b000	\               shcore
ELF	7e75b000-7e7cd000	Deferred        shlwapi<elf>
  \-PE	7e770000-7e7cd000	\               shlwapi
ELF	7e7cd000-7e7e7000	Deferred        version<elf>
  \-PE	7e7d0000-7e7e7000	\               version
ELF	7e7e7000-7e918000	Deferred        gdi32<elf>
  \-PE	7e7f0000-7e918000	\               gdi32
ELF	7e918000-7eb26000	Dwarf           user32<elf>
  \-PE	7e930000-7eb26000	\               user32
ELF	7eb26000-7eb50000	Dwarf           mpr<elf>
  \-PE	7eb30000-7eb50000	\               mpr
ELF	7eb50000-7eb6f000	Deferred        libz.so.1
ELF	7eb6f000-7ebee000	Deferred        wininet<elf>
  \-PE	7eb80000-7ebee000	\               wininet
ELF	7ebee000-7ec6b000	Deferred        advapi32<elf>
  \-PE	7ec00000-7ec6b000	\               advapi32
ELF	7ec6b000-7ecf2000	Deferred        rpcrt4<elf>
  \-PE	7ec80000-7ecf2000	\               rpcrt4
ELF	7ecf2000-7ed06000	Deferred        libnss_files.so.2
ELF	7ed06000-7ed21000	Deferred        libnsl.so.1
ELF	7ed21000-7ed2f000	Deferred        libnss_nis.so.2
ELF	7ed2f000-7ed39000	Deferred        libnss_compat.so.2
ELF	7eeea000-7eefe000	Deferred        wow64cpu<elf>
  \-PE	7eef0000-7eefe000	\               wow64cpu
ELF	7eefe000-7f000000	Deferred        libm.so.6
ELF	f7ba6000-f7bab000	Deferred        libdl.so.2
ELF	f7bab000-f7d87000	Deferred        libc.so.6
ELF	f7d87000-f7da6000	Deferred        libpthread.so.0
ELF	f7da6000-f7f73000	Dwarf           libwine.so.1
ELF	f7f75000-f7f9d000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000023    0
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000024    0
	00000022    0
	00000021    0
	0000001f    0
00000025 explorer.exe
	00000029    0
	00000028    0
	00000027    0
	00000026    0
0000012d explorer.exe
	00000133    0
	00000132    0
	00000131    0
	0000012e    0
0000015a (D) C:\Riot Games\League of Legends\RADS\projects\league_client\releases\0.0.0.193\deploy\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\abarge\Temp\BsSndRpt.ini"  /dl]
	0000015b    0 <==
System information:
    Wine build: wine-4.4 (Staging)
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-46-generic

**Comment by mmtrt** [comment]
Rito Please!!!

`snap refresh --edge wine-platform`

should do the trick. :100:

**Comment by Aerodin** [comment]
Sweet, works now!  Thanks!
