### ISSUE TITLE
Fresh install, can't reach loading screen

### ISSUE THREAD

**Issue by exic** [mmtrt/leagueoflegends#32]
Hi, firstly, thanks for providing this!

I've installed as described here: http://ubuntuhandbook.org/index.php/2018/09/install-league-of-legends-ubuntu-snap/

Everything worked fine until I tried to start a practice mode game. I got a crash. Backtrace: [backtrace.txt](https://github.com/mmtrt/leagueoflegends/files/2997384/backtrace.txt)

Probably I am missing something? Do you need any more information? This is Ubuntu 18.10.

I tried `sudo snap refresh --edge wine-platform` because I read it in some other issue here but it didn't change anything.

Thanks in advance.

**Comment by mmtrt** [comment]
looks from backtrace that wineprefix is set to Version: Windows Server 2008 R2

can you set wineprefix os back to winxp by running

leagueoflegends.winecfg

**Comment by exic** [comment]
awesome <3 that fixed it!
