### ISSUE TITLE
Revert to Previous Patch Error then Offline Error

### ISSUE THREAD

**Issue by Aerodin** [mmtrt/leagueoflegends#33]
Ubuntu 18.04.2 LTS

Ran snap refresh wine-platform --edge
Ran snap refresh leagueoflegends --edge --devmode

Issue repeats every time I launch the game.

https://imgur.com/a/MWa5BkM

**Comment by mmtrt** [comment]
is this issue returned after league recent update?

**Comment by Aerodin** [comment]
Yes, it returned after the client patched today.

**Comment by mmtrt** [comment]
alright I've pushed revert wine-staging back to 4.4 it should be built after 10+min approx.

**Comment by vzsigmond** [comment]
The update didn't help in my case. Just updated wine-platform but the client is crashing with:

`wine: Unhandled page fault on write access to 0x7eb3f0a0 at address 0x7eb3f0a0 (thread 0146), starting debugger...`

Current versions:
`leagueoflegends       Ver: 1.0  Rev: 30`
`wine-platform        Ver: 3.0.4-4.4 Rev: 109`

**Comment by Aerodin** [comment]
The lobby issues are resolved, but the game won't load for it.

I get 2 Program Error Details boxes which I have pasted below.
Crash dump #1:
Unhandled exception: page fault on write access to 0x7eb460a0 in 32-bit code (0x7eb460a2).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb460a2 ESP:0032f18c EBP:0032f1a8 EFLAGS:00010286(  R- --  I S - -P- )
 EAX:7eb460a0 EBX:7ea16000 ECX:00000000 EDX:00000001
 ESI:0032f2f8 EDI:7ffd8000
Stack dump:
0x0032f18c:  7e977004 00000000 00000000 0032f730
0x0032f19c:  7ea16000 0032f2f8 7ffd8000 0032f258
0x0032f1ac:  7e97792b 7eb460a0 00000000 00000000
0x0032f1bc:  0032f730 00000000 7bc62186 0032f1f0
0x0032f1cc:  0000003b 00000000 00000000 ffffffff
0x0032f1dc:  00000000 00000000 00000000 7eb460a0
Backtrace:
=>0 0x7eb460a2 WNetGetConnectionA+0x162() in mpr (0x0032f1a8)
  1 0x0032f730 (0x0032f258)
  2 0x7e977bd8 HOOKPROC_wrapper+0xbe7() in user32 (0x0032f538)
  3 0x7e978391 CallMsgFilterW+0x40() in user32 (0x0032f578)
  4 0x7e968030 IsDialogMessageW+0x7f() in user32 (0x0032f6f8)
  5 0x7e9688ec IsDialogMessageW+0x93b() in user32 (0x0032f768)
  6 0x7e968b0f DialogBoxParamW+0x9e() in user32 (0x0032f7a8)
  7 0x0040ce67 EntryPoint+0xffffffff() in bssndrpt (0x0032f914)
  8 0x00403c3b EntryPoint+0xffffffff() in bssndrpt (0x0032fe5c)
  9 0x004028f0 EntryPoint+0xffffffff() in bssndrpt (0x0032fe64)
  10 0x00423731 in bssndrpt (+0x23730) (0x0032feb0)
  11 0x7b4687b9 call_process_entry+0x18() in kernel32 (0x0032fed8)
  12 0x7b46a7da ExitProcess+0x200d() in kernel32 (0x0032ffd8)
  13 0x7b4687ca call_process_entry+0x29() in kernel32 (0x0032ffec)
0x7eb460a2 WNetGetConnectionA+0x162 in mpr: addb	%al,0x0(%eax)
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Export          bssndrpt
PE	  460000- 3a8c000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b804000	Dwarf           kernel32<elf>
  \-PE	7b420000-7b804000	\               kernel32
ELF	7bc00000-7bd38000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bd38000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d34c000-7d378000	Deferred        iphlpapi<elf>
  \-PE	7d350000-7d378000	\               iphlpapi
ELF	7d3be000-7d401000	Deferred        uxtheme<elf>
  \-PE	7d3c0000-7d401000	\               uxtheme
ELF	7d403000-7d40a000	Deferred        libxfixes.so.3
ELF	7d40a000-7d416000	Deferred        libxcursor.so.1
ELF	7d4d3000-7d505000	Deferred        libexpat.so.1
ELF	7d505000-7d550000	Deferred        libfontconfig.so.1
ELF	7d550000-7d58a000	Deferred        libpng16.so.16
ELF	7d58a000-7d647000	Deferred        libfreetype.so.6
ELF	7d647000-7d65a000	Deferred        libxi.so.6
ELF	7d65a000-7d65e000	Deferred        libxcomposite.so.1
ELF	7d65e000-7d66b000	Deferred        libxrandr.so.2
ELF	7d66b000-7d677000	Deferred        libxrender.so.1
ELF	7d677000-7d67e000	Deferred        libxxf86vm.so.1
ELF	7d67e000-7d682000	Deferred        libxinerama.so.1
ELF	7d682000-7d68c000	Deferred        librt.so.1
ELF	7d68c000-7d6a7000	Deferred        libbsd.so.0
ELF	7d6a7000-7d6ae000	Deferred        libxdmcp.so.6
ELF	7d6ae000-7d6b2000	Deferred        libxau.so.6
ELF	7d6b2000-7d6de000	Deferred        libxcb.so.1
ELF	7d6de000-7d828000	Deferred        libx11.so.6
ELF	7d828000-7d83d000	Deferred        libxext.so.6
ELF	7d83d000-7d8cf000	Deferred        winex11<elf>
  \-PE	7d850000-7d8cf000	\               winex11
ELF	7d8cf000-7d9fa000	Deferred        oleaut32<elf>
  \-PE	7d8f0000-7d9fa000	\               oleaut32
ELF	7d9fa000-7da32000	Deferred        ws2_32<elf>
  \-PE	7da00000-7da32000	\               ws2_32
ELF	7da32000-7da56000	Deferred        imm32<elf>
  \-PE	7da40000-7da56000	\               imm32
ELF	7da56000-7da9c000	Deferred        usp10<elf>
  \-PE	7da60000-7da9c000	\               usp10
ELF	7da9c000-7dbdb000	Deferred        comctl32<elf>
  \-PE	7daa0000-7dbdb000	\               comctl32
ELF	7dbdb000-7dbf6000	Deferred        aclui<elf>
  \-PE	7dbe0000-7dbf6000	\               aclui
ELF	7dbf6000-7dd53000	Deferred        ole32<elf>
  \-PE	7dc10000-7dd53000	\               ole32
ELF	7dd53000-7dd78000	Deferred        shcore<elf>
  \-PE	7dd60000-7dd78000	\               shcore
ELF	7dd78000-7e761000	Deferred        shell32<elf>
  \-PE	7dd90000-7e761000	\               shell32
ELF	7e761000-7e7d3000	Deferred        shlwapi<elf>
  \-PE	7e770000-7e7d3000	\               shlwapi
ELF	7e7d3000-7e7ed000	Deferred        version<elf>
  \-PE	7e7e0000-7e7ed000	\               version
ELF	7e7ed000-7e91e000	Deferred        gdi32<elf>
  \-PE	7e800000-7e91e000	\               gdi32
ELF	7e91e000-7eb2c000	Dwarf           user32<elf>
  \-PE	7e930000-7eb2c000	\               user32
ELF	7eb2c000-7eb56000	Dwarf           mpr<elf>
  \-PE	7eb30000-7eb56000	\               mpr
ELF	7eb56000-7eb75000	Deferred        libz.so.1
ELF	7eb75000-7ebf4000	Deferred        wininet<elf>
  \-PE	7eb80000-7ebf4000	\               wininet
ELF	7ebf4000-7ec71000	Deferred        advapi32<elf>
  \-PE	7ec00000-7ec71000	\               advapi32
ELF	7ec71000-7ecf8000	Deferred        rpcrt4<elf>
  \-PE	7ec80000-7ecf8000	\               rpcrt4
ELF	7ecf8000-7ed0c000	Deferred        libnss_files.so.2
ELF	7ed0c000-7ed27000	Deferred        libnsl.so.1
ELF	7ed27000-7ed35000	Deferred        libnss_nis.so.2
ELF	7ed35000-7ed3f000	Deferred        libnss_compat.so.2
ELF	7eeea000-7eefe000	Deferred        wow64cpu<elf>
  \-PE	7eef0000-7eefe000	\               wow64cpu
ELF	7eefe000-7f000000	Deferred        libm.so.6
ELF	f7b6c000-f7b71000	Deferred        libdl.so.2
ELF	f7b71000-f7d4d000	Deferred        libc.so.6
ELF	f7d4d000-f7d6c000	Deferred        libpthread.so.0
ELF	f7d6c000-f7f39000	Dwarf           libwine.so.1
ELF	f7f3b000-f7f63000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000024 explorer.exe
	00000028    0
	00000027    0
	00000026    0
	00000025    0
0000002a LeagueClient.exe
	["C:/Riot Games/League of Legends/RADS/projects/league_client/releases/0.0.0.193/deploy/LeagueClient.exe" "--release=0.0.0.163"]
	000000e0    0
	000000dd    0
	0000007d    0
	0000007b    0
	0000007a    0
	00000076    0
	00000075    0
	00000074    0
	00000073    0
	00000072    0
	00000071   15
	00000070    0
	0000006f    0
	0000006e    0
	0000006d    0
	0000006b    0
	0000006a    0
	00000066    0
	00000065    0
	0000004b    0
	0000004a    0
	00000049    0
	00000048    0
	00000047    0
	00000046    0
	00000045    0
	00000044    0
	00000043    0
	00000042    0
	00000041    0
	00000040    0
	0000003f    0
	0000003e    0
	0000003d    0
	0000003c    0
	0000003b    0
	0000003a    0
	00000039    0
	00000038    0
	00000037    0
	00000036    0
	00000035    0
	00000034    0
	00000033    0
	00000032    0
	00000031    0
	00000030    0
	0000002f    0
	0000002e    0
	0000002d    0
	0000002c    0
	0000002b    0
00000119 League of Legends.exe
	["C:/Riot Games/League of Legends/RADS/solutions/lol_game_client_sln/releases/0.0.2.7/deploy/League of Legends.exe" "192.64.173.162 5151 ZXhFiNZZQlupu/RUx2Htkw== 20102954" "-PlayerID=20102954" "-GameID=3008892847" "-GameBaseDir=C:/Riot Games/League of Legends" "-Locale=en_US" "-SkipBuild" "-EnableLNP" "-UseNewX3D=1" "-UseNewX3DFramebuffers=1" "-RiotClientPort=41663" "-RiotClientAuthToken=CoRPRsk5iTIOHrx4dBZWwA"]
	00000121    0
	00000120    0
	0000011f    0
	0000011e    0
	0000011a    0
00000133 (D) C:\Riot Games\League of Legends\RADS\projects\league_client\releases\0.0.0.193\deploy\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\abarge\Temp\BsSndRpt.ini"  /dl]
	00000134    0 <==
00000138 LeagueClientUx.exe
	["C:/Riot Games/League of Legends/RADS/projects/league_client/releases/0.0.0.193/deploy/LeagueClientUx.exe" "--release=0.0.0.163" "--rads-product-directory=C:/Riot Games/League of Legends/RADS/solutions/league_client_sln/releases/0.0.0.163/deploy/" "--remoting-auth-token=CoRPRsk5iTIOHrx4dBZWwA" "--respawn-command=LeagueClient.exe" "--respawn-display-name=League of Legends" "--app-port=41663" "--install-directory=C:/Riot Games/League of Legends/" "--app-name=LeagueClient" "--ux-name=LeagueClientUx" "--ux-helper-name=LeagueClientUxHelper" "--log-dir=LeagueClient Logs" "--bugsplat-name=league_client_riotgames_com" "--bugsplat-platform-id=NA1" "--app-log-file-path=C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-03-28T21-03-51_42_LeagueClient.log" "--app-pid=42" "--no-proxy-server"]
	00000155    0
	00000154    0
	00000153    0
	00000152    0
	00000151    0
	00000150    0
	0000014f    0
	0000014e    0
	0000014d    0
	0000014c    0
	0000014b    0
	0000014a    0
	00000149    0
	00000148    0
	00000147    0
	00000146    0
	00000145    0
	00000144    0
	00000143    0
	00000142    0
	00000141    0
	00000140    0
	0000013f    0
	00000139    0
0000013a explorer.exe
	0000013e    0
	0000013d    0
	0000013c    0
	0000013b    0
System information:
    Wine build: wine-4.4 (Staging)
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-46-generic

Crash Dump #2
Unhandled exception: page fault on read access to 0x2c000010 in 32-bit code (0x7eb460c8).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb460c8 ESP:0032f18c EBP:0032f1a8 EFLAGS:00010a03(  R- --O I   - - -C)
 EAX:7eb46093 EBX:7ea0f000 ECX:00000000 EDX:00000001
 ESI:0032f2f8 EDI:7ffd8000
Stack dump:
0x0032f18c:  7e970004 00000000 00000000 0032f730
0x0032f19c:  7ea0f000 0032f2f8 7ffd8000 0032f258
0x0032f1ac:  7e97092b 7eb460a0 00000000 00000000
0x0032f1bc:  0032f730 00000000 7bc62186 0032f1f0
0x0032f1cc:  0000005a 00000000 00000000 ffffffff
0x0032f1dc:  00000000 00000000 00000000 7eb460a0
Backtrace:
=>0 0x7eb460c8 in mpr (+0x160c8) (0x0032f1a8)
  1 0x7e97092b HOOKPROC_wrapper+0x93a() in user32 (0x0032f258)
  2 0x7e970bd8 HOOKPROC_wrapper+0xbe7() in user32 (0x0032f538)
  3 0x7e971391 CallMsgFilterW+0x40() in user32 (0x0032f578)
  4 0x7e961030 IsDialogMessageW+0x7f() in user32 (0x0032f6f8)
  5 0x7e9618ec IsDialogMessageW+0x93b() in user32 (0x0032f768)
  6 0x7e961b0f DialogBoxParamW+0x9e() in user32 (0x0032f7a8)
  7 0x0040ce67 EntryPoint+0xffffffff() in bssndrpt (0x0032f914)
  8 0x00403c3b EntryPoint+0xffffffff() in bssndrpt (0x0032fe5c)
  9 0x004028f0 EntryPoint+0xffffffff() in bssndrpt (0x0032fe64)
  10 0x00423731 in bssndrpt (+0x23730) (0x0032feb0)
  11 0x7b4687b9 call_process_entry+0x18() in kernel32 (0x0032fed8)
  12 0x7b46a7da ExitProcess+0x200d() in kernel32 (0x0032ffd8)
  13 0x7b4687ca call_process_entry+0x29() in kernel32 (0x0032ffec)
0x7eb460c8: movb	0x2c000010,%al
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Export          bssndrpt
PE	  460000- 3a8c000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b804000	Dwarf           kernel32<elf>
  \-PE	7b420000-7b804000	\               kernel32
ELF	7bc00000-7bd38000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bd38000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d345000-7d371000	Deferred        iphlpapi<elf>
  \-PE	7d350000-7d371000	\               iphlpapi
ELF	7d3b7000-7d3fa000	Deferred        uxtheme<elf>
  \-PE	7d3c0000-7d3fa000	\               uxtheme
ELF	7d3fc000-7d403000	Deferred        libxfixes.so.3
ELF	7d403000-7d40f000	Deferred        libxcursor.so.1
ELF	7d4cc000-7d4fe000	Deferred        libexpat.so.1
ELF	7d4fe000-7d549000	Deferred        libfontconfig.so.1
ELF	7d549000-7d583000	Deferred        libpng16.so.16
ELF	7d583000-7d640000	Deferred        libfreetype.so.6
ELF	7d640000-7d653000	Deferred        libxi.so.6
ELF	7d653000-7d657000	Deferred        libxcomposite.so.1
ELF	7d657000-7d664000	Deferred        libxrandr.so.2
ELF	7d664000-7d670000	Deferred        libxrender.so.1
ELF	7d670000-7d677000	Deferred        libxxf86vm.so.1
ELF	7d677000-7d67b000	Deferred        libxinerama.so.1
ELF	7d67b000-7d685000	Deferred        librt.so.1
ELF	7d685000-7d6a0000	Deferred        libbsd.so.0
ELF	7d6a0000-7d6a7000	Deferred        libxdmcp.so.6
ELF	7d6a7000-7d6ab000	Deferred        libxau.so.6
ELF	7d6ab000-7d6d7000	Deferred        libxcb.so.1
ELF	7d6d7000-7d821000	Deferred        libx11.so.6
ELF	7d821000-7d836000	Deferred        libxext.so.6
ELF	7d836000-7d8c8000	Deferred        winex11<elf>
  \-PE	7d840000-7d8c8000	\               winex11
ELF	7d8c8000-7d9f3000	Deferred        oleaut32<elf>
  \-PE	7d8e0000-7d9f3000	\               oleaut32
ELF	7d9f3000-7da2b000	Deferred        ws2_32<elf>
  \-PE	7da00000-7da2b000	\               ws2_32
ELF	7da2b000-7da4f000	Deferred        imm32<elf>
  \-PE	7da30000-7da4f000	\               imm32
ELF	7da4f000-7da95000	Deferred        usp10<elf>
  \-PE	7da60000-7da95000	\               usp10
ELF	7da95000-7dbd4000	Deferred        comctl32<elf>
  \-PE	7daa0000-7dbd4000	\               comctl32
ELF	7dbd4000-7dbef000	Deferred        aclui<elf>
  \-PE	7dbe0000-7dbef000	\               aclui
ELF	7dbef000-7dd4c000	Deferred        ole32<elf>
  \-PE	7dc10000-7dd4c000	\               ole32
ELF	7dd4c000-7dd71000	Deferred        shcore<elf>
  \-PE	7dd50000-7dd71000	\               shcore
ELF	7dd71000-7e75a000	Deferred        shell32<elf>
  \-PE	7dd80000-7e75a000	\               shell32
ELF	7e75a000-7e7cc000	Deferred        shlwapi<elf>
  \-PE	7e770000-7e7cc000	\               shlwapi
ELF	7e7cc000-7e7e6000	Deferred        version<elf>
  \-PE	7e7d0000-7e7e6000	\               version
ELF	7e7e6000-7e917000	Deferred        gdi32<elf>
  \-PE	7e7f0000-7e917000	\               gdi32
ELF	7e917000-7eb25000	Dwarf           user32<elf>
  \-PE	7e930000-7eb25000	\               user32
ELF	7eb25000-7eb4f000	Dwarf           mpr<elf>
  \-PE	7eb30000-7eb4f000	\               mpr
ELF	7eb4f000-7eb6e000	Deferred        libz.so.1
ELF	7eb6e000-7ebed000	Deferred        wininet<elf>
  \-PE	7eb80000-7ebed000	\               wininet
ELF	7ebed000-7ec6a000	Deferred        advapi32<elf>
  \-PE	7ec00000-7ec6a000	\               advapi32
ELF	7ec6a000-7ecf1000	Deferred        rpcrt4<elf>
  \-PE	7ec80000-7ecf1000	\               rpcrt4
ELF	7ecf1000-7ed05000	Deferred        libnss_files.so.2
ELF	7ed05000-7ed20000	Deferred        libnsl.so.1
ELF	7ed20000-7ed2e000	Deferred        libnss_nis.so.2
ELF	7ed2e000-7ed38000	Deferred        libnss_compat.so.2
ELF	7eeea000-7eefe000	Deferred        wow64cpu<elf>
  \-PE	7eef0000-7eefe000	\               wow64cpu
ELF	7eefe000-7f000000	Deferred        libm.so.6
ELF	f7b05000-f7b0a000	Deferred        libdl.so.2
ELF	f7b0a000-f7ce6000	Deferred        libc.so.6
ELF	f7ce6000-f7d05000	Deferred        libpthread.so.0
ELF	f7d05000-f7ed2000	Dwarf           libwine.so.1
ELF	f7ed4000-f7efc000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000024 explorer.exe
	00000028    0
	00000027    0
	00000026    0
	00000025    0
00000119 League of Legends.exe
	["C:/Riot Games/League of Legends/RADS/solutions/lol_game_client_sln/releases/0.0.2.7/deploy/League of Legends.exe" "192.64.173.162 5151 ZXhFiNZZQlupu/RUx2Htkw== 20102954" "-PlayerID=20102954" "-GameID=3008892847" "-GameBaseDir=C:/Riot Games/League of Legends" "-Locale=en_US" "-SkipBuild" "-EnableLNP" "-UseNewX3D=1" "-UseNewX3DFramebuffers=1" "-RiotClientPort=41663" "-RiotClientAuthToken=CoRPRsk5iTIOHrx4dBZWwA"]
	00000121    0
	00000120    0
	0000011f    0
	0000011e    0
	0000011a    0
0000013a explorer.exe
	0000013e    0
	0000013d    0
	0000013c    0
	0000013b    0
0000015a (D) C:\Riot Games\League of Legends\RADS\projects\league_client\releases\0.0.0.193\deploy\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\abarge\Temp\BsSndRpt.ini"  /dl]
	0000015b    0 <==
System information:
    Wine build: wine-4.4 (Staging)
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-46-generic

**Comment by mmtrt** [comment]
I'm afraid game is totally broken in 4.4 but works fine with 4.0 apart from login issues which are seen on Debian based distros so I'm not able reproduce that login issue here.

**Comment by Aerodin** [comment]
Latest changes work for me with no issues so far.
