### ISSUE TITLE
Crashes on game start (immediately after champ select)

### ISSUE THREAD

**Issue by dlahman** [mmtrt/leagueoflegends#35]
There must have been a patch that came out today - everything was working fine up until this evening. The client works, but as soon as champ select finishes, the game crashes and starts spitting up error logs. Is anyone else running into this issue?

**Comment by freefri** [comment]
Same here. Hard crash with ram dump when going to game load screen

**Comment by iagogutierre** [comment]
same here.

**Comment by mmtrt** [comment]
works fine here after reverting wine-staging to `4.0` on `wine-platform` snap.

**Comment by freefri** [comment]
How can we revert to `4.0`?

**Comment by freefri** [comment]
I've just refreshed the snap `snap refresh --edge --devmode leagueoflegends` and it worked

**Comment by dlahman** [comment]
For whatever reason, doing that didn't fix it immediately. But it mysteriously started working again the next day(?). Thanks for the help! (I think!)

**Comment by freefri** [comment]
I think we can close this issue since it is no longer up to date @dlahman
