### ISSUE TITLE
Very laggy 

### ISSUE THREAD

**Issue by alibabaei12** [mmtrt/leagueoflegends#36]
I was finally able to fix the crashing issue when starting but now when I am in the game, I'm very laggy and it has nothing to do with my internet.

**Comment by mmtrt** [comment]
can you post system specs and also gpu drivers that you are using.

**Comment by mjuraszek** [comment]
well im very laggy too

**Comment by mmtrt** [comment]
check cpu usage sometimes league launcher uses 100% cpu for no reason so relaunching it fixes that issue.
