### ISSUE TITLE
Client does not load at all

### ISSUE THREAD

**Issue by BeratAdemi** [mmtrt/leagueoflegends#37]
As soon as the client loads, the snap just works amazingly well for me.

The bug:
Sometimes, if I start my PC and try to launch the snap, the LoL logo, wich you see before the client opens, does not display and the client dos not open at all. There is a Wine process running but nothing happens. I tried waiting for quite some time. Unfortunately this bug does not seem to be reproducible. It appears to be at random times for no specific reason.
I'm willing to test this some more, so if you can tell me, how I can figure out what the problem is, I'm very happy to help. 
Right now, I just don't know where logs might be and I can't really thing of a reason for the bug.

**Comment by mmtrt** [comment]
Yes client does that sometimes but you can close game process then start over, its usually game client hangs or timeout to ip connections. Literally could be many things idk either what causing the problem in wine.

**Comment by turtle-bazon** [comment]
That also often happens on windows client. Simply you should close all league processes and launch again. Said, but true.

**Comment by BeratAdemi** [comment]
Ok thank you guys :) I just wanted to mention it here, because there wasn't anything about it in the other issues. I'll close the issue then.
