### ISSUE TITLE
Crashing during Load Screen (About 3% of the time)

### ISSUE THREAD

**Issue by Aerodin** [mmtrt/leagueoflegends#38]
Ubuntu - 18.04

Crash Dump
----------------
Unhandled exception: page fault on write access to 0x7eb05760 in 32-bit code (0x7eb05760).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb05760 ESP:0032f18c EBP:0032f1a8 EFLAGS:00010202(  R- --  I   - - - )
 EAX:7eb05760 EBX:7e9a8000 ECX:00000000 EDX:00000001
 ESI:0032f2f8 EDI:7ffd8000
Stack dump:
0x0032f18c:  7e8f0ca4 00000000 00000000 0032f730
0x0032f19c:  7e9a8000 0032f2f8 7ffd8000 0032f258
0x0032f1ac:  7e8f1c93 7eb05760 00000000 00000000
0x0032f1bc:  0032f730 00000000 0019e678 7e8b98d1
0x0032f1cc:  7e942acc 00000000 00000000 ffffffff
0x0032f1dc:  00000000 00000470 00000000 7eb05760
Backtrace:
=>0 0x7eb05760 zError+0xffffffff() in libz.so.1 (0x0032f1a8)
  1 0x7e8b98d1 CreateCaret+0xffffffff() in user32 (0x0019e678)
  2 0x7e942acc UserRealizePalette+0xbcb() in user32 (0x0019e678)
  3 0x00110328 (0x00110328)
  4 0x0019e678 (0x0019e678)
  5 0x00110328 (0x00110328)
  6 0x0019e678 (0x0019e678)
  7 0x00110328 (0x00110328)
  8 0x0019e678 (0x0019e678)
  9 0x00110328 (0x00110328)
  10 0x0019e678 (0x0019e678)
  11 0x00110328 (0x00110328)
  12 0x0019e678 (0x0019e678)
  13 0x00110328 (0x00110328)
  14 0x0019e678 (0x0019e678)
  15 0x00110328 (0x00110328)
  16 0x0019e678 (0x0019e678)
  17 0x00110328 (0x00110328)
  18 0x0019e678 (0x0019e678)
  19 0x00110328 (0x00110328)
  20 0x0019e678 (0x0019e678)
  21 0x00110328 (0x00110328)
  22 0x0019e678 (0x0019e678)
  23 0x00110328 (0x00110328)
  24 0x0019e678 (0x0019e678)
  25 0x00110328 (0x00110328)
  26 0x0019e678 (0x0019e678)
  27 0x00110328 (0x00110328)
  28 0x0019e678 (0x0019e678)
  29 0x00110328 (0x00110328)
  30 0x0019e678 (0x0019e678)
  31 0x00110328 (0x00110328)
  32 0x0019e678 (0x0019e678)
  33 0x00110328 (0x00110328)
  34 0x0019e678 (0x0019e678)
  35 0x00110328 (0x00110328)
  36 0x0019e678 (0x0019e678)
  37 0x00110328 (0x00110328)
  38 0x0019e678 (0x0019e678)
  39 0x00110328 (0x00110328)
  40 0x0019e678 (0x0019e678)
  41 0x00110328 (0x00110328)
  42 0x0019e678 (0x0019e678)
  43 0x00110328 (0x00110328)
  44 0x0019e678 (0x0019e678)
  45 0x00110328 (0x00110328)
  46 0x0019e678 (0x0019e678)
  47 0x00110328 (0x00110328)
  48 0x0019e678 (0x0019e678)
  49 0x00110328 (0x00110328)
  50 0x0019e678 (0x0019e678)
  51 0x00110328 (0x00110328)
  52 0x0019e678 (0x0019e678)
  53 0x00110328 (0x00110328)
  54 0x0019e678 (0x0019e678)
  55 0x00110328 (0x00110328)
  56 0x0019e678 (0x0019e678)
  57 0x00110328 (0x00110328)
  58 0x0019e678 (0x0019e678)
  59 0x00110328 (0x00110328)
  60 0x0019e678 (0x0019e678)
  61 0x00110328 (0x00110328)
  62 0x0019e678 (0x0019e678)
  63 0x00110328 (0x00110328)
  64 0x0019e678 (0x0019e678)
  65 0x00110328 (0x00110328)
  66 0x0019e678 (0x0019e678)
  67 0x00110328 (0x00110328)
  68 0x0019e678 (0x0019e678)
  69 0x00110328 (0x00110328)
  70 0x0019e678 (0x0019e678)
  71 0x00110328 (0x00110328)
  72 0x0019e678 (0x0019e678)
  73 0x00110328 (0x00110328)
  74 0x0019e678 (0x0019e678)
  75 0x00110328 (0x00110328)
  76 0x0019e678 (0x0019e678)
  77 0x00110328 (0x00110328)
  78 0x0019e678 (0x0019e678)
  79 0x00110328 (0x00110328)
  80 0x0019e678 (0x0019e678)
  81 0x00110328 (0x00110328)
  82 0x0019e678 (0x0019e678)
  83 0x00110328 (0x00110328)
  84 0x0019e678 (0x0019e678)
  85 0x00110328 (0x00110328)
  86 0x0019e678 (0x0019e678)
  87 0x00110328 (0x00110328)
  88 0x0019e678 (0x0019e678)
  89 0x00110328 (0x00110328)
  90 0x0019e678 (0x0019e678)
  91 0x00110328 (0x00110328)
  92 0x0019e678 (0x0019e678)
  93 0x00110328 (0x00110328)
  94 0x0019e678 (0x0019e678)
  95 0x00110328 (0x00110328)
  96 0x0019e678 (0x0019e678)
  97 0x00110328 (0x00110328)
  98 0x0019e678 (0x0019e678)
  99 0x00110328 (0x00110328)
  100 0x0019e678 (0x0019e678)
  101 0x00110328 (0x00110328)
  102 0x0019e678 (0x0019e678)
  103 0x00110328 (0x00110328)
  104 0x0019e678 (0x0019e678)
  105 0x00110328 (0x00110328)
  106 0x0019e678 (0x0019e678)
  107 0x00110328 (0x00110328)
  108 0x0019e678 (0x0019e678)
  109 0x00110328 (0x00110328)
  110 0x0019e678 (0x0019e678)
  111 0x00110328 (0x00110328)
  112 0x0019e678 (0x0019e678)
  113 0x00110328 (0x00110328)
  114 0x0019e678 (0x0019e678)
  115 0x00110328 (0x00110328)
  116 0x0019e678 (0x0019e678)
  117 0x00110328 (0x00110328)
  118 0x0019e678 (0x0019e678)
  119 0x00110328 (0x00110328)
  120 0x0019e678 (0x0019e678)
  121 0x00110328 (0x00110328)
  122 0x0019e678 (0x0019e678)
  123 0x00110328 (0x00110328)
  124 0x0019e678 (0x0019e678)
  125 0x00110328 (0x00110328)
  126 0x0019e678 (0x0019e678)
  127 0x00110328 (0x00110328)
  128 0x0019e678 (0x0019e678)
  129 0x00110328 (0x00110328)
  130 0x0019e678 (0x0019e678)
  131 0x00110328 (0x00110328)
  132 0x0019e678 (0x0019e678)
  133 0x00110328 (0x00110328)
  134 0x0019e678 (0x0019e678)
  135 0x00110328 (0x00110328)
  136 0x0019e678 (0x0019e678)
  137 0x00110328 (0x00110328)
  138 0x0019e678 (0x0019e678)
  139 0x00110328 (0x00110328)
  140 0x0019e678 (0x0019e678)
  141 0x00110328 (0x00110328)
  142 0x0019e678 (0x0019e678)
  143 0x00110328 (0x00110328)
  144 0x0019e678 (0x0019e678)
  145 0x00110328 (0x00110328)
  146 0x0019e678 (0x0019e678)
  147 0x00110328 (0x00110328)
  148 0x0019e678 (0x0019e678)
  149 0x00110328 (0x00110328)
  150 0x0019e678 (0x0019e678)
  151 0x00110328 (0x00110328)
  152 0x0019e678 (0x0019e678)
  153 0x00110328 (0x00110328)
  154 0x0019e678 (0x0019e678)
  155 0x00110328 (0x00110328)
  156 0x0019e678 (0x0019e678)
  157 0x00110328 (0x00110328)
  158 0x0019e678 (0x0019e678)
  159 0x00110328 (0x00110328)
  160 0x0019e678 (0x0019e678)
  161 0x00110328 (0x00110328)
  162 0x0019e678 (0x0019e678)
  163 0x00110328 (0x00110328)
  164 0x0019e678 (0x0019e678)
  165 0x00110328 (0x00110328)
  166 0x0019e678 (0x0019e678)
  167 0x00110328 (0x00110328)
  168 0x0019e678 (0x0019e678)
  169 0x00110328 (0x00110328)
  170 0x0019e678 (0x0019e678)
  171 0x00110328 (0x00110328)
  172 0x0019e678 (0x0019e678)
  173 0x00110328 (0x00110328)
  174 0x0019e678 (0x0019e678)
  175 0x00110328 (0x00110328)
  176 0x0019e678 (0x0019e678)
  177 0x00110328 (0x00110328)
  178 0x0019e678 (0x0019e678)
  179 0x00110328 (0x00110328)
  180 0x0019e678 (0x0019e678)
  181 0x00110328 (0x00110328)
  182 0x0019e678 (0x0019e678)
  183 0x00110328 (0x00110328)
  184 0x0019e678 (0x0019e678)
  185 0x00110328 (0x00110328)
  186 0x0019e678 (0x0019e678)
  187 0x00110328 (0x00110328)
  188 0x0019e678 (0x0019e678)
  189 0x00110328 (0x00110328)
  190 0x0019e678 (0x0019e678)
  191 0x00110328 (0x00110328)
  192 0x0019e678 (0x0019e678)
  193 0x00110328 (0x00110328)
  194 0x0019e678 (0x0019e678)
  195 0x00110328 (0x00110328)
  196 0x0019e678 (0x0019e678)
  197 0x00110328 (0x00110328)
  198 0x0019e678 (0x0019e678)
  199 0x00110328 (0x00110328)
  200 0x0019e678 (0x0019e678)
0x7eb05760 zError+0xffffffff in libz.so.1: addl	%eax,0x0(%eax)
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Deferred        bssndrpt
PE	  460000- 3a77000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b834000	Deferred        kernel32<elf>
  \-PE	7b420000-7b834000	\               kernel32
ELF	7bc00000-7bd6e000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bd6e000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d1b9000-7d1e6000	Deferred        iphlpapi<elf>
  \-PE	7d1c0000-7d1e6000	\               iphlpapi
ELF	7d22c000-7d274000	Deferred        uxtheme<elf>
  \-PE	7d230000-7d274000	\               uxtheme
ELF	7d276000-7d27d000	Deferred        libxfixes.so.3
ELF	7d27d000-7d289000	Deferred        libxcursor.so.1
ELF	7d349000-7d37b000	Deferred        libexpat.so.1
ELF	7d37b000-7d3c6000	Deferred        libfontconfig.so.1
ELF	7d3c6000-7d400000	Deferred        libpng16.so.16
ELF	7d400000-7d4bd000	Deferred        libfreetype.so.6
ELF	7d4bd000-7d4d0000	Deferred        libxi.so.6
ELF	7d4d0000-7d4d4000	Deferred        libxcomposite.so.1
ELF	7d4d4000-7d4e1000	Deferred        libxrandr.so.2
ELF	7d4e1000-7d4ed000	Deferred        libxrender.so.1
ELF	7d4ed000-7d4f4000	Deferred        libxxf86vm.so.1
ELF	7d4f4000-7d4f8000	Deferred        libxinerama.so.1
ELF	7d4f8000-7d513000	Deferred        libbsd.so.0
ELF	7d513000-7d51a000	Deferred        libxdmcp.so.6
ELF	7d51a000-7d51e000	Deferred        libxau.so.6
ELF	7d51e000-7d54a000	Deferred        libxcb.so.1
ELF	7d54a000-7d694000	Deferred        libx11.so.6
ELF	7d694000-7d6a9000	Deferred        libxext.so.6
ELF	7d6a9000-7d750000	Deferred        winex11<elf>
  \-PE	7d6b0000-7d750000	\               winex11
ELF	7d750000-7d895000	Deferred        oleaut32<elf>
  \-PE	7d770000-7d895000	\               oleaut32
ELF	7d895000-7d8cf000	Deferred        ws2_32<elf>
  \-PE	7d8a0000-7d8cf000	\               ws2_32
ELF	7d8cf000-7d8f4000	Deferred        imm32<elf>
  \-PE	7d8e0000-7d8f4000	\               imm32
ELF	7d8f4000-7d94b000	Deferred        usp10<elf>
  \-PE	7d900000-7d94b000	\               usp10
ELF	7d94b000-7daaa000	Deferred        comctl32<elf>
  \-PE	7d950000-7daaa000	\               comctl32
ELF	7daaa000-7dac5000	Deferred        aclui<elf>
  \-PE	7dab0000-7dac5000	\               aclui
ELF	7dac5000-7dc3a000	Deferred        ole32<elf>
  \-PE	7dae0000-7dc3a000	\               ole32
ELF	7dc3a000-7dc6d000	Deferred        shcore<elf>
  \-PE	7dc40000-7dc6d000	\               shcore
ELF	7dc6d000-7e68e000	Deferred        shell32<elf>
  \-PE	7dc80000-7e68e000	\               shell32
ELF	7e68e000-7e71b000	Deferred        shlwapi<elf>
  \-PE	7e6a0000-7e71b000	\               shlwapi
ELF	7e71b000-7e746000	Deferred        version<elf>
  \-PE	7e720000-7e746000	\               version
ELF	7e746000-7e892000	Deferred        gdi32<elf>
  \-PE	7e750000-7e892000	\               gdi32
ELF	7e892000-7eabe000	Dwarf           user32<elf>
  \-PE	7e8b0000-7eabe000	\               user32
ELF	7eabe000-7eaf9000	Deferred        mpr<elf>
  \-PE	7eac0000-7eaf9000	\               mpr
ELF	7eaf9000-7eb18000	Dwarf           libz.so.1
ELF	7eb18000-7ebb4000	Deferred        wininet<elf>
  \-PE	7eb20000-7ebb4000	\               wininet
ELF	7ebb4000-7ec49000	Deferred        advapi32<elf>
  \-PE	7ebc0000-7ec49000	\               advapi32
ELF	7ec49000-7ece5000	Deferred        rpcrt4<elf>
  \-PE	7ec50000-7ece5000	\               rpcrt4
ELF	7ece5000-7ecf9000	Deferred        libnss_files.so.2
ELF	7ecf9000-7ed14000	Deferred        libnsl.so.1
ELF	7ed14000-7ed22000	Deferred        libnss_nis.so.2
ELF	7ed22000-7ed2c000	Deferred        libnss_compat.so.2
ELF	7eee0000-7eef4000	Deferred        wow64cpu<elf>
  \-PE	7eef0000-7eef4000	\               wow64cpu
ELF	7eef4000-7eff6000	Deferred        libm.so.6
ELF	7eff6000-7f000000	Deferred        librt.so.1
ELF	f7b23000-f7b28000	Deferred        libdl.so.2
ELF	f7b28000-f7d04000	Deferred        libc.so.6
ELF	f7d04000-f7d23000	Deferred        libpthread.so.0
ELF	f7d23000-f7eec000	Dwarf           libwine.so.1
ELF	f7eee000-f7f16000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000024 explorer.exe
	00000028    0
	00000027    0
	00000026    0
	00000025    0
0000002a LeagueClient.exe
	["C:/Riot Games/League of Legends/RADS/projects/league_client/releases/0.0.0.200/deploy/LeagueClient.exe" "--release=0.0.0.170"]
	000000f8    0
	000000f5    0
	00000081    0
	0000007f    0
	0000007e    0
	0000007b    0
	00000079    0
	00000078    0
	00000077    0
	00000076    0
	00000075   15
	00000074    0
	00000073    0
	00000072    0
	00000071    0
	0000006e    0
	0000006c    0
	00000069    0
	00000054    0
	00000053    0
	0000004c    0
	0000004b    0
	0000004a    0
	00000049    0
	00000048    0
	00000047    0
	00000046    0
	00000045    0
	00000044    0
	00000043    0
	00000042    0
	00000041    0
	00000040    0
	0000003f    0
	0000003e    0
	0000003d    0
	0000003c    0
	0000003b    0
	0000003a    0
	00000039    0
	00000038    0
	00000037    0
	00000036    0
	00000035    0
	00000034    0
	00000033    0
	00000032    0
	00000031    0
	00000030    0
	0000002f    0
	0000002e    0
	0000002d    0
	0000002c    0
	0000002b    0
00000089 LeagueClientUxRender.exe
	[LeagueClientUxRender.exe --type=renderer --no-sandbox --disable-databases --lang=en-US --lang=en-US --log-file="C:\Riot Games\League of Legends\RADS\projects\league_client\releases\0.0.0.200\deploy\debug.log" --disable-spell-checking --device-scale-factor=1 --num-raster-threads=4 --content-image-texture-target=3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553,3553 --video-image-texture-target=3553 --disable-accelerated-video-decode --disable-webrtc-hw-encoding --disable-gpu-compositing --channel="77.0.1160722908\195403276" /prefetch:1 --app-name=LeagueClient --ux-name=LeagueClientUx --ux-helper-name=LeagueClientUxHelper --log-dir="LeagueClient Logs" --bugsplat-name=league_client_riotgames_com --app-port=42181 --bugsplat-platform-id=NA1 --app-log-file-path="C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-05-09T09-03-03_42_LeagueClient.log" --primary-ux-log-file-path="C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-05-09T09-03-05_77_LeagueClientUx.log"]
	000001ef    0
	00000188    0
	000001f2    0
	000000fc    0
	0000023a    0
	00000145    0
	00000157    0
	000000fa    0
	0000027a    0
	00000301    0
	00000306    0
	00000300    0
	000002ff    0
	000002bd    0
	00000205    0
	00000015    0
	000000c4    0
	000000d2    0
	0000019b    0
	00000266    0
	0000026f    0
	000002ec    0
	00000222    0
	000002b1    0
	00000239    0
	00000158    0
	00000235    0
	0000026a    0
	000002cd    0
	0000027c    0
	000001d4    0
	00000248    0
	00000285    0
	00000214    0
	00000153    0
	0000010f    0
	000002b0    0
	00000277    0
	00000276    0
	000002e3    0
	000000f7    0
	00000174    0
	000000f6    0
	0000019e    0
	00000234    0
	00000147    0
	000001a0    0
	00000252    0
	0000013e    0
	0000015e    0
	000000ac    0
	000000bc    0
	000000bb    0
	000000e9    0
	000000b7    0
	000000b8    0
	000000ef    0
	00000175    0
	0000015a    0
	00000159    0
	000001d2    0
	000001fa    0
	00000259    0
	000002a6    0
	0000000b    0
	0000025a    0
	000001e3    0
	0000009e    0
	000001ea    0
	000001eb    0
	000002da    0
	0000013d    0
	0000013c    0
	0000013b    0
	0000013a    0
	00000137    0
	00000136    0
	00000130    0
	0000012f    0
	0000012e    0
	0000012d    0
	0000012b    0
	0000012a    0
	00000129    0
	00000128    0
	00000127    0
	00000126    0
	00000125    0
	00000124    0
	00000123    0
	00000122    0
	00000121    0
	00000120    0
	0000011b    0
	0000011a    0
	00000119    0
	00000118    0
	00000115    0
	00000114    0
	00000113    0
	00000112    0
	00000111    0
	00000110    0
	0000010e    0
	0000010d    0
	0000010c    0
	0000010b    0
	0000010a    0
	00000109    0
	00000108    0
	00000105    0
	00000104    0
	00000102    0
	00000101    0
	00000100    0
	000000ff    0
	000000df    0
	000000d8    0
	000000d1    0
	000000d0    0
	000000cf    0
	000000ce    0
	000000cd    0
	000000c6    0
	000000c5    0
	000000c2    0
	000000c0    0
	000000bf    0
	000000b2    0
	000000a9    0
	0000009f    0
	0000009b    0
	00000099    0
	00000098    0
	00000097    0
	00000096    0
	00000095    0
	00000094    0
	00000093    0
	00000092    0
	00000091    0
	00000090    0
	0000008e    0
	0000008d    0
	0000008a    0
000002f1 League of Legends.exe
	["C:/Riot Games/League of Legends/Game/League of Legends.exe" "192.64.173.136 5327 TAxfZQpYCKOFBVt7NrgI+g== 20102954" "-PlayerID=20102954" "-GameID=3038589874" "-GameBaseDir=C:/Riot Games/League of Legends" "-Locale=en_US" "-SkipRads" "-SkipBuild" "-EnableLNP" "-UseNewX3D=1" "-UseNewX3DFramebuffers=1" "-RiotClientPort=42181" "-RiotClientAuthToken=usJ6w_TvPxGCym0wnCt_UA"]
	0000028c    0
	000001b7    0
	000002bf    0
	0000011c    0
	0000020f    0
	00000224    0
	00000251    0
000000b1 (D) C:\Riot Games\League of Legends\RADS\projects\league_client\releases\0.0.0.200\deploy\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\abarge\Temp\BsSndRpt.ini"  /dl]
	0000028d    0 <==
000001f6 explorer.exe
	000001c9    0
	000001df    0
	00000225    0
	00000237    0
System information:
    Wine build: wine-4.6 (Staging)
    Platform: i386 (WOW64)
    Version: Windows XP
    Host system: Linux
    Host version: 4.15.0-48-generic

**Comment by mmtrt** [comment]
Looks like you are using winxp on wineprefix try changing it to win7 via winecfg. `leagueoflegends.winecfg`
