### ISSUE TITLE
[REQ] Battle.net

### ISSUE THREAD

**Issue by apolitech** [mmtrt/leagueoflegends#4]
A great part of the gaming and snaps community will appreciate if you could make a version of Battle.net snap version.
Thank you for your time and hard work.
P.S https://github.com/lutris/lutris/wiki/Game:-Blizzard-App classic wine works,dxvk it's broken for Battle.net  . This link is to help you with what Wine dependencies you need

**Comment by mmtrt** [comment]
We talked about this in emails though At the moment I'm using a single `wine` bundle snap for my other wine snaps that are still `i386` so it would also required me to create new bundle snap that has both `wine` `arch` and then create `battle.net` snap that will need quite lot a work. Still you can also request for this snap on [snapcraft forum](https://forum.snapcraft.io).

**Comment by jatin-cbs** [comment]
Battle net works great on DXVK now ! all games in BattleNet run like a charm :)
