### ISSUE TITLE
Error When Loading

### ISSUE THREAD

**Issue by Aerodin** [mmtrt/leagueoflegends#41]
Ubuntu 18.04 => Crashes immediately when trying to load.

Data Dump
----------------
Unhandled exception: page fault on write access to 0x7eb04760 in 32-bit code (0x7eb04760).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb04760 ESP:0032f18c EBP:0032f1a8 EFLAGS:00010202(  R- --  I   - - - )
 EAX:7eb04760 EBX:7e9a7000 ECX:00000000 EDX:00000001
 ESI:0032f2f8 EDI:7ffd8000
Stack dump:
0x0032f18c:  7e8efca4 00000000 00000000 0032f730
0x0032f19c:  7e9a7000 0032f2f8 7ffd8000 0032f258
0x0032f1ac:  7e8f0c93 7eb04760 00000000 00000000
0x0032f1bc:  0032f730 00000000 0019e680 7e8b88d1
0x0032f1cc:  7e941acc 00000000 00000000 ffffffff
0x0032f1dc:  00000000 00000000 00000000 7eb04760
Backtrace:
=>0 0x7eb04760 zError+0xffffffff() in libz.so.1 (0x0032f1a8)
  1 0x7e8b88d1 CreateCaret+0xffffffff() in user32 (0x0019e680)
  2 0x7e941acc UserRealizePalette+0xbcb() in user32 (0x0019e680)
  3 0x00110328 (0x00110328)
  4 0x0019e680 (0x0019e680)
  5 0x00110328 (0x00110328)
  6 0x0019e680 (0x0019e680)
  7 0x00110328 (0x00110328)
  8 0x0019e680 (0x0019e680)
  9 0x00110328 (0x00110328)
  10 0x0019e680 (0x0019e680)
  11 0x00110328 (0x00110328)
  12 0x0019e680 (0x0019e680)
  13 0x00110328 (0x00110328)
  14 0x0019e680 (0x0019e680)
  15 0x00110328 (0x00110328)
  16 0x0019e680 (0x0019e680)
  17 0x00110328 (0x00110328)
  18 0x0019e680 (0x0019e680)
  19 0x00110328 (0x00110328)
  20 0x0019e680 (0x0019e680)
  21 0x00110328 (0x00110328)
  22 0x0019e680 (0x0019e680)
  23 0x00110328 (0x00110328)
  24 0x0019e680 (0x0019e680)
  25 0x00110328 (0x00110328)
  26 0x0019e680 (0x0019e680)
  27 0x00110328 (0x00110328)
  28 0x0019e680 (0x0019e680)
  29 0x00110328 (0x00110328)
  30 0x0019e680 (0x0019e680)
  31 0x00110328 (0x00110328)
  32 0x0019e680 (0x0019e680)
  33 0x00110328 (0x00110328)
  34 0x0019e680 (0x0019e680)
  35 0x00110328 (0x00110328)
  36 0x0019e680 (0x0019e680)
  37 0x00110328 (0x00110328)
  38 0x0019e680 (0x0019e680)
  39 0x00110328 (0x00110328)
  40 0x0019e680 (0x0019e680)
  41 0x00110328 (0x00110328)
  42 0x0019e680 (0x0019e680)
  43 0x00110328 (0x00110328)
  44 0x0019e680 (0x0019e680)
  45 0x00110328 (0x00110328)
  46 0x0019e680 (0x0019e680)
  47 0x00110328 (0x00110328)
  48 0x0019e680 (0x0019e680)
  49 0x00110328 (0x00110328)
  50 0x0019e680 (0x0019e680)
  51 0x00110328 (0x00110328)
  52 0x0019e680 (0x0019e680)
  53 0x00110328 (0x00110328)
  54 0x0019e680 (0x0019e680)
  55 0x00110328 (0x00110328)
  56 0x0019e680 (0x0019e680)
  57 0x00110328 (0x00110328)
  58 0x0019e680 (0x0019e680)
  59 0x00110328 (0x00110328)
  60 0x0019e680 (0x0019e680)
  61 0x00110328 (0x00110328)
  62 0x0019e680 (0x0019e680)
  63 0x00110328 (0x00110328)
  64 0x0019e680 (0x0019e680)
  65 0x00110328 (0x00110328)
  66 0x0019e680 (0x0019e680)
  67 0x00110328 (0x00110328)
  68 0x0019e680 (0x0019e680)
  69 0x00110328 (0x00110328)
  70 0x0019e680 (0x0019e680)
  71 0x00110328 (0x00110328)
  72 0x0019e680 (0x0019e680)
  73 0x00110328 (0x00110328)
  74 0x0019e680 (0x0019e680)
  75 0x00110328 (0x00110328)
  76 0x0019e680 (0x0019e680)
  77 0x00110328 (0x00110328)
  78 0x0019e680 (0x0019e680)
  79 0x00110328 (0x00110328)
  80 0x0019e680 (0x0019e680)
  81 0x00110328 (0x00110328)
  82 0x0019e680 (0x0019e680)
  83 0x00110328 (0x00110328)
  84 0x0019e680 (0x0019e680)
  85 0x00110328 (0x00110328)
  86 0x0019e680 (0x0019e680)
  87 0x00110328 (0x00110328)
  88 0x0019e680 (0x0019e680)
  89 0x00110328 (0x00110328)
  90 0x0019e680 (0x0019e680)
  91 0x00110328 (0x00110328)
  92 0x0019e680 (0x0019e680)
  93 0x00110328 (0x00110328)
  94 0x0019e680 (0x0019e680)
  95 0x00110328 (0x00110328)
  96 0x0019e680 (0x0019e680)
  97 0x00110328 (0x00110328)
  98 0x0019e680 (0x0019e680)
  99 0x00110328 (0x00110328)
  100 0x0019e680 (0x0019e680)
  101 0x00110328 (0x00110328)
  102 0x0019e680 (0x0019e680)
  103 0x00110328 (0x00110328)
  104 0x0019e680 (0x0019e680)
  105 0x00110328 (0x00110328)
  106 0x0019e680 (0x0019e680)
  107 0x00110328 (0x00110328)
  108 0x0019e680 (0x0019e680)
  109 0x00110328 (0x00110328)
  110 0x0019e680 (0x0019e680)
  111 0x00110328 (0x00110328)
  112 0x0019e680 (0x0019e680)
  113 0x00110328 (0x00110328)
  114 0x0019e680 (0x0019e680)
  115 0x00110328 (0x00110328)
  116 0x0019e680 (0x0019e680)
  117 0x00110328 (0x00110328)
  118 0x0019e680 (0x0019e680)
  119 0x00110328 (0x00110328)
  120 0x0019e680 (0x0019e680)
  121 0x00110328 (0x00110328)
  122 0x0019e680 (0x0019e680)
  123 0x00110328 (0x00110328)
  124 0x0019e680 (0x0019e680)
  125 0x00110328 (0x00110328)
  126 0x0019e680 (0x0019e680)
  127 0x00110328 (0x00110328)
  128 0x0019e680 (0x0019e680)
  129 0x00110328 (0x00110328)
  130 0x0019e680 (0x0019e680)
  131 0x00110328 (0x00110328)
  132 0x0019e680 (0x0019e680)
  133 0x00110328 (0x00110328)
  134 0x0019e680 (0x0019e680)
  135 0x00110328 (0x00110328)
  136 0x0019e680 (0x0019e680)
  137 0x00110328 (0x00110328)
  138 0x0019e680 (0x0019e680)
  139 0x00110328 (0x00110328)
  140 0x0019e680 (0x0019e680)
  141 0x00110328 (0x00110328)
  142 0x0019e680 (0x0019e680)
  143 0x00110328 (0x00110328)
  144 0x0019e680 (0x0019e680)
  145 0x00110328 (0x00110328)
  146 0x0019e680 (0x0019e680)
  147 0x00110328 (0x00110328)
  148 0x0019e680 (0x0019e680)
  149 0x00110328 (0x00110328)
  150 0x0019e680 (0x0019e680)
  151 0x00110328 (0x00110328)
  152 0x0019e680 (0x0019e680)
  153 0x00110328 (0x00110328)
  154 0x0019e680 (0x0019e680)
  155 0x00110328 (0x00110328)
  156 0x0019e680 (0x0019e680)
  157 0x00110328 (0x00110328)
  158 0x0019e680 (0x0019e680)
  159 0x00110328 (0x00110328)
  160 0x0019e680 (0x0019e680)
  161 0x00110328 (0x00110328)
  162 0x0019e680 (0x0019e680)
  163 0x00110328 (0x00110328)
  164 0x0019e680 (0x0019e680)
  165 0x00110328 (0x00110328)
  166 0x0019e680 (0x0019e680)
  167 0x00110328 (0x00110328)
  168 0x0019e680 (0x0019e680)
  169 0x00110328 (0x00110328)
  170 0x0019e680 (0x0019e680)
  171 0x00110328 (0x00110328)
  172 0x0019e680 (0x0019e680)
  173 0x00110328 (0x00110328)
  174 0x0019e680 (0x0019e680)
  175 0x00110328 (0x00110328)
  176 0x0019e680 (0x0019e680)
  177 0x00110328 (0x00110328)
  178 0x0019e680 (0x0019e680)
  179 0x00110328 (0x00110328)
  180 0x0019e680 (0x0019e680)
  181 0x00110328 (0x00110328)
  182 0x0019e680 (0x0019e680)
  183 0x00110328 (0x00110328)
  184 0x0019e680 (0x0019e680)
  185 0x00110328 (0x00110328)
  186 0x0019e680 (0x0019e680)
  187 0x00110328 (0x00110328)
  188 0x0019e680 (0x0019e680)
  189 0x00110328 (0x00110328)
  190 0x0019e680 (0x0019e680)
  191 0x00110328 (0x00110328)
  192 0x0019e680 (0x0019e680)
  193 0x00110328 (0x00110328)
  194 0x0019e680 (0x0019e680)
  195 0x00110328 (0x00110328)
  196 0x0019e680 (0x0019e680)
  197 0x00110328 (0x00110328)
  198 0x0019e680 (0x0019e680)
  199 0x00110328 (0x00110328)
  200 0x0019e680 (0x0019e680)
0x7eb04760 zError+0xffffffff in libz.so.1: addl	%eax,0x0(%eax)
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Deferred        bssndrpt
PE	  460000- 3aa1000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b834000	Deferred        kernel32<elf>
  \-PE	7b420000-7b834000	\               kernel32
ELF	7bc00000-7bd6e000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bd6e000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d096000-7d0c3000	Deferred        iphlpapi<elf>
  \-PE	7d0a0000-7d0c3000	\               iphlpapi
ELF	7d109000-7d151000	Deferred        uxtheme<elf>
  \-PE	7d110000-7d151000	\               uxtheme
ELF	7d153000-7d15a000	Deferred        libxfixes.so.3
ELF	7d15a000-7d166000	Deferred        libxcursor.so.1
ELF	7d224000-7d256000	Deferred        libexpat.so.1
ELF	7d256000-7d2a1000	Deferred        libfontconfig.so.1
ELF	7d2a1000-7d2db000	Deferred        libpng16.so.16
ELF	7d2db000-7d398000	Deferred        libfreetype.so.6
ELF	7d498000-7d4ab000	Deferred        libxi.so.6
ELF	7d4ab000-7d4af000	Deferred        libxcomposite.so.1
ELF	7d4af000-7d4bc000	Deferred        libxrandr.so.2
ELF	7d4bc000-7d4c8000	Deferred        libxrender.so.1
ELF	7d4c8000-7d4cf000	Deferred        libxxf86vm.so.1
ELF	7d4cf000-7d4ea000	Deferred        libbsd.so.0
ELF	7d4ea000-7d516000	Deferred        libxcb.so.1
ELF	7d516000-7d660000	Deferred        libx11.so.6
ELF	7d660000-7d675000	Deferred        libxext.so.6
ELF	7d675000-7d71c000	Deferred        winex11<elf>
  \-PE	7d680000-7d71c000	\               winex11
ELF	7d71c000-7d861000	Deferred        oleaut32<elf>
  \-PE	7d730000-7d861000	\               oleaut32
ELF	7d861000-7d89b000	Deferred        ws2_32<elf>
  \-PE	7d870000-7d89b000	\               ws2_32
ELF	7d89b000-7d8c0000	Deferred        imm32<elf>
  \-PE	7d8a0000-7d8c0000	\               imm32
ELF	7d8c0000-7da1f000	Deferred        comctl32<elf>
  \-PE	7d8d0000-7da1f000	\               comctl32
ELF	7da1f000-7db94000	Deferred        ole32<elf>
  \-PE	7da40000-7db94000	\               ole32
ELF	7dbb8000-7dbbc000	Deferred        libxinerama.so.1
ELF	7dbbc000-7dbc3000	Deferred        libxdmcp.so.6
ELF	7dbc3000-7dbc7000	Deferred        libxau.so.6
ELF	7dbc7000-7dc1e000	Deferred        usp10<elf>
  \-PE	7dbd0000-7dc1e000	\               usp10
ELF	7dc1e000-7dc39000	Deferred        aclui<elf>
  \-PE	7dc20000-7dc39000	\               aclui
ELF	7dc39000-7dc6c000	Deferred        shcore<elf>
  \-PE	7dc40000-7dc6c000	\               shcore
ELF	7dc6c000-7e68d000	Deferred        shell32<elf>
  \-PE	7dc80000-7e68d000	\               shell32
ELF	7e68d000-7e71a000	Deferred        shlwapi<elf>
  \-PE	7e6a0000-7e71a000	\               shlwapi
ELF	7e71a000-7e745000	Deferred        version<elf>
  \-PE	7e720000-7e745000	\               version
ELF	7e745000-7e891000	Deferred        gdi32<elf>
  \-PE	7e750000-7e891000	\               gdi32
ELF	7e891000-7eabd000	Dwarf           user32<elf>
  \-PE	7e8a0000-7eabd000	\               user32
ELF	7eabd000-7eaf8000	Deferred        mpr<elf>
  \-PE	7eac0000-7eaf8000	\               mpr
ELF	7eaf8000-7eb17000	Dwarf           libz.so.1
ELF	7eb17000-7ebb3000	Deferred        wininet<elf>
  \-PE	7eb20000-7ebb3000	\               wininet
ELF	7ebb3000-7ec48000	Deferred        advapi32<elf>
  \-PE	7ebc0000-7ec48000	\               advapi32
ELF	7ec48000-7ece4000	Deferred        rpcrt4<elf>
  \-PE	7ec50000-7ece4000	\               rpcrt4
ELF	7ece4000-7ecf8000	Deferred        libnss_files.so.2
ELF	7ecf8000-7ed13000	Deferred        libnsl.so.1
ELF	7ed13000-7ed21000	Deferred        libnss_nis.so.2
ELF	7ed21000-7ed2b000	Deferred        libnss_compat.so.2
ELF	7eee0000-7eef4000	Deferred        wow64cpu<elf>
  \-PE	7eef0000-7eef4000	\               wow64cpu
ELF	7eef4000-7eff6000	Deferred        libm.so.6
ELF	7eff6000-7f000000	Deferred        librt.so.1
ELF	f7be2000-f7be7000	Deferred        libdl.so.2
ELF	f7be7000-f7dc3000	Deferred        libc.so.6
ELF	f7dc3000-f7de2000	Deferred        libpthread.so.0
ELF	f7de2000-f7fab000	Dwarf           libwine.so.1
ELF	f7fad000-f7fd5000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000024 explorer.exe
	00000028    0
	00000027    0
	00000026    0
	00000025    0
00000139 explorer.exe
	0000013d    0
	0000013c    0
	0000013b    0
	0000013a    0
00000217 (D) C:\Riot Games\League of Legends\RADS\projects\league_client\releases\0.0.0.201\deploy\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\abarge\Temp\BsSndRpt.ini"  /dl]
	00000218    0 <==
System information:
    Wine build: wine-4.6 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.15.0-48-generic

**Comment by mmtrt** [comment]
No need to post additional issues. Read my post in #40
