### ISSUE TITLE
"The program BsSndRpt.exe has encountered a serious problem and needs to close. We are sorry for the inconvinience."

### ISSUE THREAD

**Issue by DreinX** [mmtrt/leagueoflegends#42]
Every time I try to start any kind of match doesn't matter pvp or a tutorial the game throws me an error. 
here is the code for the error:

Unhandled exception: illegal instruction in 32-bit code (0x7eb13760).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb13760 ESP:0032f18c EBP:0032f1a8 EFLAGS:00010202(  R- --  I   - - - )
 EAX:7eb13760 EBX:7e9b1000 ECX:00000000 EDX:00000001
 ESI:0032f2f8 EDI:7ffd8000
Stack dump:
0x0032f18c:  7e8f9ca4 00000000 00000000 0032f730
0x0032f19c:  7e9b1000 0032f2f8 7ffd8000 0032f258
0x0032f1ac:  7e8fac93 7eb13760 00000000 00000000
0x0032f1bc:  0032f730 00000000 0019fe68 7e8c28d1
0x0032f1cc:  7e94bacc 00000000 00000000 ffffffff
0x0032f1dc:  00000000 00000000 00000000 7eb13760
Backtrace:
=>0 0x7eb13760 zError+0x18a0() in libz.so.1 (0x0032f1a8)
  1 0x7e8c28d1 CreateCaret+0xffffffff() in user32 (0x0019fe68)
  2 0x7e94bacc UserRealizePalette+0xbcb() in user32 (0x0019fe68)
0x7eb13760 zError+0x18a0 in libz.so.1: 	
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Deferred        bssndrpt
PE	  460000- 3aa1000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b834000	Deferred        kernel32<elf>
  \-PE	7b420000-7b834000	\               kernel32
ELF	7bc00000-7bd6e000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bd6e000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d15f000-7d18c000	Deferred        iphlpapi<elf>
  \-PE	7d170000-7d18c000	\               iphlpapi
ELF	7d1d2000-7d21a000	Deferred        uxtheme<elf>
  \-PE	7d1e0000-7d21a000	\               uxtheme
ELF	7d21c000-7d223000	Deferred        libxfixes.so.3
ELF	7d223000-7d22f000	Deferred        libxcursor.so.1
ELF	7d2e4000-7d316000	Deferred        libexpat.so.1
ELF	7d316000-7d361000	Deferred        libfontconfig.so.1
ELF	7d361000-7d39b000	Deferred        libpng16.so.16
ELF	7d409000-7d4c6000	Deferred        libfreetype.so.6
ELF	7d4c6000-7d4d9000	Deferred        libxi.so.6
ELF	7d4d9000-7d4dd000	Deferred        libxcomposite.so.1
ELF	7d4dd000-7d4ea000	Deferred        libxrandr.so.2
ELF	7d4ea000-7d4f6000	Deferred        libxrender.so.1
ELF	7d4f6000-7d4fd000	Deferred        libxxf86vm.so.1
ELF	7d4fd000-7d501000	Deferred        libxinerama.so.1
ELF	7d501000-7d51c000	Deferred        libbsd.so.0
ELF	7d51c000-7d523000	Deferred        libxdmcp.so.6
ELF	7d523000-7d527000	Deferred        libxau.so.6
ELF	7d527000-7d553000	Deferred        libxcb.so.1
ELF	7d553000-7d69d000	Deferred        libx11.so.6
ELF	7d69d000-7d6b2000	Deferred        libxext.so.6
ELF	7d6b2000-7d759000	Deferred        winex11<elf>
  \-PE	7d6c0000-7d759000	\               winex11
ELF	7d759000-7d89e000	Deferred        oleaut32<elf>
  \-PE	7d770000-7d89e000	\               oleaut32
ELF	7d89e000-7d8d8000	Deferred        ws2_32<elf>
  \-PE	7d8b0000-7d8d8000	\               ws2_32
ELF	7d8d8000-7d8fd000	Deferred        imm32<elf>
  \-PE	7d8e0000-7d8fd000	\               imm32
ELF	7d8fd000-7d954000	Deferred        usp10<elf>
  \-PE	7d900000-7d954000	\               usp10
ELF	7d954000-7dab3000	Deferred        comctl32<elf>
  \-PE	7d960000-7dab3000	\               comctl32
ELF	7dab3000-7dace000	Deferred        aclui<elf>
  \-PE	7dac0000-7dace000	\               aclui
ELF	7dace000-7dc43000	Deferred        ole32<elf>
  \-PE	7daf0000-7dc43000	\               ole32
ELF	7dc43000-7dc76000	Deferred        shcore<elf>
  \-PE	7dc50000-7dc76000	\               shcore
ELF	7dc76000-7e697000	Deferred        shell32<elf>
  \-PE	7dc90000-7e697000	\               shell32
ELF	7e697000-7e724000	Deferred        shlwapi<elf>
  \-PE	7e6a0000-7e724000	\               shlwapi
ELF	7e724000-7e74f000	Deferred        version<elf>
  \-PE	7e730000-7e74f000	\               version
ELF	7e74f000-7e89b000	Deferred        gdi32<elf>
  \-PE	7e760000-7e89b000	\               gdi32
ELF	7e89b000-7eac7000	Dwarf           user32<elf>
  \-PE	7e8b0000-7eac7000	\               user32
ELF	7eac7000-7eb02000	Deferred        mpr<elf>
  \-PE	7ead0000-7eb02000	\               mpr
ELF	7eb02000-7eb21000	Dwarf           libz.so.1
ELF	7eb21000-7ebbd000	Deferred        wininet<elf>
  \-PE	7eb30000-7ebbd000	\               wininet
ELF	7ebbd000-7ec52000	Deferred        advapi32<elf>
  \-PE	7ebd0000-7ec52000	\               advapi32
ELF	7ec52000-7ecee000	Deferred        rpcrt4<elf>
  \-PE	7ec60000-7ecee000	\               rpcrt4
ELF	7ecee000-7ed02000	Deferred        libnss_files.so.2
ELF	7ed02000-7ed1d000	Deferred        libnsl.so.1
ELF	7ed1d000-7ed2b000	Deferred        libnss_nis.so.2
ELF	7ed2b000-7ed35000	Deferred        libnss_compat.so.2
ELF	7eeea000-7eefe000	Deferred        wow64cpu<elf>
  \-PE	7eef0000-7eefe000	\               wow64cpu
ELF	7eefe000-7f000000	Deferred        libm.so.6
ELF	f7ba0000-f7baa000	Deferred        librt.so.1
ELF	f7bac000-f7bb1000	Deferred        libdl.so.2
ELF	f7bb1000-f7d8d000	Deferred        libc.so.6
ELF	f7d8d000-f7dac000	Deferred        libpthread.so.0
ELF	f7dac000-f7f75000	Dwarf           libwine.so.1
ELF	f7f77000-f7f9f000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001b    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	00000018    0
	00000017    0
	00000016    0
	00000012    0
00000019 plugplay.exe
	0000001d    0
	0000001c    0
	0000001a    0
0000001e winedevice.exe
	00000023    0
	00000022    0
	00000021    0
	0000001f    0
00000166 explorer.exe
	0000016a    0
	00000169    0
	00000168    0
	00000167    0
0000004a explorer.exe
	000000c3    0
	000000c4    0
	000000c5    0
	000000c6    0
0000015f (D) C:\Riot Games\League of Legends\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\kyouma\Temp\BsSndRpt.ini"  /dl]
	00000037    0 <==
System information:
    Wine build: wine-4.6 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.15.0-50-generic

**Comment by mnsotelo** [comment]
#40

**Comment by mmtrt** [comment]
game is currently broken on wine see #40 for more info, closing this.
