### ISSUE TITLE
[Question] Double Free or Corruption (libx11 ?)

### ISSUE THREAD

**Issue by Bloodiko** [mmtrt/leagueoflegends#43]
In roughly 4 of 5 tries to start League it never starts or it starts with 100% CPU usage perma

but in those cases where its not opening at all there is something in the log which may be the issue for lol not starting:

" Double free or corruption! "   and right after it 
ntdll errors:
 `0206:err:ntdll:RtlpWaitForCriticalSection section 0x7bd4bfe0 "loader.c: loader_section" wait timed out in thread 0206, blocked by 000a, retrying (60 sec)
01bd:err:ntdll:RtlpWaitForCriticalSection section 0x7bd4bfe0 "loader.c: loader_section" wait timed out in thread 01bd, blocked by 000a, retrying (60 sec)
01d0:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
01f7:err:ntdll:RtlpWaitForCriticalSection section 0x7bd4bfe0 "loader.c: loader_section" wait timed out in thread 01f7, blocked by 000a, retrying (60 sec)
01f8:err:ntdll:RtlpWaitForCriticalSection section 0x7bd4bfe0 "loader.c: loader_section" wait timed out in thread 01f8, blocked by 000a, retrying (60 sec)
01bb:err:ntdll:RtlpWaitForCriticalSection section 0x7bd4bfe0 "loader.c: loader_section" wait timed out in thread 01bb, blocked by 000a, retrying (60 sec)
`

as this exists for a bit longer now, i searched previously and someone stated in the wine bug forum that it seems to be connected to an overflow in libx11, but the patch did not get accepted upstream. 

So i know that you might not be able to fix it yourself - but heres where the question comes in: 

i've read several guides to Snap but i cannot find a useful way to Stop a running program (which does not have a GUI yet) despite killing its process in htop or any other taskmgr 

can you tell me a way to do so ?  or maybe kill the existing wineserver on start before starting a new one 

Thx 
Bastian

**Comment by mmtrt** [comment]
wineserver usually closes with its other processes when game launcher is closed after some seconds.

Can you link me to the patch I might try to compile that lib if that patch still applies to the current version of pkg.

league launcher is really bugged and cpu hog but it is with ritos choice to improve the quality instead of wasting development on skins n champs.

**Comment by Bloodiko** [comment]
Yep, problem though: if I don't see the client, I cannot close it (cause technically it didn't start yet)
So if I can't kill the league sub process, the wineserver will continue to run, and I'm forced to kill the sub processes to stop wine 

https://bugs.winehq.org/show_bug.cgi?id=35041#c38

This is the link to the patched lib code, not sure if it rly is the solution for this though

But a regular way something like "snap --killall" (doesn't exist just as example) to stop snaps does not exist, does it?

**Comment by mmtrt** [comment]
`snap stop xyz` exists but that expects snap to have actual services to be added and executed which I never added nor explorer that options but I'll check it out sometime.

Or I could add `wineserver -k` to league command and pipe it to a flag like `leagueoflegends -k` executes command added that could suffice.

Yea for the moment have to use task managers to kill the client.

**Comment by Bloodiko** [comment]
Okay, thx for your work though :)

**Comment by mmtrt** [comment]
ah those patches did not worked build fail as these were from 2017 lot of changed since then.

**Comment by mmtrt** [comment]
so I've added `wineserver -k` command to
`leagueoflegends.wineserver`

whenever launching that command triggers `wineserver -k` in snap wineprefix..
