### ISSUE TITLE
Wine AppImage only works once

### ISSUE THREAD

**Issue by stuartfoxcroft** [mmtrt/leagueoflegends#46]
Currently I've been able to launch League precisely once using the AppImage, immediately after first installing. After closing the client, I haven't been able to launch LoL again, running "./wine-staging-i386_lol-patched_x86_64-bionic.AppImage wine ../.wine-appimage-lol/drive_c/Riot\ Games/League\ of\ Legends/LeagueClient.exe" or "./wine-staging-i386_lol-patched_x86_64-bionic.AppImage wine League\ of\ Legends\ installer\ EUW.exe"

**Comment by stuartfoxcroft** [comment]
I get repeated errors of the format: "0036:err:ntdll:RtlpWaitForCriticalSection section 0x7bd4c040 "loader.c: loader_section" wait timed out in thread 0036, blocked by 0035, retrying (60 sec)"

**Comment by stuartfoxcroft** [comment]
@mmtrt any ideas as to what the issue is?

**Comment by mmtrt** [comment]
could be wine services already running or leagues make sure these are closed from task manager though sometimes league processes go zombie not closes I had that one time so had to reboot system in order launch game again that could be but I'm not sure.

Why not using preinstalled game.

**Comment by stuartfoxcroft** [comment]
Trying to run the preinstalled game from the snap caused various errors for me, so I opted to try the AppImage instead.

**Comment by stuartfoxcroft** [comment]
Also I tried rebooting and got the same errors already, so I'm completely reinstalling the wineprefix having run "rm -rf .wine-appimage-lol/" to rule out potential corruption of files

**Comment by mmtrt** [comment]
guess I'll try to compile wine again with different league patch without glibc though it will take sometime then will separate appimage with that patch.

**Comment by mmtrt** [comment]
maybe try copying appimage to leagueclient.exe path then launching "./wine-staging-i386_lol-patched_x86_64-bionic.AppImage wine LeagueClient.exe"

**Comment by stuartfoxcroft** [comment]
After reinstalling, closing the client, and ensuring that there aren't any ongoing wine processes, I get this error: "Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x00614318)."

**Comment by stuartfoxcroft** [comment]
This does however at least bring up a Wine dialogue saying "LeagueClient.exe has encountered an error", which is more positive than no Wine dialogue I guess.

**Comment by stuartfoxcroft** [comment]
Moving the AppImage to the league folder seems to have worked however.

**Comment by stuartfoxcroft** [comment]
I've closed and reopened the client 10 times now consecutively without fail, so I think that moving the AppImage is a viable solution.

**Comment by mmtrt** [comment]
could be due to launching path to league have spaces in folders causing that issue

Launching like this should also work

` ./wine-staging-i386_lol-patched_x86_64-bionic.AppImage wine "$HOME/.wine-appimage-lol/drive_c/Riot Games/League of Legends/LeagueClient.exe"`

**Comment by stuartfoxcroft** [comment]
After updating to 9.11, the LoL client quits after the Init phase.
Example output:
LeagueClient.exe(000000F6): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(000000F6): ALWAYS| Direct Launch not configured for league_of_legends.live in environment ''
LeagueClient.exe(000000E0): ALWAYS| Tracing worker thread running.
LeagueClient.exe(000000F6): ALWAYS| Running LeagueClient version 9.11.275.6613
LeagueClient.exe(000000E0): ALWAYS| Keeping up to 10 tracing logs.
LeagueClient.exe(000000E0): ALWAYS| Tracing CompactJsonWriter at C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-05-30T17-10-36_234_LeagueClient-tracing.json
LeagueClient.exe(000000F6): ALWAYS| Phase Begin - Init
LeagueClient.exe(000000F6): ALWAYS|             Plugin Manager| Loaded plugin manifest file plugin-manifest.json.
LeagueClient.exe(000000F6): ALWAYS| Phase End - Init - duration was 1154.60ms
