### ISSUE TITLE
LOL error

### ISSUE THREAD

**Issue by titirocki** [mmtrt/leagueoflegends#48]
Hi,
When i execute the command `snap install --edge leagueoflegends`, i got an error like this :
- Gtk-Message: 17:58:47.336: Failed to load module  "pk-gtk-module"
- Gtk-Message: 17:58:47.339: Failed to load module "canberra-gtk-module"
- Gtk-Message: 17:58:47.346: Failed to load module "pk-gtk-module"
- Gtk-Message: 17:58:47.346: Failed to load module "canberra-gtk-module"
- wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
- 000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
- Gtk-Message: 17:59:44.360: Failed to load module "pk-gtk-module"
- Gtk-Message: 17:59:44.360: Failed to load module "canberra-gtk-module"
- Gtk-Message: 17:59:44.362: Failed to load module "pk-gtk-module"
- Gtk-Message: 17:59:44.362: Failed to load module "canberra-gtk-module"
- Gtk-Message: 17:59:47.880: Failed to load module "pk-gtk-module"
- Gtk-Message: 17:59:47.880: Failed to load module "canberra-gtk-module"
- Gtk-Message: 17:59:47.881: Failed to load module "pk-gtk-module"
- Gtk-Message: 17:59:47.881: Failed to load module "canberra-gtk-module"
- wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
- 000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -r" (2).
- wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
- wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
- wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"

Is this a serious issue ? What I have to do to fix that ?
Thanks in advance

**Comment by mmtrt** [comment]
if game works without any problem then you don't have to worry about these errors are harmless though I'll issue about about fixing that winemenubuilder logspam.

**Comment by titirocki** [comment]
Yeah but the problem is that I have an error page when the page qould normally load (even if I used the wine-platform update)

**Comment by mmtrt** [comment]
from Pinned Issue #7
> **Update - 07/6/19**
> * Migrated league snap to use new `wine-platform-xxxx` snaps.
> * New league snap users now have to install `wine-platform-runtime` and `wine-platform-4-staging` from candidate snap branch.
> `snap install --candidate wine-platform-runtime`
> `snap install --candidate wine-platform-4-staging`
> * Old users that have updated league snap have to install above two snaps if these snaps were auto installed on updating league snap then do refresh instead of install on above two commands.
> * I will not be maintaining `wine-platform` snap from now on so that will receive no updates better do update snap. 

So you need to refresh these snaps after install which is mandatory to do now.

> `snap refresh --candidate wine-platform-runtime`
> `snap refresh --candidate wine-platform-4-staging`

**Comment by titirocki** [comment]
This works fine, thanks a lot !

**Comment by Getta91** [comment]
Thank you so much! You are doing such a great work here. Love u <3
