### ISSUE TITLE
amd radv driver

### ISSUE THREAD

**Issue by adserba** [mmtrt/leagueoflegends#49]
hi,
thank you for the effort on this project
the game is working fine with d9vk. i have installed mesa 19.2 and dxvk 1.2.1 
vulkaninfo returns GPU id : 0 (AMD RADV POLARIS10 (LLVM 9.0.0))
but when dxvk_hud is enabled it reports  GPU id : 0 (AMD RADV POLARIS10 (LLVM 7.0.0))
and driver 18.2.3
Is this normal?

**Comment by mmtrt** [comment]
I think it's normal because snap is using drivers packages provided within from snap.

**Comment by adserba** [comment]
ok thanks...last few days..i tried to fin dout if it's aproblem on my side

**Comment by mmtrt** [comment]
I've added updated driver pkgs to `wine-platform-runtime` which is currently uploaded in beta branch and you can test.

`snap refresh --beta wine-platform-runtime`

**Comment by adserba** [comment]
after refresh:
info:  AMD RADV POLARIS10 (LLVM 8.0.0):
info:    Driver: 19.1.99
info:    Vulkan: 1.1.107
and  I get beter fps!
thank you!

**Comment by adserba** [comment]
I just switched from doitsujin/dxvk to Joshua-Ashton/d9vk, for the d3d9 dll and minimum fps is now around 80 witch is great!! thank you!

**Comment by Getta91** [comment]
Hi! Can someone explain me how you dis thèse changes please? Have a nice day
