### ISSUE TITLE
updating wine-platform-i386 breaks leagueoflegends

### ISSUE THREAD

**Issue by fedexyz** [mmtrt/leagueoflegends#5]
Client will work fine, but it breaks after champion select once the game should start.

executing a snap revert wine-platform-i386 fixed it, so I guess theres something in 3.18 that the league snap does not like, or is there anything that needs to be changed for league to work with wine 3.18 ?

**Comment by mmtrt** [comment]
Maybe try this

* move 'Riot Games' out from `/home/$USER/snap/leagueoflegends/common/.wine/drive_c` to a safe location where you can move back to above `DIR` later.

* now that the game folder is on safe location then remove `/home/$USER/snap/leagueoflegends` `DIR` completely.

* run game but make sure you have the latest snaps now when snap ask you choose game `region` close that dialog.

* move game folder from safe location to `/home/$USER/snap/leagueoflegends/common/.wine/drive_c`

* now test the game see if it crashes.

**Comment by mmtrt** [comment]
I've reverted wine snap to `3.17` however `3.18` is on `edge` channel though I'm getting game crashes on both after champ select then loading screen when it hits 68+.
