### ISSUE TITLE
Blank text fields

### ISSUE THREAD

**Issue by BeAsYit** [mmtrt/leagueoflegends#50]
Hi, firstly thank you for your job!
Secondly, when I enter the game, there is no numbers(like gold, hp/mp, k/d/a, time, lvls and so on) or text(nicknames). In chat everything is working, in launcher too. Like the game missing all of this text. I can see only strange symbols, or different letters like P, when in loading screen.
Game works completely normal, except this fonts.
Do you know what is happening?

**Comment by mmtrt** [comment]
from pinned issue #7 
> * https://i.redd.it/3ggp5eyg0hq21.png [ `font issue on wine release 4.1 above still exists` ]
( workaround is to fresh install game **OR** backup your game files `$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games` then remove the league snap then install it again with your current region installer when it downloads the game close the launcher then the new so fresh game files are still on `wineprefix` here `$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games` so remove that folder [`make sure you have game backup earlier`] and then move your game backup back to `$HOME/snap/leagueoflegends/common/.wine/drive_c` and then start your game then no longer font issue )
