### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Getta91** [mmtrt/leagueoflegends#51]
Hi! Thank you for all your work. I am trying to install league by snap but i don't really know how to do it. I don't mean with the basic command: snap install leagueoflegends --edge --devmode, but with the things of wine platform... Can you please help me with the order of the different command? Thank you again!

**Comment by mmtrt** [comment]
can you read the install instructions about `wine-platform` snaps from [Readme](https://github.com/mmtrt/leagueoflegends/blob/master/README.md#install)

**Comment by Getta91** [comment]
Thanks! I think it worked!

**Comment by Getta91** [comment]
By the way how to launch this snap? Does I have to do : "snap run leagueoflegends" or should I add: "--edge" and "--devmode"?

**Comment by mmtrt** [comment]
`snap run leagueoflegends` or `leagueoflegends` or you launch it from start menu icon though that will appear after logout then login.

`--edge` and `--devmode` are only used with install and refresh command for snap.

**Comment by Getta91** [comment]
When I am doing those commands, The picture of league appeard but then a pop up arrive: a bugsplat one.
I don't know how to solve this. Thank you again for your help

**Comment by mmtrt** [comment]
I need info of these

`snap info leagueoflegends | grep installed`

`snap connections leagueoflegends`

and launch snap with this command and post log file here when it crashes

`leagueoflegends &> league.log`

**Comment by Getta91** [comment]
I got this:

![Capture d’écran du 2019-06-10 12-30-31](https://user-images.githubusercontent.com/50636257/59189879-90e9f200-8b7b-11e9-95f0-f0a076d75943.png)

**Comment by Getta91** [comment]
For the log file: 
![Capture d’écran du 2019-06-10 12-33-42](https://user-images.githubusercontent.com/50636257/59190051-0950b300-8b7c-11e9-9012-a4390a3a155b.png)

It is strange! Nothing is happening, except the bugsplat and the league icon!

**Comment by mmtrt** [comment]
post `league.log` file

**Comment by Getta91** [comment]
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: EUW
common.session_id: a2e710f7-e25f-3647-a083-6371c32cf2e3
event_name: render_terminate
exit_code: -3
termination_type: segmentation fault
LeagueClient.exe(00000009): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(00000009): ALWAYS| Ux state set to HideAll.
LeagueClient.exe(00000009): ALWAYS| Ux state set to Quit.
LeagueClient.exe(00000009): ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__js_memory_stats_summary
common.os_platform: Windows
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 9.11.276.3025
totalHeapSize: 0
common.installation_id: 1LwVng==
common.locale: en_GB
common.machine_id: 5cJ4zA6xtESoLI+HNXrn+w==
common.os_version_major: 7
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: EUW
common.session_id: a2e710f7-e25f-3647-a083-6371c32cf2e3
heapSizeLimit: 0
usedHeapSize: 0
LeagueClient.exe(00000009): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(00000009): ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__event
common.os_platform: Windows
common.application_name: LeagueClient
common.client_id: lol
common.application_version: 9.11.276.3025
common.installation_id: 1LwVng==
common.locale: en_GB
common.machine_id: 5cJ4zA6xtESoLI+HNXrn+w==
common.os_version_major: 7
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: EUW
common.session_id: a2e710f7-e25f-3647-a083-6371c32cf2e3
event_name: render_terminate
exit_code: -3
termination_type: segmentation fault
LeagueClient.exe(00000009): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(00000079):   WARN|           <unknown-plugin>| Patcher: Error making 2108390-byte 1-range request with ID 171 / unknown to server 2606:4700::6811:ad05 from CDN unknown over connection 4 for URL https://lol.dyn.riotcdn.net/channels/public/bundles/5662E26B60DB2972.bundle after 0.251 secs, 0 downloaded bytes and 0 retries: HTTP request failed with error code 7: 
LeagueClient.exe(00000079):   WARN|           <unknown-plugin>| Patcher: Error making 153223-byte 1-range request with ID 172 / unknown to server 2606:4700::6811:ae05 from CDN unknown over connection 7 for URL https://lol.dyn.riotcdn.net/channels/public/bundles/5662E26B60DB2972.bundle after 0.00100:err:eventlog:ReportEventW L"league_client_riotgames_com"
0100:err:eventlog:ReportEventW L"LeagueClientUxHelper"
0100:err:eventlog:ReportEventW L"51669985"

**Comment by mmtrt** [comment]
can you try game with setting windows xp from winecfg
`leagueoflegends.winecfg`

**Comment by Getta91** [comment]
It's downloading fine now

**Comment by mmtrt** [comment]
IDK users have got it workaround on older distros previously needing this to work, check for more info https://github.com/mmtrt/leagueoflegends/issues/39#issuecomment-495944067

**Comment by Getta91** [comment]
Thank you so much!
