### ISSUE TITLE
Existing Install - Followed Readme

### ISSUE THREAD

**Issue by Aerodin** [mmtrt/leagueoflegends#53]
snap install --edge leagueoflegends
snap refresh --candidate wine-platform-runtime
snap refresh --candidate wine-platform-4-staging

Ubuntu 18.04 LTS - Existing LeagueofLegends snap updated, "Wine-Platform" removed.  Tried Win XP option in leagueoflegends.winecfg but it is the same issue.

Ran the above to update League of Legends per the readme.  Client loads, game fails to load but no errors show.  Just the "RECONNECT" button.

**Comment by Getta91** [comment]
My brother has the same here. But i don't think it's because of Snap. A lot
of users are experiencing the same behaviour (look at the forum).
Leagueoflegends is currently in work in order to fix this.

Le mer. 12 juin 2019 20:43, Andrew Barge <notifications@github.com> a
écrit :

**Comment by newhoa** [comment]
This started happening after the last League patch this week for me. I can open the client fine but can't connect to a game once it starts, reconnect doesn't work.

**Comment by SplotyCode** [comment]
For me a full reinstall of lol and wine helped. I did it without exsiting files so maby thst is the key

**Comment by Aerodin** [comment]
I tried a full re-install - the installer lists a bunch of errors.

Here is one of them:
000000.000| ALWAYS| Logging started at 2019-06-18T07:17:21.919
000000.000| ALWAYS| Application Version:9.12.277.6038 - CL:2776038 - Build Date: Jun 07 2019 - Build Time:12:30:24
000000.000| ALWAYS| Log file C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-06-18T07-17-21_218_LeagueClientUx.log
000000.000| ALWAYS| Running LeagueClientUx version 9.12.277.6038
000000.000|   OKAY| Initial working directory: "C:\Riot Games\League of Legends"
000000.000|   OKAY| Current process: "C:\Riot Games\League of Legends\LeagueClientUx.exe"
000000.000|   OKAY| Command line arguments:
	--remoting-auth-token=GYvrx4dbZiqqiT_e2_AdbQ
	--respawn-command=LeagueClient.exe
	--respawn-display-name=League of Legends
	--app-port=36893
	--install-directory=C:\Riot Games\League of Legends
	--app-name=LeagueClient
	--ux-name=LeagueClientUx
	--ux-helper-name=LeagueClientUxHelper
	--log-dir=LeagueClient Logs
	--bugsplat-name=league_client_riotgames_com
	--bugsplat-platform-id=NA1
	--app-log-file-path=C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-06-18T07-15-57_8_LeagueClient.log
	--app-pid=8
	--no-proxy-server
000000.000|   OKAY| Memory Monitor enabled:
000000.000|   OKAY| - update interval 5s
000000.000|   OKAY| - memory delta threshold 10MiB
000000.000|   OKAY| - page fault delta threshold 100K
000000.000|   OKAY| - region count delta threshold 10
000000.000| ALWAYS| Using Ux render executable path: LeagueClientUxRender.exe
000000.001|   OKAY| Working Set Size: 80MiB Peak: 80MiB   Pagefile Usage: 63MiB Peak: 63MiB   Private Usage: 0MiB
000000.001|   OKAY| Paged Pool Usage: 0MiB Peak: 0MiB   Non-Paged Pool Usage: 0MiB Peak: 0MiB
000000.001|   OKAY| Committed Total: 148MiB   Committed Image: 93MiB   Committed Mapped: 0MiB   Committed Private: 54MiB   Reserved Total: 2352MiB   Reserved Image: 0MiB   Reserved Mapped: 0MiB   Reserved Private: 2352MiB   Free Total: 1595MiB   Limit: 4095MiB   Largest Free: 1355MiB   Region Count: 373
000000.001|   OKAY| Page Fault Count: 0K
000000.001| ALWAYS| Cef CommandLine: "C:/Riot Games/League of Legends/LeagueClientUx.exe" --app-log-file-path="C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-06-18T07-15-57_8_LeagueClient.log" --app-name=LeagueClient --app-pid=8 --app-port=36893 --browser-subprocess-path=LeagueClientUxRender.exe --bugsplat-name=league_client_riotgames_com --bugsplat-platform-id=NA1 --install-directory="C:\Riot Games\League of Legends" --lang=en-US --log-dir="LeagueClient Logs" --log-file="C:\Riot Games\League of Legends\debug.log" --no-proxy-server --no-sandbox --remoting-auth-token=GYvrx4dbZiqqiT_e2_AdbQ --respawn-command=LeagueClient.exe --respawn-display-name="League of Legends" --ux-helper-name=LeagueClientUxHelper --ux-name=LeagueClientUx --disable-spell-checking --no-displaying-insecure-content
000000.044| ALWAYS| Initial dpiScale = 1.000000
000000.044| ALWAYS| Using cookie store at C:/Riot Games/League of Legends/Cookies
000000.045|   OKAY| Creating browser process.
000000.045| ALWAYS| App file system path is: C:\Riot Games\League of Legends\
000000.045| ALWAYS| Plugins file system path used : Plugins\.
000000.045| ALWAYS| Trying to connect to app process.
000000.054| ALWAYS| Connected to app process after 1 attempts.
000000.058| ALWAYS| Backend process is now running.
000000.123|   OKAY| Setting mouse intercept hook.
000000.123|   OKAY| Registering window.
000000.123|   OKAY| Registering window class R.
000000.123|   OKAY| Loading icons.
000000.140|   OKAY| New window requested at 0,0 with dimensions 1280,720.
000000.140|   OKAY| Creating ux window with url https://riot:GYvrx4dbZiqqiT_e2_AdbQ@127.0.0.1:36893/bootstrap.html.
000000.140| ALWAYS| Deleting non-whitelisted cookies
000000.140|   OKAY| Running message loop.
000000.159|   OKAY| Creating main WindowAppModule window 1.
000000.159|   OKAY| Ux window 1 created.
000000.203|  ERROR| ZoomScale 0.000000 not found, returning default index.
000000.203|   OKAY| Ignoring zoom value of 1.000000 since it's already been applied
000000.203|   OKAY| Creating main browser window 1.
000001.493|   OKAY| render_pid = 200
000002.570|  ERROR| Render process terminated unexpectedly: segmentation fault
000002.615|  ERROR| Browser Process Info:
Process Memory:
    1524M free.
    2356M reserved.
     215M commited.
    Largest free block is 1355M.

    PageFaultCount: 0
    PeakWorkingSetSize: 102M
    WorkingSetSize: 102M
    QuotaPeakPagedPoolUsage: 0M
    QuotaPagedPoolUsage: 0M
    QuotaPeakNonPagedPoolUsage: 0M
    QuotaNonPagedPoolUsage: 0M
    PagefileUsage: 75M
    PeakPagefileUsage: 75M
    PrivateUsage: 11M

Process Info:
    ThreadCount: 33
000002.615|  ERROR| Render process terminated with exit code -3
000002.617| ALWAYS| Window 1 is now hidden.
000002.617|   OKAY| Close browsers
000002.626|   OKAY| Main windows received quit command.
000002.762|   OKAY| Terminating window manager.
000002.767|   OKAY| Shutting down RiotRemoting.
000002.769|   OKAY| ClientWebSocketTransport: Statistics at socket close:
000002.769|   OKAY| Reads - Count : 82   Total Bytes: 48557   Average Bytes: 592
000002.769|   OKAY| Writes - Count : 18   Total Bytes: 1296   Average Bytes: 72
000002.769|   OKAY| Retries: 0
000002.769|   OKAY| Releasing browser process.
000002.771|   OKAY| Shutting down CEF.
000002.799|   OKAY| Exiting ux.
000002.800|   OKAY| Working Set Size: 98MiB Peak: 102MiB   Pagefile Usage: 75MiB Peak: 75MiB   Private Usage: 0MiB
000002.800|   OKAY| Paged Pool Usage: 0MiB Peak: 0MiB   Non-Paged Pool Usage: 0MiB Peak: 0MiB
000002.800|   OKAY| Committed Total: 187MiB   Committed Image: 95MiB   Committed Mapped: 10MiB   Committed Private: 82MiB   Reserved Total: 2356MiB   Reserved Image: 0MiB   Reserved Mapped: 0MiB   Reserved Private: 2356MiB   Free Total: 1551MiB   Limit: 4095MiB   Largest Free: 1355MiB   Region Count: 529
000002.800|   OKAY| Page Fault Count: 0K

**Comment by mmtrt** [comment]
pushed `wine-staging` 4.10 with custom patches same build as wine appimage to beta branch see if that build helps

`snap refresh --beta wine-platform-4-staging`

**Comment by Aerodin** [comment]
Gave that one a shot.  Still a number of different bug splats being produced like the one below:

000000.000| ALWAYS| Logging started at 2019-06-18T19:14:21.619
000000.000| ALWAYS| Application Version:9.12.277.8490 - CL:2778490 - Build Date: Jun 10 2019 - Build Time:14:01:47
000000.001| ALWAYS| Log file C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-06-18T19-14-21_305_LeagueClientUx.log
000000.001| ALWAYS| Running LeagueClientUx version 9.12.277.8490
000000.001|   OKAY| Initial working directory: "C:\Riot Games\League of Legends"
000000.003|   OKAY| Current process: "C:\Riot Games\League of Legends\LeagueClientUx.exe"
000000.003|   OKAY| Command line arguments:
	--remoting-auth-token=a8KpJwTbc0lVFKSWM8aBAA
	--respawn-command=LeagueClient.exe
	--respawn-display-name=League of Legends
	--app-port=34993
	--install-directory=C:\Riot Games\League of Legends
	--app-name=LeagueClient
	--ux-name=LeagueClientUx
	--ux-helper-name=LeagueClientUxHelper
	--log-dir=LeagueClient Logs
	--bugsplat-name=league_client_riotgames_com
	--bugsplat-platform-id=NA1
	--app-log-file-path=C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-06-18T19-13-37_64_LeagueClient.log
	--app-pid=64
	--no-proxy-server
000000.003|   OKAY| Memory Monitor enabled:
000000.003|   OKAY| - update interval 5s
000000.003|   OKAY| - memory delta threshold 10MiB
000000.003|   OKAY| - page fault delta threshold 100K
000000.003|   OKAY| - region count delta threshold 10
000000.007| ALWAYS| Using Ux render executable path: LeagueClientUxRender.exe
000000.007|   OKAY| Working Set Size: 81MiB Peak: 81MiB   Pagefile Usage: 64MiB Peak: 64MiB   Private Usage: 0MiB
000000.007|   OKAY| Paged Pool Usage: 0MiB Peak: 0MiB   Non-Paged Pool Usage: 0MiB Peak: 0MiB
000000.007|   OKAY| Committed Total: 148MiB   Committed Image: 94MiB   Committed Mapped: 0MiB   Committed Private: 53MiB   Reserved Total: 2352MiB   Reserved Image: 0MiB   Reserved Mapped: 0MiB   Reserved Private: 2352MiB   Free Total: 1595MiB   Limit: 4095MiB   Largest Free: 1355MiB   Region Count: 384
000000.007|   OKAY| Page Fault Count: 0K
000000.011| ALWAYS| Cef CommandLine: "C:/Riot Games/League of Legends/LeagueClientUx.exe" --app-log-file-path="C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-06-18T19-13-37_64_LeagueClient.log" --app-name=LeagueClient --app-pid=64 --app-port=34993 --browser-subprocess-path=LeagueClientUxRender.exe --bugsplat-name=league_client_riotgames_com --bugsplat-platform-id=NA1 --install-directory="C:\Riot Games\League of Legends" --lang=en-US --log-dir="LeagueClient Logs" --log-file="C:\Riot Games\League of Legends\debug.log" --no-proxy-server --no-sandbox --remoting-auth-token=a8KpJwTbc0lVFKSWM8aBAA --respawn-command=LeagueClient.exe --respawn-display-name="League of Legends" --ux-helper-name=LeagueClientUxHelper --ux-name=LeagueClientUx --disable-spell-checking --no-displaying-insecure-content
000000.245| ALWAYS| Initial dpiScale = 1.000000
000000.245| ALWAYS| Using cookie store at C:/Riot Games/League of Legends/Cookies
000000.246|   OKAY| Creating browser process.
000000.251| ALWAYS| App file system path is: C:\Riot Games\League of Legends\
000000.251| ALWAYS| Plugins file system path used : Plugins\.
000000.253| ALWAYS| Trying to connect to app process.
000000.304| ALWAYS| Connected to app process after 1 attempts.
000003.339| ALWAYS| Backend process is now running.
000005.008|   OKAY| Private Usage: 12MiB (+12)
000007.460|   OKAY| Setting mouse intercept hook.
000007.460|   OKAY| Registering window.
000007.460|   OKAY| Registering window class R.
000007.460|   OKAY| Loading icons.
000007.575|   OKAY| New window requested at 0,0 with dimensions 1280,720.
000007.577|   OKAY| Creating ux window with url https://riot:a8KpJwTbc0lVFKSWM8aBAA@127.0.0.1:34993/bootstrap.html.
000007.577| ALWAYS| Deleting non-whitelisted cookies
000007.577|   OKAY| Running message loop.
000007.695|   OKAY| Creating main WindowAppModule window 1.
000007.696|   OKAY| Ux window 1 created.
000007.702|   OKAY| Creating main browser window 1.

**Comment by Getta91** [comment]
I am not a spécialiste liké mmtrt but I had a lot of bugsplat. To fix this all I did was running this (thanks to mmtrt 😉) : leagueoflegends.winecfg
And then setting the Windows environment to Windows XP. Nos it is working fine. Hope this help.

**Comment by Aerodin** [comment]
Changing the default from Windows 7 to  XP worked.

**Comment by Getta91** [comment]
perfect
