### ISSUE TITLE
erro 

### ISSUE THREAD

**Issue by zeroacucar** [mmtrt/leagueoflegends#58]
"The League Of Legends snap is experimental, built with development releases of upstream WINE and may not function as expected. 

IF you encounter issues please report them on the League Of Legends snap issue tracker."

what I have to do to fix that?

**Comment by mmtrt** [comment]
That's the notification shown in when league snap starts every time, if the game not working for you make sure you post log from the terminal when launching snap via command

snap run leagueoflegends

**Comment by zeroacucar** [comment]
**snap run leagueoflegends**
0009:err:module:import_dll Library libcurl.dll (which is needed by L"C:\\Riot Games\\League of Legends\\LeagueClient.exe") not found
0009:err:module:import_dll Library libssl-1_1.dll (which is needed by L"C:\\Riot Games\\League of Legends\\LeagueClient.exe") not found
0009:err:module:import_dll Library libcrypto-1_1.dll (which is needed by L"C:\\Riot Games\\League of Legends\\LeagueClient.exe") not found
0009:err:module:import_dll Library libzstd.dll (which is needed by L"C:\\Riot Games\\League of Legends\\LeagueClient.exe") not found
0009:err:module:import_dll Library MSVCP140.dll (which is needed by L"C:\\Riot Games\\League of Legends\\LeagueClient.exe") not found
0009:err:module:LdrInitializeThunk Importing dlls for L"C:\\Riot Games\\League of Legends\\LeagueClient.exe" failed, status c0000135

**Comment by mmtrt** [comment]
can you post info of these commands

snap info leagueoflegends
snap interfaces leagueoflegends

**Comment by zeroacucar** [comment]
**snap info leagueoflegends**
name:      leagueoflegends
summary:   leagueoflegends is MOBA game developed and published by Riot Games.
publisher: Taqi Raza (mmtrt)
license:   unset
description: |
  * League of Legends is a 3D, third-person multiplayer online battle arena
  (MOBA) game. The game consists of 3 current running game modes: Summoner's
  Rift, Twisted Treeline, and Howling Abyss. Another game mode, The Crystal
  Scar, has since been removed. Players compete in matches, lasting anywhere
  from 20 to 60 minutes on average. In each game mode teams work together to
  achieve a victory condition, typically destroying the core building (called
  the Nexus) in the enemy team's base after bypassing a line of defensive
  structures called turrets, or towers.
  
  * In League of Legends, players assume the role of an unseen "summoner"
  that controls a "champion" with unique abilities and battle against a team
  of other players or computer-controlled champions. The goal is usually to
  destroy the opposing team's "nexus", a structure which lies at the heart of
  a base protected by defensive structures, although other distinct game
  modes exist as well. Each League of Legends match is discrete, with all
  champions starting off fairly weak but increasing in strength by
  accumulating items and experience over the course of the game. The
  champions and setting blend a variety of elements, including high fantasy,
  steampunk, and Lovecraftian horror.
  
  * League of Legends was generally well received upon its release in 2009,
  and has since grown in popularity, with an active and expansive fanbase. By
  July 2012, League of Legends was the most played PC game in North America
  and Europe in terms of the number of hours played. As of January 2014, over
  67 million people played League of Legends per month, 27 million per day,
  and over 7.5 million concurrently during peak hours. League has among the
  largest footprints of any game in streaming media communities on platforms
  such as YouTube and Twitch; it routinely ranks first in the most-watched
  hours. In September 2016 the company estimated that there are over 100
  million active players each month. The game's popularity has led it to
  expand into merchandise, with toys, accessories, apparel, as well as
  tie-ins to other media through music videos, web series, documentaries, and
  books.
  
  Support me: https://bit.ly/2XkT2bl
commands:
  - leagueoflegends
  - leagueoflegends.wineboot
  - leagueoflegends.winecfg
  - leagueoflegends.wineserver
  - leagueoflegends.winetricks
snap-id:      TnAzZk88wGeE2DHZLeX5DMJrAC5kdGj5
tracking:     edge
refresh-date: today at 01:03 -03
channels:
  stable:    –                        
  candidate: –                        
  beta:      –                        
  edge:      1.0 2019-06-16 (45) 90kB devmode
installed:   1.0            (45) 90kB devmode

**snap interfaces leagueoflegends**

Slot                                    Plug
:desktop                                leagueoflegends
:desktop-legacy                         leagueoflegends
:home                                   leagueoflegends
:network                                leagueoflegends
:network-bind                           leagueoflegends
:opengl                                 leagueoflegends
:pulseaudio                             leagueoflegends
:wayland                                leagueoflegends
:x11                                    leagueoflegends
gtk-common-themes:gtk-3-themes          leagueoflegends
gtk-common-themes:icon-themes           leagueoflegends
wine-platform-4-staging:wine-4-staging  leagueoflegends
wine-platform-runtime:wine-runtime      leagueoflegends
-                                       leagueoflegends:hardware-observe
-                                       leagueoflegends:joystick
-                                       leagueoflegends:process-control

'snap interfaces' is deprecated; use 'snap connections'.

**Comment by mmtrt** [comment]
Can you tell me which os you are using and is it i386 or amd64

Also make sure you have install wine dependencies

https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell/

**Comment by zeroacucar** [comment]
i386

**Comment by Getta91** [comment]
#57 . Try using the wine app-image. It worked for me!

**Comment by mmtrt** [comment]
I don't think that will work for him as he's using i386 os and appimage is amd64.

**Comment by Getta91** [comment]
Humm... Ye sure.
