### ISSUE TITLE
Installing League from scratch fails on Arch

### ISSUE THREAD

**Issue by plntyk** [mmtrt/leagueoflegends#59]
Error:
On a clean snap install the League of Legends installer on Arch does not work with the 3 commands provided in the 
README. seems like issue mentioned in #7 / issue #52

Solution:
setting the wineprefix to Windows XP via 

`snap run leagueoflegends.winecfg`

makes the Installer run

So the documentation should be enhanced to state that command more explicitly - the "winecfg" command isnt mentioned in #7 so users have to read through the closed tickets to find it.

**Comment by mmtrt** [comment]
Ty I've updated #7 now should be more clear with solution.
