### ISSUE TITLE
Enhancing performance

### ISSUE THREAD

**Issue by IronJuancho** [mmtrt/leagueoflegends#6]
Is there a way to enhance the game performance? Like maybe upgrading wine. Do the open source amd drivers work better or should i install the amd gpu pro?

**Comment by mmtrt** [comment]
my suggestion would be `gallium nine` which works best only with `amd` `intel` in directx9 games with native performance though this snap does not support it so you would have setup it outside of snap env and as for drivers open source ones should be good.

I don't have `amd` hardware to test these myself.

**Comment by IronJuancho** [comment]
I am very new to linux and dont know much. I ran the snap on a fresh install of linux mint. I didnt installl wine before running the snap, should i do that?

The gallium nine thing you sent me has a tutorial https://wiki.ixit.cz/d3d9_tutorial, I think i can follow it but I have some questions
In step 6 it says:
`sudo apt-get install aptitude && sudo aptitude install wine3.0`
should it say another number of wine since there are newer versions?
and from step 8 to launching the game im completely lost. I don know what a wineprefix is

**Comment by mmtrt** [comment]
you can skip `wineprefix` step though it is necessary if you want to use `wineprefix` to a different directory and `wine3.0` package name which has version `3.18` is on the ppa that you added from tutorial.

**Comment by mmtrt** [comment]
it doesn't matter when you launch game with wine it also setups wine prefix auto and `winecfg` command opens winecfg dialog which has wine prefix settings when running wine cfg for first time when no wine prefix is created so that command also creates wine prefix then open wine cfg of it.

**Comment by IronJuancho** [comment]
THanks a lot for the help man. Unfortunately the game gives a Bugsplat when i try to run it with gallium enabled.
But still thanks for helping me with the process, perhaps it might come handy with another game
