### ISSUE TITLE
hi cpu usage

### ISSUE THREAD

**Issue by adserba** [mmtrt/leagueoflegends#62]
It's not really a problem , because everything works verry well, but sometimes , I would say randomly after a few games, the client uses one thread of cpu to 100%, not allowing cpu boost. after restart everything goes to normal...cpu usage spread across all cores.
ubuntu 19.04
d9vk

**Comment by mmtrt** [comment]
Yes league client is quite buggy and uses high cpu some times it better to kill `wineserver` and start over again which is why I've added this command to kill `wineserver`

`leagueoflegends.wineserver`

**Comment by mmtrt** [comment]
There is nothing I can do about this issue so closing this.
