### ISSUE TITLE
[Question] Can I use my default cursor in this application?

### ISSUE THREAD

**Issue by denielt** [mmtrt/leagueoflegends#63]
Well, when I open the client or when I hover over it my cursor becomes small and black (Adwaita) just like ubuntu, can I use this application with my default cursor (Xcursor-breeze)? I'm playing it on Manjaro Gnome. Thanks for your help :)

**Comment by mmtrt** [comment]
I don't think I can do anything about this since this snap uses `gtk-common-themes` snap which unfortunately don't have breeze cursors.

Though you can see progress regarding this issue [Link](https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues/6)
