### ISSUE TITLE
Bugsplat after login

### ISSUE THREAD

**Issue by Jose-Sampaio** [mmtrt/leagueoflegends#64]
After the JUly 17th patch, i've tried to login to league, as usual, but after putting my username and password the client crashes. I've tried a full restauration, but it didn't work. Could anyone help me? Ubuntu 18.04

**Comment by mmtrt** [comment]
Try setting `winxp` in wineprefix
`leagueoflegends.winecfg`

**Comment by Jose-Sampaio** [comment]
Could you explain me how to do that? Kind of a linux noob here

**Comment by mmtrt** [comment]
@Jose-Sampaio see above post updated.

**Comment by Jose-Sampaio** [comment]
Just did it, still bugsplatting :/
![Screenshot from 2019-07-18 13-15-59](https://user-images.githubusercontent.com/42847309/61474129-4ae43300-a95e-11e9-804f-5a162f4f560b.png)

**Comment by Jose-Sampaio** [comment]
The weird thing is that it worked just fine untill this morning, I've even played yesterday and it was OK... I've tried uninstalling and reinstalling, but nothing happened

**Comment by mmtrt** [comment]
can you post output of this command from terminal
`snap list | grep -e wine -e league `

**Comment by Jose-Sampaio** [comment]
leagueoflegends          1.0                         45    edge       mmtrt         devmode
wine-platform            3.0.4-4.6                   128   stable     mmtrt         -
wine-platform-4-staging  4.9                         7     candidate  mmtrt         -
wine-platform-runtime    v1.0                        7     candidate  mmtrt         -

**Comment by Jose-Sampaio** [comment]
Well, I don't know what happened, but it logged in... I'll keep this issue open for a few more days to see if the problem returns, but Iactually didn't changed anything, it just started working fine again...
My theory is that maybe Riot was working with the client at the time I tried to Log in, beacause there was an error with spec mode and now there is no warning. Thx anyway!
