### ISSUE TITLE
crash after hiting play

### ISSUE THREAD

**Issue by observer1988** [mmtrt/leagueoflegends#65]
Unhandled exception: page fault on read access to 0x7eb09310 in 32-bit code (0x7eb09310).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb09310 ESP:0032f1cc EBP:0032f1e8 EFLAGS:00010202(  R- --  I   - - - )
 EAX:7eb09310 EBX:0032f318 ECX:00000001 EDX:00000001
 ESI:7ffd8000 EDI:00000000
Stack dump:
0x0032f1cc:  7e8e9744 00000000 00000000 0032f740
0x0032f1dc:  0032f318 7ffd8000 00000000 0032f288
0x0032f1ec:  7e8ea5ae 7eb09310 00000000 00000000
0x0032f1fc:  0032f740 00000000 00000001 00000000
0x0032f20c:  ffffffff 00000000 0000008c 7eb09310
0x0032f21c:  00000000 0032f24c 00000000 00000000
Backtrace:
=>0 0x7eb09310 in libz.so.1 (+0x1e310) (0x0032f1e8)
  1 0x7e8ea5ae UnhookWindowsHookEx+0x5fd() in user32 (0x0032f288)
  2 0x7e8ea7e5 UnhookWindowsHookEx+0x834() in user32 (0x0032f558)
  3 0x7e8eac41 CallMsgFilterW+0x40() in user32 (0x0032f598)
  4 0x7e8d9f1b IsDialogMessageW+0x6a() in user32 (0x0032f708)
  5 0x7e8da70a IsDialogMessageW+0x859() in user32 (0x0032f778)
  6 0x7e8da90f DialogBoxParamW+0x8e() in user32 (0x0032f7b8)
  7 0x0040ce67 EntryPoint+0xffffffff() in bssndrpt (0x0032f924)
  8 0x00403c3b EntryPoint+0xffffffff() in bssndrpt (0x0032fe6c)
  9 0x004028f0 EntryPoint+0xffffffff() in bssndrpt (0x0032fe74)
  10 0x00423731 in bssndrpt (+0x23730) (0x0032fec0)
  11 0x7b482ac9 call_process_entry+0x18() in kernel32 (0x0032fee8)
  12 0x7b485091 ExitProcess+0x25b4() in kernel32 (0x0032ffd8)
  13 0x7b482ada call_process_entry+0x29() in kernel32 (0x0032ffec)
0x7eb09310: pop	%ss
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Export          bssndrpt
PE	  460000- 3af0000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b84b000	Dwarf           kernel32<elf>
  \-PE	7b430000-7b84b000	\               kernel32
ELF	7bc00000-7bd71000	Deferred        ntdll<elf>
  \-PE	7bc30000-7bd71000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d13f000-7d16d000	Deferred        iphlpapi<elf>
  \-PE	7d150000-7d16d000	\               iphlpapi
ELF	7d1b3000-7d1fe000	Deferred        uxtheme<elf>
  \-PE	7d1c0000-7d1fe000	\               uxtheme
ELF	7d200000-7d207000	Deferred        libxfixes.so.3
ELF	7d207000-7d213000	Deferred        libxcursor.so.1
ELF	7d2d7000-7d309000	Deferred        libexpat.so.1
ELF	7d309000-7d354000	Deferred        libfontconfig.so.1
ELF	7d354000-7d38e000	Deferred        libpng16.so.16
ELF	7d38e000-7d44b000	Deferred        libfreetype.so.6
ELF	7d44b000-7d45e000	Deferred        libxi.so.6
ELF	7d45e000-7d462000	Deferred        libxcomposite.so.1
ELF	7d462000-7d46f000	Deferred        libxrandr.so.2
ELF	7d46f000-7d47b000	Deferred        libxrender.so.1
ELF	7d47b000-7d482000	Deferred        libxxf86vm.so.1
ELF	7d482000-7d486000	Deferred        libxinerama.so.1
ELF	7d486000-7d4a1000	Deferred        libbsd.so.0
ELF	7d4a1000-7d4a8000	Deferred        libxdmcp.so.6
ELF	7d4a8000-7d4ac000	Deferred        libxau.so.6
ELF	7d4ac000-7d4d8000	Deferred        libxcb.so.1
ELF	7d4d8000-7d622000	Deferred        libx11.so.6
ELF	7d622000-7d637000	Deferred        libxext.so.6
ELF	7d637000-7d6ec000	Deferred        winex11<elf>
  \-PE	7d660000-7d6ec000	\               winex11
ELF	7d6ec000-7d83b000	Deferred        oleaut32<elf>
  \-PE	7d720000-7d83b000	\               oleaut32
ELF	7d83b000-7d877000	Deferred        ws2_32<elf>
  \-PE	7d850000-7d877000	\               ws2_32
ELF	7d877000-7d89c000	Deferred        imm32<elf>
  \-PE	7d880000-7d89c000	\               imm32
ELF	7d89c000-7d8f7000	Deferred        usp10<elf>
  \-PE	7d8b0000-7d8f7000	\               usp10
ELF	7d8f7000-7da63000	Deferred        comctl32<elf>
  \-PE	7d920000-7da63000	\               comctl32
ELF	7da63000-7da7f000	Deferred        aclui<elf>
  \-PE	7da70000-7da7f000	\               aclui
ELF	7da7f000-7dbfe000	Deferred        ole32<elf>
  \-PE	7dab0000-7dbfe000	\               ole32
ELF	7dbfe000-7dc32000	Deferred        shcore<elf>
  \-PE	7dc10000-7dc32000	\               shcore
ELF	7dc32000-7e667000	Deferred        shell32<elf>
  \-PE	7dc60000-7e667000	\               shell32
ELF	7e667000-7e6f8000	Deferred        shlwapi<elf>
  \-PE	7e680000-7e6f8000	\               shlwapi
ELF	7e6f8000-7e723000	Deferred        version<elf>
  \-PE	7e700000-7e723000	\               version
ELF	7e723000-7e879000	Deferred        gdi32<elf>
  \-PE	7e740000-7e879000	\               gdi32
ELF	7e879000-7eab0000	Dwarf           user32<elf>
  \-PE	7e8a0000-7eab0000	\               user32
ELF	7eab0000-7eaeb000	Deferred        mpr<elf>
  \-PE	7eac0000-7eaeb000	\               mpr
ELF	7eaeb000-7eb0a000	Dwarf           libz.so.1
ELF	7eb0a000-7ebac000	Deferred        wininet<elf>
  \-PE	7eb20000-7ebac000	\               wininet
ELF	7ebac000-7ec45000	Deferred        advapi32<elf>
  \-PE	7ebc0000-7ec45000	\               advapi32
ELF	7ec45000-7eceb000	Deferred        rpcrt4<elf>
  \-PE	7ec60000-7eceb000	\               rpcrt4
ELF	7ee99000-7eead000	Deferred        wow64cpu<elf>
  \-PE	7eea0000-7eead000	\               wow64cpu
ELF	7eead000-7eec1000	Deferred        libnss_files.so.2
ELF	7eec1000-7eedc000	Deferred        libnsl.so.1
ELF	7eedc000-7eeea000	Deferred        libnss_nis.so.2
ELF	7eeea000-7eef4000	Deferred        libnss_compat.so.2
ELF	7eef4000-7eff6000	Deferred        libm.so.6
ELF	7eff6000-7f000000	Deferred        librt.so.1
ELF	f7ba9000-f7bae000	Deferred        libdl.so.2
ELF	f7bae000-f7d8a000	Deferred        libc.so.6
ELF	f7d8a000-f7da9000	Deferred        libpthread.so.0
ELF	f7da9000-f7f73000	Dwarf           libwine.so.1
ELF	f7f75000-f7f9d000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000008 LeagueClient.exe
	["C:\Riot Games\League of Legends\LeagueClient.exe"]
	000000e0    0
	000000dd    0
	0000007f    0
	0000007d    0
	0000007a    0
	00000079    0
	00000077    0
	00000076    0
	00000075   15
	00000074    0
	00000073    0
	00000072    0
	00000071    0
	00000070    0
	0000006f    0
	00000056    0
	00000053    0
	00000052    0
	00000051    0
	0000004c    0
	0000004b    0
	0000004a    0
	00000049    0
	00000048    0
	00000047    0
	00000046    0
	00000045    0
	00000044    0
	00000043    0
	00000042    0
	00000041    0
	00000040    0
	0000003f    0
	0000003e    0
	0000003d    0
	0000003c    0
	0000003b    0
	0000003a    0
	00000039    0
	00000038    0
	00000037    0
	00000036    0
	00000035    0
	00000034    0
	00000033    0
	00000032    0
	00000031    0
	00000030    0
	0000002f    0
	0000002e    0
	0000002d    0
	0000002c    0
	0000002b    0
	0000002a    0
	00000009    0
0000000e services.exe
	00000025    0
	00000022    0
	0000001a    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	0000001f    0
	0000001c    0
	0000001b    0
	00000019    0
0000001d explorer.exe
	00000029    0
	00000028    0
	00000027    0
	0000001e    0
00000020 winedevice.exe
	00000026    0
	00000024    0
	00000023    0
	00000021    0
000000b5 League of Legends.exe
	["C:/Riot Games/League of Legends/Game/League of Legends.exe" "192.64.173.107 5398 /Wrc4sMWuhhV+PBDAOKI/g== 108000906" "-PlayerID=108000906" "-GameID=3109491679" "-GameBaseDir=C:/Riot Games/League of Legends" "-Region=NA" "-Locale=en_US" "-SkipRads" "-SkipBuild" "-EnableLNP" "-UseNewX3D=1" "-UseNewX3DFramebuffers=1" "-RiotClientPort=46827" "-RiotClientAuthToken=66Vl2UHsUTa74dnu2xFVFQ"]
	000000be    0
000000ef (D) C:\Riot Games\League of Legends\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\jinx\Temp\BsSndRpt.ini"  /dl]
	000000ed    0 <==
00000089 explorer.exe
	00000109    0
	00000108    0
	0000010a    0
	00000088    0
System information:
    Wine build: wine-4.9 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.15.0-20-generic

**Comment by mmtrt** [comment]
Any info about you system hardware and drivers used, distro used and how are you launching snap and also provide info of `snap list | grep -e wine -e league` .
