### ISSUE TITLE
Wait timed out in thread error

### ISSUE THREAD

**Issue by NickPignato** [mmtrt/leagueoflegends#66]
Both of these paste bins are from running the game from root:
https://pastebin.com/c1eXsjGW
https://pastebin.com/dpdtpvvP

This pastebin is smaller because I killed the process too fast because this error is haunting me
https://pastebin.com/BuD2HS7r

I was able to fix it for alittle by swapping from beta and candidate wine versions but now thats not fixing it

**Comment by mmtrt** [comment]
That issue happens time to time there is nothing I can about it and please don't launch snap with root this will likely break snap execution avoid it.

**Comment by stuartfoxcroft** [comment]
Can confirm this issue is benign and doesn't affect gameplay, just make sure to ctrl-C the process if you then want to run other intensive processes
