### ISSUE TITLE
League snap and dxvk

### ISSUE THREAD

**Issue by Getta91** [mmtrt/leagueoflegends#67]
Hi @mmtrt! I hope you are well and thanks for all your help😁👍. I am trying to install dxvk for 1 week into league snap (I mean d9vk) in order to improve my gaming experience. After following the instructions on the official dxvk github, everything seemed to be fine in the leagueoflegends.winecfg (I see 5 libraries : d3d9, d3d11, d3d10, d3d10_core, dxgi) but when I launch league I am getting this error : 

00078:err:vulkan:wine_vk_instance_load_physical_devices Failed to enumerate physical devices, res=-3
00078:err:vulkan:wine_vkCreateInstance Failed to load physical devices, res=-3
terminate called after throwing an instance of 'dxvk::DxvkError'

I don't know why I am getting this... 
So I was wondering if league snap is compatible with d9vk or not? And if the answer is yes, can you explain to me how to do this? Thanks again
         From a vel'koz lover 😂👍😁😁😁

Ps: I have wine staging 4.13 and kubuntu 19.04

**Comment by mmtrt** [comment]
You could be missing i386 vulkan pkgs [see: how to install](https://github.com/lutris/lutris/wiki/Installing-drivers) and yes vulkan support is there.

**Comment by Getta91** [comment]
For now I am not home but I will check this! Thanks for your support 👍

**Comment by Getta91** [comment]
Ok so I did so and installed new packages, but league still frozen on the first logo before the login screen. Here is the log file:
[league.log](https://github.com/mmtrt/leagueoflegends/files/3538683/league.log)

Thanks

**Comment by mmtrt** [comment]
Can you tell me about your gpu and drivers used, i think there is issue with amd cards with vulkan in snap and appimg it could be related to it and since I don't own amd devices can't locally test.

**Comment by Getta91** [comment]
Here we go:
cat /proc/cpuinfo 
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Celeron(R) CPU B840 @ 1.90GHz
stepping        : 7
microcode       : 0x2f
cpu MHz         : 1027.559
cache size      : 2048 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 3791.36
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Celeron(R) CPU B840 @ 1.90GHz
stepping        : 7
microcode       : 0x2f
cpu MHz         : 1099.987
cache size      : 2048 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 3791.36
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
 

blotemmanuel@BLOT-Emmanuel-HP-6469b:~$ sudo ubuntu-drivers devices
[sudo] Mot de passe de blotemmanuel : 
== /sys/devices/pci0000:00/0000:00:1c.3/0000:24:00.0 ==
modalias : pci:v000014E4d00004727sv0000103Csd0000145Cbc02sc80i00
vendor   : Broadcom Inc. and subsidiaries
model    : BCM4313 802.11bgn Wireless Network Adapter
driver   : bcmwl-kernel-source - distro non-free


Greetings from France

**Comment by mmtrt** [comment]
That does not have gpu info, can you install `vulkan-tools` pkg and test `vkcube` see if that runs and post info of `vulkaninfo` command.

**Comment by Getta91** [comment]
There are some errors

blotemmanuel@BLOT-Emmanuel-HP-6469b:~$ sudo apt install vulkan-tools
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
vulkan-tools est déjà la version la plus récente (1.1.101.0+dfsg1-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
blotemmanuel@BLOT-Emmanuel-HP-6469b:~$ vkcube
vkcube: /build/vulkan-tools-35Ffza/vulkan-tools-1.1.101.0+dfsg1/cube/cube.c:3164: demo_init_vk: Assertion `!err' failed.
Abandon (core dumped)
blotemmanuel@BLOT-Emmanuel-HP-6469b:~$ vulkaninfo
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_intel.so: wrong ELF class: ELFCLASS32
ERROR: [Loader Message] Code 0 : /usr/lib/i386-linux-gnu/libvulkan_radeon.so: wrong ELF class: ELFCLASS32
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.97

/build/vulkan-tools-35Ffza/vulkan-tools-1.1.101.0+dfsg1/vulkaninfo/vulkaninfo.c:5028: failed with VK_ERROR_INITIALIZATION_FAILED

**Comment by mmtrt** [comment]
do you have installed amd64 vulkan pkgs installed?

apt list --installed 2>/dev/null | grep vulkan

**Comment by Getta91** [comment]
I am getting this : blotemmanuel@BLOT-Emmanuel-HP-6469b:~$ apt list --installed 2>/dev/null | grep vulkan
libvulkan-dev/disco,now 1.1.101.0-2 amd64  [installé]
libvulkan1/disco,now 1.1.101.0-2 amd64  [installé]
libvulkan1/disco,now 1.1.101.0-2 i386  [installé, automatique]
mesa-vulkan-drivers/disco-updates,now 19.0.8-0ubuntu0~19.04.1 amd64  [installé]
mesa-vulkan-drivers/disco-updates,now 19.0.8-0ubuntu0~19.04.1 i386  [installé]
vulkan-tools/disco,now 1.1.101.0+dfsg1-1 amd64  [installé]
vulkan-utils/disco,disco,now 1.1.101.0+dfsg1-1 all  [installé]

**Comment by Getta91** [comment]
is this the GPU info?

blotemmanuel@BLOT-Emmanuel-HP-6469b:~$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

**Comment by mmtrt** [comment]
Yeah thats `intel` your laptop has two gpus `amd` and `intel` and I think you need to launch apps and games with `primusrun` or `optirun` to use discrete gpu and I know these option nor I have dual gpu system to test. Maybe try to fix your vulkan.

**Comment by Getta91** [comment]
How to maunch league with primusrun or optirun?

**Comment by mmtrt** [comment]
optirun leagueoflegends

**Comment by Getta91** [comment]
ok will try

**Comment by Getta91** [comment]
Hi! I found the problem. The fact is that my intel card doesn't support vulkan. I will just renounce to d9vk.

Thanks!
