### ISSUE TITLE
the game does not open

### ISSUE THREAD

**Issue by GPaso** [mmtrt/leagueoflegends#68]
i wait and wait and try again, and no.

**Comment by mitrechosa** [comment]
do you did this?

Setting the wineprefix os to Windows XP via
snap run leagueoflegends.winecfg

**Comment by mmtrt** [comment]
Anything in log when launching game from terminal command `leagueoflegends`. Also can you post info of this command `snap list | grep -e wine -e league`

**Comment by GPaso** [comment]
I am sorry to bother, i really do not recall to have opened this issue.
But in short, i found and followed this blog: https://www.linuxmadesimple.info/2018/11/how-to-install-league-of-legends-on_23.html
It worked until i started a game, and crashed.
Then i found this repo and followed the Readme, all works as expected!
Thanks for the snap, and again sorry to bother.

**Comment by emost41** [comment]
Hey, i have the same issue launcher is opening but after champ select, it crashed 
i did this wineprefix to windows xp 
and my nap list | grep -e wine -e league result is 
leagueoflegends          1.0                         46    edge      mmtrt            devmode
wine-platform-4-staging  4.9                         5     stable    mmtrt            -
wine-platform-runtime    v1.0                        23    stable    mmtrt 
can u help me guys ?
