### ISSUE TITLE
Voice chat in game doesn't work

### ISSUE THREAD

**Issue by mitrechosa** [mmtrt/leagueoflegends#69]
game runs flawessly but, voice chat doesn't work.
is a built in function inside the game.

I don't know if something is missing or it is just a normal behavior where you are working on.
any further information just let me know.

**Comment by mmtrt** [comment]
Is there anything in wine log when using it and does game crashes when using it or just it not works, also do note that I've not tested that game feature entirely and nor I play league these days so I can't test much.

**Comment by mitrechosa** [comment]
The functionally of voice chat is embebbed in the game and runs automatically when you belong to a party with more than 1 member.
There is an icon bottom in the screen where you can adjust volume and mute players. That part doenst work and you are will not added in the coversation automatilly (or even forced) as usually happens.
I cannot see errors in the log or something rare but it shows the actions when you try to press the buttons to adjust options in the voice chat. Tomorrow I can add some screenshots

**Comment by mitrechosa** [comment]
guys, is working,
I will close this.
