### ISSUE TITLE
[10/6/19] Important Notice

### ISSUE THREAD

**Issue by mmtrt** [mmtrt/leagueoflegends#7]
**Disclaimer**

> This snap is Devmode atm so it is posted only for testing purpose and it is only meant for development or testing at this point. As a consequence ( This snap will not refresh automatically and may perform arbitrary system changes outside of the security sandbox snaps are generally confined to, which may put your system at risk ) and this may change in the future when this snap is fit for confinement change.
##

**It is mandatory to update snap manually by this command**
* `snap refresh --edge leagueoflegends`

**Constant bugsplat Issue on launcher**
* Snap needs `winxp` in wineprefix to fix constant bugspalt issue reported by some users #39 #44 #51 #52  
> **Solution**
* Setting the wineprefix os to Windows XP via
`snap run leagueoflegends.winecfg`
* Fixes launcher to run on fresh installed game.

##
**Update - 07/6/19**
* Migrated league snap to use new `wine-platform-xxxx` snaps.
* New league snap users now have to refresh `wine-platform-runtime` and `wine-platform-4-staging` from candidate snap branch.
`snap refresh --candidate wine-platform-runtime`
`snap refresh --candidate wine-platform-4-staging`
* Old users that have updated league snap have to install above two snaps if these snaps were auto installed on updating league snap then launch above two commands.
* I will not be maintaining `wine-platform` snap from now on so that will receive no updates better do update snap. 

**Update - 09/6/19**
* Removed `dgvoodoo` install options
* Added new `d9vk` install options
`D9VK_S - This installs currently available stable release`
`D9VK_M - This installs currently available master release`
* Added `dxvk` hud envar detection (`checks for native d3dx in wine if yes then do magic`)
* Added default `dxvk` hud envar (`if user not have envar used then default is used`)
* Added back winetricks verb d3d9x (`fixes font issue for users that are using preinstalled league`)

**Update - 10/6/19**
* Pushed `wine-platform-runtime` rev with updated driver pkgs to beta branch. This should help `Intel` and `Amd` users in getting some fps increase.
`snap refresh --beta wine-platform-runtime`
##
<details>
  <summary>Older changelog</summary>

**old changes**
* This snap has changed its `wine-base`
* Means it will now use `wine-platform` instead of `wine-platform-i386` which will soon be removed from snapstore as I no longer maintain it.
* Snap now uses win64 `WINEPREFIX` by default on `amd64` systems.
* Backup game files before removing win32 `WINEPREFIX` --> `$HOME/snap/leagueoflegends/common/.wine`

**Update changed base: core18** - **12/3/19**
* Users must run above update command to update the snap.
* Update `wine-platform` snap from edge as well till its update is pushed to stable.

**Update added dgVoodoo + DXVK** - **13/3/19**
* Users are warned using modified directx dlls could lead getting ban in online games.
* Read Vulkan Driver support https://github.com/doitsujin/dxvk/wiki/Driver-support
* Read Hud settings https://github.com/doitsujin/dxvk/blob/master/README.md#hud

**Update - 14/4/19**
* reverted changing os to winxp on fresh install. (`Now game works under win7 with wine 4.6`) [currently changes are in edge branch it needs more testing]
* https://i.redd.it/3ggp5eyg0hq21.png [ `font issue on wine release 4.1 above still exists` ]
( workaround is to fresh install game **OR** backup your game files `$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games` then remove the league snap then install it again with your current region installer when it downloads the game close the launcher then the new so fresh game files are still on `wineprefix` here `$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games` so remove that folder [`make sure you have game backup earlier`] and then move your game backup back to `$HOME/snap/leagueoflegends/common/.wine/drive_c` and then start your game then no longer font issue )

**Update - 21/5/19**
* `wine-platform` snap update includes patched glibc + wine for league patch 9.10 + new snap revision update fixes missing wine vulkan support by compiling wine-staging with libvukan-dev pkg previous patched wine had build missing. Now `d9vk` works.
* `league` snap update adds newer `d9vk` build + some cosmetic changes added and removed.
</details>

**Comment by Brunoxd123** [comment]
This is the message that appears dps that I try to enter lol
![Captura de tela de 2019-06-01 15-38-16](https://user-images.githubusercontent.com/51273116/58752698-e5111a00-8489-11e9-8f48-d89b9a6deccb.png)

**Comment by mmtrt** [comment]
@Brunoxd123 Yes it appears when league snap is launched what about it?
