### ISSUE TITLE
Leagueoflegends on snap fps problem

### ISSUE THREAD

**Issue by emost41** [mmtrt/leagueoflegends#70]
Finally i opened LoL after snap updates it's working fine now but fps during max 20-30. when together other champs it 10-5. i have amd and intel graphic card . and i'm new on ubuntu.

**Comment by emost41** [comment]
i think my amd driver is not working

**Comment by mmtrt** [comment]
I think you need to launch game from terminal `leagueoflegends' in starting of command first write primusrun or optirun then snap command written above to use discrete gpu.

**Comment by emost41** [comment]
i think this things for nvidia i have amd graphic card. 
when i wrote primus leagueoflegends
 primusrun leagueoflegends

Command 'primusrun' not found, but can be installed with:

sudo apt install primus
and then tried nstall primus 
Reading packing lists ... Done
Creating dependency tree
Reading status info ... Done
Some packages could not be installed. This situation requested an impossible situation
or use unstable distribution; and
some packages have not been created or are
indicates that.
The following information can help you resolve the situation:

The following packages have unmet dependencies:
 primus: Addictions: bumblebee but will not be established
E: If the problems could not be resolved, you have corrupted packages that are maintained
what should i do ?

**Comment by mmtrt** [comment]
[This](https://www.reddit.com/r/linux_gaming/comments/aoh5be/guide_hybrid_graphics_on_linux_nvidia_optimus/) guide has how to do it for `intel/amd` gpus though I don't have system with such gpus to test.

**Comment by emost41** [comment]
i think it never will be happen i got a lot of mistakes even sudo apt update ! 
even bumblebee  or amd drives even worse what should i do ? Clean system completely and start again ? is it helpfull ?

**Comment by mmtrt** [comment]
remove this old ppa `ubuntu-wine/ppa/ubuntu` which is obsolete [see how to](https://vitux.com/how-to-add-remove-ppa-repositories-in-ubuntu/)

**Comment by emost41** [comment]
I installed the system from the beginning, i will write about

**Comment by emost41** [comment]
hi again. now i have a different issues. when i try to install optimus or optirun for bumblebee my sistem locks after boot. becaıse of this again erase all things and clean install ubuntu. now i'm trying same things bla bla bla. i'm using ubuntu 18.04 . shuold i use linux mint vs is there any difference between these ?

**Comment by mmtrt** [comment]
I don't think you need to install these I've posted guide which had method for intel/amd, I don't think there is difference since mint uses same ubuntu base for there os and there might be some more applications added in there or more.

**Comment by emost41** [comment]
i couldnt find any solition thank u again :) but i erased ubuntu and instal windows again i think my gpu is dead
