### ISSUE TITLE
Run the Snap with the debug all

### ISSUE THREAD

**Issue by Getta91** [mmtrt/leagueoflegends#71]
Hi! I read on the Ubuntu forum that there IS a way to boost our performance on game :

<code>WINEDEBUG=-all wine "executable"</code>

The fact is that I can't figure out how to run this command with the snap package... Can you help me please?

Thanks for all your work. 😉

**Comment by mmtrt** [comment]
I do have plan to change all `envars` user changeable like I have implemented in wine appimages.

**Comment by Getta91** [comment]
That would be lovely!

**Comment by Getta91** [comment]
So I just installed Gallium nine on my wine staging. But I can't find how to enable it in the wine of the snap. Plz help

**Comment by mmtrt** [comment]
It doesn't work like that since rito made changes to league it needs patched wine to play it. Or you can build patched gallium wine to play it without snap or anything else needed.
