### ISSUE TITLE
Install d9vk

### ISSUE THREAD

**Issue by Getta91** [mmtrt/leagueoflegends#72]
Hi!
You said:

Added new d9vk install options
D9VK_S - This installs currently available stable release
D9VK_M - This installs currently available master release

How to activate those?

**Comment by mmtrt** [comment]
These options install d9vk to snap wineprefix ATM will only be selectable from fresh snap install and you can select it from bottom of list when it asks for region selection. Or you can move installed league folder riotgames from wineprefix to show that dialog and move back game folder when you have installed it.

**Comment by Getta91** [comment]
I didn't understand this well:

Or you can move installed league folder riotgames from wineprefix to show that dialog and move back game folder when you have installed it.

Sorry I am french

**Comment by mmtrt** [comment]
I meant you have to either remove `riot games` folder OR move it from `wineprefix` to show the region selection dialog. `wineprefix` path is `$HOME/snap/leagueoflegends/common/.wine`

**Comment by Getta91** [comment]
Ok I moved it but how to see the region selection dialog?

**Comment by mmtrt** [comment]
When you launch leagueoflegends snap

**Comment by Getta91** [comment]
by a command line?

**Comment by Getta91** [comment]
oh I found it

**Comment by Getta91** [comment]
I think so thanks

**Comment by Getta91** [comment]
Wait, should I use the stable one or the master one?

**Comment by Getta91** [comment]
My friend recommend me to use the stable one. Thanks man, u are the best
