### ISSUE TITLE
Well getting bugsplat after the champion choosing screen.

### ISSUE THREAD

**Issue by HekHek** [mmtrt/leagueoflegends#73]
Unhandled exception: page fault on write access to 0x0000000f in 32-bit code (0x7eb0c310).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb0c310 ESP:0032f1cc EBP:0032f1e8 EFLAGS:00010202(  R- --  I   - - - )
 EAX:7eb0c310 EBX:0032f318 ECX:00000001 EDX:00000001
 ESI:7ffd8000 EDI:00000000
Stack dump:
0x0032f1cc:  7e8ef744 00000000 00000000 0032f740
0x0032f1dc:  0032f318 7ffd8000 00000000 0032f288
0x0032f1ec:  7e8f05ae 7eb0c310 00000000 00000000
0x0032f1fc:  0032f740 00000000 00000001 00000000
0x0032f20c:  ffffffff 00000000 000000e0 7eb0c310
0x0032f21c:  00000000 0032f24c 00000000 00000000
Backtrace:
=>0 0x7eb0c310 in libz.so.1 (+0x1b310) (0x0032f1e8)
  1 0x7e8f05ae UnhookWindowsHookEx+0x5fd() in user32 (0x0032f288)
  2 0x7e8f07e5 UnhookWindowsHookEx+0x834() in user32 (0x0032f558)
  3 0x7e8f0c41 CallMsgFilterW+0x40() in user32 (0x0032f598)
  4 0x7e8dff1b IsDialogMessageW+0x6a() in user32 (0x0032f708)
  5 0x7e8e070a IsDialogMessageW+0x859() in user32 (0x0032f778)
  6 0x7e8e090f DialogBoxParamW+0x8e() in user32 (0x0032f7b8)
  7 0x0040ce67 EntryPoint+0xffffffff() in bssndrpt (0x0032f924)
  8 0x00403c3b EntryPoint+0xffffffff() in bssndrpt (0x0032fe6c)
  9 0x004028f0 EntryPoint+0xffffffff() in bssndrpt (0x0032fe74)
  10 0x00423731 in bssndrpt (+0x23730) (0x0032fec0)
  11 0x7b482ac9 call_process_entry+0x18() in kernel32 (0x0032fee8)
  12 0x7b485091 ExitProcess+0x25b4() in kernel32 (0x0032ffd8)
  13 0x7b482ada call_process_entry+0x29() in kernel32 (0x0032ffec)
0x7eb0c310: xorb	%dl,0xe(%edx)
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Export          bssndrpt
PE	  460000- 3465000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b84b000	Dwarf           kernel32<elf>
  \-PE	7b430000-7b84b000	\               kernel32
ELF	7bc00000-7bd71000	Deferred        ntdll<elf>
  \-PE	7bc30000-7bd71000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d12a000-7d158000	Deferred        iphlpapi<elf>
  \-PE	7d130000-7d158000	\               iphlpapi
ELF	7d19e000-7d1e9000	Deferred        uxtheme<elf>
  \-PE	7d1b0000-7d1e9000	\               uxtheme
ELF	7d1eb000-7d1f2000	Deferred        libxfixes.so.3
ELF	7d1f2000-7d1fe000	Deferred        libxcursor.so.1
ELF	7d271000-7d2a3000	Deferred        libexpat.so.1
ELF	7d2a3000-7d2ee000	Deferred        libfontconfig.so.1
ELF	7d2ee000-7d328000	Deferred        libpng16.so.16
ELF	7d394000-7d451000	Deferred        libfreetype.so.6
ELF	7d451000-7d464000	Deferred        libxi.so.6
ELF	7d464000-7d468000	Deferred        libxcomposite.so.1
ELF	7d468000-7d475000	Deferred        libxrandr.so.2
ELF	7d475000-7d481000	Deferred        libxrender.so.1
ELF	7d481000-7d488000	Deferred        libxxf86vm.so.1
ELF	7d488000-7d48c000	Deferred        libxinerama.so.1
ELF	7d48c000-7d4a7000	Deferred        libbsd.so.0
ELF	7d4a7000-7d4ae000	Deferred        libxdmcp.so.6
ELF	7d4ae000-7d4b2000	Deferred        libxau.so.6
ELF	7d4b2000-7d4de000	Deferred        libxcb.so.1
ELF	7d4de000-7d628000	Deferred        libx11.so.6
ELF	7d628000-7d63d000	Deferred        libxext.so.6
ELF	7d63d000-7d6f2000	Deferred        winex11<elf>
  \-PE	7d660000-7d6f2000	\               winex11
ELF	7d6f2000-7d841000	Deferred        oleaut32<elf>
  \-PE	7d720000-7d841000	\               oleaut32
ELF	7d841000-7d87d000	Deferred        ws2_32<elf>
  \-PE	7d850000-7d87d000	\               ws2_32
ELF	7d87d000-7d8a2000	Deferred        imm32<elf>
  \-PE	7d890000-7d8a2000	\               imm32
ELF	7d8a2000-7d8fd000	Deferred        usp10<elf>
  \-PE	7d8b0000-7d8fd000	\               usp10
ELF	7d8fd000-7da69000	Deferred        comctl32<elf>
  \-PE	7d920000-7da69000	\               comctl32
ELF	7da69000-7da85000	Deferred        aclui<elf>
  \-PE	7da70000-7da85000	\               aclui
ELF	7da85000-7dc04000	Deferred        ole32<elf>
  \-PE	7dac0000-7dc04000	\               ole32
ELF	7dc04000-7dc38000	Deferred        shcore<elf>
  \-PE	7dc10000-7dc38000	\               shcore
ELF	7dc38000-7e66d000	Deferred        shell32<elf>
  \-PE	7dc70000-7e66d000	\               shell32
ELF	7e66d000-7e6fe000	Deferred        shlwapi<elf>
  \-PE	7e680000-7e6fe000	\               shlwapi
ELF	7e6fe000-7e729000	Deferred        version<elf>
  \-PE	7e700000-7e729000	\               version
ELF	7e729000-7e87f000	Deferred        gdi32<elf>
  \-PE	7e750000-7e87f000	\               gdi32
ELF	7e87f000-7eab6000	Dwarf           user32<elf>
  \-PE	7e8b0000-7eab6000	\               user32
ELF	7eab6000-7eaf1000	Deferred        mpr<elf>
  \-PE	7eac0000-7eaf1000	\               mpr
ELF	7eaf1000-7eb10000	Dwarf           libz.so.1
ELF	7eb10000-7ebb2000	Deferred        wininet<elf>
  \-PE	7eb20000-7ebb2000	\               wininet
ELF	7ebb2000-7ec4b000	Deferred        advapi32<elf>
  \-PE	7ebd0000-7ec4b000	\               advapi32
ELF	7ec4b000-7ecf1000	Deferred        rpcrt4<elf>
  \-PE	7ec70000-7ecf1000	\               rpcrt4
ELF	7eea3000-7eeb7000	Deferred        wow64cpu<elf>
  \-PE	7eeb0000-7eeb7000	\               wow64cpu
ELF	7eeb7000-7eecb000	Deferred        libnss_files.so.2
ELF	7eecb000-7eee6000	Deferred        libnsl.so.1
ELF	7eee6000-7eef4000	Deferred        libnss_nis.so.2
ELF	7eef4000-7eefe000	Deferred        libnss_compat.so.2
ELF	7eefe000-7f000000	Deferred        libm.so.6
ELF	f7b43000-f7b4d000	Deferred        librt.so.1
ELF	f7b4f000-f7b54000	Deferred        libdl.so.2
ELF	f7b54000-f7d30000	Deferred        libc.so.6
ELF	f7d30000-f7d4f000	Deferred        libpthread.so.0
ELF	f7d4f000-f7f19000	Dwarf           libwine.so.1
ELF	f7f1b000-f7f43000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000008 LeagueClient.exe
	["C:\Riot Games\League of Legends\LeagueClient.exe"]
	000000e6    0
	000000e5    0
	00000085    0
	00000084    0
	00000083    0
	00000080    0
	0000007f    0
	0000007d    0
	0000007c    0
	0000007b   15
	0000007a    0
	00000079    0
	00000078    0
	00000077    0
	00000075    0
	00000074    0
	00000073    0
	00000071    0
	00000070    0
	0000006d    0
	00000051    0
	00000050    0
	0000004f    0
	0000004e    0
	0000004d    0
	0000004c    0
	0000004b    0
	0000004a    0
	00000049    0
	00000048    0
	00000047    0
	00000046    0
	00000045    0
	00000044    0
	00000043    0
	00000042    0
	00000041    0
	00000040    0
	0000003f    0
	0000003e    0
	0000003d    0
	0000003c    0
	0000003b    0
	0000003a    0
	00000039    0
	00000038    0
	00000037    0
	00000036    0
	00000035    0
	00000034    0
	00000033    0
	00000032    0
	00000031    0
	00000030    0
	0000002f    0
	0000002e    0
	00000009    0
0000000e services.exe
	00000022    0
	0000001a    0
	00000013    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	0000001f    0
	0000001c    0
	0000001b    0
	00000019    0
00000020 winedevice.exe
	00000025    0
	00000024    0
	00000023    0
	00000021    0
00000029 explorer.exe
	0000002d    0
	0000002c    0
	0000002b    0
	0000002a    0
0000001e League of Legends.exe
	["C:/Riot Games/League of Legends/Game/League of Legends.exe" "162.249.79.102 5301 cl34zI23W+Vy6qB6SRwUPg== 8380803" "-PlayerID=8380803" "-GameID=899455043" "-GameBaseDir=C:/Riot Games/League of Legends" "-Region=TR" "-Locale=tr_TR" "-SkipRads" "-SkipBuild" "-EnableLNP" "-UseNewX3D=1" "-UseNewX3DFramebuffers=1" "-RiotClientPort=43673" "-RiotClientAuthToken=EEE1djwMBzTIIgniKnpk8w"]
	0000006b    0
000000c0 (D) C:\Riot Games\League of Legends\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\kenan\Temp\BsSndRpt.ini"  /dl]
	00000111    0 <==
00000014 explorer.exe
	000000eb    0
	000000e9    0
	000000ea    0
	000000bb    0
System information:
    Wine build: wine-4.9 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 4.15.0-1024-oem

**Comment by mmtrt** [comment]
Any info about you system hardware and drivers used, distro used and how are you launching snap and also provide info of snap list | grep -e wine -e league .

**Comment by HekHek** [comment]
My system hardware is
Intel Core I5 
Amd Radeon 520 
12 GB RAM 
120 GB SSD and 1TB HDD 
And thats from the terminal 
  Notes
core                     16-2.41                     7713  stable    canonical✓    core
core18                   20190904                    1144  stable    canonical✓    base
discord                  0.0.9                       93    stable    snapcrafters  -
firefox                  69.0-2                      258   stable    mozilla✓      -
gnome-3-26-1604          3.26.0.20190830             92    stable/…  canonical✓    -
gnome-3-28-1804          3.28.0-10-gaa70833.aa70833  71    stable    canonical✓    -
gnome-calculator         3.34.0+git1.822e4b58        501   stable/…  canonical✓    -
gnome-characters         v3.32.1+git2.3367201        317   stable/…  canonical✓    -
gnome-logs               3.34.0                      73    stable/…  canonical✓    -
gnome-system-monitor     3.32.1-3-g0ea89b4922        100   stable/…  canonical✓    -
gtk-common-themes        0.1-22-gab0a26b             1313  stable/…  canonical✓    -
leagueoflegends          1.0                         46    edge      mmtrt         devmode
spotify                  1.1.10.546.ge08ef575-19     36    stable    spotify✓      -
wine-platform-3-stable   3.0.4                       6     stable    mmtrt         -
wine-platform-4-staging  4.9                         5     stable    mmtrt         -
wine-platform-runtime    v1.0                        30    stable    mmtrt         -

**Comment by HekHek** [comment]
I am new at Linux-Ubuntu system and I am not a pro of it.

**Comment by mmtrt** [comment]
I see you have non lol patched wine-platform snaps, update these snaps with to fix that issue
```
snap refresh --candidate wine-platform-runtime
snap refresh --candidate wine-platform-4-staging
```

**Comment by HekHek** [comment]
Well thank you for your time bro. It worked. Thank you sincerely
