### ISSUE TITLE
THE PBE

### ISSUE THREAD

**Issue by Getta91** [mmtrt/leagueoflegends#74]
Hi! How are you today ^^?

I was wondering if there is a way to play on the PBE. Can you help me with this? Thanks!

**Comment by Getta91** [comment]
PLZ

**Comment by mmtrt** [comment]
I'll take a look at implementing pbe tomorrow.

**Comment by Getta91** [comment]
Thanks you for your work

**Comment by mmtrt** [comment]
I've added the PBE install options. Please do test and report any issues thanks.
