### ISSUE TITLE
PBE

### ISSUE THREAD

**Issue by Getta91** [mmtrt/leagueoflegends#75]
Hi! It's me again. I wanted to install the PBE but its kind of complicated for me because I don't want to uninstall the normal league. Is there a way to install both league PBE and normal?
Greetings,
Getta91

**Comment by mmtrt** [comment]
Try snap parallel install method, 
 https://snapcraft.io/blog/parallel-installs-test-and-run-multiple-instances-of-snaps

I've not tested this snap feature so can't confirm this works or not and good luck.

**Comment by Getta91** [comment]
I did it and by the way the pbe snap seemed to work! ty!!!! U R THE BEST

**Comment by mmtrt** [comment]
did parallel method work or you just install pbe normally?

**Comment by Getta91** [comment]
I didn't understand well how to do it so i installed it normally and saved
my riot games folder 😉
