### ISSUE TITLE
choose region

### ISSUE THREAD

**Issue by dinhokusanagi** [mmtrt/leagueoflegends#77]
Unhandled exception: page fault on read access to 0x005e1be4 in 32-bit code (0x005093a0).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:005093a0 ESP:0566fc60 EBP:00010078 EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:00262590 EBX:00000009 ECX:0566fc40 EDX:01190fd8
 ESI:00000000 EDI:00000003
Stack dump:
0x0566fc60:  0067eba4 019a6d40 00010078 0051366a
0x0566fc70:  00000001 0566fe18 019a6d40 0051367a
0x0566fc80:  00000009 ffffffff 0566fcb8 7d5553a9
0x0566fc90:  0566fce4 00000000 0566fe18 01190fd8
0x0566fca0:  00000000 0566fce4 0566fcd0 00010078
0x0566fcb0:  0566fdb0 00000000 0566fce8 7e99d58c
Backtrace:
=>0 0x005093a0 in league%20of%20legends%20install (+0x1093a0) (0x00010078)
0x005093a0: movl	0x005e1be4,%edx
Modules:
Module	Address			Debug info	Name (135 modules)
PE	  3c0000-  3d7000	Deferred        br63e1.tmp
PE	  400000-  6be000	Export          league%20of%20legends%20installer%20br
PE	  f70000-  fd5000	Deferred        br63b6.tmp
PE	10000000-10069000	Deferred        br6059.tmp
PE	61740000-618f2000	Deferred        br6321.tmp
PE	62e80000-62e8e000	Deferred        br6035.tmp
PE	66680000-6668e000	Deferred        br637a.tmp
PE	66c00000-66c14000	Deferred        br66a7.tmp
PE	67e00000-67e1b000	Deferred        br66be.tmp
PE	710c0000-710df000	Deferred        br6397.tmp
ELF	7b400000-7b84c000	Deferred        kernel32<elf>
  \-PE	7b430000-7b84c000	\               kernel32
ELF	7bc00000-7bd72000	Deferred        ntdll<elf>
  \-PE	7bc30000-7bd72000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7c6ab000-7c6c3000	Deferred        libgpg-error.so.0
ELF	7c6c3000-7c7a4000	Deferred        libgcrypt.so.20
ELF	7c7a4000-7c7ba000	Deferred        liblz4.so.1
ELF	7c7ba000-7c7e6000	Deferred        liblzma.so.5
ELF	7c7e6000-7c876000	Deferred        libsystemd.so.0
ELF	7c876000-7c87f000	Deferred        libffi.so.6
ELF	7c87f000-7c897000	Deferred        libresolv.so.2
ELF	7c897000-7c89c000	Deferred        libkeyutils.so.1
ELF	7c89c000-7c8f7000	Deferred        libdbus-1.so.3
ELF	7c8f7000-7c982000	Deferred        libgmp.so.10
ELF	7c982000-7c9b8000	Deferred        libhogweed.so.4
ELF	7c9b8000-7c9f4000	Deferred        libnettle.so.6
ELF	7c9f4000-7ca09000	Deferred        libtasn1.so.6
ELF	7ca09000-7cb8a000	Deferred        libunistring.so.2
ELF	7cb8a000-7cba8000	Deferred        libidn2.so.0
ELF	7cba8000-7ccf6000	Deferred        libp11-kit.so.0
ELF	7ccf6000-7cd03000	Deferred        libkrb5support.so.0
ELF	7cd03000-7cd08000	Deferred        libcom_err.so.2
ELF	7cd08000-7cd3d000	Deferred        libk5crypto.so.3
ELF	7cd3d000-7ce19000	Deferred        libkrb5.so.3
ELF	7ce19000-7ce2d000	Deferred        libavahi-client.so.3
ELF	7ce2d000-7ce3b000	Deferred        libavahi-common.so.3
ELF	7ce3b000-7cfd1000	Deferred        libgnutls.so.30
ELF	7cfd1000-7d025000	Deferred        libgssapi_krb5.so.2
ELF	7d025000-7d0b8000	Deferred        libcups.so.2
ELF	7d0b8000-7d104000	Deferred        uxtheme<elf>
  \-PE	7d0c0000-7d104000	\               uxtheme
ELF	7d106000-7d10d000	Deferred        libxfixes.so.3
ELF	7d10d000-7d119000	Deferred        libxcursor.so.1
ELF	7d19c000-7d1ce000	Deferred        libexpat.so.1
ELF	7d1ce000-7d219000	Deferred        libfontconfig.so.1
ELF	7d219000-7d238000	Deferred        libz.so.1
ELF	7d238000-7d272000	Deferred        libpng16.so.16
ELF	7d272000-7d32f000	Deferred        libfreetype.so.6
ELF	7d32f000-7d342000	Deferred        libxi.so.6
ELF	7d342000-7d346000	Deferred        libxcomposite.so.1
ELF	7d346000-7d353000	Deferred        libxrandr.so.2
ELF	7d353000-7d35f000	Deferred        libxrender.so.1
ELF	7d35f000-7d366000	Deferred        libxxf86vm.so.1
ELF	7d366000-7d36a000	Deferred        libxinerama.so.1
ELF	7d36a000-7d385000	Deferred        libbsd.so.0
ELF	7d385000-7d38c000	Deferred        libxdmcp.so.6
ELF	7d38c000-7d390000	Deferred        libxau.so.6
ELF	7d390000-7d3bc000	Deferred        libxcb.so.1
ELF	7d3bc000-7d506000	Deferred        libx11.so.6
ELF	7d506000-7d51b000	Deferred        libxext.so.6
ELF	7d51b000-7d5d0000	Deferred        winex11<elf>
  \-PE	7d540000-7d5d0000	\               winex11
ELF	7d5d0000-7d60c000	Deferred        ws2_32<elf>
  \-PE	7d5e0000-7d60c000	\               ws2_32
ELF	7d60c000-7d75b000	Deferred        oleaut32<elf>
  \-PE	7d640000-7d75b000	\               oleaut32
ELF	7d75b000-7d7b2000	Deferred        winspool<elf>
  \-PE	7d770000-7d7b2000	\               winspool
ELF	7d7b2000-7d7ce000	Deferred        aclui<elf>
  \-PE	7d7c0000-7d7ce000	\               aclui
ELF	7d7ce000-7d874000	Deferred        rpcrt4<elf>
  \-PE	7d7f0000-7d874000	\               rpcrt4
ELF	7d874000-7d9f4000	Deferred        ole32<elf>
  \-PE	7d8b0000-7d9f4000	\               ole32
ELF	7d9f4000-7da28000	Deferred        shcore<elf>
  \-PE	7da00000-7da28000	\               shcore
ELF	7da28000-7dab9000	Deferred        shlwapi<elf>
  \-PE	7da40000-7dab9000	\               shlwapi
ELF	7dab9000-7e4ee000	Deferred        shell32<elf>
  \-PE	7daf0000-7e4ee000	\               shell32
ELF	7e4ee000-7e5f6000	Deferred        comdlg32<elf>
  \-PE	7e500000-7e5f6000	\               comdlg32
ELF	7e5f6000-7e6cc000	Deferred        msvcrt<elf>
  \-PE	7e620000-7e6cc000	\               msvcrt
ELF	7e6cc000-7e6f1000	Deferred        imm32<elf>
  \-PE	7e6d0000-7e6f1000	\               imm32
ELF	7e6f1000-7e74c000	Deferred        usp10<elf>
  \-PE	7e700000-7e74c000	\               usp10
ELF	7e74c000-7e777000	Deferred        version<elf>
  \-PE	7e750000-7e777000	\               version
ELF	7e777000-7e8ce000	Deferred        gdi32<elf>
  \-PE	7e7a0000-7e8ce000	\               gdi32
ELF	7e8ce000-7eb05000	Deferred        user32<elf>
  \-PE	7e900000-7eb05000	\               user32
ELF	7eb05000-7ec64000	Deferred        comctl32<elf>
  \-PE	7eb20000-7ec64000	\               comctl32
ELF	7ec64000-7ecfe000	Deferred        advapi32<elf>
  \-PE	7ec80000-7ecfe000	\               advapi32
ELF	7eeab000-7eebf000	Deferred        wow64cpu<elf>
  \-PE	7eeb0000-7eebf000	\               wow64cpu
ELF	7eef4000-7eff6000	Deferred        libm.so.6
ELF	7eff6000-7f000000	Deferred        librt.so.1
ELF	f72ad000-f72cb000	Deferred        libgcc_s.so.1
ELF	f741d000-f7439000	Deferred        kerberos<elf>
  \-PE	f7420000-f7439000	\               kerberos
ELF	f7439000-f7572000	Deferred        msvcp60<elf>
  \-PE	f7480000-f7572000	\               msvcp60
ELF	f7572000-f760c000	Deferred        setupapi<elf>
  \-PE	f7590000-f760c000	\               setupapi
ELF	f760c000-f7625000	Deferred        wtsapi32<elf>
  \-PE	f7610000-f7625000	\               wtsapi32
ELF	f7625000-f764c000	Deferred        userenv<elf>
  \-PE	f7630000-f764c000	\               userenv
ELF	f764c000-f7693000	Deferred        secur32<elf>
  \-PE	f7660000-f7693000	\               secur32
ELF	f7693000-f76b9000	Deferred        powrprof<elf>
  \-PE	f76a0000-f76b9000	\               powrprof
ELF	f76b9000-f76f4000	Deferred        mpr<elf>
  \-PE	f76c0000-f76f4000	\               mpr
ELF	f76f4000-f77cc000	Deferred        winmm<elf>
  \-PE	f7700000-f77cc000	\               winmm
ELF	f77cc000-f77fa000	Deferred        pdh<elf>
  \-PE	f77d0000-f77fa000	\               pdh
ELF	f7960000-f798e000	Deferred        iphlpapi<elf>
  \-PE	f7970000-f798e000	\               iphlpapi
ELF	f798e000-f79d4000	Deferred        netapi32<elf>
  \-PE	f79a0000-f79d4000	\               netapi32
ELF	f79d4000-f79e8000	Deferred        psapi<elf>
  \-PE	f79e0000-f79e8000	\               psapi
ELF	f7b5a000-f7b5f000	Deferred        libdl.so.2
ELF	f7b5f000-f7d3b000	Deferred        libc.so.6
ELF	f7d3b000-f7d5a000	Deferred        libpthread.so.0
ELF	f7d5a000-f7f23000	Dwarf           libwine.so.1
ELF	f7f25000-f7f4d000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) Z:\tmp\League%20of%20Legends%20installer%20BR.exe
	[Z:\tmp\League%20of%20Legends%20installer%20BR.exe --mode unattended]
	0000002c    2 <==
	0000002b    2
	0000002a    0
	00000029    2
	00000009    0
0000000e services.exe
	00000022    0
	0000001c    0
	00000015    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000019    0
	00000018    0
	00000012    0
00000013 explorer.exe
	00000028    0
	00000027    0
	00000026    0
	00000014    0
0000001a winedevice.exe
	0000001f    0
	0000001e    0
	0000001d    0
	0000001b    0
00000020 winedevice.exe
	00000025    0
	00000024    0
	00000023    0
	00000021    0
00000033 explorer.exe
	00000037    0
	00000036    0
	00000035    0
	00000034    0
System information:
    Wine build: wine-4.10 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 5.2.14-1-default

**Comment by mmtrt** [comment]
can you please post some info about your systen, like os, gpu, gpu drivers, and also post `snap list | grep -e wine -e league`

**Comment by dinhokusanagi** [comment]
snap list
Name                     Version          Rev   Tracking   Publisher   Notes
core18                   20190904         1144  stable     canonical✓  base
gtk-common-themes        0.1-22-gab0a26b  1313  stable     canonical✓  -
leagueoflegends          1.0              48    edge       mmtrt       devmode
snapd                    2.41             4605  stable     canonical✓  snapd
wine-platform-4-staging  4.10             12    candidate  mmtrt       -
wine-platform-runtime    v1.0             33    candidate  mmtrt       -

**Comment by dinhokusanagi** [comment]
OS: openSUSE Tumbleweed x86_6
Kernel: 5.2.14-1-default 
Packages: 2710 (rpm), 9 (flat
Shell: zsh 5.7.1
Resolution: 1920x1080
DE: Plasma
WM: KWin
CPU: AMD Ryzen 5 1600 (12) @ 
GPU: AMD ATI Radeon RX 470/48
Memory: 4106MiB / 7961MiB 
07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef)

**Comment by Getta91** [comment]
Hi mmtrt, maybe does that Guy have the same issue as me? @dinhokusanagi Don't do anything i did if it's not the same.

#78

**Comment by mmtrt** [comment]
Yeah it could be, maybe try `snap refresh` which would update back old as I've reverted the platform revisions.

**Comment by dinhokusanagi** [comment]
bug has been fixed, now what happens is that until this image of the soon after instead of opening the client it closes by itself
![logo-lol](https://user-images.githubusercontent.com/43162113/65336568-fe56e700-db9c-11e9-8131-1cd9d70288cc.png)

**Comment by mmtrt** [comment]
if it stuck then close game and relaunch it tough you can kill all instances of league snap by this command.
`leagueoflegends.wineserver`

**Comment by dinhokusanagi** [comment]
I did as directed and still closes alone

**Comment by mmtrt** [comment]
try setting `winxp` wineprefix `leagueoflegends.winecfg` and if that still not fixes then try wine-staging from beta ` snap refresh --beta wine-platform-4-staging`.

**Comment by dinhokusanagi** [comment]
I did the procedures and it didn't work

**Comment by mmtrt** [comment]
anything interesting in logs btw do you have d9vk installed for some reason and maybe you can try fresh install.

**Comment by dinhokusanagi** [comment]
I'll try
