### ISSUE TITLE
Low FPS [Resolved]

### ISSUE THREAD

**Issue by brunooow1** [mmtrt/leagueoflegends#79]
Hello

I am having trouble during the game. I usually play with 140+ fps in fights. After installing via SNAP, my fps is very low. Does anyone know what can it be?

![Captura de tela de 2019-09-20 08 09 22](https://user-images.githubusercontent.com/17989338/65322763-0eab9980-db7e-11e9-9433-b9c383307d88.png)

I'm using this driver:

![Captura de tela de 2019-09-20 08 11 08](https://user-images.githubusercontent.com/17989338/65322871-54686200-db7e-11e9-8291-f2bfe7599770.png)

**Comment by mmtrt** [comment]
Try to use `d9vk` should help in fixing low fps.

**Comment by brunooow1** [comment]
Thanks for your reply, how i do it?

**Comment by mmtrt** [comment]
Read #72 for info regarding d9vk

**Comment by brunooow1** [comment]
Ok, I installed the stable version and made it a test in training mode, the lowest fps that I had was 105. I think in a 5x5 game mode will stabilize 100+ fps!

Thank you, I really appreciate your help.
