### ISSUE TITLE
Game crashes after champ select

### ISSUE THREAD

**Issue by MontFox** [mmtrt/leagueoflegends#80]
https://pastebin.com/ujMDFgqa

**Comment by mmtrt** [comment]
can you post info of this command `snap list | grep -e wine -e league`

**Comment by MontFox** [comment]
leagueoflegends          1.0              48    edge       mmtrt       devmode
wine-platform-4-staging  4.9              7     candidate  mmtrt       -
wine-platform-runtime    v1.0             7     candidate  mmtrt       -

**Comment by mmtrt** [comment]
ah that looks fine hmm maybe you need to clean wineprefix to fix that issue which is at `$HOME/snap/leagueoflegends/common/.wine` best would be moving out `Riot Games` dir & then nuke league snap dir completely and restore game dir when launching snap again and closing when it reaches region selection dialog and relaunch snap after game dir is in placed.

**Comment by MontFox** [comment]
Success! However, now I am getting abysmal frames (0-3fps) with this error after getting into game
```
0158:err:ole:marshal_object couldn't get IPSFactory buffer for interface {9c6b4cb0-23f8-49cc-a3ed-45a55000a6d2}
0158:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0158:err:ole:CoMarshalInterface Failed to marshal the interface {9c6b4cb0-23f8-49cc-a3ed-45a55000a6d2}, 80004002
02f0:err:ole:marshal_object couldn't get IPSFactory buffer for interface {9c6b4cb0-23f8-49cc-a3ed-45a55000a6d2}
02f0:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
02f0:err:ole:CoMarshalInterface Failed to marshal the interface {9c6b4cb0-23f8-49cc-a3ed-45a55000a6d2}, 80004002
libGL error: pci id for fd 118: 1002:731f, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
libGL error: pci id for fd 118: 1002:731f, driver (null)
pci id for fd 119: 1002:731f, driver (null)
libGL error: failed to create dri screen
libGL error: failed to load driver: radeonsi
02d6:err:d3d:wined3d_adapter_find_polyoffset_scale PolygonOffset scale factor detection failed, using fallback value 2^23.
```

**Comment by mmtrt** [comment]
which gpu and drivers you have?

**Comment by mmtrt** [comment]
ah you have navi then try wine platform runtime from beta branch which has newer mesa drivers `snap refresh --beta wine-platform-runtime`

**Comment by MontFox** [comment]
That seemed to work great! Thank you!!
