### ISSUE TITLE
Can't even install

### ISSUE THREAD

**Issue by medalog** [mmtrt/leagueoflegends#81]
Yesterday i had a problem in game. I try to reinstall but now it doesn't work. A lot of bugsplat appear after select region.

**Comment by mmtrt** [comment]
try changing wineprefix os to winxp `leagueoflegends.winecfg`

**Comment by Ignacy-s** [comment]
> try changing wineprefix os to winxp `leagueoflegends.winecfg`

This worked for me. The wineprefix os got set to win7 after reinstalling league snap.
