### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by gongus** [mmtrt/leagueoflegends#82]
Hello! League install was fine and I can also run the game without any kind of problem. But the FPS are low. I have 58 fps when moving the player or standing, even sometimes goes up to 61. When using abilities fps drops to ~40. Is there any thing that i could do to get higher fps ?

EDIT: I'm running the game with video setings at very low. Another thing i forget to mention is that my computer is a thinkpad T480

**Comment by mmtrt** [comment]
it probably because its using Intel GPU causing such low fps though you could try updating snap which have updated mesa etc.
`snap refresh --beta wine-platform-runtime`

**Comment by gongus** [comment]
I've tryed that with no positive results. is there any other solution to this problem ?

**Comment by Getta91** [comment]
I had the same problem a few month ago. I fix it by changing my ingame framecap to 60. If it still doesnt work, try 30. U will get less FPS but at least your game will be more stable even in teamfight
