### ISSUE TITLE
Can't launch the new client

### ISSUE THREAD

**Issue by HowBoutSomeSnus** [mmtrt/leagueoflegends#83]
`LeagueClient.exe(00000009): ALWAYS| Application Version:9.19.290.7765 - CL:2907765 - Build Date:Sep 25 2019 - Build Time:12:34:31

LeagueClient.exe(00000009): ALWAYS| Direct Launch enabled for league_of_legends.live in environment 'live' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'

LeagueClient.exe(00000009): ALWAYS| Found Riot Client live install (C:/Riot Games/Riot Client/RiotClientServices.exe)

LeagueClient.exe(00000009): ALWAYS| Riot Client started. Exiting with the expectation of being restarted (ExitForDirectLaunch).

wine: Unhandled exception 0x80000003 in thread 3d at address 0x4135c7 (thread 003d), starting debugger...

004b:fixme:thread:create_user_shared_data_thread Creating user shared data update thread.
005a:err:ole:marshal_object couldn't get IPSFactory buffer for interface {9c6b4cb0-23f8-49cc-a3ed-45a55000a6d2}

005a:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
005a:err:ole:CoMarshalInterface Failed to marshal the interface {9c6b4cb0-23f8-49cc-a3ed-45a55000a6d2}, 80004002
`
Not only me that have this issue:
[Reddit post](https://www.reddit.com/r/leagueoflinux/comments/dcju9j/most_recent_pbe_update_breaks_the_ingame_client/)

**Comment by ssayebee** [comment]
in Ubuntu 18.04

I don't know if it's the same problem,
when i start lol to chess, it was not working

Program Error Dialog
The program BsCndRpt.exe has enCountered a serious problem and needs to close. We are sorry for the inConvenience.

it is backtrace

---

Unhandled exception: page fault on read access to 0x7eb0e310 in 32-bit code (0x7eb0e310).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:7eb0e310 ESP:0032f1cc EBP:0032f1e8 EFLAGS:00010202(  R- --  I   - - - )
 EAX:7eb0e310 EBX:0032f318 ECX:00000001 EDX:00000001
 ESI:7ffd8000 EDI:00000000
Stack dump:
0x0032f1cc:  7e8ef744 00000000 00000000 0032f740
0x0032f1dc:  0032f318 7ffd8000 00000000 0032f288
0x0032f1ec:  7e8f05ae 7eb0e310 00000000 00000000
0x0032f1fc:  0032f740 00000000 00000001 00000000
0x0032f20c:  ffffffff 00000000 00000000 7eb0e310
0x0032f21c:  00000000 0018d950 00000000 00000000
Backtrace:
=>0 0x7eb0e310 in libz.so.1 (+0x1d310) (0x0032f1e8)
  1 0x7e8f05ae UnhookWindowsHookEx+0x5fd() in user32 (0x0032f288)
  2 0x7e8f07e5 UnhookWindowsHookEx+0x834() in user32 (0x0032f558)
  3 0x7e8f0c41 CallMsgFilterW+0x40() in user32 (0x0032f598)
  4 0x7e8dff1b IsDialogMessageW+0x6a() in user32 (0x0032f708)
  5 0x7e8e070a IsDialogMessageW+0x859() in user32 (0x0032f778)
  6 0x7e8e090f DialogBoxParamW+0x8e() in user32 (0x0032f7b8)
  7 0x0040ce67 EntryPoint+0xffffffff() in bssndrpt (0x0032f924)
  8 0x00403c3b EntryPoint+0xffffffff() in bssndrpt (0x0032fe6c)
  9 0x004028f0 EntryPoint+0xffffffff() in bssndrpt (0x0032fe74)
  10 0x00423731 in bssndrpt (+0x23730) (0x0032fec0)
  11 0x7b482bc9 call_process_entry+0x18() in kernel32 (0x0032fee8)
  12 0x7b485191 ExitProcess+0x25b4() in kernel32 (0x0032ffd8)
  13 0x7b482bda call_process_entry+0x29() in kernel32 (0x0032ffec)
0x7eb0e310: incl	%ecx
Modules:
Module	Address			Debug info	Name (80 modules)
PE	  400000-  453000	Export          bssndrpt
PE	  460000- 347a000	Deferred        league of legends
PE	10000000-10030000	Deferred        bugsplatrc
ELF	7b400000-7b84b000	Dwarf           kernel32<elf>
  \-PE	7b430000-7b84b000	\               kernel32
ELF	7bc00000-7bd72000	Deferred        ntdll<elf>
  \-PE	7bc30000-7bd72000	\               ntdll
ELF	7c000000-7c004000	Deferred        <wine-loader>
ELF	7d113000-7d141000	Deferred        iphlpapi<elf>
  \-PE	7d120000-7d141000	\               iphlpapi
ELF	7d188000-7d1d3000	Deferred        uxtheme<elf>
  \-PE	7d190000-7d1d3000	\               uxtheme
ELF	7d1d5000-7d1dc000	Deferred        libxfixes.so.3
ELF	7d1dc000-7d1e8000	Deferred        libxcursor.so.1
ELF	7d274000-7d2a6000	Deferred        libexpat.so.1
ELF	7d2a6000-7d2f1000	Deferred        libfontconfig.so.1
ELF	7d35a000-7d394000	Deferred        libpng16.so.16
ELF	7d394000-7d451000	Deferred        libfreetype.so.6
ELF	7d451000-7d464000	Deferred        libxi.so.6
ELF	7d464000-7d468000	Deferred        libxcomposite.so.1
ELF	7d468000-7d475000	Deferred        libxrandr.so.2
ELF	7d475000-7d481000	Deferred        libxrender.so.1
ELF	7d481000-7d488000	Deferred        libxxf86vm.so.1
ELF	7d488000-7d48c000	Deferred        libxinerama.so.1
ELF	7d48c000-7d4a7000	Deferred        libbsd.so.0
ELF	7d4a7000-7d4ae000	Deferred        libxdmcp.so.6
ELF	7d4ae000-7d4b2000	Deferred        libxau.so.6
ELF	7d4b2000-7d4de000	Deferred        libxcb.so.1
ELF	7d4de000-7d628000	Deferred        libx11.so.6
ELF	7d628000-7d63d000	Deferred        libxext.so.6
ELF	7d63d000-7d6f2000	Deferred        winex11<elf>
  \-PE	7d660000-7d6f2000	\               winex11
ELF	7d6f2000-7d841000	Deferred        oleaut32<elf>
  \-PE	7d720000-7d841000	\               oleaut32
ELF	7d841000-7d87d000	Deferred        ws2_32<elf>
  \-PE	7d850000-7d87d000	\               ws2_32
ELF	7d87d000-7d8a2000	Deferred        imm32<elf>
  \-PE	7d890000-7d8a2000	\               imm32
ELF	7d8a2000-7d8fd000	Deferred        usp10<elf>
  \-PE	7d8b0000-7d8fd000	\               usp10
ELF	7d8fd000-7da69000	Deferred        comctl32<elf>
  \-PE	7d920000-7da69000	\               comctl32
ELF	7da69000-7da85000	Deferred        aclui<elf>
  \-PE	7da70000-7da85000	\               aclui
ELF	7da85000-7dc04000	Deferred        ole32<elf>
  \-PE	7dac0000-7dc04000	\               ole32
ELF	7dc04000-7dc38000	Deferred        shcore<elf>
  \-PE	7dc10000-7dc38000	\               shcore
ELF	7dc38000-7e66d000	Deferred        shell32<elf>
  \-PE	7dc70000-7e66d000	\               shell32
ELF	7e66d000-7e6fe000	Deferred        shlwapi<elf>
  \-PE	7e680000-7e6fe000	\               shlwapi
ELF	7e6fe000-7e729000	Deferred        version<elf>
  \-PE	7e700000-7e729000	\               version
ELF	7e729000-7e87f000	Deferred        gdi32<elf>
  \-PE	7e750000-7e87f000	\               gdi32
ELF	7e87f000-7eab6000	Dwarf           user32<elf>
  \-PE	7e8b0000-7eab6000	\               user32
ELF	7eab6000-7eaf1000	Deferred        mpr<elf>
  \-PE	7eac0000-7eaf1000	\               mpr
ELF	7eaf1000-7eb10000	Dwarf           libz.so.1
ELF	7eb10000-7ebb2000	Deferred        wininet<elf>
  \-PE	7eb20000-7ebb2000	\               wininet
ELF	7ebb2000-7ec4b000	Deferred        advapi32<elf>
  \-PE	7ebd0000-7ec4b000	\               advapi32
ELF	7ec4b000-7ecf1000	Deferred        rpcrt4<elf>
  \-PE	7ec70000-7ecf1000	\               rpcrt4
ELF	7eea3000-7eeb7000	Deferred        wow64cpu<elf>
  \-PE	7eeb0000-7eeb7000	\               wow64cpu
ELF	7eeb7000-7eecb000	Deferred        libnss_files.so.2
ELF	7eecb000-7eee6000	Deferred        libnsl.so.1
ELF	7eee6000-7eef4000	Deferred        libnss_nis.so.2
ELF	7eef4000-7eefe000	Deferred        libnss_compat.so.2
ELF	7eefe000-7f000000	Deferred        libm.so.6
ELF	f7ba3000-f7bad000	Deferred        librt.so.1
ELF	f7baf000-f7bb4000	Deferred        libdl.so.2
ELF	f7bb4000-f7d90000	Deferred        libc.so.6
ELF	f7d90000-f7daf000	Deferred        libpthread.so.0
ELF	f7daf000-f7f79000	Dwarf           libwine.so.1
ELF	f7f7b000-f7fa3000	Deferred        ld-linux.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000026    0
	0000001f    0
	0000001c    0
	00000015    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	00000019    0
	00000018    0
	00000012    0
00000013 explorer.exe
	00000023    0
	00000022    0
	00000021    0
	00000014    0
0000001a winedevice.exe
	00000020    0
	0000001e    0
	0000001d    0
	0000001b    0
00000024 winedevice.exe
	00000029    0
	00000028    0
	00000027    0
	00000025    0
0000002e RiotClientServices.exe
	["C:/Riot Games/Riot Client/RiotClientServices.exe" "--rso-auth.platform=KR" "--region=KR" "--locale=ko_KR" "--priority-launch-pid=8" "--priority-launch-path=C:\Riot Games\League of Legends\LeagueClient.exe" "--upgrade-install-path=C:\Riot Games\League of Legends" "--upgrade-product=league_of_legends" "--upgrade-patchline=live"]
	00000062    0
	00000061    0
	00000060    0
	0000005f    0
	0000005e    0
	0000005b    0
	00000058    0
	00000057    0
	00000056    0
	00000055    0
	00000054    0
	00000053    0
	00000052    0
	00000051    0
	00000050    0
	0000004f    0
	0000004e    0
	0000004d    0
	0000004c    0
	0000004b    0
	0000004a    0
	00000049    0
	00000048    0
	00000047    0
	00000046    0
	0000003a    0
	00000033    0
	00000032    0
	00000031    0
	00000030    0
	0000002f    0
0000003b RiotClientCrashHandler.exe
	["C:/Riot Games/Riot Client/RiotClientCrashHandler.exe" "--database=C:/users/ssayebee/Local Settings/Application Data/Riot Games/Riot Client/Crashes/Riot Client" "--metrics-dir=C:/users/ssayebee/Local Settings/Application Data/Riot Games/Riot Client/Crashes/Riot Client" --url=https://sentry.io/api/1339107/minidump/?sentry_key=dc54709324504ab18ddf517a83f99e1a "--annotation=2019-10-09T16-49-16_46_Riot Client.0.log=C:/users/ssayebee/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2019-10-09T16-49-16_46_Riot Client.0.log" "--annotation=2019-10-09T16-49-16_46_Riot Client.log=C:/users/ssayebee/Local Settings/Application Data/Riot Games/Riot Client/Logs/Riot Client Logs/2019-10-09T16-49-16_46_Riot Client.log" --initial-client-data=0xdc,0xe0,0xe4,0x94,0xe8,0xef0751c,0xef0752c,0xef0753c]
	00000045    0
	00000044    0
	00000042    0
	00000041    0
	00000040    0
	0000003f    0
	0000003e    0
	0000003d    0
	0000003c    0
000000d7 LeagueClient.exe
	["C:/Riot Games/League of Legends/LeagueClient.exe" "--riotclient-auth-token=HPn06hbT_cw9VdbSkTGR3A" "--riotclient-app-port=39387" "--no-rads" "--disable-self-update" "--region=KR" "--locale=ko_KR"]
	0000016a    0
	00000137    0
	00000135    0
	00000133    0
	0000012e    0
	0000012d    0
	0000012b    0
	0000012a    0
	00000129   15
	00000128    0
	00000127    0
	00000126    0
	00000125    0
	00000124    0
	00000120    0
	0000011e    0
	0000011d    0
	0000011c    0
	0000011b    0
	00000100    0
	000000fd    0
	000000fc    0
	000000fb    0
	000000fa    0
	000000f9    0
	000000f8    0
	000000f7    0
	000000f6    0
	000000f5    0
	000000f4    0
	000000f3    0
	000000f2    0
	000000f1    0
	000000f0    0
	000000ef    0
	000000ee    0
	000000ed    0
	000000ec    0
	000000eb    0
	000000ea    0
	000000e9    0
	000000e8    0
	000000e7    0
	000000e6    0
	000000e5    0
	000000e4    0
	000000e3    0
	000000e2    0
	000000e1    0
	000000e0    0
	000000df    0
	000000de    0
	000000dd    0
	000000dc    0
	000000db    0
	000000da    0
	000000d8    0
00000087 League of Legends.exe
	["C:/Riot Games/League of Legends/Game/League of Legends.exe" "182.162.121.144 5299 VUwTHwfS/VR1r2OMbVyH3Q== 5003780" "-PlayerID=5003780" "-GameID=3905477541" "-GameBaseDir=C:/Riot Games/League of Legends" "-Region=KR" "-Locale=ko_KR" "-SkipRads" "-SkipBuild" "-EnableLNP" "-UseNewX3D=1" "-UseNewX3DFramebuffers=1" "-RiotClientPort=45345" "-RiotClientAuthToken=KzUxf4FjHqTEUAZzNcqCnA"]
	000000a5    0
000000a6 (D) C:\Riot Games\League of Legends\BsSndRpt.exe
	["BsSndRpt.exe" /i "C:\users\ssayebee\Temp\BsSndRpt.ini"  /dl]
	000000c2    0 <==
000000b0 explorer.exe
	000000d6    0
	000000d4    0
	00000090    0
	0000009e    0
System information:
    Wine build: wine-4.9 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 5.0.0-31-generic

**Comment by HowBoutSomeSnus** [comment]
This solution worked with the new client:
https://www.reddit.com/r/leagueoflinux/comments/de39cq/it_worked_i_got_league_of_legends_working_with/
Maybe implement that in the snap?

**Comment by mmtrt** [comment]
That uses same patches as snap which already has it for wine and glibc and aside from rpath changes which are only needed for that method.

**Comment by Ignacy-s** [comment]
> That uses same patches as snap which already has it for wine and glibc and aside from rpath changes which are only needed for that method.

Can it be graphic card specific? Redditer from the solution linked by HowBoutSomeSnus is using an AMD card. 

I'm using nvidia card with 435.21 drivers and seem to get the same bug. 

People at winehq are aware of this bug and created a new issue on winehq that can't be found at:
https://bugs.winehq.org/show_bug.cgi?id=47915

**Comment by Getta91** [comment]
Look at wine hq link: there are major changes (some people are getting it to work)

**Comment by mmtrt** [comment]
Thanks for informing me about fixes, I've updated Snap and AppImg with that patch and tested both working fine.

**Comment by Getta91** [comment]
Finally, it's so cool! We have such a great community 😁 i'll give it a try then see if it's working. I'll inform you (i am on debian)

**Comment by Getta91** [comment]
Dude there's no updates available and no appimage. I took some pictures:
![Capture du 2019-10-12 10-24-20](https://user-images.githubusercontent.com/50636257/66698003-aeba9580-ecda-11e9-9245-c38e241d0cdb.png)
![Capture du 2019-10-12 10-24-46](https://user-images.githubusercontent.com/50636257/66698004-aeba9580-ecda-11e9-9dcd-28b8aba918d1.png)

**Comment by mmtrt** [comment]
Use AppImg from continuous tag and yes I've removed AppImg from that tag was outdated.

As for wine-platform snaps they would have been already auto updated and for league snap which was not updated today.

**Comment by Getta91** [comment]
Thanks you for answering. But I am kind of confuse with all those appimage. Is it the good one to use?
![Capture du 2019-10-12 12-58-54](https://user-images.githubusercontent.com/50636257/66700414-234bff00-ecf0-11e9-9033-4021c644cedc.png)

**Comment by Getta91** [comment]
It's ok i found it. Thank you for all dude! have a nice day

**Comment by Frombb12** [comment]
I don't understand how upgrading wine to lol or lol can work, can anyone explain me?

**Comment by Frombb12** [comment]
I don't understand how upgrading wine to LOL can work, can anyone explain me?

**Comment by jctaveras** [comment]
Do I have to run 
`
./wine-staging-i386_lol-patched_x86_64-bionic.AppImage wine "../snap/leagueoflegends/common/.wine/drive_c/Riot Games/League of Legends/LeagueClient.exe"
`
every time I would like to play league?

**Comment by Getta91** [comment]
> Do I have to run
> `./wine-staging-i386_lol-patched_x86_64-bionic.AppImage wine "../snap/leagueoflegends/common/.wine/drive_c/Riot Games/League of Legends/LeagueClient.exe"`
> every time I would like to play league?

Yes, for now, because the official league snap hasn't been updated yet. It will be updated soon (At the next update of the client if I understood well...)

**Comment by jctaveras** [comment]
Awesome then. Waiting for the update!

**Comment by Getta91** [comment]
> Awesome then. Waiting for the update!

Idk know why, but I am able to use the normal league xD. All I did, was getting the latest wine: https://github.com/mmtrt/leagueoflegends/commit/7d3ce5f121cc8ec12d9d3b14279970156b8f61e1
 (save your Riotgames folder and create a new wine prefix or you will experience some crashes).
I think it's kind of an auto update or Idk. You should give it a try

**Comment by jctaveras** [comment]
> Idk know why, but I am able to use the normal league xD. All I did, was getting the latest wine: [7d3ce5f](https://github.com/mmtrt/leagueoflegends/commit/7d3ce5f121cc8ec12d9d3b14279970156b8f61e1)
> (save your Riotgames folder and create a new wine prefix or you will experience some crashes).
> I think it's kind of an auto update or Idk. You should give it a try

I will give it a try and see what happen

**Comment by Getta91** [comment]
Do a practice game, it's better xD

**Comment by mmtrt** [comment]
FYI as I mentioned in my previous post that I have updated and tested both `wine` snap and AppImg.

`leagueoflegends` snap depends on `wine-platform-4-staging` snap which was already updated with latest wine patch fix.

**Comment by Bloodiko** [comment]
@mmtrt i did update to the Beta version of wine-platform-4-staging, yet my game is still crashing - is there something else to be updated ?

**Comment by mmtrt** [comment]
You need fresh wineprefix as I mentioned on #7 in changelog note.

**Comment by Bloodiko** [comment]
okay, got it - worked with a fresh wineprefix - didnt see the note

**Comment by Ignacy-s** [comment]
Working on Ubuntu 19.04. Had to reinstall the game and then set emulated windows to winXP (game wouldn't install). Full documentation of what I did for less technical league fans:

Sun 13 Oct 2019 09:09:15 AM CEST
Running Ubuntu 19.04 and league of legends trough snaps:
leagueoflegends, wine-platform-4-staging and wine-platform-runtime.  I
also installed latest version of wine as suggested in some other
tutorial linked by mmtrt (aforementioned snaps author).

Patch 9.20 has broken the game, causing bug in wine right after
character select (when the actual game engine was loading).

After few days somebody has posted a fix on winehq and the fix was
included in snap called wine-platform-runtime.

* Notice *: Even when the game is "working", it still crashes a lot
  and requires restarts. To make the restart process easier I'm using a one
  line script that grabs process ID's of all processes with 'windows'
  and 'league' in name and sends a kill signal to them. Very handy
  when you're about to play a ranked game and the game crashes. Even
  after installing the game and seeing that the launcher/gamelanucher
  works, please see that it works with a 'Practice Tool Game' before
  you try to join a regular game and find out it doesn't work. Game
  stopping script is this:

  for tobekilled in windows league; do kill -9 $(ps aux  | grep -v grep | grep "$tobekilled" | awk '{ print $2}') ; done


To install the fix you have to refresh the snap in 'candidate' version
like this:
`sudo snap refresh --candidate wine-platform-runtime`

This still didn't help, so I reinstalled league snap with
`sudo snap remove leagueoflegends`
`sudo snap install --devmode --edge leagueoflegends`

Game refused to install after reinstalling snap, so I run
`leagueoflegends.winetricks` and `leagueoflegends.winecfg`

In wine.cfg I've noticed that the windows version got set back to
win7. This should be at 'Windows XP'.

Installation started after changing the Windows version. Game hanged
multiple times in the process of installation and had to be killed
with killing script. After installation and downloading the game I've
tried playing a game with Practice Tool, which worked.

**Comment by ibrahimpmahmood** [comment]
@Ignacy-s thanks, changing the wine.cfg to use windows xp worked for me
