### ISSUE TITLE
Client crashes when a game starts

### ISSUE THREAD

**Issue by markvanlan** [mmtrt/leagueoflegends#84]
After the update that I downloaded today, when the game was about to start, it crashed, and I can no longer log into my account on the client, because it will crash on login.

**Comment by mmtrt** [comment]
Game is currently broken in WINE after that update see current bugreport [Link](https://bugs.winehq.org/show_bug.cgi?id=47915)

**Comment by Getta91** [comment]
Do you think that your app image of wine can work with this?

**Comment by mmtrt** [comment]
I don't think so as these use same patches as snaps and since rito broke game completely in WINE, better is to wait until wine Devs come up with fixes for this issue.

**Comment by GPaso** [comment]
Happened to me yesterday, I reinstalled league, snap and wine, even restarted the PC from a backup. I' ll wait for WINE then

**Comment by Getta91** [comment]
Does this usually take a long Time ?

**Comment by Riselia** [comment]
> Does this usually take a long Time ?

Yes, expect **2 weeks**

**Comment by Amoki** [comment]
https://github.com/M-Reimer/wine-lol maintains a wine version (based on staging) with the latest fixes for League of Legends. A fix has been found this weekend (https://bugs.winehq.org/show_bug.cgi?id=47915). 
Is there a way to manually set the wine version?

**Comment by mmtrt** [comment]
@Amoki `wine-platform-4-staging` snap was already updated with league fixes 2 days ago if this still crashes for you follow readme for info and likely you would had old wineprefix causing issues recreating fresh wineprefix see #7 for howto or reinstalling league snap which will redownload game again.

**Comment by SamyCoenen** [comment]
Above link fixed my install, only took a couple of minutes

I did the following:
```
sudo snap refresh wine-platform-4-staging --beta
mv ~/snap/leagueoflegends/common/.wine/drive_c/Riot\ Games/ ~
rm -rf ~/snap/leagueoflegends/
leagueoflegends
# close the window when it asks to choose something
mv ~/Riot\ Games/ ~/snap/leagueoflegends/common/.wine/drive_c/
leagueoflegends
```

**Comment by Ads20000** [comment]
Crucially, need to run `leagueoflegends.winecfg` and change to Windows XP after the penultimate step, otherwise you end up with endless Bugsplats when attempting to launch the client.
