### ISSUE TITLE
New Client Won't Run

### ISSUE THREAD

**Issue by vahtos** [mmtrt/leagueoflegends#86]
I had this snap installed previously, and it stopped working around patch 9.18 for me, which is when I was one of the lucky people selected to have the new client (yay me /s). I have followed the directions for patch 9.20 to uninstall the snap, update the wine snaps and then reinstall. I also set the prefix to use Windows XP.

The game installs and the client loads and everything works, but then the next time I open it (after logging with my account), it tries to install the new client and from that point on fails to launch. Here is the output, hope you can point me in the right direction. Thanks!

```
Running /bin/env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/leagueoflegends_leagueoflegends.desktop /var/lib/snapd/snap/bin/leagueoflegends
gamemodeauto: 
wine: Unhandled exception 0x80000003 in thread 3e at address 004135C7 (thread 003e), starting debugger...
005a:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
LeagueClient.exe(00000009): ALWAYS| Application Version:9.20.292.8264 - CL:2928264 - Build Date:Oct 10 2019 - Build Time:19:09:30
LeagueClient.exe(00000009): ALWAYS| Direct Launch enabled for league_of_legends.live in environment 'live' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
LeagueClient.exe(00000009): ALWAYS| Found Riot Client live install (C:/Riot Games/Riot Client/RiotClientServices.exe)
LeagueClient.exe(00000009): ALWAYS| Riot Client started. Exiting with the expectation of being restarted (ExitForDirectLaunch).
Waiting on children
Waiting on children
```

![specs](https://user-images.githubusercontent.com/30844190/66724479-4e1f7b80-edf4-11e9-8490-3dc627323af6.png)
![image](https://user-images.githubusercontent.com/30844190/66724497-760edf00-edf4-11e9-8810-815af92d2bec.png)

**Comment by mmtrt** [comment]
I had to try 2,3 times to get this new launcher work and make sure kill wine processes when starting again.

Use this command to stop wineserver.

`leagueoflegends.wineserver`

**Comment by vahtos** [comment]
So try to reinstall again? I've tried the install twice, and tried to start it at least 10 times. Does the same thing, just hangs at that point.

**Comment by mmtrt** [comment]
if you are planing to reinstall maybe just try to delete league snap data folder instead.
`$HOME/snap/leagueoflegends`

**Comment by ibrahimpmahmood** [comment]
It seems I need to keep refreshing wineprefix to use old league launcher every time I exit client

**Comment by vahtos** [comment]
I tried reinstalling again, and deleting the snap folder before reinstall. Same result. It starts once and patches, restart the client and it does the new client update and then every time after that it fails to launch the new client. It isn't that it just takes a long time, I left it for 2 hours.

**Comment by mmtrt** [comment]
You can try wine AppImg as snap is not working for you for some reason.

**Comment by vahtos** [comment]
The appimage on Lutris works except I get the reconnect bug when trying to join a game. I'll give this a try.

**Comment by vahtos** [comment]
> You can try wine AppImg as snap is not working for you for some reason.
> 
> EDIT: when you have fully updated game then run this command on terminal to block new launcher from executing and make sure client is not running after this command launch game as usual and I'm not sure how longer this method will work.
> 
> NOTE: Before executing this command make sure launcher has installed new launcher update.
> 
> `for f in RiotClientServices.exe RiotClientCrashHandler.exe; do sudo chmod 0 "$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games/Riot Client/$f"; sudo chown root:root "$HOME/snap/leagueoflegends/common/.wine/drive_c/Riot Games/Riot Client/$f"; done`

Very clever. It works for now! lol
