### ISSUE TITLE
DirectX error after character selection

### ISSUE THREAD

**Issue by valotam** [mmtrt/leagueoflegends#89]
![image](https://user-images.githubusercontent.com/26079796/67207051-c36efa00-f44d-11e9-9337-56bd1a12e75a.png)

**The error of wine occurs after selecting a champion.**

---

```
$ leagueoflegends
LeagueClient.exe(00000009): ALWAYS| Application Version:9.20.292.8264 - CL:2928264 - Build Date:Oct 10 2019 - Build Time:19:09:30
LeagueClient.exe(00000009): ALWAYS| Direct Launch enabled for league_of_legends.live in environment 'live' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
LeagueClient.exe(00000009): ALWAYS| Found Riot Client live install (C:/Riot Games/Riot Client/RiotClientServices.exe)
LeagueClient.exe(00000009): ALWAYS| Riot Client started. Exiting with the expectation of being restarted (ExitForDirectLaunch).
wine: Unhandled exception 0x80000003 in thread 3e at address 004135C7 (thread 003e), starting debugger...
005a:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
```

---

As you mentioned on the other thread. (issue: Game crashes after champ select #80)

Put my info below.

```
leagueoflegends          1.0              54    edge       mmtrt       devmode
wine-platform-4-staging  4.16             24    candidate  mmtrt       -
wine-platform-runtime    v1.0             44    candidate  mmtrt       -
```

```
$ lspci -k | grep -EA3 'VGA|3D|Display' 
07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Device 15d8 (rev c8)
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device 15d8
07:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device 15de
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device 15de
```

```
$ glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: VMware, Inc. (0xffffffff)
OpenGL vendor string: VMware, Inc
```

Same error happened after changing `wine-platform` to `snap refresh --beta wine-platform-runtime`.

```
00a4:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
X Error:  BadWindow
  Request Major code 10 ()
  ResourceID 0x7400003
  Error Serial #184
  Current Serial #204
```

**Comment by mmtrt** [comment]
> OpenGL vendor string: VMware, Inc
Are you testing in vm?

**Comment by valotam** [comment]
No.
I had tried to run it on the MX linux though...

**Comment by mmtrt** [comment]
Did you test any other snap beside this one if not then try this and check for similar issue.

`sudo snap install bombsquad`

**Comment by Getta91** [comment]
Hi! I had the same problem yesterday but I found a fix. First, you will need winetricks (`sudo apt install winetricks`). Then in a terminal do: `export WINEPREFIX=/path/to/your/wine/prefixe && winetricks`.
Now, winetricks, will open --> *Select the default wineprefix* --> **Change settings** --> click on **ddr = opengl**. Now, confirmed your changes and quit winetricks. Everything will be working fine now! Hope this helps

**Comment by valotam** [comment]
> Did you test any other snap beside this one if not then try this and check for similar issue.
> 
> `sudo snap install bombsquad`

@mmtrt, I intalled the package and played well.

> Hi! I had the same problem yesterday but I found a fix. First, you will need winetricks (`sudo apt install winetricks`). Then in a terminal do: `export WINEPREFIX=/path/to/your/wine/prefix && winetricks`.
> Now, winetricks, will open --> **Select the default wineprefix** --> **Change settings** --> click on **ddr = opengl**. Now, confirm your changes and quit winetricks. Everything will be working fine now! Hope this helps
> 
> PS: Sorry for my english

@Getta91, it didn't work well to me... The directX error still appears
