### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by jpgrewal** [mmtrt/leagueoflegends#90]
Hi, League of Legends won't start on my linux laptop (Mint).

Below is the message returned when I try and run the game:

LeagueClient.exe(00000009): ALWAYS| Application Version:9.20.292.351 - CL:2920351 - Build Date:Oct 04 2019 - Build Time:13:46:43
LeagueClient.exe(00000009): ALWAYS| Direct Launch not configured for league_of_legends.live in environment '' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
LeagueClient.exe(0000002F): ALWAYS| Tracing worker thread running.
LeagueClient.exe(00000009): ALWAYS| Running LeagueClient version 9.20.292.351
LeagueClient.exe(0000002F): ALWAYS| Keeping up to 10 tracing logs.
LeagueClient.exe(0000002F): ALWAYS| Tracing CompactJsonWriter at C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-10-21T16-12-28_8_LeagueClient-tracing.json
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Init
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded plugin manifest file plugin-manifest.json.
LeagueClient.exe(00000009): ALWAYS| Begin Launch Ux Process
LeagueClient.exe(00000009): ALWAYS| End Launch Ux Process
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Mounted all WadFiles in 6.916 milliseconds.
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded all plugins in 57.077 milliseconds. All warming in 0.000 milliseconds. All loading in 35.433 milliseconds.
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Initializing plugins
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-client-config: 1.6.1
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-rso-auth: 1.8.24
LeagueClient.exe(0000003A): ALWAYS|        rcp-be-lol-rso-auth| RSOClient::SetRSOConfig url: https://auth.riotgames.com/token, clientId: lol, scopes: openid offline_access lol ban profile email phone
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-patch: 1.5.96
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-patcher: 1.20.35
LeagueClient.exe(00000009): ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__rads__patcher_operation
common.os_platform: Windows
common.application_name: LeagueClient
common.application_version: 9.20.292.351
common.cef_version: 3.2623.1397.gaf139d7
common.installation_id: lwLOgg==
common.locale: en_US
common.machine_id: Dv7YJTCDK0m25DOZ5g4ffg==
common.os_version_major: 7
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: NA
common.session_id: 461fe2f1-7c1f-2d4e-a8b8-961b20698fdc
initial_check: true
cdn: akamai
last_host_ip: 184.150.160.26
success: success
operation_type: check
patchline: live-na-win
patcher: chunking
published_at: 2019-10-11T05:01:16.212000
version: 62
url: https://lol.secure.dyn.riotcdn.net/channels/public/live-na-win.json
LeagueClient.exe(00000009): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(0000003A): ALWAYS|        rcp-be-lol-rso-auth| rso-auth: OpenID configuration fetch succeeded after 1 tries
LeagueClient.exe(0000003B): ALWAYS|       rcp-be-client-config| Updated public config for LeagueClient with 60 entries
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-riot-messaging-service: 1.3.10
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-entitlements: 0.0.28
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-bootstrap: 1.0.20
LeagueClient.exe(00000009): ALWAYS| Phase End - Initializing plugins - duration was 243.48ms
LeagueClient.exe(00000033): ALWAYS|        rcp-be-lol-rso-auth| Client is configured. RSO Proxy: true
LeagueClient.exe(00000009): ALWAYS| Foundation is now running.
LeagueClient.exe(00000009): ALWAYS| Phase End - Init - duration was 472.24ms
LeagueClient.exe(00000009): ALWAYS| Phase Begin - MainLoop
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 155 (GLX)
  Request Minor code 6 ()
  Error Serial #244
  Current Serial #243

**Comment by mmtrt** [comment]
Which GPU your laptop has and specify laptop model using also make sure you have i386 GL driver pkgs installed.

**Comment by jpgrewal** [comment]
NVIDIA GeForce GTX 1650 GDDR5 graphic card with 4GB video memory
ASUS Rog Laptop - uninstalled windows and installed Mint
Looking at the GL driver pkgs now, and installing latest, will post an update after trying to let you know if it worked or not

**Comment by jpgrewal** [comment]
Still not working, I downloaded NVIDIA-Linux-x86_64-430.50.run, below is what was returned:

LeagueClient.exe(00000009): ALWAYS| Application Version:9.20.292.351 - CL:2920351 - Build Date:Oct 04 2019 - Build Time:13:46:43
LeagueClient.exe(00000009): ALWAYS| Direct Launch not configured for league_of_legends.live in environment '' for app path 'C:\Riot Games\League of Legends\LeagueClient.exe' and install dir 'C:\Riot Games\League of Legends'
LeagueClient.exe(0000002F): ALWAYS| Tracing worker thread running.
LeagueClient.exe(00000009): ALWAYS| Running LeagueClient version 9.20.292.351
LeagueClient.exe(0000002F): ALWAYS| Keeping up to 10 tracing logs.
LeagueClient.exe(0000002F): ALWAYS| Tracing CompactJsonWriter at C:/Riot Games/League of Legends/Logs/LeagueClient Logs/2019-10-21T17-59-31_8_LeagueClient-tracing.json
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Init
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded plugin manifest file plugin-manifest.json.
LeagueClient.exe(00000009): ALWAYS| Begin Launch Ux Process
LeagueClient.exe(00000009): ALWAYS| End Launch Ux Process
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Mounted all WadFiles in 4.440 milliseconds.
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Loaded all plugins in 49.912 milliseconds. All warming in 0.000 milliseconds. All loading in 34.555 milliseconds.
LeagueClient.exe(00000009): ALWAYS| Phase Begin - Initializing plugins
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-client-config: 1.6.1
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-rso-auth: 1.8.24
LeagueClient.exe(00000039): ALWAYS|        rcp-be-lol-rso-auth| RSOClient::SetRSOConfig url: https://auth.riotgames.com/token, clientId: lol, scopes: openid offline_access lol ban profile email phone
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-patch: 1.5.96
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-patcher: 1.20.35
LeagueClient.exe(00000009): ALWAYS| The following message is prepared to be sent to dradis:
Event Name: riot__rclient__rads__patcher_operation
common.os_platform: Windows
common.application_name: LeagueClient
common.application_version: 9.20.292.351
common.cef_version: 3.2623.1397.gaf139d7
common.installation_id: lwLOgg==
common.locale: en_US
common.machine_id: Dv7YJTCDK0m25DOZ5g4ffg==
common.os_version_major: 7
common.os_edition: Ultimate N, x64
common.os_version_minor: Service Pack 1
common.region: NA
common.session_id: d81b025c-aee7-5e4d-810d-b237722a11c8
initial_check: true
cdn: akamai
last_host_ip: 184.150.160.26
success: success
operation_type: check
patchline: live-na-win
patcher: chunking
published_at: 2019-10-11T05:01:16.212000
version: 62
url: https://lol.secure.dyn.riotcdn.net/channels/public/live-na-win.json
LeagueClient.exe(00000009): ALWAYS| Queued Dradis event to be sent.
LeagueClient.exe(00000039): ALWAYS|        rcp-be-lol-rso-auth| rso-auth: OpenID configuration fetch succeeded after 1 tries
LeagueClient.exe(00000038): ALWAYS|       rcp-be-client-config| Updated public config for LeagueClient with 60 entries
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-riot-messaging-service: 1.3.10
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-entitlements: 0.0.28
LeagueClient.exe(00000009): ALWAYS|             Plugin Manager| Initializing plugin rcp-be-lol-bootstrap: 1.0.20
LeagueClient.exe(00000009): ALWAYS| Phase End - Initializing plugins - duration was 250.16ms
LeagueClient.exe(00000040): ALWAYS|        rcp-be-lol-rso-auth| Client is configured. RSO Proxy: true
LeagueClient.exe(00000009): ALWAYS| Foundation is now running.
LeagueClient.exe(00000009): ALWAYS| Phase End - Init - duration was 398.35ms
LeagueClient.exe(00000009): ALWAYS| Phase Begin - MainLoop
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 155 (GLX)
  Request Minor code 6 ()
  Error Serial #244
  Current Serial #243

**Comment by mmtrt** [comment]
did you installed previous drivers from nv `run` pkg as well and also does you laptop has single gpu or multi vendor like intel+nv.
