### ISSUE TITLE
Client Crashed

### ISSUE THREAD

**Issue by bonber** [mmtrt/leagueoflegends#91]
Hi when repair program is active, i recibed this:
"MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work."
The game doesn't start after that.
If i reinstall goes well, until repair program appear.
Rewards

**Comment by mmtrt** [comment]
Is this happen after new launcher update installed?

**Comment by bonber** [comment]
Yes, i take a game but crashed when i restart. After a new splash update

**Comment by mmtrt** [comment]
try this https://github.com/mmtrt/leagueoflegends/issues/86#issuecomment-542162609

**Comment by Ignacy-s** [comment]
> try this [#86 (comment)](https://github.com/mmtrt/leagueoflegends/issues/86#issuecomment-542162609)

Had the same problem and it seems to work. Same as, there was an unhandled exception and a midi sound report right before it (tho it is likely not the issue itself). What does that hack from the comment do? Looks like it "disables" the bugsplatter reporter and sets its permissions to 0 and owner to root?

Usually the game worked first time after installation. The bug would occur only the second time, the game would have a strange "update-repair" splash and then stop working at all.
Below screenshot of the splash screen seen before the game gets botched.
![Screenshot at 2019-10-21 19-30-35](https://user-images.githubusercontent.com/24595235/68077291-21d69980-fdb9-11e9-8ebf-c748db9edb64.png)

**Comment by bonber** [comment]
Hi, i solved temporarily the problem, when leagueoflegends is instaled i created a new directory with root permissions "sudo mkdir '/snap/leagueoflegends/common/.wine/drive_c/Riot Games/Riot Client'"
The new client doesn't install and if you kill all process and execute again it works.
Rewards.
