### ISSUE TITLE
Cant install the game

### ISSUE THREAD

**Issue by kholis1** [mmtrt/leagueoflegends#92]
Hello i have recently installed Linux Mint 19.2 and tried to install league of legends,when i launch the client i am asked in which region am i.I am in EUNE so i press EUNE and when i press install the installer stacks and does not do anything.

**Comment by mmtrt** [comment]
Can you launch `leagueoflegends` command from terminal and post log.

**Comment by kholis1** [comment]
> Can you launch `leagueoflegends` command from terminal and post log.
Hello, i tried it and it works just fine thanks a lot.But why it didnt start properly from the launch icon?

**Comment by mmtrt** [comment]
That could be due to first time instal league snap on some desktop environments user need to reboot system or logout user in order to fix snap launcher icon.
