### ISSUE TITLE
when changing tabs in the middle of the game

### ISSUE THREAD

**Issue by theliso** [mmtrt/leagueoflegends#94]
I've just installed the game in my linux mint 19, and so far the experiment is going great, but i must warned you that i've noticed when playing normal game and suddenly i change to google chrome, when i come back to game i can't put the camera as it was. It just still blocked and i have to move it on the map to see things ahead or things in other lanes, etc.

Hope this bug get fixed, so the game experience improve. But overall great work ;)

**Comment by mmtrt** [comment]
Yeah `alt+tabbing` is broken which never worked for me and is usually hit n miss so doing multple times could fix that behaviour, though one should be using wine virtual desktop to fix that which works most of the time with some games.

You can enable it via this command.

`leagueoflegends.winecfg`

**Comment by theliso** [comment]
thank you very much that worked just fine!!
