### ISSUE TITLE
9.23 crash after champ select (no error message) 

### ISSUE THREAD

**Issue by Bloodiko** [mmtrt/leagueoflegends#97]
soo - 
i've seen the other issue with bugsplat opened, but since 9.23 my game doesnt work too, but i have no bugsplat

I am able to login into the client (without riot launcher, i'm blocking it from installing), but as soon as i want to open the actual game client, after champ select or when spectating, or on tft matches, the game doesnt even open and your client opens back up with the possibility to reconnect - which also results in no error message, but it doesnt open it either 

might be only a small issue this time, hopefully your able to fix it pretty fast (although i have no clue where the issue lies)

actually , i had the same issue occasionally in the previous patches too, but it was only temporary, and fixed itself after a while, and sometimes a client restart helped- 
though now it seems like its a permanent issue

**Comment by mmtrt** [comment]
This needs new wine patch fixes.

**Comment by lorenzwinkler1** [comment]
Is there a temporary workaround? I am encountering the same issue.

**Comment by mmtrt** [comment]
@lorenzwinkler1 I'm trying to add patch fix to wine source and issue build then test and last release it if all goes well though it will take some time as I had changed distro but its not setup for build dev doing it right now and hopefully game should be working later today.

**Comment by Bloodiko** [comment]
so, i've just seen that someone already seems to have realeased a working wine-lol build:
https://github.com/cosarara/wine-lol (pkgbuild)

https://github.com/matiaskotlik/wine-lol-builds/releases/tag/4.17-2 (deb + source)

maybe you can try adding them (i suppose your still working on a fix too)

**Comment by Complex54** [comment]
@Bloodiko is this working on Linux Mint ?

**Comment by lorenzwinkler1** [comment]
I don't use linux mint but i guess downloading the .deb package and trying it is worth a try and pretty likely to work since linux mint is debian based.

**Comment by Bloodiko** [comment]
@Complex54 i dont know 
i'm waiting for mmtrt to deploy an actual fix to my issue - i have no clue on how to add this wine version to the snap manually 
but from what i've seen in the league of linux reddit, it seems to work pretty good

**Comment by lorenzwinkler1** [comment]
Do you have further information about when league of legends will be playable with this snap again?

**Comment by mmtrt** [comment]
It is playable for some users read #96 for more information.

**Comment by Bloodiko** [comment]
As it is playable for me (client is even more fluid that before), i may close this issue here - answers on how to get the fix are in the other issue log
