### ISSUE TITLE
League of legends account are now Riot window issue

### ISSUE THREAD

**Issue by jpobeda** [mmtrt/leagueoflegends#98]
Hi,

When the game first load I get a pop window that doesn't let me do anything else than clicking the arrow but then I get ```{"httpStatus":401,"errorCode":"No magic link found"}```

I makes a call to the API https://update-account.riotgames.com/api/v1/magic-link/{removedByMe}

Is anyone else getting this? How do I get around it?

![image](https://user-images.githubusercontent.com/13456559/69606002-89b19480-1086-11ea-8da9-9b72eb8e8fa5.png)

Don't know actually what data would be useful to help with this.

```
leagueoflegends          1.0                         56    edge       mmtrt           devmode
wine-platform-4-staging  4.20                        30    candidate  mmtrt           -
wine-platform-runtime    v1.0                        58    candidate  mmtrt           -
```

**Comment by mmtrt** [comment]
create new username for riot account that will associate that one account for all rito games.

**Comment by jpobeda** [comment]
Finally got an email on my inbox to update my account and now I don't get that pop up.
